### ISSUE TITLE
Animate the transition of the on/off states of the switch component

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#1000]
Instead of fully switching from white to blue (on/off states) of the switch, this issue is to add more of a smooth transition and animate that change in color. Definitely connects with #998 

[Example prototype](https://drive.google.com/file/d/1jYMqh-qV0-YQJ10TJYbNQeyF2-n_xfl-/view?usp=sharing)

**Comment by mcarrano** [comment]
Will address as part of https://github.com/patternfly/patternfly/issues/4979
