### ISSUE TITLE
Animate the appearance and disappearance of the Modal component

### ISSUE THREAD

**Issue by nirfarkas** [patternfly/patternfly-design#1001]
**HIGH PRIORITY**
After clicking any interactive element that fires up a modal, we should introduce the modal in a soft fashion, meaning fading it in. The soft fade-in will make the appearance of the modal less abrupt and add more finesse to the transition. 
The above text also applies to the transition of closing the modal (e.g fade-out).
*This is only a rough concept and the animation is not finalized. 

![Pop](https://user-images.githubusercontent.com/65043359/105634171-74402200-5e65-11eb-8658-da821100d4c0.gif)

**Comment by mcarrano** [comment]
Will address as part of https://github.com/patternfly/patternfly/issues/4979
