### ISSUE TITLE
Animate the expansion of the Modal component when more content is added

### ISSUE THREAD

**Issue by nirfarkas** [patternfly/patternfly-design#1002]
**HIGH PRIORITY**
There are cases when a modal opens up and has a certain height to show its content & the user can interact with the content resulting in more content (for example, selecting a checkbox that reveals more options). In order to make the change of the modal's heights softer, we should introduce an animated transition.
* This animation is just a concept idea and not finalized.
![modal_expand_transition](https://user-images.githubusercontent.com/65043359/105634480-ca619500-5e66-11eb-9098-2c5846d5f35f.gif)

**Comment by mcarrano** [comment]
Will address as part of https://github.com/patternfly/patternfly/issues/4979

**Comment by andrew-ronaldson** [comment]
This is being picked up in another v6 issue
