### ISSUE TITLE
UX: Typeahead entry clears when dropdown dismissed

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-design#1003]
## Background

In Cockpit, we're using a PF4 typeahead as a remote-system directorly selector. (You type and/or click around with a mouse to select a directory to create a storage pool for virtual machines.)

## Description of the problem

Typing (including pasting with the keyboard) works. However, if an entry is not selected either with the mouse or via the keyboard (by pressing down and hitting enter, for example), then the entry field is cleared.

When someone is working on the rest of the form and has submitted it, it is easy to overlook a form they've already entered (and didn't expect to get cleared).

Cockpit BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1866225

## How to trigger this issue (on PF4's demo)

1. Copy this string: **Florida**
2. Visit https://www.patternfly.org/v4/documentation/react/components/select#typeahead
3. Enter the typeahead with a click (or by tabbing to it)
4. Paste (or type) the string Florida
5. Important: **_Do not_** select the dropdown's "Florida" entry. Do not click it or use the keyboard to select it.
6. Click elsewhere or tab away to another widget to dismiss the dropdown
7. Notice how the text that was entered via the keyboard is gone!

## Expected results

Any text that was typed or pasted into the entry should persist. It should not be cleared.

**Comment by mcarrano** [comment]
@garrett I'd love to get your opinion on @jessiehuff 's question above, also. I agree with your basic point that someone could enter text into the field and tab away thinking there entry would be saved as it is for any other text field only to find it wasn't. We could change this so tabbing out of the field commits the entry as you are suggesting, but it begs the question of what to do if they make a typo for example and the `isCreatable` prop is set. This would add the string to the menu, which might not be what you want. It seems like we could recommend that someone write a more robust callback function that requires the user to confirm the "create" or require the user to take a more explicit action like pressing Enter or selecting the Create option from the menu to add a new value. Thoughts?

**Comment by garrett** [comment]
What if we don't add any more interactions, but add a tiny bit of messaging instead? Here's how I think that could work:

- If the value matches something in the list, the typeahead widget would act as it currently does.

- If the value doesn't match anything in the list and...

  - **`isCreatable` prop is set**: There could be a message about something being created. Perhaps an optional (but default) message under the typeahead widget, like:

    > :information_source: **ExampleThing** will be created

  - **`isCreatable` prop is not set**: We could use the same idea of having text under the typeahead entry, but it would say something like:
    
     > :warning: **ExampleThing** is not in the list

     (And this may block the form from being submitted.)

While I imagine the strings would be default (perhaps with some different text), each should be able to be turned off independently (so they can be handled by the app) and also customized (so PatternFly could provide the mechanism, but the app could control the string).

What do you think?

**Comment by mcarrano** [comment]
@garrett I think this is a good approach. However it seems like in the first case you'd want some kind of confirmation, right? What if I just made a type and I didn't really want to create ExampleThing? How would I prevent it from getting created if `isCreatable` is set?

**Comment by garrett** [comment]
@mcarrano I was thinking about this within the context of a modal dialog, with delayed-apply (which we use a _lot_ in Cockpit), not within an instant-apply context. Thanks for pointing it out. You're right. When this is used for instant-apply, having a confirmation makes sense, especially if it's not easy (or even possible) to remove the created item.

Three different options for an instant apply mode:
1. the same text that something will be created could be in a modal confirmation instead (with create and cancel buttons)
2. change the tense "ExampleThing was created" and then have an undo link next to it
3. add an inline create action button next to the "ExampleThing will be created" string

I think all of the solutions are becoming very application and context specific, suggesting that a default that works for everyone, everywhere is not possible. I guess the page would show different examples, depending on context, and application authors could choose what is best for their usage.

Thoughts on what's best:
- The modal confirmation is probably the most disruptive, so it would probably make sense to avoid it when possible. This is especially the case for when the widget is used in a modal already (if instant apply mode isn't default, and the developer didn't realize it). Apps should always avoid modal-spawned-from-modal actions.
- Auto-create is nice, but undo is probably harder to add for some apps. It would definitely require custom tooling.
- An inline create can extend the auto-create feature and would work in both delayed and instant apply modes. (Although it's a delayed create and not really instant-apply, really.) When it's used in an modal and the modal is saved, it should probably auto-create, even if the button wasn't clicked.

_Therefore_, I would suggest:
- On the PatternFly website, it should show examples of the different ways this could be used.
- There should be text explaining which to use (and when it should be used) on the website.
- The default should probably be an in-line confirmation with a message. (So if a developer picks the wrong one, it's the least wrong and should still work regardless.)
- A modal method should really be a callback with a normal modal. And it should never be used from within another modal. It should be the last example out of these solutions.
- Hopefully all of this can be done with normal PF widgets, without extending this one too much. :wink: It might mean a few more property toggles and callbacks though.

**Comment by mcarrano** [comment]
Thanks for this detailed analysis @garrett . What you are saying above all makes sense. @tlabaj is this validation something we could support now? Looks like we do support a callback attached to the `onCreateOption` prop, so I would assume that we could include code to prompt the user for validation before we added a new item. Is that correct? If so, it might make sense to create a demo for that as @garrett describes. I could create mockups for that if you think it makes sense.

But back to the original issue then. Sounds like the only change we would want to make at the component level is to consider tabbing away from the field as an implicit selection, and if `isCreatable` is set, make the consumer responsible for validation.

@tlabaj @jessiehuff thoughts?

**Comment by tlabaj** [comment]
@mcarrano For the question of maintaining what is entered in the text input, the answer is that we can do that.  But i feel it is an interaction decision on if we should.  I would not change the current default behaviour regardless of if we decide that interaction makes sense to implement.  We would probably need to add an additional prop fo the retained value to support what is being asked for.

**Comment by mcarrano** [comment]
@tlabaj @garrett @jessiehuff I spent some more time thinking through the options. I agree with @tlabaj that we would not change the default behavior, but rather add a prop to enable a new behavior if we want to commit the value of the field when the component looses focus. When we enable that, here are some options for how I think this could work when `isCreatable` is set.

**Option 1**
The user tabs away from the field. The value entered in the field is retained, however onCreateOption is not called unless the user explicitly selects that either from the menu or by pressing Enter (as it is today). Therefore, the new value will not be added to the list and consumer would be responsible to validate the value entered.

**Option 2**
We make creation of a new option a more explicit action and new items are only created when the user explicitly takes an action to accept it. This is mocked up below.

![typeahead-select-explicit-create.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/4a35a42f-d407-4622-87d7-df7e82a6b85e)

In this case the user must click the accept button or navigate to it using the keyboard to create "Connecticut." Otherwise the new value is not retained.

**Option 3**
We retain whatever was typed into the field upon loss of focus and leave it to the consumer to decide what to do. I think this is what @garrett has proposed above. It would be left to the consumer to attach that action to the `onCreateOption` event. Here, I've shown how we could use a popover to confirm whether the new item is to be added when we tab out of the field. But you could also leave this validation to happen when the user clicks submit in the case of a modal operation.

![typeahead-select-onCreateOption.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/eb773e3e-ba9f-4836-b7d5-e6985e6f781b)

If we go this way, I suggest that we create a demo based on the above mocks.

Let me know your thoughts.

**Comment by mcarrano** [comment]
I have opened an issue here to add a new prop: https://github.com/patternfly/patternfly-react/issues/5502 This will enable a consumer to implement option 3 as described above.

**Comment by mcarrano** [comment]
We will follow the approach outlined in Option 3. Closing this design issue in favor of the React issue referenced above.
