### ISSUE TITLE
Default "overfiltered" empty state has redundant text

### ISSUE THREAD

**Issue by mattreid** [patternfly/patternfly-design#1004]
## Requesting new features, enhancements, or design changes to PatternFly 
- Describe the use cases and requirements of the new feature or enhancement you are requesting.
The current text in the example empty state says "No results found
No results match the filter criteria. Remove all filters or clear all filters to show results." with a Clear all filters action underneath.

**Remove** and **Clear** seem functionally the same to me, and Clear matches the action text. Are we able to simplify this and drop the "Remove all filters or" portion of the description?

- Explain *why* this feature is needed and/or why these requirements cannot be met using existing components.
The default text is redundant and could be more succinct. 

- If this is for specific applications, list them here along with any dates that you need this for.

- Link any detailed design documents, rough sketches, wireframes or workflows.

- State whether this is a new feature or an enhancement on an existing pattern by labeling it accordingly
Enhancement to existing

- If this is an enhancement to an existing feature, identify the feature that you want to modify.
https://www.patternfly.org/v4/components/table#empty-state
https://www.patternfly.org/v4/components/empty-state#no-match-found
https://www.patternfly.org/v4/components/table/html-demos/empty-state/

![Screen Shot 2021-01-26 at 3 30 30 PM](https://user-images.githubusercontent.com/1242413/105901602-9a8fca00-5feb-11eb-9f56-138f9de094ed.png)

![Screen Shot 2021-01-26 at 3 31 10 PM](https://user-images.githubusercontent.com/1242413/105901609-9ebbe780-5feb-11eb-9a3f-6d433fe8249b.png)

**Comment by mcarrano** [comment]
@mmenestr Can you take a look at this? Do we intend the messaging to be as it is on the PF site? Thanks.

**Comment by mmenestr** [comment]
This seems reasonable to me!

> **No results found**
> No results match the filter criteria. Clear all filters to show results.
> 
> Clear all filters

**Comment by mattreid** [comment]
That looks better to me, thanks!

**Comment by mcarrano** [comment]
@mmenestr are you suggesting that we should update the demos on the PatternFly site then? What do we say in the design guidelines for this use case?

**Comment by mmenestr** [comment]
Yes, that's correct - why not update the text in the demos! Hopefully it's a one string fix?

In the empty state design guidelines for this use case, this is the guideline and image accompanying it - it's kept quite vague. 
![image](https://user-images.githubusercontent.com/51165119/106172012-43f7cc80-6160-11eb-89bd-86504ee94c06.png)

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly-react/issues/5395 to update the example and will close this design issue.
