### ISSUE TITLE
Explore Input Group styling for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1005]
Borders between elements in an Input Group need to be reconsidered for dark theme. Here's what it looks like now without making changes:

![Screen Shot 2021-01-29 at 9.10.49 AM.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/f0c37942-899a-4f1e-8d7d-55d6c785f363)

Want to be able to differentiate between elements (i.e. buttons and fields) without being too heavy-handed.

**Comment by mceledonia** [comment]
@doruskova @mcarrano @mcoker 

Here's my proposal for dark theme input group styling, these are the same designs on our 2 main BG colors:
![image](https://user-images.githubusercontent.com/30935938/106500144-791d5b00-648f-11eb-8c47-c8c016d3446f.png)
![image](https://user-images.githubusercontent.com/30935938/106500155-7cb0e200-648f-11eb-814b-ad9aee9bd46b.png)

These differ from the current theme in that they have a vertical line separating each section. The vertical line in this case is drawn on top and it our lightest background color `#26292D`. This is to create the illusion that the sections have a 1px gap, so in terms of implementation approach, it could either be a literal border/divider drawn on top, or actually have the gap itself. 

I think this does a good job of showing each individual part without worrying about a background color change.

**Comment by mcarrano** [comment]
Looks good @mceledonia . I will close.
