### ISSUE TITLE
Copy to Clipboard for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1008]
Propose styling for Copy to Clipboard component seen in dark theme.

**Comment by mceledonia** [comment]
@mcarrano @doruskova @mcoker What do you think about something like this? It is a departure from our light theme approach but I was running into issues when trying to differentiate clearly between default, read only, read only expanded, and disabled.

![image](https://user-images.githubusercontent.com/30935938/108381625-fa862480-71d5-11eb-95a9-df9928326939.png)

@mcoker This approach would require changing the vertical border styling for read only states as well, you can see they get brighter to match the border of the rest of the input styling for read only. Would this be an issue?

**Comment by mcarrano** [comment]
@mceledonia did we ever do final/updated mocks for this? If so, can you post them here and I will close this out? Thanks.

**Comment by mcarrano** [comment]
Final designs resolved in CSS prototype. Will close.
