### ISSUE TITLE
Feedback on the copy to clipboard component 

### ISSUE THREAD

**Issue by lwrigh** [patternfly/patternfly-design#1009]
## Requesting enhancements

Both @bgliwa01 and I have gotten feedback recently from the OpenShift dev console team about the copy to clipboard component being too clunky. In my situation, I am trying to use the copy to clipboard for adding code snippets to
 Quick Starts so the user can either copy the code snippet to their clipboard or run the code snippet in the terminal. 

Design example:
<img width="187" alt="Screen Shot 2021-02-08 at 2 51 56 PM" src="https://user-images.githubusercontent.com/20227374/107273548-332b3e80-6a1d-11eb-91ab-9ab1c7f4c806.png">
The copy to clipboard component works better for single lines of code but when it comes to multiple lines of code, it can become cumbersome to use. I have received feedback saying that folks would like to see more of the code snippet previewed before it truncates. I think this feedback is really valid in the Quick Starts situation since multiple people have noted that a user who is just getting started with OpenShift would probably want to see the full code snippet so they can get a clearer sense of what's going on and what they are doing. 

Link to the issue that Brigid is working on: https://github.com/openshift/console/pull/8097 @bgliwa01 Feel free to elaborate on your situation. 

I did some research to see if I could find good examples of copy to clipboard components and I found the [Carbon code snippet component](https://www.carbondesignsystem.com/components/code-snippet/usage/) to be a really nice example. I think if we could pull some inspiration from it to update the PatternFly copy to clipboard to be more simplified I think it would be a nice improvement. 

For making it more simplified I would suggest getting rid of the grey background around the text line and making the multiple line variation surface more before it truncates the rest of the lines. I think if we could include an inline copy to clipboard option and room for additional actions that would be a really nice option. 

Here are some rough wireframes of what a PF code snippet/copy to clipboard inspired by Carbon might look like. 
![Artboard](https://user-images.githubusercontent.com/20227374/107276503-1abd2300-6a21-11eb-9116-a09385fb190c.png)
![No web terminal- single line 1](https://user-images.githubusercontent.com/20227374/107276505-1b55b980-6a21-11eb-9d91-ebcfb454a17c.png)
![Web terminal installed- Single line 1 Copy 2](https://user-images.githubusercontent.com/20227374/107276506-1bee5000-6a21-11eb-8028-a67bedad8e15.png)

Both of these designs are being worked on for the 4.8 OpenShift release.

**Comment by mcarrano** [comment]
@lwrigh I have assigned this to you as we discussed and pull it into our March 10 design milestone. Let's also consider this related issue as part of this: https://github.com/patternfly/patternfly/issues/3725

**Comment by lwrigh** [comment]
Here are the latest design updates to the enhancements to the copy to clipboard components for inline and single line variations. These updates were made after the in progress design with @mcarrano, @mceledonia, and @mcoker.   

![Enhancements to the copy to clipboard component](https://user-images.githubusercontent.com/20227374/108753702-11e54a80-7513-11eb-98ef-c90dac6a2d89.png)
[Enhancements to the copy to clipboard component.pdf](https://github.com/patternfly/patternfly-design/files/6024347/Enhancements.to.the.copy.to.clipboard.component.pdf)

Here are the latest design updates to the proposal for creating a new component to support a multi line/block code snippet. The goal of this design is to create a design solution for a code snippet for Quick Starts in OpenShift but also contribute the component pattern back to PatternFly.
![New component proposal: Code snippet block](https://user-images.githubusercontent.com/20227374/108753703-127de100-7513-11eb-84e4-206d01b7a54d.png)
[New component proposal: Code snippet block.pdf](https://github.com/patternfly/patternfly-design/files/6024346/New.component.proposal.Code.snippet.block.pdf)

Feel free to leave any feedback, questions, or comments about either of these proposals.

**Comment by mcarrano** [comment]
These are looking good @lwrigh . Let's review these at the next design share meeting to see if there is further feedback.

@coreyvickery please take a look at the Code snippet option. Would this also work for the Code Block component you were looking for?

**Comment by lwrigh** [comment]
That sounds good to me. I just added to the next design share agenda.

**Comment by coreyvickery** [comment]
@mcarrano Looking at the PDF, I think the developers I work with are pretty dead set on using multiple colors. I think our teams just need to come to an agreement about what those fonts and colors need to be.

**Comment by mcarrano** [comment]
@coreyvickery So sounds like what you are looking for is syntax highlighting. I doubt that we would write our own syntax highlighter. In PatternFly 3, we supported [Google Code Prettify](https://code.google.com/archive/p/google-code-prettify/wikis/GettingStarted.wiki) that does this job. Do you think that would work? Looks like there is some ability to customize the styling if we wanted. Or are there other syntax highlighters that your team is already using? Agree that it would be nice to have a consistent solution.

**Comment by ssbarnea** [comment]
I do think that the proposed new component should also have an example where the text to be copied is not visible, where you have only the copy button and the text is hidden, basically only the Copy icon should be visible, even if internally the element would exist.

There are cases where very limited space require for that approach. Still, I would find useful for these to also display the text to be copied into the tooltip, or the copy action could become bit confusing, as you will not get a glimpse of what you would copy to clipboard before effectively doing it.

**Comment by mcarrano** [comment]
Thanks for your feedback @ssbarnea . So are you saying that the text field would still exist in the structure, but just be hidden from view? I think that's an interesting idea, however I'm not sure if just placing the copy icon in a page with no other context would be confusing. Do you have an example of where this might be used?

**Comment by christianvogt** [comment]
I don't like the designs where the copy button is outside of the code snippet block. When you get to a examples where there are multiple code blocks with and without copy beside each other, it may not be clear what will be copied.
eg:
Run `this command` [C] `another command`.
`code that isn't copied` `command to copy` [C]

**Comment by lwrigh** [comment]
![Enhancements to the copy to clipboard component](https://user-images.githubusercontent.com/20227374/109184079-9e367e00-775c-11eb-9a5b-bea32188d2d2.png)
@christianvogt I brought that feedback to the PF this week and discussed it with them. I made edits to the inline and single line options to include the action buttons inside of the code snippet. What do you think?

**Comment by christianvogt** [comment]
@lwrigh this looks much better.
One question in regards to the spacing between normal text and the code blocks. In your mocks the spacing of the code block is adjacent to the normal text, meanwhile code blocks code blocks in katacoda and github have a whitespace inbetween:
![image](https://user-images.githubusercontent.com/14068621/109185177-beb30800-775d-11eb-87f2-8e157b97e113.png)
![image](https://user-images.githubusercontent.com/14068621/109185416-fa4dd200-775d-11eb-916f-521b3b12e5b7.png)

**Comment by lwrigh** [comment]
There should ideally have the whitespace in between the text and code snippet. That will be addressed in the design doc which I'm in the middle of updating.

**Comment by coreyvickery** [comment]
@mcarrano We created our own (accessible) styles for syntax highlighting. I am happy to provide those values in case PatternFly ever adds custom syntax highlighting. I think we're good on the PFE team moving forward with finalizing that component.

**Comment by mcarrano** [comment]
That sounds good @coreyvickery . If the PFE team does an implementation, perhaps that's something that can be contributed back to PatternFly so we don't need to duplicate effort.

**Comment by mcarrano** [comment]
I have split this into two new Core issues to begin HTML/CSS implementation.

https://github.com/patternfly/patternfly/issues/3906 for making enhancements to Clipboard copy for the single-line and inline variants.

https://github.com/patternfly/patternfly/issues/3907 for introducing a new Code Block component.

@lwrigh can you separate out your design mocks and attach them to these separate issues? It will also be helpful to link your final Marvel deck here so reference. Thanks so much for your contribution on this!

@christianvogt if you are doing a parallel implementation in product, perhaps there's an opportunity to contribute that code back? 

cc @mcoker @jcaianirh

**Comment by christianvogt** [comment]
@mcarrano so far we haven't planned any implementation work on this. We'll be sure to coordinate if we get to it first.
