### ISSUE TITLE
Are nested form groups supported?

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-design#1012]
In Cockpit we have multiple dialogs with nested form groups. See for example the following:

![Screen Shot 2021-02-23 at 12 30 10](https://user-images.githubusercontent.com/14921356/108837814-1b35ec00-75d3-11eb-97a4-427a08adab76.png)

or:

![Screen Shot 2021-02-23 at 12 32 03](https://user-images.githubusercontent.com/14921356/108837856-29840800-75d3-11eb-865b-3baf76dd95d4.png)

PF4 right now does not seems to support such a pattern and we use some custom CSS for this. Would you like to support such a pattern? If not, do you suggest some alternative?
I appreciate any feedback.

**Comment by mcarrano** [comment]
@KKoukiou we do have this implementation of nested field groups within the Form component: https://www.patternfly.org/v4/components/form/html#field-groups This is only implemented in Core right now, but hopefully will be available in React in time for the next release. Will this meet this need?

**Comment by KKoukiou** [comment]
@mcarrano thanks for the pointer. That field groups feature is cool, but it's very different that our current usage of nested form groups.

Accurately, if you look at the screenshots above there are labels that are just shifted to the right, to show that they belong to and are changing according to the previous group option.

The link to the docs, shows the nested groups with expanders, which are not needed in our case and also there is not example of nested group which is changing according to user input like we do above.

So it seems to me that the field-groups feature is not a drop-in replacement for what we have right now.

**Comment by mcarrano** [comment]
@KKoukiou I see what you are saying. So I think this is more of a question of how to achieve a layout like what you are showing above. We actually currently have a PR up for nesting form controls within a checkbox or radio button group. See https://github.com/patternfly/patternfly/pull/3884 Looks like you want a similar thing.

@mcoker any advise on the best way to achieve this? Could we somehow make the nesting that you are applying to Check and Radio work for other things like a Select? Off the top of my head, I can think of other controls that would call for this. Maybe a Switch?

**Comment by mcoker** [comment]
Hey @KKoukiou you could do that using `<FormSection>`s. Here's a demo - https://codesandbox.io/s/loving-galois-jezdx?file=/index.js

Would that work?

**Comment by KKoukiou** [comment]
OH sure, did not realize it can be used like that. thanks!

**Comment by KKoukiou** [comment]
@mcoker when using FormSection for creating the nested fields, there is too much padding above the first child I feel. I will create an issue in patternfly repo.

![Screen Shot 2021-02-25 at 08 48 21](https://user-images.githubusercontent.com/14921356/109120599-72100280-7746-11eb-996f-d0c2ae76e2f5.png)

See above, the margin above Ipv4 network is bigger than the gap between form groups.

**Comment by mcoker** [comment]
@KKoukiou ah hah, good point! I talked to @mceledonia and he agrees, and says that the spacing of the nested elements should be tighter than the regular spacing between form groups, to imply a grouped relationship. We have a "stack" variation that you can add to the control group in a form group that allows you to stack multiple elements that are all associated with a single label in a form group that @mceledonia says would work well for this use case. Here is a demo - https://codepen.io/mcoker/pen/xxRpeVY

However the stack layout has yet to be implemented in the react form component. Here is the issue for that - https://github.com/patternfly/patternfly-react/issues/5286

Also another way of doing this would be to use the `<Flex>` layout, though I'm not sure if that offers any benefit over your current custom CSS approach.

**Comment by KKoukiou** [comment]
@mcoker this looks perfect. Thanks a lot :)
