### ISSUE TITLE
Skeleton for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1014]
Need to update the Skeleton component designs for dark theme.

**Comment by doruskova** [comment]
@mcarrano @mceledonia Update on skeleton loading https://codepen.io/doruskova/pen/mdOvVQb

Background color: black 900 (`#0f1214`)
Card bg color: black 800 (`#1b1d21`)
Loading: black 600(`#36373A`)
Loading after (effect): black 500 (`#444548`)

**Comment by mcarrano** [comment]
Looks great. @mcoker let's add this to the prototype.
