### ISSUE TITLE
Website: Make it easier to differentiate component from the background on component pages

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1015]
When viewing component examples, it's sometimes hard to tell what's the component and what's the workspace background. Below is an example:

![Screen Shot 2021-03-09 at 4.24.05 PM.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/c1849758-1daa-43af-879e-2b996e39231a)

In this case it's easy to mistaken that example title/heading from the Card header.

Want to identify some styling options to restyle these pages to make it clear what's a component and what's part of the workspace background.

**Comment by maryshak1996** [comment]
Reviewed these designs with @mcarrano and I think that we are comfortable with this design for now.
I've mocked up the component pages in the context of the 'Card component page' and the 'Accordion component page'. 
[Marvel doc here](https://marvelapp.com/prototype/h964d3h) | [Sketch file here](https://www.sketch.com/s/0085290d-2966-45c4-9d4b-e11e44c9600d)

**Comment by mcarrano** [comment]
I've opened https://github.com/patternfly/patternfly-org/issues/2843 to address both this and the TOC issue and will close this one out. Thanks for your efforts on this @maryshak1996 !
