### ISSUE TITLE
Wizard for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1016]
Explore wizard translation to dark theme.

**Comment by doruskova** [comment]
@mcarrano @mceledonia Updated wizard https://marvelapp.com/prototype/963bhhh/screen/77631616

Default step: `$pf-color-black-500: #444548;`
Default step - text: `$pf-color-white: #fff`
Current step and text: `$pf-color-blue-300: #1fa7f8`
Disabled step and text:` $pf-color-black-200: #aaabac;`

Description below title: `$pf-color-black-50: #e0e0e0;`
Background color for the header: `$pf-color-black-1000: #030303`
Background color for the content: `$pf-color-black-700: #26292d;`

**Comment by doruskova** [comment]
@mcoker FYI

**Comment by mcarrano** [comment]
Looks good. Thanks @doruskova . Will close.
