### ISSUE TITLE
inconsistent disabled state color for switch and others

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-design#1018]
**Describe the issue. What is the expected and unexpected behavior?**
Let's compare some PF disabled states:
![image](https://user-images.githubusercontent.com/14068621/111002767-f91ec680-8353-11eb-9a98-490b8f9b083d.png)
![image](https://user-images.githubusercontent.com/14068621/111002779-0045d480-8354-11eb-933a-a340aaba3b31.png)
![image](https://user-images.githubusercontent.com/14068621/111002790-076ce280-8354-11eb-8839-497752592fbf.png)
![image](https://user-images.githubusercontent.com/14068621/111002831-194e8580-8354-11eb-83dc-603f9406b0c3.png)
![image](https://user-images.githubusercontent.com/14068621/111002963-48fd8d80-8354-11eb-936c-6a06cc20d44b.png)

Now for the toggle switch disabled state:
![image](https://user-images.githubusercontent.com/14068621/111003018-57e44000-8354-11eb-92a9-1a90cc7a5380.png)

Now when a switch is `off` it looks disabled to me. The disabled state of the switch doesn't match any of the others.
![image](https://user-images.githubusercontent.com/14068621/111003039-60d51180-8354-11eb-9fe5-befc2265d644.png)

IMO there needs to be more consistency in the disabled state colors. Especially the toggle switch. I've been fooled thinking that the off state of the toggle switch is actually disabled when in fact it wasn't.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Look at patternfly documentation

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
OpenShift Console

**Comment by mceledonia** [comment]
I wonder if the disabled styling for the switch can be something other than a color change, for example switching from fills to borders. It would likely be an exception to the others which work better with the color change. We are going to transfer this over to design so I'll tag you with any updates.

**Comment by mceledonia** [comment]
@mcarrano This looks like a good candidate for the visual refresh effort, refactoring/improving our approach to disabled states across components.

**Comment by mcarrano** [comment]
@christianvogt We had a similar issue come in recently and as a result agreed to rework the visual appearance of the switch which should address these concerns. Therefore I am going to close this. You can follow updates to the switch in this new issue here: https://github.com/patternfly/patternfly-design/issues/1137

We will also be re-considering our overall visual system for a future PatternFly refresh that is outlined here: https://github.com/patternfly/patternfly-design/issues/1026 Feel free to provide any further input to that effort. Let me know if you have any questions.
