### ISSUE TITLE
Nav: are you interested in supporting a search functionality? 

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-design#1021]
In cockpit we have a custom search for our page sidebar, one of the features we actually miss from PF4 is the search. Is it something that PF4 would be interested to support?
 
Here is a screenshot of the feature in question.
![Screen Shot 2021-03-26 at 19 16 21](https://user-images.githubusercontent.com/14921356/112676059-4462ca00-8e68-11eb-9e53-8eba8f2ba763.png)

**Comment by mcarrano** [comment]
@KKoukiou I'm a little bit unclear what you are searching against. Where does the "contains" term come from?

**Comment by KKoukiou** [comment]
@mcarrano looks just in the top of the screenshot there is a search box where you can type to filter your navigation items.

**Comment by mcarrano** [comment]
@KKoukiou So is the intent then to filter nav items? I guess that you could put a Search input above the navigation like we do for the context selector in this example: https://www.patternfly.org/v4/components/context-selector/design-guidelines#navigation-level-impact  Other teams have done that. You would be responsible for writing the logic for implementing the filter. 

Another way to think about this would be to use a global search function like we do on the PatternFly website (or other websites) that would sit in the masthead like this.

![Screen Shot 2021-04-06 at 3 01 45 PM](https://user-images.githubusercontent.com/6619860/113764858-87832f80-96e9-11eb-8ed8-f94169891ac1.png)

Does any of that work?

**Comment by KKoukiou** [comment]
Sure, we have exactly this thing implemented. I was just wondering if you are interested to add support for it in the Nav component, since more teams use it. If not, feel free to close the issue.

**Comment by mcarrano** [comment]
Thanks @KKoukiou . I have not had any other requests for this, so I am going to close. Can reopen in the future if there is a wider need.
