### ISSUE TITLE
Dark skeleton

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-design#1032]
Cloud.redhat.com is using skeletons in dark background, they are not really visible and are a bit off. 

@epwinchell came up with a sollution to show different gradient. However I think others might benefit from this as well and we should backport it to PF styles.

**Comment by mcarrano** [comment]
Thanks for filing this issue @karelhala. We are currently investigating a more global solution for dark theme so we rather handle this within that context. Sounds like you have a short term solution here? Therefore I am going to close.

**Comment by epwinchell** [comment]
@mcarrano We came up with a custom solution for the Console Landing page, using some transparency when rendering over a background image: https://github.com/RedHatInsights/landing-page-frontend/pull/251 Thanks.

![Screen Shot 2021-05-06 at 11 33 54 AM](https://user-images.githubusercontent.com/1287144/117325719-fc6b9580-ae5e-11eb-991c-b606df40cf46.png)
