### ISSUE TITLE
[Existing icon addition] Add eye and eye slash icons 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design#1036]
I'm working on a template file that includes an eye and eye slash icon. These icons have been used in a [Login page (React)](https://www.patternfly.org/v4/components/login-page/react/showhide-password/). And I need to get these two icons to PF icons set and Sketch library so that designer can easily use these icons that represent showing/hiding passwords. Both icons are available in Fontawesome ([eye icon](https://fontawesome.com/icons/eye?style=solid) and [eye slash icon](https://fontawesome.com/icons/eye-slash?style=solid)) 

Type of the icon: Object

**Comment by evwilkin** [comment]
Opened related Org issue https://github.com/patternfly/patternfly-org/issues/2461 to implement this change.

**Comment by bdellasc** [comment]
Should the icons be categorized as "Framework", not "Object"? Much like a dropdown arrow, ellipses, etc they're clickable and have an interaction associated with them? Sorry, I didn't catch this earlier. 

@mcarrano @evwilkin @doruskova @mceledonia

**Comment by mcarrano** [comment]
@bdellasc perhaps we should use "hidden" vs "obscured" in the proposed usage? I think that's a word that people will be more likely to search on. Agree that "Framework" makes more sense for the category.

**Comment by bdellasc** [comment]
@mcarrano - fine by me. I'll change the suggestion above to reflect that. Thanks!

**Comment by doruskova** [comment]
@mcarrano @bdellasc Framework works for me too. I'll update it in Sketch.
