### ISSUE TITLE
Secondary actions dropdown

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#1038]
We have come across a few different use cases in OpenShift, OCM and ACM where a secondary version of the `primary toggle` we have today would be useful. Mostly for the cases where we have a primary action on the page and multiple secondary buttons, where one may contain multiple actions.

I added my example we have in OCM that has to do with adding identity providers. I also attached the design that takes the same styling as our secondary button does today... but uses the same shape as the primary toggle.

![secondary-dropdown](https://user-images.githubusercontent.com/30870144/116620069-52948200-a90f-11eb-9df3-17bc7dc82399.png)

OCM example

![secondary-dropdown-1](https://user-images.githubusercontent.com/30870144/116619992-3690e080-a90f-11eb-82e8-d974feda904b.png)
![secondary-dropdown-2](https://user-images.githubusercontent.com/30870144/116619993-3690e080-a90f-11eb-8215-9b8d5cb2d249.png)

@bmignano I think this came up with your actions menu audit recently!

**Comment by mcarrano** [comment]
@gdoyle1 is there a reason you can't just use the default dropdown in these cases?

**Comment by gdoyle1** [comment]
@mcarrano I guess not really other than the default dropdown doesn't create the same visual hierarchy as the secondary buttons do so it isn't _as obvious_ that it's an action. I'm going to have them use a default dropdown for the time being though

**Comment by mcarrano** [comment]
That's probably a good plan for the short term. I'd be open to reconsidering Dropdown styling in general to conform more to button variants rather than just adding a new variant. Maybe something to consider as part of a larger visual refresh.

cc @mceledonia

**Comment by bmignano** [comment]
I did run into this with a design I was working on, although we don't know that we will actually use it at this point. But, hypothetically if we were to have two action dropdowns and want one to be primary and one secondary, it does feel weird that the primary dropdown styling and actions dropdown styling are so different. I agree with Gina that they don't provide the same visual hierarchy that a secondary dropdown styling would.

![Artboard](https://user-images.githubusercontent.com/40238481/116703100-deea8780-a997-11eb-9d89-d13efa64efda.png)

I do think it's use case based though and hesitate to update dropdown styling in general just to match this case. For example, I don't think the secondary dropdown styling that Gina is proposing would work well in a form.

**Comment by gdoyle1** [comment]
Andrew had an additional use case for this: https://marvelapp.com/prototype/8592c3a/screen/79048227

**Comment by andrew-ronaldson** [comment]
My example is using expandable field groups with secondary buttons. In this particular case a secondary toggle would generate a new section of the form based on the selected dropdown option. 
 
<img width="1039" alt="Screen Shot 2021-05-05 at 12 03 33 PM" src="https://user-images.githubusercontent.com/28658548/117177006-ea2e2080-ada6-11eb-8486-75e50a5b9e02.png">

**Comment by mcarrano** [comment]
Let's consider updating the default dropdown style as part of our more global visual refresh.

**Comment by andrew-ronaldson** [comment]
This styling for the secondary actions dropdown is being used in console today for Network policies. Can this be brought up at the next sprint @mcarrano ?
