### ISSUE TITLE
Would like option to use grey in charts

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design#1046]
I have a couple charts in the Insights for RHEL compliance application on cloud.redhat.com, which are meant to show the overall completion of something.
With the existing charts, we cannot change the color of the light blue to grey (as designed). The grey better represents that this is an incomplete amount than the light blue.

![image](https://user-images.githubusercontent.com/23172038/116618911-b9b13700-a90d-11eb-9474-9e23d3e4e901.png)

**Comment by mcarrano** [comment]
@katierik there are really two separate issues here so let me address them both. 

First regarding the donut chart shown in your comment above, I believe you can pass in custom color values for the segments. If there are questions about how to do this @dlabrecq should be able to help. You might also consider whether the [Donut Utilization Chart](https://www.patternfly.org/v4/charts/donut-utilization-chart) is more appropriate for this use case.

Regarding a change to the background color in the Progress component, while I see your point about using a gray background here, I am reluctant to make a global change at this time. But I can add this as something to consider for the visual refresh we are planning for a future date. In the mean time, I'd support the idea of customizing this to replace the light blue background with something from our gray palette. @mcoker can you advise on the way to do this? I think your developer should be able to update this by overriding the appropriate CSS variable.

**Comment by dlabrecq** [comment]
There are multiple ways to provide your own custom colors, in addition to the existing color themes. For example, the donut chart has a `colorScale` property. You can also specify colors via `style` props. You can even create a custom theme with your own color scales.

You can find multiple examples here http://patternfly-react.surge.sh/charts/themed-charts#custom-colors

**Comment by mcoker** [comment]
Hi @katierik to change the background color, you just need to define these 2 variables, and you can replace the colors with the ones appropriate for your design.

* `--pf-c-progress__bar--before--BackgroundColor: var(--pf-global--BackgroundColor--200);` - the base/grey color
* `--pf-c-progress__indicator--BackgroundColor: var(--pf-global--primary-color--100);` - the progress status fill color
* `--pf-c-progress__bar--before--Opacity: 1;`

I created a demo here - https://codesandbox.io/s/jolly-cache-rw2ke?file=/style.css

**Comment by katierik** [comment]
@mcoker Thank you for the demo! I'm going to pass this on to my dev team.

**Comment by mcarrano** [comment]
@katierik can I close this one out? Is there anything else you need from a PatternFly perspective?

**Comment by mcarrano** [comment]
Closing. We can reopen if there are still issues for PatternFly to address.
