### ISSUE TITLE
Change to cancel button makes it look misaligned

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design#1050]
The current placement of the cancel button in wizards is strange. It is not a consistent distance from the other buttons and appears misaligned.
![image](https://user-images.githubusercontent.com/23172038/119145999-2fde2080-ba18-11eb-84b5-6432a0439b79.png)

As per this discussion in patternfly slack (https://patternfly.slack.com/archives/CGR204RM2/p1620153087090100) this was an intentional change to make the cancel button more difficult to click by accident

I would like to suggest either aligning it back to where it was, or aligning it to the right corner.
![image](https://user-images.githubusercontent.com/23172038/119146783-f954d580-ba18-11eb-9151-9a3e597616f7.png)
![image](https://user-images.githubusercontent.com/23172038/119146824-040f6a80-ba19-11eb-98df-0c1f9a1d1a89.png)

Related jira: https://issues.redhat.com/browse/RHICOMPL-1819

**Comment by mcarrano** [comment]
Here is the original issue that drove the change to the current spacing: https://github.com/patternfly/patternfly/issues/1894

**Comment by katierik** [comment]
The original issue is interesting, as the key problem seems to be "The click area of the cancel button is larger than it visually appears, causing possible user error."
Instead of moving the cancel button an arbitrary space away, this could have also been solved by reducing the click area of "Cancel". Or moving it to another anchoring point (such as the right corner, as shown above).

**Comment by mcarrano** [comment]
I would be reluctant to change the click area since that would be a global change affecting everything that's a link-style button. We could consider changing the style to a secondary button to make the boundaries more obvious. Frankly, the current alignment has never bothered me @katierik . Is this something you had gotten feedback on from testing? I'm willing to revisit prior decisions, but only if we have evidence of a problem.

**Comment by katierik** [comment]
I have not gotten user feedback on this specifically, it is something logged as a bug internally.

**Comment by mcarrano** [comment]
This is not something I'm willing to address at present. But we can revisit this again if it continues to come up.
