### ISSUE TITLE
Breadcrumb switcher

### ISSUE THREAD

**Issue by MariSvirik** [patternfly/patternfly-design#1054]
For a redesign of Satellite/Foreman moving from PF3 to PF4 we need a breadcrumb switcher which is currently a [the component in PF3 ](http://foreman-storybook.surge.sh/?path=/story/components-breadcrumbbar--with-open-switcher) but not in PF4.
This component is used almost everywhere within the product and we would like to have it in PF4 for the next release that's coming in 5 months.

Current implementation in Satellite
<img width="594" alt="Screenshot 2021-06-01 at 16 12 41" src="https://user-images.githubusercontent.com/51960547/120338237-56436c00-c2f4-11eb-918a-b19ccdc117de.png">

**Comment by mcarrano** [comment]
@MariSvirik this was a component that existed in PatternFly 3 that we chose not to port over to PatternFly 4. This could pretty easily be built using existing components by placing a button either in the end node of the breadcrumb or immediately following the breadcrumb and use that to open a menu using the new composable Menu component: https://www.patternfly.org/v4/components/menu#filtering-with-text-input

@beanh66 I seem to recall that you worked on the in PF3 days for use in OpenShift, is that right? Do you know if OpenShift still uses this pattern or did they move away from it?

**Comment by MariSvirik** [comment]
@mcarrano Thank you, Matt. Sorry for bothering you, but can I use this design? 
I'm talking mainly about embedded pagination.
<img width="484" alt="Screenshot 2021-06-11 at 14 06 52" src="https://user-images.githubusercontent.com/51960547/121685550-5bf13c80-cac0-11eb-9cab-b631161def01.png">

It's currently used. The number of items can be huge and an endless scroll or 'View more' version wouldn't work

Example 1
<img width="528" alt="Screenshot 2021-06-11 at 14 23 30" src="https://user-images.githubusercontent.com/51960547/121685803-aecaf400-cac0-11eb-9c04-ab67a6a8dd8e.png">

Example 2
<img width="373" alt="Screenshot 2021-06-11 at 14 22 58" src="https://user-images.githubusercontent.com/51960547/121685808-af638a80-cac0-11eb-95a0-a9856729d120.png">

**Comment by mcarrano** [comment]
Yes, you can make that using the Menu component and placing a Pagination component in the footer. I made that here:

![Screen Shot 2021-06-11 at 2 10 35 PM](https://user-images.githubusercontent.com/6619860/121731452-f3ee2680-cabe-11eb-9d63-41b62dbc4582.png)

Here's the code for that:

`<Menu activeItemId={activeItem} onSelect={this.onSelect}>
        <MenuContent>
          <MenuList>
            <MenuItem itemId={0}>Action</MenuItem>
            <MenuItem
              itemId={1}
              to="#default-link2"
              // just for demo so that navigation is not triggered
              onClick={event => event.preventDefault()}
            >
              Link
            </MenuItem>
            <MenuItem isDisabled>Disabled Action</MenuItem>
            <MenuItem isDisabled to="#default-link4">
              Disabled Link
            </MenuItem>
          </MenuList>
        </MenuContent>
        <MenuFooter>
          <Pagination
        variant={PaginationVariant.bottom}
        itemCount={523}
        perPage={this.state.perPage}
        page={this.state.page}
        onSetPage={this.onSetPage}
        widgetId="pagination-options-menu-top"
        onPerPageSelect={this.onPerPageSelect}
        isCompact
      />
        </MenuFooter>
      </Menu>`

**Comment by mcarrano** [comment]
@MariSvirik will the above work for Satellite? Let me know if we need to discuss further, but I'm hoping that we can somehow solve this using existing components.

**Comment by MariSvirik** [comment]
@mcarrano I think it will work and there is no need for further discussion. The assigned dev plans to tackle this issue in the very near future.

**Comment by mcarrano** [comment]
Looks like we are all set then. I will close, but let me know if you have more questions.
