### ISSUE TITLE
Resolve icons to use for Helper Text component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1062]
A new Helper text component was added that supports dynamic field validation per [this design](https://marvelapp.com/prototype/6jehce7/screen/78511266) but also existing use cases for field validation as in the Form component. During implementation, we noticed that different icons are being used for error and success states. Seems like these should all be consistent. Here's what this currently looks like:

Static
![Screen Shot 2021-06-18 at 5 00 01 PM](https://user-images.githubusercontent.com/6619860/122615564-bb1df680-d056-11eb-85f2-ab41a255b6c2.png)

Dynamic
![Screen Shot 2021-06-18 at 5 00 13 PM](https://user-images.githubusercontent.com/6619860/122615590-c3763180-d056-11eb-8c79-9f11999d7aad.png)

We made them all consistent for now but should review these to identify a consistent set to use for all field level help text elements (static or dynamic).

**Comment by mcarrano** [comment]
@doruskova can you take a look at this issue? It was raised during implementation of the new helper text. We can discuss more when we meet on Friday.

**Comment by doruskova** [comment]
@mcarrano Yeah, I'll take a look at it. Do you have a link to the PR with the implementation so that I can take a look?

**Comment by mcarrano** [comment]
It was just released this week. Take a look here: https://www.patternfly.org/v4/components/helper-text

**Comment by doruskova** [comment]
@mcarrano I've updated mocks for a feedback session. https://marvelapp.com/prototype/6jehce7/screen/80602884
I used "static" icons only for our password strength meter to keep consistent visual elements. There are two versions

- Version 1 - it's my preference. Just change icons and the text is grey
- Version 2 - used colorful helper text. However, I think it's too much and the text should be grey. The main message get lost IMHO.

**Comment by mcarrano** [comment]
Thanks @doruskova . I do agree with you about the colored text. So right now we do support red text for simple form validation errors (https://www.patternfly.org/v4/components/form/html). I don't think we would change that. I think we could handle this a couple of ways:

* Make the text coloring optional and provide design guidance on when to use it.
* Keep the same structure of the component as we have now with static helper text that takes the color and "dynamic" that only has an icon. While that seems like an odd distinction, it works.

In any case, having the consistent icons makes sense. @mcoker @mceledonia what do you think?

**Comment by doruskova** [comment]
@mcarrano Absolutely agree!

**Comment by mcoker** [comment]
@mcarrano sounds good to me!

**Comment by mcarrano** [comment]
I've opened https://github.com/patternfly/patternfly/issues/4205 for core implementation. Thanks @doruskova
