### ISSUE TITLE
Allow multiple files upload in FileUpload component 

### ISSUE THREAD

**Issue by shirimordechay** [patternfly/patternfly-design#1064]
Currently, the FileUpload component allows only a single file upload. a multiple file uploader is needed for several use cases and probably would be beneficial to many more. for example, a user/ SRE reporting a bug in OCM/ OpenShift will be required to upload a number of files such as logs, screenshots, .etc.). this cannot be completed by using the current FileUpload component. 

**The design enhancement should include:** 
* Browse/ drag and drop multiple files 
* Show each upload progress 
* Show an option to cancel/ clear an upload
* Show general progress for all uploads 
* Handle errors/ upload failures for each file
* Collapse/ expand (or hide/ show) all uploads 

**Suggested design:** 
Drag and drop number of files indication

![Drag and drop](https://user-images.githubusercontent.com/10331355/123543919-834f3700-d759-11eb-8edc-e82237f450ba.png)

Indication for each upload with a cancel option

![Loading](https://user-images.githubusercontent.com/10331355/123543923-84806400-d759-11eb-84b9-64429063f2ec.png)

Collapsable suggestion

![Loading collapsed](https://user-images.githubusercontent.com/10331355/123543921-84806400-d759-11eb-822c-1222db6b39e0.png)

**Comment by mcarrano** [comment]
@shirimordechay thanks for creating this issue. I will get it on the roadmap. Do you have any requirements around timing/availability? Right now I am scheduling into Q4.

**Comment by shirimordechay** [comment]
I think Q4 should be fine! thank you @mcarrano

**Comment by cgrayes** [comment]
Here is the latest proposal that I will iterate on.
[Multiple File Upload - High Fi.pdf](https://github.com/patternfly/patternfly-design/files/7137326/Multiple.File.Upload.-.High.Fi.pdf)

**Comment by cgrayes** [comment]
The latest high-fi design
[Multiple File Upload - 9-29-2021pdf.pdf](https://github.com/patternfly/patternfly-design/files/7252417/Multiple.File.Upload.-.9-29-2021pdf.pdf)
.

**Comment by lboehling** [comment]
Hi @cgrayes! Thanks for sharing these designs at the PF design share. These are looking great! I have a couple small visual suggestions I wanted to mention on the call, but didn’t want to take too much time. 

1. We don’t show the blue border in the collapsed states for accordion or expandable data list rows, so I think we should be consistent and not show it in the collapsed state here either.
2. Are these designs using the small progress bar? If not, I would consider trying the small progress bar instead of standard — I think it will free up a lot of space and and give the text/icons more room to breathe.

**Comment by cgrayes** [comment]
Thanks @lboehling I will take a look and make the changes.

**Comment by megan-hall** [comment]
Final marvel prototype: https://marvelapp.com/prototype/69jc198

**Comment by mcarrano** [comment]
@doruskova @mmenestr This is currently in implementation. See the final design linked above. Seems like we should have this in the Sketch template and we will need docs. Can you open related issues and link them here?

@megan-hall would you be willing to create design documentation?

**Comment by doruskova** [comment]
@mcarrano Yes! Here's the Design kit issue https://github.com/patternfly/patternfly-design/issues/1064
@megan-hall Could you send me a sketch file so that I can add it to our template file? Thank you!

**Comment by megan-hall** [comment]
@doruskova Here is a link to the sketch file: https://sketch.com/s/55446f68-c5d0-4845-94dc-6d8385e3f523

@mcarrano No problem - happy to help with design documentation.
