### ISSUE TITLE
Add blog highlights to website home page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1069]
I've long felt that while our home page looks good visually, it does not really convey that much useful information - or maybe at least my take from looking at it so often. I wonder if we can/should use this space to expose some of the content we post in our Medium blog, training tutorials, and/or similar content. I think some of the existing static content could be moved to an About or Get Started page to make room. The "Flyer Fundamentals" for example are nice, but I doubt many visitors to the site really take the time to read and consider those.

If we choose to do this, not sure what the mechanics would be for exposing that content and keeping it up to date, but wanted to just throw this idea out there to see if you all think it's something we might pursue.

**Comment by maryshak1996** [comment]
On hold due to larger IA changes in progress that could effect the homepage, but here is my work in progress file: https://www.sketch.com/s/8c0acc28-9136-46ad-bcff-13cd5f861231

**Comment by mcarrano** [comment]
I guessing we can close this given that the blog feed has been incorporated in the new homepage designs. @lboehling do you agree?  But I appreciate the work you did on this @maryshak1996 !

**Comment by lboehling** [comment]
yes, i agree. thank you @mcarrano and @maryshak1996!
