### ISSUE TITLE
New Pattern: Non-actionable card

### ISSUE THREAD

**Issue by kywalker-rh** [patternfly/patternfly-design#1072]
## Requesting new features, enhancements, or design changes to PatternFly 
- We have the need to show a card that cannot be clicked within a catalog primary-detail view.
- Currently the cards are only selectable or actionable, but for our use case we want to show cards that preview future features, but aren't currently actionable.
- This is currently being used in RHODS. This is a proposal to get the pattern already in use into Patternfly.
- Marvel showing proposal: https://marvelapp.com/prototype/6765ag3

Visual spec:

**On gray background**
- Card fill: $pf-color-black-100
- Border: None
- Outer Shadow: None
- Inner Shadow: Y axis 4px, $pf-color-black-300

**On white background**
- Card fill: $pf-color-black-100
- Border: 1px, $pf-color-black-300
- Outer Shadow: None
- Inner Shadow: Y axis 4px, $pf-color-black-300

There are no visual changes for `hover` or `select`, since the card, by definition, cannot be interacted with.

**Comment by mcarrano** [comment]
@mceledonia this issue was raised in today's PF design share by @kywalker-rh. It seems like we should consider this as part of the restyling for selected cards and tiles. So a card/time would have the following states available: normal, hover, selected, and disabled (or unavailable).

**Comment by kywalker-rh** [comment]
@mceledonia I added a visual spec into the description above, and also added it to the Marvel. If you need more info please let me know.

**Comment by mcarrano** [comment]
Thanks @kywalker-rh and @mceledonia . I am going to close this out and will open a new core issue to pass along to development.

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/4359 to begin development. Will close this design issue. Thanks @mceledonia @kywalker-rh.
