### ISSUE TITLE
Editable label affordance

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1073]
A new editable label group is being introduced in release 2021.10. A preview can be seen here: https://patternfly-react-pr-6065.surge.sh/components/label-group  It was pointed out that there is currently no affordance to indicate when a label is editable or not. Should there be? If so, what would that look like?

**Comment by imjoyjean** [comment]
@mcarrano and I were discussing the [Auto-complete input](https://docs.google.com/document/d/11U-lJ6B7l6uGPW6A-lgteFREY874mzBhy1LxHZfNQb8/edit#) for search and editing labels. The suggestion was to include the behavior of autocomplete for inputting and editing labels in this issue. 

Specifically in context of ACM and OCP, this modal is used to add labels, and can we provide an interaction there for labels to autocomplete when they're being typed or edited?
![image](https://user-images.githubusercontent.com/57908474/130264484-726b8706-0e13-4226-bec8-10a5cf2f5da9.png)

**Comment by gonoraj** [comment]
Hi @mcarrano @imjoyjean ! I put together [this doc](https://docs.google.com/document/d/1OZfDXRqbc9Y5d1gWhXVhv2I1z_MI1z5PdobNbyfSVKw/edit?usp=sharing) with options for editable label affordances and auto-complete behavior. 

A brief summary is: 
- 2 possible solutions for affordances, although styling might still need adjustments
- Designs for auto-completing a new label, and for editing a label. There are a few styling options as well (I tried to note them in the doc, but feel free to leave comments if it's unclear!)

**Comment by gonoraj** [comment]
Updated designs for this with the added dashed underline are in [this document](https://docs.google.com/document/d/1ReoW10DzrrWxdAnzwuXbeTMdGXpFfiIAE9JHu-43o4U/edit?usp=sharing) as well as in the image below
![editable-labels](https://user-images.githubusercontent.com/33614237/144122323-0dd11875-a886-47cc-a298-fc419df79cd9.jpg)

**Comment by mcarrano** [comment]
This looks good @gonoraj . Just a couple small nits...

1. It feels like to me the underline should only extend to the end of the text label and not fill the gap between the label and the close button. Did you have a reason for extending that line?

2. While implementing this, @srambach pointed out that the spacing between the text and the underline is smaller than in other places where we use this approach. @mceledonia @srambach do you know what this spacing should be for consistency?

**Comment by mmenestr** [comment]
Opened design guideline issue to address this here: https://app.zenhub.com/workspaces/design-doc-workspace-5f08c64d6a6ef2001d56a458/issues/patternfly/patternfly-org/2822

**Comment by doruskova** [comment]
Opened design kit issue https://github.com/patternfly/patternfly-design-kit/issues/496
