### ISSUE TITLE
Allow set size for Avatar

### ISSUE THREAD

**Issue by kunyan** [patternfly/patternfly-design#1076]
**Describe the issue. What is the expected and unexpected behavior?**

The `Avatar` component should be able to support set size for it.

* sm
* md
* lg
* xl

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

**Comment by mcarrano** [comment]
Consider whether we should support a `height` and `width` prop for the React component. If we decide to support fixed sizing, need to determine what those would be.

**Comment by ajacobs21e** [comment]
Here are two places I'm using the avatar at larger sizes:
Profile - 134px diameter in this example
https://marvelapp.com/prototype/7597af3/screen/81391914

User menu - 64px here
https://marvelapp.com/prototype/7597af3/screen/81391915

**Comment by mcarrano** [comment]
Thanks for posting these @ajacobs21e .

@mceledonia @mcoker Do you think it would be useful to have some set sizes. Based on the usage I'm seeing, perhaps a sm, med, and large where small is for masthead use and then medium and large based on Allie's mocks. The advantage is that this would encourage consistent sizing.

@kunyan Would these sizes work for you? Did you have uses for an avatar that differ from this?

**Comment by mcoker** [comment]
> The advantage is that this would encourage consistent sizing.

@mcarrano agree, sounds good to me.

**Comment by kunyan** [comment]
@mcarrano LGTM

**Comment by mcarrano** [comment]
I will add this to the PatternFly roadmap. Currently planning into Q1 2022.

**Comment by mcarrano** [comment]
Thanks @mceledonia ! 

@mcoker Do you see any issues? If not, I will open a core issue to queue this up for implementation.

**Comment by mcoker** [comment]
@mcarrano LGTM!

**Comment by mcarrano** [comment]
Note that in the course of implementation we modified the supported sizes so the smallest is 24px and the largest in 128px. We found that 16px was too small to be useful. So final sizes are:

--sm 24px
--md 36px
--lg 72px
--xl 128px

With `md` being the default.

cc @mmenestr @doruskova for sketch kit and documentation follow-up

**Comment by mmenestr** [comment]
design guidelines issue: https://app.zenhub.com/workspaces/design-doc-workspace-5f08c64d6a6ef2001d56a458/issues/patternfly/patternfly-org/2847

**Comment by doruskova** [comment]
design kit issue: https://github.com/patternfly/patternfly-design-kit/issues/509
