### ISSUE TITLE
Interaction design for drag and drop

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-design#1077]
React needs drag and drop interaction design and colors. The implementation will use [react-beautiful-dnd](https://react-beautiful-dnd.netlify.app/?path=/story/*) or a partial implementation of it.

## Draggable area
Should we default to only allowing a toggle button to drag, or anything on the item?

Option A
![image](https://user-images.githubusercontent.com/47335686/128082309-eaa9d71f-2a38-4945-9600-cbe1def3bf5d.png)

Option B
![image](https://user-images.githubusercontent.com/47335686/128082354-aa839893-4d58-4163-9942-932478d341e5.png)

## Dragging item

What should an item look like when dragging? Keep in mind that it may be ANY component.
![image](https://user-images.githubusercontent.com/47335686/128082751-5cee73cf-23f6-46c1-8799-068697e23493.png)

Should there be any special styling for an item over an undroppable zone (like above?)

## Droppable zone

![image](https://user-images.githubusercontent.com/47335686/128084840-31054d38-7548-4cf1-8865-43bc876da689.png)

Since there can be any content in the droppable zone this may present a color problem.

### Reordering

Should we eliminate ghost row styling and just leave a blank spot in the list?

## Scrolling

Should dragging the item up/down scroll the page? When should the scrolling start?
![drag-scroll](https://user-images.githubusercontent.com/47335686/128085518-c0b4ddb5-0e2c-4612-8ea2-b332cb025618.gif)

## Animation
Any?

**Comment by andrew-ronaldson** [comment]
@mceledonia @mcarrano Here are some of the design options I am working on. https://marvelapp.com/prototype/h198be4/screen/81623894

**Comment by redallen** [comment]
See https://github.com/patternfly/patternfly-react/pull/6258 .

**Comment by mmenestr** [comment]
Design doc issue: https://app.zenhub.com/workspaces/design-doc-workspace-5f08c64d6a6ef2001d56a458/issues/patternfly/patternfly-org/2459
