### ISSUE TITLE
Consider refining/tightening use cases for tooltip and popover

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-design#1081]
@mcarrano 

I think everyone is aware of the tooltip vs popover confusion we run into every now and then which has led to discussions around expanding the functionality of either the tooltip or popover component.

 I’m wondering if an easy solution to this is to bring the tooltip back to its roots and restrict it to essentially being a “tool tip” - pretty much a description or label of an icon action. For example the icon actions on a toolbar or in a data table. Examples of these elsewhere would be the google docs icons as well as the google meet controls in the bottom/center. 

<img width="199" alt="image" src="https://user-images.githubusercontent.com/30935938/128723237-d68a8566-3f4f-42d7-92a7-1763b32b2e47.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/30935938/128723278-7c81fe95-4058-4ef5-9b31-efe950a06997.png">

These are by-name "tool tips" and thus make the most sense for this use case. 

Anything that requires some kind of explanation or additional information would be a popover, and this would help ease the tension of allowing multiple popover triggers - click or hover, whichever makes more sense for the context. Example of this where we currently use a tooltip would be the info icon in forms. Since it is an explanation or additional information rather than simply a label on an action, it would get a popover. The hover-triggered popover can work as a tooltip does now, and the click-triggered popover can work as it currently does. 

Since there is no ambiguity here in terms of use cases, we aren't relying on the interaction to be the defining feature of the component (hover = tooltip, click = popover). This allows us to be more flexible in what interactions they both use, since they are now more clearly defined by their use cases.

This sort of minimizes the tool tip component use cases and magnifies the popover use cases, but I think that actually makes sense, since the popover is designed to handle larger amounts of information and actions. It scales well, from simply a description and no actions to something that needs a title/description and multiple actions. 

Ultimately this avoids situations where we would currently recommend a tooltip but more functionality is needed, and creates a clear distinction between the use cases for tooltips and popovers where there is currently some ambiguity.

Worth noting that this is very close to what we currently recommend for both components. It is more a proposal to "tighten up" and remove any ambiguity that currently exists between the two. Really restricting the tooltip to being labels of actions like seen in the examples above, and popovers for anything else. In other words, if the information displayed isn't a "tip of the tool" being interacted with, it qualifies for popover.

**Comment by sunilmalagi** [comment]
Hi Michael and Matt, I have adjusted spacing around the tooltip and popover.  Here is the marvel link with couple of variations.  Please let me know if you have any feedback:
https://marvelapp.com/prototype/ch6id28

**Comment by mcarrano** [comment]
@sunilmalagi Thanks for posting these. I definitely think think the tighter spacing looks better. Do you have a preference for 24px or 16px spacing? My opinion is that the 16 px spacing looks fine for popover but maybe a little tight for the tooltip? @mceledonia what do you think?

**Comment by sunilmalagi** [comment]
@mcarrano Thank you for your feedback.  I agree with you 16px padding for both Popover and Tooltip, I think you are looking at 8px padding for the tool tip (which looks little tight..)

**Comment by mcarrano** [comment]
@doruskova This issue tightens the spacing for tooltips and popovers a bit. We should make corresponding changes to the Sketch kit. Can you open an issue? @sunilmalagi perhaps you can make those updates? Thanks.

**Comment by doruskova** [comment]
@mcarrano Opened an issue and tagged @sunilmalagi if she wants to make an update :)
