### ISSUE TITLE
Pagination for unknown page count

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-design#1084]
Paginated endpoints may sometimes utilize a cursor-based pagination to optimize for performance or simply not show the total count or total pages. While this is good for improving performance, it means we have no way of knowing how many pages there will be

This poses an issue for the current PF pagination, as all the designs and the React implementation requires count to work properly

One design I have in mind could remove the total count of entries, and change number of pages to "many":
![image](https://user-images.githubusercontent.com/6598829/130067498-13141823-1819-4395-8c4f-73ec9c2c34ab.png)

Which for compact looks like this:
![image](https://user-images.githubusercontent.com/6598829/130067689-409cd8f7-4bcc-4c0b-9c30-cbc3dff41ecb.png)

**Comment by mcarrano** [comment]
@SpyTec A similar issue was raised here: https://github.com/patternfly/patternfly-design/issues/1025 See the discussion. Changing the total page count to "many" is an interesting idea we had not thought of. 

cc @doruskova

**Comment by mcarrano** [comment]
@SpyTec I am going to close this issue in favor of #1025 that is already on our roadmap. We will go with your solution to substitute the word "many" when the exact number of pages is not known.
