### ISSUE TITLE
Support for country level phone formatting

### ISSUE THREAD

**Issue by jknilans** [patternfly/patternfly-design#1086]
**Describe the use cases and requirements of the new feature or enhancement you are requesting.**
- This component can be used anywhere where users will need to either provide or read a phone number in a way that allows for quick recall and recognition.
- This feature will convert phone numbers from a generic number, e.g. 8662733428 into a country-specific format, e.g. +1 (866) 273-3428 automatically for users.
- It will most likely utilize a [3rd party React library](https://gitlab.com/catamphetamine/react-phone-number-input) for the country specific formatting. 

**Explain *why* this feature is needed and/or why these requirements cannot be met using existing components.**
- Formatting phone numbers aids recall and scalability for users. Being able to display a phone number appropriately for a given country will aid users in being able to recognize a phone number, and may also provide an idea of the basic time zone/normal working hours if they intend to call the number.

**If this is for specific applications, list them here along with any dates that you need this for.**
- This component would be used in the [Red Hat Ecosystem Catalog](https://catalog.redhat.com), [Red Hat Partner Connect](https://connect.redhat.com), and most likely on the new Red Hat Account application and sign up workflow. We have an open JIRA to add this functionality currently and would like to wrap it up as soon as possible.

**Link any detailed design documents, rough sketches, wireframes or workflows.**
- Wireframe: https://marvelapp.com/prototype/2b20gj46/screen/81440046
- 3rd party code: https://gitlab.com/catamphetamine/react-phone-number-input
- Demo from 3rd party code: https://catamphetamine.gitlab.io/react-phone-number-input/

**State whether this is a new feature or an enhancement on an existing pattern by labeling it accordingly**
- This would be enhancing two existing components to create a new one

**If this is an enhancement to an existing feature, identify the feature that you want to modify.**
- [Select component](https://www.patternfly.org/v4/components/select/design-guidelines)
- [Form](https://www.patternfly.org/v4/components/form)

**Comment by nicolethoen** [comment]
I believe that this could already be accomplished as drawn up in the marvel wireframe using a MenuToggle + Menu + third party data source to build the country dropdown, and possibly a TextInput + country specific formatting/validation to build the input.

**Comment by mcarrano** [comment]
@jknilans Sorry to take so long to get back to you on this request. We are trying to limit bundling of 3rd party libraries into PatternFly and don't feel like this is something we should support directly. I'm wondering if this is something that would be more appropriate as a PatternFly extension. If you have existing code for this built on top of core PatternFly components, perhaps it can be shared as a community extension (see https://www.patternfly.org/v4/extensions/community-extensions) or this could be part of a UXD supported extension for capturing user level information in the end to end workflow. Let me know your thoughts.

**Comment by mcarrano** [comment]
Per the comment above, I'm going to close this out. We can always reopen this discussion in the future if needed @jknilans .
