### ISSUE TITLE
List View: Example in Overview page is too wide to fit container 

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#109]
The example used in the Overview page for List View is too wide to fit in the page template and therefor wraps.  It therefore looks different when opened in a separate window.

Recommendation:  Redesign the example so it fits.

**Comment by yih-wang** [comment]
@mcarrano I went over the Overview page of List View (http://www.patternfly.org/pattern-library/content-views/list-view/) but haven't detected the bug. Can you please check if the issue still exists. If so, I can fix it.

**Comment by mcarrano** [comment]
@yih-wang I think what this is referring to is the fact that the example at the top of the Overview page shows what the list view will look like when it wraps because it's too wide to fit the container. But if you click the link to view the full page example, you'll actually see that all the elements are inline. You'll also see that the examples below look different. That was the confusion when some people looked at this.

We could replace the static mockup with something that can fit in the page without wrapping. @LHinson what do you think? Should we update this with a new example?
