### ISSUE TITLE
Consider how we could retire component demos on PF.org

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-design#1098]
Currently, when we want to demonstrate a component's use in some relevant context or demonstrate a components possible relationship to a different component, we build a `demo`. 
Often enough, `demos` are the way we'd be inclined to highlight the implementation of more complex feature requests.

Our `examples` for each component are intended to be a simple way to demonstrate the various states and styling of the component which the consumer can control by changing props or applied classes. Any demonstration that would need to use multiple components, are usually considered too complex for an `example`.

More recently, when we implement complex feature requests, there has been push back or hesitancy expressed regarding to adding the implementation to the docs under `demos`. The hesitancy stems from an increased awareness that users are just not looking under demos often enough to find the features.

I wonder if there could be a way to retire the component demos and create a new way to present complex feature requests or solutions we build using multiple components.

**Comment by mcarrano** [comment]
@nicolethoen do you feel like the recent website IA restructuring proposal addresses this or does this issue call for a more fundamental look at demos and why we need them?

**Comment by nicolethoen** [comment]
@mcarrano I think we have addressed this :)

**Comment by mcarrano** [comment]
Great. Will close then.
