### ISSUE TITLE
List View/Card View: Drill-down behavior needs clarification

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#110]
Existing documentation is not clear about how to handle drill-down if multiple elements within a list item or card are linked.  Current guidance that a single click on a list or card item should drill down to the next level may not be sufficient for all use cases.  

Recommendation:  Consider cases where there may be multiple drill-down links and how one should handle this case vs. single drill-down link.

**Comment by LHinson** [comment]
For reference, here are the links to the two patterns being referred to in this issue. 
List view: http://www.patternfly.org/pattern-library/content-views/list-view/#/api
Card view: http://www.patternfly.org/pattern-library/content-views/card-view/#/api

**Comment by LHinson** [comment]
Multiple drill downs can be supported by including links, buttons, icons. 

Under the standard view, we said: 
"If drill down behavior is supported, clicking on an item will link to the appropriate page."

Under the expansion example, it says: 
Interaction
"Hovering over a row highlights it. Single clicking anywhere in the row expands the row.
If the list supports both expansion and drill-down to details, a button or link must be added to the row to support the drill-down action."

@mcarrano will you clarify what additional details that you would expect?

**Comment by mcarrano** [comment]
This was an issue that was raised during the pattern audit.  It has nothing to do with expansion.  Basically a strict reading of this implies that there would only be a single drill down link from any row.  But what if you have multiple elements that are linked?  Just clicking on the row would be ambiguous in that case and I think we would need explicit actions or links within the row item.

I remember that this issue also came up with Card view.  

I think this may just need rewording to state that "when an item only has a single drill-down link, clicking on an item will link to the appropriate page, otherwise include multiple drill-down links within the body of an item."  Or something like that.

**Comment by mcarrano** [comment]
I've created a PF story for this as https://patternfly.atlassian.net/browse/PTNFLY-2610 and moving back to discovery queue as more requirements research is needed here.

**Comment by mcarrano** [comment]
I have marked this story as 'Help Wanted' in case anyone is interested in taking it on. As a first step, we should research and understand all relevant product use cases and requirements. Want to understand how we are supporting drill-down in product now, what are valid options, and make recommendations to guide designers towards consistent solutions.

FYI @catrobson @serenamarie125 @maryclarke  There is also a related PF story referenced above.
