### ISSUE TITLE
Include pagination to the Dual List Selector

### ISSUE THREAD

**Issue by nlcwong** [patternfly/patternfly-design#1101]
This is a request for enhancement to the dual list selector to include a way to paginate through a list of items on either list selectors.

Cost Management has encountered a severe performance issue (experience of the UI hanging for over a minute) with loading in excess of 40,000 items into the dual list selector.  We are hoping that having pagination as an added feature on the lists, this could help with dulling the long loading issue.

Even though this issue was found in our staging environment where we had an account with a very high number of items, we performed tests where even 1,000 would cause a loading time greater than the ideal 3 seconds and we do have two customer accounts that exceeds that 1k item threshold.

**Comment by mcarrano** [comment]
@nlcwong is this still an issue for you? If not, I'd like to close.

**Comment by nlcwong** [comment]
@mcarrano I need to consult with @dlabrecq one more time to understand if its a lost cause to pursue vs. finding another pattern to use instead.

**Comment by mcarrano** [comment]
@nlcwong @dlabrecq is there still an issue here or can we close this?

**Comment by nlcwong** [comment]
We can close this as I'm going to have to figure out an alternative component to use for my use case since there are too many constraints involved.  Thank you @mcarrano
