### ISSUE TITLE
Add table striped rows

### ISSUE THREAD

**Issue by Ron-Lavi** [patternfly/patternfly-design#1102]
In addition to the discussion about hovering: https://github.com/patternfly/patternfly-design/issues/923
are there any plans of adding table-striped where each second row has a greyed background?
something similar to https://community.theforeman.org/t/apply-table-pf4-classname-and-use-pf4-pagination/25640/5?u=laviro

just for an example I used here the CSS styles:
```css
tr:nth-child(even) {
  background-color: color;
}
```
![](https://community.theforeman.org/uploads/default/original/2X/f/f449ed35d4edcd20e26fbab3e23dc15b7c5c4489.png)

**Comment by sunilmalagi** [comment]
Hi @mcarrano @mceledonia ,
Here are the variations for stripped rows, I have reused to the existing table pages from PF and tried with couple of subtle color variations, there are existing screens at the beginning and followed by variations option 1, 2, 3 & 1A, 2A ,3A... let me know for any feedback if you have:

https://marvelapp.com/prototype/2ccbf976

Thank you

**Comment by mcarrano** [comment]
These looks great @sunilmalagi . I'm leaning towards the lightest gray variation as I think the others call too much attention to this. But I'll defer to @mceledonia on that. I see that you also considered expanded rows, but what happens if a highlighted row is expanded? Does the background color extend to the expansion or does the expanded panel remain white? Would be good to see what that looks like.

**Comment by sunilmalagi** [comment]
Thank you @mcarrano , I have included the screens with bg color applied for expanded rows.. please see the last 3 screens, and the expanded area remains white because it appears heavy if the entire area filled with any shades.

**Comment by mcarrano** [comment]
I agree. @mceledonia what are your thoughts?

**Comment by sunilmalagi** [comment]
Hi @mcarrano, here is the marvel link, https://marvelapp.com/prototype/2ccbf976.  Out of 3 different color variants, the team decided to go with "PF Black 100" for striped rows.  You can see 2 slides for the reference how the rows appear when you choose to go with "PF Black 100" for the alternative rows / expanded rows.

**Comment by mcarrano** [comment]
Excellent. Thanks @sunilmalagi !

**Comment by mcarrano** [comment]
@MariSvirik Please see the above Marvel link that contains a design proposal for optional striped rows in tables. Our current thinking is to utilize our lightest gray (Black-100) to keep this minimal. Let me know if you think this will meet your needs for Satellite.

**Comment by mcarrano** [comment]
@doruskova @mmenestr This should be added to the Sketch kit and design docs as a new feature for tables. Might be good to have some guidance on when to use this for tables.

**Comment by doruskova** [comment]
@mcarrano Issue for Sketch was created https://github.com/patternfly/patternfly-design-kit/issues/487

**Comment by mmenestr** [comment]
Design doc issue here: https://github.com/patternfly/patternfly-org/issues/2783
