### ISSUE TITLE
Show and hide password action in read-only form

### ISSUE THREAD

**Issue by nding-anges** [patternfly/patternfly-design#1117]
## Requesting new features, enhancements, or design changes to PatternFly 
-Currently, in our Managed Kafka connectors design, we need to provide show/hide password action in the review step of creating connector wizard, which is a form in read-only format and it gives the user a high-level preview of the property's configurations. But the password needs to be hidden by default and the user can click the Show button to display it.

As we didn't find any corresponding component in PF, we have made some design proposals and hoping to get more guidance and suggestion at this point. Thanks!
 Please find the designs below: 

<img width="664" alt="屏幕快照 2021-12-21 下午1 04 11" src="https://user-images.githubusercontent.com/34368385/146874407-2fadb03f-eb34-46d8-a23d-07635326f92d.png">

<img width="664" alt="屏幕快照 2021-12-21 下午1 04 36" src="https://user-images.githubusercontent.com/34368385/146874444-1af3fb75-7ef4-4ae7-bd36-17297e4193e0.png">
<img width="662" alt="屏幕快照 2021-12-21 下午1 05 54" src="https://user-images.githubusercontent.com/34368385/146874464-59e40040-a3fd-4538-b57b-6df806cd7f10.png">

**Comment by mcarrano** [comment]
@nding-anges we do have an implementation of this here: https://www.patternfly.org/v4/components/login-page/react/showhide-password/

@mcoker any reason we couldn't apply this same approach to a read-only field to implement the designs above?

**Comment by mcoker** [comment]
@mcarrano the show/hide password feature looks like it's built into the login component. An input group could be used to pair a read only text input/form control with a button that toggles the button type dynamically like this - https://codepen.io/mcoker/pen/YzrvzxV

**Comment by nding-anges** [comment]
@mcarrano @mcoker Thank you! and sorry for the late reply. Just thinking about using the text input /form control with a button that you just shared will make the user feel this is editable, but in our review UI, it is read-only. so our developers customized this component by hiding the input field. it looks like this:
<img width="1017" alt="屏幕快照 2022-01-21 下午6 34 21" src="https://user-images.githubusercontent.com/34368385/150512331-9abefb23-e772-447b-a9ed-a39967c1f154.png">
I think that is fine for our connectors UI. And feel free to let me know if there is anything that would not be aligned with PatternFly guidance. @mcarrano

**Comment by mcarrano** [comment]
@nding-anges I agree with you that the fields feel like they are edit boxes in the original mockups and this is better. We don't have any specific guidance or pattern for this currently in PatternFly as I don't believe it has come up before. Feel free to bring this to the PF design share meeting sometime if you want more feedback from other designers, but for now, I am glad you found a good solution for this. I will close this request.
