### ISSUE TITLE
List View: Inconsistent behavior for row expansion

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#112]
Behavior for row expansion is inconsistent between HTML and Angular implementations.  HTML expands when clicking the row.  Angular only when clicking the caret icon.  Design is closer to HTML implelmentation.

**Comment by dabeng** [comment]
PR - https://github.com/patternfly/angular-patternfly/pull/400

**Comment by LHinson** [comment]
Nice! Thank you @dabeng. I see this is merged so closing here!
