### ISSUE TITLE
Sticky Toolbar demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1120]
Want to define a full page demo that shows use of a sticky toolbar in context.

**Comment by andrew-ronaldson** [comment]
Here is a link to the Sketch file demo of a sticky toobar https://www.sketch.com/s/41516374-5f4b-4000-9cf6-043637852501

Here is a quick demo video as well.

https://user-images.githubusercontent.com/28658548/150850159-5663e41b-3e1a-408a-a1b0-40d8b451dbea.mov

**Comment by mcarrano** [comment]
@nicolethoen does this meet the needs for creating a full page sticky tool bar demo? If so, I will open a new React issue to create this.

**Comment by nicolethoen** [comment]
looks good to me! @mcarrano

**Comment by mcarrano** [comment]
I've opened a new React issue here and will close out this design issue: https://github.com/patternfly/patternfly-react/issues/6889 Thanks for your work on this @andrew-ronaldson
