### ISSUE TITLE
Highlighting new table rows when filters are applied 

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1122]
## Requesting PatternFly table enhancements 
This is a unique product use case where our PF table is logging traffic and we allow users to refresh the data manually or by time interval. If a user has applied filters to the data (ex: Show only data matching Source: Pod A) and they refresh the data it would be helpful to identify the new rows in the table. 

NOTE: Because each column has ascending / descending sorting option the data may not appear in chronological order. I am proposing a subtle highlight on the new rows that disappears after a short time. This will help to identify new data quickly without being disorienting.

**Comment by mcarrano** [comment]
@andrew-ronaldson As discussed, I'm fine to let you run with this and ideate on some potential visual solutions that we can discuss further. In thinking more about this, I wanted to call your attention to this solution we implemented a while ago for indicating favorited items in a table: https://www.patternfly.org/v4/components/table#composable-favoritable-implemented-with-sortable

Yours is not exactly the same use case but maybe can build off this idea. It allows for sorting (in this case on favorities) which might be something desired to bring all new items to the top.

**Comment by andrew-ronaldson** [comment]
thanks for this @mcarrano. I had thought about something similar but I hadn't drawn it up when I shared in the meeting. I've seen blue dots used to indicate new items and thought I'd try something like that. I'll share progress next week.
