### ISSUE TITLE
Tree view, make it possible to click text without collapse/expand happen

### ISSUE THREAD

**Issue by svenna** [patternfly/patternfly-design#1124]
It is hard to use the current Tree view as both navigation and selection as a click toggles the expansion of the node
if it has children.
It would be nice to be able to configure the treeview to handle both when an item is a pure navigation item
and the case where it is both navigation and clickable. The basic idea would be that the left box in the image below
toggles expansion and the right box triggers an onSelect/onClick event

![image](https://user-images.githubusercontent.com/94612/147681091-7ddeeb2c-9aed-4cc4-8d0a-57192e7712f9.png)

one of my use cases are selecting an item to be able to add/edit data on the selected item or to link other items into
the selected node. When selecting items in the hierarchy it will constantly expand and collapse which makes the interaction
less than perfect.
That it is impossible to configure to keep the node "selected" when leaving focus makes it even harder to visualize the 
current state of the view. :)
![image](https://user-images.githubusercontent.com/94612/147681485-40768a5f-df9d-4af5-8c72-de91f2279f9c.png)

**Comment by mcarrano** [comment]
@svenna thank you for bringing this to our attention. We agree that it makes sense to allow parent nodes to be used for navigation as well as exposing successive levels of the tree. We will get this on our feature roadmap as an enhancement to TreeView.

**Comment by mcarrano** [comment]
@nicolethoen @tlabaj any reason we couldn't just create a new variant of the Tree view that works as described above? I would see this as similar to the checkbox variant that we already have where the caret is used to toggle the node open/close and clicking on the label would select the node for navigation. Thoughts?

**Comment by mcarrano** [comment]
@nicolethoen @tlabaj After discussing in today's design team meeting we decided that we should just proceed with this as requested and not introduce any special visual styling or affordance. We were wary of introducing a new menu pattern and felt the new behavior would be easily discoverable.

Therefore I am going to transfer this back to dev for implementation. we would leave all current behavior in place, but introduce and new variant called "Tree navigation" that allows the caret and text element to behave independently. @mcoker will this require any core work or can this go directly to React?

**Comment by nicolethoen** [comment]
I'll note that i also created this issue to track the inconsistent interaction pattern for the treeview with checkboxes. It is sort of related I think. Not sure if it needs core work first either.

https://github.com/patternfly/patternfly-react/issues/6991

**Comment by mcarrano** [comment]
@nicolethoen Yes, I agree with this. @mmenestr can you also take a look for a second opinion?

**Comment by mcarrano** [comment]
The following core issue will be used to track follow up work: https://github.com/patternfly/patternfly/issues/4724 It's on our roadmap for Q2. Closing this in design.
