### ISSUE TITLE
Create demo to show how alerts can be used in forms and modals

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-design#1125]
**Describe the issue. What is the expected and unexpected behavior?**
Frequently in product, our Alert component is being combined with our Form and Modal components, but we don't have a demo showing this interaction. We have an Invalid with form alert example, but I think it would be helpful to show the full interaction that could happen between a modal, a form, and hitting the submit button to create an alert. (Especially given that users can be unaware of how to make this interaction accessible.) It might also be helpful to show a more complex alert like the new expandable alert to show the most complicated variation.

For example, I've seen this use case that might be helpful to demonstrate:

![F54767BC-AF9F-4B23-8148-03E92EA64720](https://user-images.githubusercontent.com/28281340/130992566-5a91a899-cd8c-4fdd-ab21-55c4d3614174.jpeg)

**Comment by mmenestr** [comment]
Design doc issue: https://github.com/patternfly/patternfly-org/issues/2988

**Comment by mcarrano** [comment]
@pankajshivpuje I think this is fine, except that I'm having trouble understanding what we should use the approach with the inline alert at the top of the page, and when we do not. For example, for short forms contained in a modal, this feels unnecessary since the entire form is in view. For longer forms, I think it's very helpful. Thoughts? Is it that the alert with links is a more accessible solution? 

@jessiehuff perhaps also take a look.

**Comment by doruskova** [comment]
@mcarrano Agree. I think that for short forms in modal or wizard we should point out the given place with an error without an inline alert. We can use https://www.patternfly.org/v4/demos/password-strength or https://www.patternfly.org/v4/components/form#invalid with a helper text under the text field. 
I would use the inline alert with other invalid form inputs in a longer form where more inputs are wrong.

Here are some other use-cases such as warnings or info inline alerts in forms or wizard. 
<img width="1119" alt="Snímek obrazovky 2022-06-13 v 11 01 06" src="https://user-images.githubusercontent.com/32618096/173322178-02d63054-64c7-4ccc-8f91-700bd9b6a086.png">

<img width="1727" alt="Snímek obrazovky 2022-06-13 v 11 01 59" src="https://user-images.githubusercontent.com/32618096/173322189-775771ec-7971-4e76-9f62-11ea4fc4e164.png">

**Comment by pankajshivpuje** [comment]
@mmenestr @mcarrano My apologies for responding late. I have completed all updates as suggested. Here is the updated [design doc](https://docs.google.com/document/d/1rXzEXvrs4_2vES-076z6ogdxTp2mC_o9DYWWxC4JXFI/edit#heading=h.ijuhbjlfru3l) and [Marvel](https://marvelapp.com/prototype/de1cb01/screen/86477649). Please let me know if any other updates are needed.

**Comment by mcarrano** [comment]
Thanks @pankajshivpuje. Looks good to me. @mmenestr do you see any additional issues?

**Comment by mmenestr** [comment]
Just looked at it once more and there are still minor changes to make - it's the same change in every image (removing the icon next to the helper text, and making the helper text regular weight font)

**Comment by pankajshivpuje** [comment]
@mmenestr design doc and marvel are now updated. Sorry, I just wanted to circle back with individual product sketch files before making these changes.

**Comment by mmenestr** [comment]
Design guideline issue opened: https://github.com/patternfly/patternfly-org/issues/2988

**Comment by pankajshivpuje** [comment]
@mmenestr @andrew-ronaldson I have started working on design guidelines that relates to the alerts demos from issue#1125. Is there a way to find out if the alerts demos were implemented in the alerts page or demo section so I can update the appropriate guidelines accordingly.

**Comment by mmenestr** [comment]
@pankajshivpuje you should able to look through the alert demos and go from there (?) But I'm not sure demos were created for this. I think it's enough to just add guidance for this in the design guidelines, along with images reflecting the guidance.
