### ISSUE TITLE
Create updated design library

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1130]
Create/update design library to embody new visual language. This will be a critical tool for building out components. The design library should embed the visual language defined by https://github.com/patternfly/patternfly-design/issues/1128. 

Explore theming - i.e., switching between light and dark themes
Explore use of tools - Sketch vs Figma

**Comment by doruskova** [comment]
@mcarrano Can I take this issue? I think it's related to the conversation we had last week.

**Comment by kmcfaul** [comment]
Will be published with the alpha.
