### ISSUE TITLE
Define header styling for React examples on website

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1139]
Many of our React examples are written to include optional settings that allow a single example to show the affect of changing component properties. These are currently just exposed as part of the example itself which can sometimes make it difficult to differentiate the actual example from the controls associated with it. The need is to create a visual template for these examples that can apply standard styles to a header area that will contain all such controls. Here are links to some examples that have optional controls:

https://www.patternfly.org/v4/components/tooltip/#options
https://www.patternfly.org/v4/components/card#with-modifiers
https://www.patternfly.org/v4/components/popover#advanced
https://www.patternfly.org/v4/components/table#composable-basic

In addition to providing styling, we should also have some guidelines for developers creating examples about what controls to use and when.

**Comment by evwilkin** [comment]
Related issues:
- https://github.com/patternfly/patternfly-org/pull/2867#issuecomment-1062003617
- https://github.com/patternfly/patternfly-react/pull/7061#issuecomment-1068492131

**Comment by mcarrano** [comment]
Close in favor of this larger issue. https://github.com/patternfly/patternfly-design/issues/1146
