### ISSUE TITLE
Design guidance for using tabular numbers

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-design#1140]
With the latest [Red Hat font](https://github.com/RedHatOfficial/RedHatFont) updates, we can enable tabular numbers, which will tell the browser to use the monospace font for any numbers used.

You can enable tabular numbers on any block on a page - either the entire page, a section of the page, a component, a random element within a component, etc.

It would be great to:
* Write usage guidelines/suggestions around when to use tabular numbers - maybe on the typography page? https://www.patternfly.org/v4/guidelines/typography
* Build some demos that use tabular numbers
  * Tables, data lists, other types of lists, anywhere that numbers may precede text in a stacked context like dropdown menu items, etc
* Look at our components and see if there is anywhere that we might want to enable tabular numbers by defualt
  * Form control elements might be good - like text inputs (including the ones used in the number input component, and pagination component page number)

**Comment by jhiadlov** [comment]
I added Red Hat Mono font to the text style in sizes 12, 14, and 16. Also 2 color variations for white and black backgrounds. I updated the numbers in tables with RH Mono in the template file.

**Comment by mcarrano** [comment]
@jhiadlov thank you for your work on this. I don't think there's anything further to do at this time, but @mceledonia can you take a look at this issue in general and let me know if you think this is something we need to add to our typography guidance?

**Comment by mcarrano** [comment]
This is being addressed here: https://github.com/patternfly/patternfly-org/issues/2760
