### ISSUE TITLE
Consider updating selectable components design (card, tile)

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-design#1142]
We've noticed that a lot of the selectable components (i.e. Card, Tile, etc.) aren't always very accessible to screen readers. When talking about the issue and potential solutions, we started to wonder if the cards/tiles/plain boxes provide the proper affordance that they are selectable (for all users, not just for a11y), especially regarding single- vs multi-select. A lot of other examples of this type of component typically include a radio button or checkbox within them to make it clearer that the item is selectable.

When I look at the [implementation for Carbon](https://www.carbondesignsystem.com/components/tile/usage/#selectable), they do have distinct visual indicators that are visually similar to native html radio buttons and checkboxes, but styled to match the overall visual theme. I would question why this option isn’t being considered, since in my opinion is will be more reliably accessible and easier to implement and maintain (as they use native elements). You can see a live example on this page if you change the variant selector: https://www.carbondesignsystem.com/components/tile/code.

**Comment by mcarrano** [comment]
Closing this in favor of https://github.com/patternfly/patternfly-design/issues/1211
