### ISSUE TITLE
Consider/Add new icon for opening quick start drawer

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#1149]
The PF Quick Start team is looking for an icon (which will be paired with a link) to indicate that the quick start/in-context documentation panel will be opening in a drawer _beside_ the current view, not redirecting the user away from their view. Before I go through the [process](https://github.com/patternfly/patternfly-design/wiki/Creating-custom-icons) of adding a new custom icon, I wanted to share some options and discuss in this issue first. 

I've created a handful of custom icon iterations for this, some influenced by the icons google workspace uses to show that content will open in a panel. I've also included some existing pf/font awesome icons that may also work for this scenario. I know there are a lot of options here, so let me know if any stand out to you in particular (for better or for worse 🙂 ) 

<img width="638" alt="Screen Shot 2022-04-12 at 2 37 20 PM" src="https://user-images.githubusercontent.com/46571616/163033613-83effa77-bed6-4354-97bb-5a3a07debeeb.png">

FYI @jgiardino @jessiehuff @CooperRedhat

**Comment by mcarrano** [comment]
@lboehling I will pull this into the current design milestone. Do you want to add this to the agenda for our weekly sync on Thursday? We can discuss. Also, is this needed by a specific deadline?

**Comment by mcarrano** [comment]
@lboehling I can take things from here and generate the required PR. Do you also have the updated `icon-exporter.sketch` file?

**Comment by mcarrano** [comment]
A PR has been opened to add this icon to the core icon set and the design repo is updated. Will close.
