### ISSUE TITLE
Button guidelines: add guidance on placement of a Test button

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1151]
On multiple occasions people have asked where to place a Test button in a form when the user is encouraged to test configuration changes before saving. We should add this topic to the Button guidelines.

**Comment by andrew-ronaldson** [comment]
Based on feedback in the PF meetings and product examples I tried this as an inline "test configuration" action on specific inputs. If this action is for an entire form it is more in-line with our existing form validation. Here are some [screens](https://marvelapp.com/prototype/b3aaaed) that show start, in-progress and final state based the test.

**Comment by mcoker** [comment]
@mcarrano this looks good to me, although the button looks like an inline link button and that button doesn't support the progress state, so we would need to add that support.

**Comment by mcarrano** [comment]
Yeah, I thought that would be the case. I've opened https://github.com/patternfly/patternfly/issues/4994 to add that variant.

**Comment by mcarrano** [comment]
This pattern will be documented as part of the Forms guidelines. Closing this in favor of https://github.com/patternfly/patternfly-org/issues/3418
