### ISSUE TITLE
Consider adding official design to incorporate text into log in via social accounts

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-design#1155]
A discussion about Log in modal's design guidelines lead to a conversation about possibly expanding the official design or recommendations to include more text in the social icon buttons to describe their purpose.

Here is an example for Ansible's use case of having multiple GitHub log in options. I'm using the PatternFly split button dropdown component in the updated mockup below.

![image](https://user-images.githubusercontent.com/13351591/163253065-3f412a5d-4220-4cea-aaaa-96b7722729aa.png)

_Originally posted by @trahman73 in https://github.com/patternfly/patternfly-org/issues/2913#issuecomment-1098269321_

**Comment by mcarrano** [comment]
While I understand the merit of this, after floating this with projects, there does not seem to be a significant cross-project need for this functionality. Will close and we can revisit in the future, if needed.
