### ISSUE TITLE
Create fake table data to drive React table demos

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1157]
It would be great if all of our table demos can be built off the same same data set both for consistency and to make demos easier to implement. Create a data table with 50-100 entries to pass to the React team for implementation. This can just be generated in the form of a spreadsheet.

**Comment by jhiadlov** [comment]
Hi,
I made a fake table with some strings and number values. Could you please check it and tell me if I should change something? :) Thank you.

https://docs.google.com/spreadsheets/d/1-sqIbCpmFfmID0fByWZSOBpn99ocGyT2KoUZ5B_s3zo/edit?usp=sharing

@mcarrano

**Comment by nicolethoen** [comment]
It looks good. I only wonder if we should have anything more complex than strings and numbers? anything with labels or links or particularly long values or anything like that?

**Comment by doruskova** [comment]
@nicolethoen Yeah, I agree. Maybe we should add, for instance, a URL and description column that shows longer text.

**Comment by jhiadlov** [comment]
I added 2 columns: Last modified and URL. I am not sure what exactly should I put in the URL, so I added a link to RedHat offices 😅 Is it alright like this?

**Comment by mcarrano** [comment]
Thanks @jhiadlov . Yes, I think this is better. Can you also create a Sketch mockup with a table that uses some of this data? Maybe the first 15-20 rows? That will give us a better idea about what this will look like in context. Thanks!

**Comment by nicolethoen** [comment]
My only concern is that tables with links run the risk of having the same link text in every row, and technically that's an accessibility violation unless all the links go to the same URL. I guess in your mocked data, all the URLs are the same, so that actually would not be a violation, but is that an expected use case? 

Links as mocked data would be a little more realistic, i think, if they are all unique URLs - even with like a different number appended at the end for each one. Additionally, it'd be helpful to have the link text also mocked up in those cases in a way that demonstrates each row's link text being unique. Does that make sense?

**Comment by mcarrano** [comment]
@nicolethoen these links don't actually need to be to a live site, correct? If so, what we could do is to make it a link to the server object represented in each row, for example, http://www.redhat.com/en/office-locations/US-node1, http://www.redhat.com/..../USnode2, etc. Would that work?

**Comment by nicolethoen** [comment]
It would work - my only question is would we want the URLs written out completely, or would they want more readable/meaningful link text? 

If it's the latter, we should consider how we'd recommend people building tables with links so that all the links don't have the same link text

**Comment by mcarrano** [comment]
@nicolethoen Maybe ideally it would be the later. But I thought that the point of having a URL would be to should how long strings should get truncated. Otherwise I don't think whether this is a link or not matters so much. Does that make sense?

**Comment by nicolethoen** [comment]
that makes sense to me!

**Comment by jhiadlov** [comment]
@mcarrano so should I replace status with labels? And also, should I make the URL in this form "http://www.redhat.com/en/office-locations/US-node1"?

**Comment by jhiadlov** [comment]
https://marvelapp.com/prototype/2ff7ahj6/screen/87992955 it's done :)

**Comment by jhiadlov** [comment]
Done :) every time I write something new into table, all data are changing values, I mean the numbers, but they are always in the range I set. Would it be that a problem?

**Comment by nicolethoen** [comment]
I like it! :)

**Comment by mcarrano** [comment]
Thanks @jhiadlov This looks great! I will close this issue as completed.
