### ISSUE TITLE
Label - Add gold label to PF labels

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design#1158]
The current PF labels include orange labels only and we're using orange (Important total risk) and gold labels (Moderate total risk) in Advisor for RHEL, OpenShift, and Ansible. 
We're integrating this info into Product case management and we want to keep it visually consistent. However, the PCM team wants to use PF labels directly instead of creating custom styles. 
Would it be possible to add gold labels to the official PF set? @mcarrano @mcoker 

Moderate labels using gold color - https://marvelapp.com/prototype/g70a1he/screen/84434999

**Comment by mcarrano** [comment]
@doruskova Is this needed in any specific timeframe? I'm currently scheduling into Q3.

**Comment by doruskova** [comment]
@mcarrano Adding design spec for a gold label https://marvelapp.com/prototype/df6d576/screen/86794697
The only thing I changed is the icon color to keep accessibility and contrast. I have no concerns when it comes to border color because blue, green, purple, and cyan are using a light shade and the main thing that needs to be accessible is the text and icon. The outline version is using a grey border. 
However, I noticed that the orange label is using gold colors. Gold-700 for text, gold-50 for background, and gold-100 for a border. The only element that is orange is the icon. That's confusing and it should be orange. I created a version for an orange label as well. But, it would need a new color variable orange-50 https://marvelapp.com/prototype/df6d576/screen/86795332

We don't have a specific timeframe. :)

**Comment by mcarrano** [comment]
@doruskova I think this looks good, except that shouldn't the text for the bordered version be colored as for other labels using one of the dark values from the Gold palette? Interesting about the orange label. I'm OK with creating an `orange-50` color for this purpose. @mceledonia @mcoker can you also take a look?

**Comment by doruskova** [comment]
@mcarrano The text in bordered/outline version is using always black-900 (`#151515`)
https://www.patternfly.org/v4/components/label#outline

**Comment by doruskova** [comment]
@mcarrano Yes, you're right. The mock is fixed now :) https://marvelapp.com/prototype/df6d576/screen/86794697

**Comment by mcoker** [comment]
@mcarrano sounds good to me. It's a pretty simple change so I put up a PR here so you can see it - https://github.com/patternfly/patternfly/pull/4863
