### ISSUE TITLE
Opening/Closing drawer in wizard design

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design#1160]
We are releasing a demo for a drawer inside of a wizard, but for now, the demo is static - ie: the drawer is open at all times.

We should create a design/demo where a user has the ability to open/close a drawer within a modal.
This would include:
- Adding a close button in the drawer
- Adding a button to open up the drawer again

The second bullet might have multiple use cases - ie: should the drawer be opened via link in the body of the wizard? And how would we show that? And is there any other use case we can think of for having a drawer that opens and closes, but maybe with a separate mechanism?

**Comment by mmenestr** [comment]
Katie mocks for similar idea: https://marvelapp.com/prototype/e6f0b14/screen/68862127

**Comment by mmenestr** [comment]
Add design for mobile interaction

Figure out a way to toggle the drawer panel
- Should the panel be closable in all viewports or just mobile?
- When it's closable, what's the trigger to re-open it?
Handle the drawer panel differently on mobile so it doesn't cover the main area
- Don't show it (doesn't seem ideal)
- Move it to come after the content or in some other kind of presentation that isn't the drawer panel (may be fairly complicated and require a custom implementation)

**Comment by mmenestr** [comment]
@mcarrano here is my final proposal, let me know what you think:

1. **Non-dismissable wizard panel [[mock](https://marvelapp.com/prototype/9389af6/section/1619656)]:** 
Launch panel from a link button with icon (idea is anyone could take this and customize it as needed). 
Mobile view works the same way - panel opens and closes from left to right and covers the whole body. No matter what, the modal buttons should never be covered.

2. **Dismissible wizard panel [[mock](https://marvelapp.com/prototype/9389af6/section/1615614)]:**
Panel always visible/present.
In mobile view, the panel collapses in the same way the navigation/steps collapses, but at the bottom of the body area, right above the buttons. A user can then expand and collapse the panel via the caret button.

**Comment by mcarrano** [comment]
This looks good @mmenestr . But I think in the comment above you confused dismissable and non-dismissable as the mocks don't align with the description. My only question is why the drawer is constrained to the body/content area of the wizard in one version but not the other. Wouldn't we want that to be consistent?

**Comment by mmenestr** [comment]
Design doc issue: https://github.com/patternfly/patternfly-org/issues/2987

**Comment by doruskova** [comment]
@mmenestr Are the mocks up-to-date? Can i use them for Sketch kit?

**Comment by mmenestr** [comment]
@doruskova - replied on Slack
