### ISSUE TITLE
Tabs - demos are unclear as to what they're highlighting

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-design#1162]
**Is this a new component or an extension of an existing one?**
Tabs

**Describe the feature**
Additional documentation that describes what is being showcased in [each demo for the Tabs component](https://www.patternfly.org/v4/components/tabs/react-demos/) (at least where reasonably) would be beneficial.

Additionally, some of the names currently used (such as Tables and tabs, auto width tabs) don't seem ideal for the changes being applied. In cases like this the name should be re-evaluated and a more descriptive name applied if possible.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
N/A

**Any other information?**

Core PR that added the HTML version of these demos: https://github.com/patternfly/patternfly/pull/3914
Design document that these demos were originally based on: https://marvelapp.com/prototype/5fba0cj

Followup to https://github.com/patternfly/patternfly-react/pull/7183#issuecomment-1095552394

**Comment by mmenestr** [comment]
Created this doc with a quick "audit"/thoughts on the current tab demos that exist for us to discuss next week @mcarrano https://docs.google.com/document/d/1q3aaFfL8h9Lyoz0awVD_1uwpdfyQtW48rIn16uFK8-I/edit#heading=h.kf8vtn57hzik

**Comment by mmenestr** [comment]
Marvel: https://marvelapp.com/prototype/9766ieg

**Comment by mmenestr** [comment]
Design doc issue: https://github.com/patternfly/patternfly-org/issues/3159

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/5058 to begin implementation.

**Comment by mcarrano** [comment]
Thanks for your work on this @mmenestr . Will close.
