### ISSUE TITLE
Delete confirmation

### ISSUE THREAD

**Issue by pankajshivpuje** [patternfly/patternfly-design#1163]
## Requesting design recommendations/demo for delete confirmation
While working on delete component feature for App Studio design, I came across several variations of delete confirmation modal designs across RH products. The primary use case to support this feature is the ability for the user to be able to delete a said object from the system. Delete is a detrimental action so when user decides to delete an object, we would like to make sure user understand it is irreversible permanent action. We would also like to make sure that user is deleting the correct object so asking user the confirm before proceeding with this action. The confirmation model presented to the user allows user to doublecheck the action and then proceed. 

Few areas that needs be to explored as a part of this issue:
1. When to enable/disable primary action button on the forms/modals? This can go beyond the delete confirmation and will allow the exploration of forms and model in various scenarios across the RH products.
2. Ask user to type the name of object being deleted and provide feedback as they start typing.
3. After delete interaction is completed, how is the object removed from the list?

PF recommendations around designing the confirmation modals will help bring the consistency across the product, reduce learning curve, and reduce errors. In addition, the recommendations/demo can help guide the future design efforts for similar use case.

Here are some examples delete confirmation modals from various RH products.

## Example 1:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/40463673/169879097-a351b104-0b03-4e98-aac4-53b27d8e0dd8.png">
<img width="613" alt="image (1)" src="https://user-images.githubusercontent.com/40463673/169879112-6c42828f-3884-41f4-b782-c161efb19b90.png">

## Example 2:
<img width="586" alt="Screen Shot 2022-05-19 at 12 04 05 PM" src="https://user-images.githubusercontent.com/40463673/169880126-1c315ea9-09bd-4af9-a89c-d7426f0eb451.png">
<img width="579" alt="Screen Shot 2022-05-19 at 12 04 15 PM" src="https://user-images.githubusercontent.com/40463673/169880127-f1c2b83f-0c07-4a4d-abf0-c2fef2598a72.png">
<img width="578" alt="Screen Shot 2022-05-19 at 12 04 22 PM" src="https://user-images.githubusercontent.com/40463673/169880128-821c186d-1ef8-4e85-808e-0a96fa6f8ccd.png">

 ## Example 3:
<img width="584" alt="Screen Shot 2022-05-19 at 12 07 42 PM" src="https://user-images.githubusercontent.com/40463673/169880149-64696504-6a48-4895-9933-6f11e9f839b8.png">
<img width="583" alt="Screen Shot 2022-05-19 at 12 07 53 PM" src="https://user-images.githubusercontent.com/40463673/169880150-672346ce-4ff5-4ea3-8558-14f6391bb701.png">

**Comment by mcarrano** [comment]
Discovery doc from @pankajshivpuje : https://docs.google.com/document/d/1l8BDhnNeXEQlFWus1dUbdgoFKZcHhVHYS_MlznKonOc/edit#

**Comment by pankajshivpuje** [comment]
Here are the latest proposal for [delete confirmation modal](https://docs.google.com/document/d/1l8BDhnNeXEQlFWus1dUbdgoFKZcHhVHYS_MlznKonOc/edit#)

**Comment by mmenestr** [comment]
Design doc issue: https://github.com/patternfly/patternfly-org/issues/3420

**Comment by mcarrano** [comment]
Will document on the website as a new pattern. See the linked Org issue.
