### ISSUE TITLE
Responsive behavior for vertical tabs

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1165]
Per the discussion here: https://github.com/patternfly/patternfly/pull/4850  We should consider usage of vertical tabs and how they respond on small viewports. The outcome would be to specify a new demo for Tabs that features vertical tabs.

**Comment by doruskova** [comment]
@mcarrano I got feedback that OpenShift is using vertical tabs. Here's their design: http://openshift.github.io/openshift-origin-design/designs/administrator/future-openshift/user-preferences/

Maria Svirikova from Satellite used them here: https://marvelapp.com/prototype/1121a8de/screen/72413287 
Margot can imagine using them on a Settings page.

**Comment by mcarrano** [comment]
@doruskova these examples are very helpful. So I guess the question is what do we expect to happen when we shrink the screen. For other things like this, like wizard steps and jump links, the vertical menu changes to a dropdown. Should we be doing the same thing here?

**Comment by doruskova** [comment]
@mcarrano I'll prepare mock for it :))

**Comment by jhiadlov** [comment]
Work in progress :)

**Comment by jhiadlov** [comment]
Here are mockups for vertical tabs. I was thinking about 2 options:

1. I made an expandable version and design as it is used with Jump links where the content is just moving down.
https://marvelapp.com/prototype/dj6cag1/screen/87992357

2. I made Drop down version and design as it is used in Wizard and the content is covered with drop down.
https://marvelapp.com/prototype/dj6cag1/screen/87992418

Let me know what do you think about it :)

**Comment by mcarrano** [comment]
@jhiadlov I think either of these would work. @mcoker @mattnolting can you also take a look at this and let us know if either of these solutions will work for transforming the vertical tabs to something that works on mobile?

**Comment by mcoker** [comment]
AFAIK the plan was to use the sidebar component to manage the layout as the jump links component does. We have demos of jump links here:

collapsed on mobile:
https://www.patternfly.org/v4/components/jump-links/html-demos/vertical-jump-links-collapsed-on-mobile/

expanded on mobile (does not overlay the content):
https://www.patternfly.org/v4/components/jump-links/html-demos/vertical-jump-links-expanded-on-mobile/

We can create demos of tabs using the sidebar component.

**Comment by mcarrano** [comment]
That's fine @mcoker . So does this give you what you need to restart work on this issue then? https://github.com/patternfly/patternfly/issues/3915

**Comment by mcoker** [comment]
@mcarrano yep 👍

**Comment by mcarrano** [comment]
@doruskova @jhiadlov Thanks for your efforts on this. I am close this as completed.
