### ISSUE TITLE
Topology - Pipeline designs

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-design#1166]
Jeff has been working on taking a look at ODC pipeline and integrating this feature into PF Topology. ([Epic for this effort with ODC example here](https://issues.redhat.com/browse/UXDENG-124).) While working on this effort though, we've realized that it would be beneficial to have some designs/visuals to help with the effort. 

@jeff-phillips-18 @andrew-ronaldson Are there any details to this effort that would be good to add?
@mceledonia

**Comment by andrew-ronaldson** [comment]
Here are the latest [designs](https://marvelapp.com/prototype/iadc037/screen/87580725) for this. I'll add follow up stories as needed to address product use cases.
