### ISSUE TITLE
Trend Card: Internal inconsistencies between design examples and implementations

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#117]
There are multiple inconsistencies between trend card design examples and Angular implementation examples.  Some of these include:
- Treatment of card with single trend and card with multiple trends are inconsistent in appearance of card title, placement of time frame selector, and placement of text labels.  
- Treatment and placement of card titles differs between examples.

**Comment by mcarrano** [comment]
@LHinson Trying to decide what to do with this issue. I'm aware that @beanh66 is making some updates to the design page, but this issue references inconsistencies between design and Angular implementation.  Given our new repo strategy, does this issue belong here or does this need to get taken up by the Angular repo team?

**Comment by beanh66** [comment]
@mcarrano I'm not sure I follow the issues mentioned here. There are multiple examples in the design tab but the ones covered by the Angular implementation look okay to me. There is  currently a bug in the angular implementation that has to do with some odd spacing. @serenamarie125 created an issue for that [here](https://github.com/patternfly/angular-patternfly/issues/579). If there are other issues pertaining to this pattern and the Angular implementation, I would suggest adding to this issue so someone can cover it in one pass! 

In terms of the update I'm making to the PF design repo, it is simply to add another alternate version where labels can go to the right of the graph. @amarie401 is working on the angular implementation of this alternate version!

**Comment by mcarrano** [comment]
Thanks for looking @beanh66 .  This was something that came out of the audit activity that we did last December, but maybe it was already addressed as I don't really see the inconsistencies anymore either.  @LHinson let me know if you see an issue, if not I will just close this one.

**Comment by LHinson** [comment]
thanks @mcarrano and @beanh66 agreed that this one should be closed so I will do so!
