### ISSUE TITLE
Quick Start & Breakpoint 

### ISSUE THREAD

**Issue by heyethankim** [patternfly/patternfly-design#1170]
## Requesting new features, enhancements, or design changes to PatternFly
When a Quick Start is displayed, all other components are resized except the navigation as below. 

<img width="1871" alt="image" src="https://user-images.githubusercontent.com/84546841/170760403-6c2e8cf8-5273-4a41-a038-0bf51ed620a1.png">

<img width="1872" alt="image" src="https://user-images.githubusercontent.com/84546841/170760372-53447d30-69d7-49ce-82c9-2d61e0d6b285.png">

As the browser width decreases, three things happen:

(1) The YAML editor gets unusable 
(2) The Quick Start stays the same
(3) The navigation is not collapsed

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/84546841/170760710-d6177610-4d41-456f-a40e-0d03695825c5.png">
 
As the browser width decreases more, the navigation collapses. 

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/84546841/170760856-5ecec86d-4b25-4814-ba4f-611b970a0c1b.png">

With more decrease, the YAML sidebar gets hidden. 

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/84546841/170760956-c76e86fc-337f-4cc5-a5b1-59bb528b0514.png">

Finally the Quick Start takes over.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/84546841/170761117-11f25f28-dcb6-4829-a708-425dec5e30a5.png">

Probably we should redefine the UI breakpoint considering the followings:

(1) Which takes more priority? Navigation or Contents
(2) In a small UI, should we hide a certain components or stack them just like we do for the wizard? 
(3) Should the Quick Start trump all other UI components?

**Comment by jessiehuff** [comment]
It seemed like based on the discussion I had with the others at the Design Share meeting, they thought this was probably more of a product by product case and that we should let products handle it individually.
