### ISSUE TITLE
layout and styling for page-level actions

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-design#1174]
After drilling down to a page that provides a resource-level view, there are actions we display in the table view kebab menu that we want to surface in this page, too. 

This seems to be a common use case, to surface resource-level actions in a dropdown in the page header of the resource-level view. We'd like some guidance regarding overall layout and visual styling of this type of dropdown menu so that we can adopt a recommended pattern throughout all services we support.

Specifically, these are the use cases we'd like guidance on:

- There is a primary action that we want to highlight in addition to a dropdown menu of less important actions
- There isn't a primary action to highlight, but only a dropdown menu.

_Link any detailed design documents, rough sketches, wireframes or workflows._

The standard pattern we were seeing in other examples provided a dropdown in the page header with the label Actions. Most patterns showed this toggle was using the default styles. We started to create mockups based on this pattern, which [you can see here](https://docs.google.com/presentation/d/1wpltSgTn3ekvVW7RaJ5bTHzdFbhSH55VOCYRou-xnKQ/edit?usp=sharing).

During a design review, one of the designers shared an example from the OpenShift design library, showing a similar dropdown toggle with a label Actions, but using the primary variant: http://openshift.github.io/openshift-origin-design/conventions/documentation/actionmenus.html

cc @mcarrano @lboehling

**Comment by mcarrano** [comment]
Thanks for entering this @jgiardino . I will consider how we can best address this in PatternFly and get back to you.

**Comment by jgiardino** [comment]
I wanted to expand on this bullet point with a couple of examples that have been explored

* There is a primary action that we want to highlight in addition to a dropdown menu of less important actions

In some cases, we have tabs, and there can be a primary action that we want to display for that tab along with the contents. 
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/21063328/176212759-b349ee34-a7c4-47ed-bbe4-7f1f4cdd7202.png">

In other cases, we did not have tabs, but still wanted to highlight a primary action for the contents that displayed. This was an example of this pattern we were considering for this use case:
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/21063328/176213654-b6abc0ff-a61d-4c17-84e4-5558f5813c68.png">

**Comment by mcarrano** [comment]
We will add design guidance to reflect our recommendations. https://github.com/patternfly/patternfly-org/issues/3267 is opened to track that. @mmenestr can you add a link to your recommendations here and I will close this design issue. Thanks.

**Comment by mmenestr** [comment]
Recommendations at bottom of this [doc](https://docs.google.com/document/d/1TA6uBuNIyA5F1X2rmz0pSUs0vkc7TYT1Rp-_fkQg-xo/edit).
