### ISSUE TITLE
[PieChart] - [docs update]

### ISSUE THREAD

**Issue by Fewwy** [patternfly/patternfly-design#1175]
**Is this a new component or an extension of an existing one?**
I would like you to update the PieChart documentation and add my example to it

**Describe the feature**
My example uses the Tooltip component that wraps the ChartLabel. 
The Patternfly Tooltip documentation contains class examples only and not a functional component.

https://codesandbox.io/s/vigorous-wozniak-ke604g?file=/index.js:0-1639
```
import ReactDOM from "react-dom";
import "@patternfly/react-core/dist/styles/base.css";
import "./fonts.css";

import React from "react";
import { ChartPie, ChartLabel } from "@patternfly/react-charts";
import { Tooltip } from "@patternfly/react-core";

const CustomLabel = ({ datum, ...rest }) => (
  <Tooltip
    content={
      <snap>
        {datum.x}:{datum.y}
      </snap>
    }
    enableFlip
  >
    <ChartLabel {...rest} />
  </Tooltip>
);

const BasicWithRightAlignedLegend = () => {
  return (
    <div style={{ height: "230px", width: "350px" }}>
      <ChartPie
        labelComponent={
          <CustomLabel
            textAnchor="middle"
            style={{ fill: "white", fontSize: 13 }}
          />
        }
        labelRadius={25}
        ariaDesc="Average number of pets"
        ariaTitle="Pie chart example"
        constrainToVisibleArea={true}
        data={[
          { x: "Cats", y: 35 },
          { x: "Dogs", y: 55 },
          { x: "Birds", y: 10 },
          { x: "Fishes", y: 15 }
        ]}
        height={230}
        labels={({ datum }) => `${datum.y}`}
        legendData={[
          { name: "Cats: 35" },
          { name: "Dogs: 55" },
          { name: "Birds: 10" },
          { name: "Fishes: 15" }
        ]}
        legendOrientation="vertical"
        legendPosition="right"
        padding={{
          bottom: 20,
          left: 20,
          right: 140, // Adjusted to accommodate legend
          top: 20
        }}
        width={350}
      />
    </div>
  );
};


const rootElement = document.getElementById("root");
ReactDOM.render(<BasicWithRightAlignedLegend />, rootElement);
```
**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.
![image](https://user-images.githubusercontent.com/62722417/164456268-e85cc3ea-9c02-4abf-a074-c661b7ad4326.png)

**Comment by mcarrano** [comment]
@Fewwy @tompsota I have similar concerns with @nlcwong and @dlabrecq about this design. Can you say more about _why_ this is needed? Is there a specific use case that the current pie chart examples won't satisfy?

**Comment by Fewwy** [comment]
@mcarrano It was requested by the UX designer, "the PieChart should be readable from the first glance"

**Comment by doruskova** [comment]
@Fewwy @mcarrano I would remove the numbers from a pie and leave them in legend only and tooltip when you hover over. I think it's not necessary to have numbers inside of the chart. Colors can be different and it can cause contrast issues.

**Comment by Fewwy** [comment]
I think we can close this issue
