### ISSUE TITLE
Explore griding / layout concepts for PatternFly 5

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1178]
Want to explore use of a layout grid or similar methods for easing the handoff from design to development that can be applied as part of the visual refresh effort.

**Comment by lboehling** [comment]
Next steps identified for this work would be to enhance our design guidelines for the existing layouts. I opened an issue for updating the design guidelines here https://github.com/patternfly/patternfly-org/issues/3283. 

FYI @mcarrano @mmenestr

**Comment by mcarrano** [comment]
Thanks for your efforts on this @lboehling . I will close in favor of the new issue above.
