### ISSUE TITLE
Consider adjusting the visual design of PF's left nav menu.

### ISSUE THREAD

**Issue by edonehoo** [patternfly/patternfly-design#1183]
Consider better visually distinguishing the PF site left nav menu from the site's background.
- This is an enhancement suggestion based on the [design system competitive analysis.](https://docs.google.com/presentation/d/161XsZ6NrUSgnCkaA1e_96oxWY72VsJAa2SVmtIEhWJg/edit#slide=id.g547716335e_0_260)
- The idea is to have more distinction, inspired by [Carbon](https://carbondesignsystem.com/components/button/usage/), [Clarity](https://clarity.design/documentation/buttons), and [Pajamas](https://design.gitlab.com/components/button/).
- In its current implementation, the contrast between the menu and the site's background is low. There is not significant separation between the menu and the rest of the site.

**Comment by mcarrano** [comment]
@edonehoo I am going to close this in favor of https://github.com/patternfly/patternfly-design/issues/1232 that was recently opened by @lboehling . Encourage the two of you to collaborate on the planned redesign and take these factors into account.
