### ISSUE TITLE
Examine the threshold for responsive site resizing.

### ISSUE THREAD

**Issue by edonehoo** [patternfly/patternfly-design#1184]
Consider adjusting the window size where the PF site is swapped to mobile.

- This is an enhancement suggestion based on the [design system competitive analysis.](https://docs.google.com/presentation/d/161XsZ6NrUSgnCkaA1e_96oxWY72VsJAa2SVmtIEhWJg/edit#slide=id.g547716335e_0_260)
- It feels like the site swaps to mobile (?) at larger windows than expected, though this may have intentional reasoning that I don't have context on.
- For example, if the left nav menu is collapsed, the site remains in a condensed view, despite having seemingly enough space to keep the web view (with the TOC on the right).

**Comment by mcarrano** [comment]
Thanks for submitting this @edonehoo , but adjusting this breakpoint could have a negative effect on certain examples that need more width, so we will not make any change at this time.
