### ISSUE TITLE
Utilization Trend Card: Unclear what label in center of donut chart should reflect

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#119]
No guidelines on what the value in the center of the donut chart should report.  Examples show either Available or Used value, but what is preferable and when?

**Comment by LHinson** [comment]
@mcarrano I do not think that PatternFly can specify such things. This is really specific to the product. Are you looking for a statement that says just that?

**Comment by mcarrano** [comment]
Well, the chart is about reporting utilization, so that's pretty specific.  My issue was that in some places we report the amount used here and in others the amount available.  I think we should have a position on which is preferred and reflect it consistently in our examples.
