### ISSUE TITLE
Color coded tool tip 

### ISSUE THREAD

**Issue by smckinno** [patternfly/patternfly-design#1192]
## Requesting new features, enhancements, or design changes to PatternFly
- Describe the use cases and requirements of the new feature or enhancement you are requesting.
 I am requesting a tool tip that uses color to help enhance the experience when a user hovers over a graph and can thus have the color associated on the graph to be on the tool tip. 
- Explain *why* this feature is needed and/or why these requirements cannot be met using existing components.
This option to include color on a tool tip allows for easier accessibility and helps the user know which part of the graph they are looking at. This enhancement cannot be met using other components because the only system we have in place for expanding the data on a small graph while hovering is through a tool tip.
- If this is for specific applications, list them here along with any dates that you need this for.
This is not needed by any date.
- Link any detailed design documents, rough sketches, wireframes or workflows.
 https://marvelapp.com/prototype/b5e30i7   This is quick mock up of what I was thinking of with my top 2 designs.
- State whether this is a new feature or an enhancement on an existing pattern by labeling it accordingly
This would create an enhanced version that would be added to the tool tip library
- If this is an enhancement to an existing feature, identify the feature that you want to modify.
 Tool tip

**Comment by mceledonia** [comment]
@smckinno Our chart tooltips actually are a separate implementation as they're packaged with Victory, our charting library, rather than utilizing the PatternFly tooltip component. [This does have support for colored legend squares](https://www.patternfly.org/v4/charts/tooltip-chart) which could be another design solution to what you're proposing. Do you think this would work for your use case?

**Comment by smckinno** [comment]
@mceledonia  That could work for this use case, thanks!
