### ISSUE TITLE
Review icon color usage [specifically inside inputs and dropdowns]

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design#1195]
I propose that we establish a more concrete pattern around icon colors. Currently, we have an established pattern for colors of stand alone icons, but not for color of icons used inside an input/dropdown/button. The reason I believe we should create some standard around this is that there has been some confusion around designers, and the guidance is not very clear right now.

After discussing with @mceledonia and @mcarrano we think that any icon inside a toggle or input, which already have their own hover state, should be black. For example, the search icon within a search input should be black, and the filter icon within a filter dropdown should be black etc. Another consideration could be to make all icons black by default, and introduce a new hover state for actionable icons. That way, the default color would always remain consistent and standardizing color usage would be easier.

Currently, the toolbar and search input demos do not align with the proposed guidance outline above as the search icon is grey by default.

**Comment by mmenestr** [comment]
**Proposal**

I created [the following proposal](https://www.sketch.com/s/b1205620-00e9-43d0-9eeb-0b89c2a55e74) that I shared at the PF Design share on Feb 8. We ultimately decided to go with Option 1 which would require changing all icons that live inside of a component **for illustrative purposes** to be black. This does not apply to icons that actually have a direct action within components. Stand alone static icons would remain black, and all standalone actionable icons would remain grey.

_Note_ that this is the proposed icon solution for PF5. For the visual refresh, we discussed the possibility of adding a highlight to our icons, instead of relying on color to denote a static vs actionable icon. This is something that @mceledonia and @lboehling will be looking at exploring.

**Explanation** 
Currently we have inconsistencies around this where some icons within a component (ie: filter icon in dropdown toggle, search icon in search input, caret in dropdown etc) are not always the same color. Sometimes they are grey, sometimes they are black. Seeing as the icon in these components does not actually do anything, we believe they should take the state of a static icon and always be black.

**Work needed**
Will need to change the icon color in the following components:
- Search input: Change search icon to black 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/51165119/217906655-64ee70c0-2a41-4eec-88ea-0dc1ea27ee11.png">

- Bread crumb caret (?) 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/51165119/217906569-805b8a11-bdf1-4486-9b8f-697ce9b240a9.png">

- Pagination dropdown caret from grey to black 
<img width="140" alt="image" src="https://user-images.githubusercontent.com/51165119/217906506-ccbad8dc-17e2-4c6b-97c5-07bad8faa9f2.png">

- Timepicker icon from grey to black
<img width="181" alt="image" src="https://user-images.githubusercontent.com/51165119/217906904-0f5dfd67-427b-4d81-9ff3-e89c746bfd1e.png">

- Toolbar search (though I assume that might be fixed with the search input change) 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/51165119/217907071-15c1da64-e879-4c5d-b38b-854e212f7ff7.png">

**Comment by mcarrano** [comment]
@mmenestr thanks for calling out the things that need to change. I do question whether we need to change the breadcrumb as I think we'd intentionally not want the carets to be as prominent as the page names. Thoughts?  And for the pagination, that dropdown caret triggers a menu, so shouldn't it remain gray?

**Comment by mmenestr** [comment]
If we follow the "guideline" set then I think we should make the breadcrumb carets black. I don't think it would look that different! And for the pagination, It's actually the whole thing that is clickable (text + caret together), not the caret alone that is clickabe and that's why I added it to the list.

**Comment by mcarrano** [comment]
I've opened https://github.com/patternfly/patternfly/issues/5395 to hand this off for development. @mmenestr @lboehling if you haven't already done so, can you make sure that we have doc and Sketch kit issue to make these updates there? Thanks. Once those are open, I will close this.

**Comment by lboehling** [comment]
Opened up a design kit issue here https://github.com/patternfly/patternfly-design-kit/issues/609!

**Comment by mmenestr** [comment]
Design doc issue: https://github.com/patternfly/patternfly-org/issues/3421
