### ISSUE TITLE
Revisit design recommendations for animation 

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1196]
A team of designers had previously looked at requirements for adding animated transition effects to PatternFly components. Their work is summarized [here](https://docs.google.com/document/d/1x8IiTnYEJm183STPdTWb0fcUxMFZCA9B0atnyFezRTs/edit?usp=sharing) and in this epic: https://github.com/patternfly/patternfly-design/issues/978

We should revisit and revise these recommendations as needed to preparation for adding this to the major PF release scheduled for Q1 2023.

cc @mceledonia

**Comment by mceledonia** [comment]
Got concepts/descriptions handed over to @srambach, we're going to start with these and refine if needed.

**Comment by srambach** [comment]
Link to the concepts here: https://docs.google.com/spreadsheets/d/1jjm2nXvqLsObuhSZ-cbII7d22WQ98W5r1ycC9BwJCIk/edit?usp=sharing
