### ISSUE TITLE
Revisit visual affordance for expanded rows

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1197]
Want to revisit visual affordance placed on expanded rows in tables and data lists. The current blue border does not work well in all cases.

cc @lboehling Anything you would add here?

**Comment by lboehling** [comment]
@tiyiprh some background for this issue: 

We did try to solve for this in the past but there were some issues when implementing and decided to revert back (https://github.com/patternfly/patternfly-design-kit/issues/222), but I think it's worth revisiting. I'm question whether the expanded rows need a left blue border at all -- it competes with our selected row state which also uses a blue border and caused us to introduce a new light blue border for expanded unselected rows which I think is overly complicated :sweat_smile:)

**Comment by tiyiprh** [comment]
@mcarrano @lboehling Sorry just getting to this issue now! Would you be able to provide some more insight on the issues with implementing the previous proposed solution? Thanks!

**Comment by mcarrano** [comment]
For reference. Here are some earlier designs from @lboehling : https://marvelapp.com/prototype/2380g666/screen/69239260

**Comment by mcarrano** [comment]
Closing this in favor of https://github.com/patternfly/patternfly-design/issues/1211
