### ISSUE TITLE
Replace icons with illustrations in Empty State

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1198]
Want to update the [Empty state component](https://www.patternfly.org/v4/components/empty-state) to include custom illustrations in place of large icons. We would offer a limited set of standard illustrations that consumers could choose from or add their own. Standard illustrations should cover most major use cases.

**Comment by tiyiprh** [comment]
- Updated [design guidelines doc](https://docs.google.com/document/d/1QeWaZQW8jO1VsIoB0jNE18IfiCjsARa2B8N5eN8Vos0/edit#heading=h.f1i9r3kx92gy) with new empty states
- Icons are from the [RH Brand Assets Library Standard Icons](https://drive.google.com/drive/folders/1YMP7wtoWgSAovc4OuMHdUZwVqwjnvwPg)

Recommended icons:
- Generic empty state: [Community icon](https://drive.google.com/drive/folders/1z3M4TXVog2gbMoYD5eePW_RDH_Yw1upc) 
![empty-state](https://user-images.githubusercontent.com/98424339/198392384-e93251cd-3eaa-4d8f-818a-87ffc3e129d8.png)
- No results: [Cloud (inspect) ](https://drive.google.com/drive/folders/1Dv1Ap7AMGnHRMNhy6I-rBo11BSZ1Hhja)
![s-nodata](https://user-images.githubusercontent.com/98424339/198392523-3e93bd6d-7ff2-4599-bd6d-890e4fb6be13.png)
- Configuration: [Gear group](https://drive.google.com/drive/folders/1WXIFvdZym2ZL_g9TPgO8in826ALJ2oPd)
![new configuration](https://user-images.githubusercontent.com/98424339/198392569-ae6ca48f-7dfd-4074-b187-87f9438483e3.png)
- No access: [Padlock](https://drive.google.com/drive/folders/1SeQjwgjeR0yd1m7lzBZARvFaIra2n44j)
![xs-noaccess](https://user-images.githubusercontent.com/98424339/198392603-c8e2e9a3-2c94-45eb-854c-0731f55177d0.png)
- Back-end failure: [Link (broken)](https://drive.google.com/drive/folders/1xv5k5mStK_Zs1zx6EU9IvCip1aFYSfjV)
![l-backendfailure](https://user-images.githubusercontent.com/98424339/198392625-573af12a-8891-4c9e-bd8f-ffcb11cf1079.png)
- Success: [Yes](https://drive.google.com/drive/folders/1rUfUuqzlfMgHCL0fY--YW52kX_tIGpO3)
![s-successwizard](https://user-images.githubusercontent.com/98424339/198392666-38c3a17b-b477-45f9-bef8-5b905b05bd8c.png)
- Creation: [Cross](https://drive.google.com/drive/folders/1x-01MQe4ZqxR5rkmLzyGx0eJnJUYgFXM)
![l-addcreate](https://user-images.githubusercontent.com/98424339/198392709-0cd615e5-ed9d-416a-8aa7-9167547596d2.png)
- Welcome/Getting started: [IT Optimization](https://drive.google.com/drive/folders/15iTdooikgnvS1zyTfP1EIJPbqI_AIf99)
![xl-getstarted](https://user-images.githubusercontent.com/98424339/198392950-44e3fc2a-a823-44b7-ae02-25a905fa5861.png)
- Celebration: [Celebration](https://drive.google.com/drive/folders/1lpZRFmfELi306_saVKx2Oai0u-vp13pQ)
![xl-celebrate](https://user-images.githubusercontent.com/98424339/198393284-27be0c75-c340-44fc-b0bd-d0c5ffb68509.jpg)

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly-org/issues/3273 to update design docs. Want to hold on update until this change is made in v5 release.

**Comment by mcarrano** [comment]
Thanks @mcarrano for your work on this. Opened https://github.com/patternfly/patternfly/issues/5217 to begin development.
