### ISSUE TITLE
Toggle components between light and dark themes

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1205]
on the patternfly.org website, We currently don't have a good way to toggle component previews between light and dark themes. Start with considering what the ideal interaction would be and what visual issues might occur in previewing dark theme components. Provide moockups to describe the interaction.

**Comment by maryshak1996** [comment]
WIP Designs: https://www.sketch.com/s/4abdb322-cd19-49af-8dbc-111adf6b071b

**Comment by andrew-ronaldson** [comment]
Since this issue was created we added light and dark theme switching in the masthead for full page theme switching. Based on the change I will be closing this issue but we can revisit if we want to show additional themes in the future.
