### ISSUE TITLE
[new icon] processor

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-design#1210]
I'm working on a project where a user can create a processor for handling events coming in from a source before the event payload is routed to a sink (i.e. a target destination, like sending a slack message or running an ansible playbook).

@lboehling recently created icons that we can use for sources and sinks, so having a processor icon that is visually similar would be ideal:
https://github.com/patternfly/patternfly/issues/5226

A processor can be simple or complex, but these are some of the things that could be defined in a processor:
- filters to decide which events to process
- transformations to either restructure the format of the data, or add/remove data to the payload
- routing logic to decide what the final action should be, with one possible action being to send the event payload to a specific sink.
  - for now, the logic definition will be simple (e.g. if x > 5, then...), but eventually we expect AI models to be supported for handling this routing logic

**Comment by yichen1yu** [comment]
![processor-icon-01](https://user-images.githubusercontent.com/108347329/206270418-20fc46bb-d79f-4cd6-99cb-81fa83392091.svg)
![processor-icon-02](https://user-images.githubusercontent.com/108347329/206270419-7585cea8-6fdd-458c-9552-c6533ae7352a.svg)
![processor-icon-03](https://user-images.githubusercontent.com/108347329/206270421-c3ec409c-1d84-45e4-aaa4-eb114e88a698.svg)

**Comment by yichen1yu** [comment]
Three options are provided above for feedback.

**Comment by sbuenafe-rh** [comment]
Thanks @yichen1yu! 

Of the three options, the last option with the diamond shape resonated the most. I reminded me of a flow diagram and diamonds represented the decision point. Processors in Smart Events, I think act in this manner, filters and/or transforms the data and then moves it through the workflow. I'm also curious to see what it would look like with an arrowhead at the top, just to show that the filter or transformed data gets routed to a sink connector.

cc: @jgiardino

**Comment by yichen1yu** [comment]
![processor-icon-04](https://user-images.githubusercontent.com/108347329/206479897-5c211e8a-1a64-420c-8750-767df0fc75b3.png)

**Comment by yichen1yu** [comment]
Here you go @sbuenafe-rh

**Comment by jgiardino** [comment]
Great suggestion, @sbuenafe-rh! I really like that latest option, @yichen1yu. I think the only final question I have is how does this look at smaller sizes? It looks good really big, but as it scales down, is the diamond appropriately sized? 🤷‍♀️ It's hard to judge that at this scale.

**Comment by sbuenafe-rh** [comment]
@yichen1yu Thank you! LGTM but reading @jgiardino's comment, it would be know how this icon scales?

**Comment by yichen1yu** [comment]
Just replied to Jenn on Slack, I think it still looks good when it's smaller. Tho the diamond shape in the middle tends to look like a circle when you shrink it really small, I enlarged the diamond shape to kinda mitigate t
![Screenshot 2022-12-12 at 10 29 13 AM](https://user-images.githubusercontent.com/108347329/207085240-579c7455-5b66-490d-9782-19a7cb0fe23b.png)
hat.

**Comment by yichen1yu** [comment]
Thanks for sending over the screenshots! Do you know what size are sink and source icons on the screenshots? I am definitely export and same size of processor icon for comparison. I guess it could be the reason that I exported icons in the last comment in png format for convenience and png always looks a bit fuzzier than svg. When it comes to hand over, icons will be in svg format. I reattached svg format for both large and medium size.
![processor-icon-large](https://user-images.githubusercontent.com/108347329/207097041-d7725736-7a4f-4f9b-972c-416d48525ec3.svg)
![processor-icon-medium](https://user-images.githubusercontent.com/108347329/207097042-45b268c3-1ce8-49bd-bb6a-ab80e4dcee9a.svg)

**Comment by jgiardino** [comment]
It looks like they are rendering at 21px wide in that example, but the classes applied also seem inconsistent with what I'm seeing on pf.org. 

Here is an updated screencap where I used the PF icon examples to render the icon, so these should be properly showing at the `md` and `lg` sizes.

<img width="115" alt="image" src="https://user-images.githubusercontent.com/21063328/207109109-3084c724-86ee-400f-9a3f-d4b2c308cfb9.png">

**Comment by yichen1yu** [comment]
![processor-icon-24px](https://user-images.githubusercontent.com/108347329/207136014-2291a601-53aa-4e2f-8480-1989309fcf3c.png)

**Comment by yichen1yu** [comment]
![Updated - processor-icon-16px](https://user-images.githubusercontent.com/108347329/207968102-03d0b497-7a16-4646-b220-b2ee77c48e3e.png)

**Comment by yichen1yu** [comment]
![Updated - processor-icon-24px-09](https://user-images.githubusercontent.com/108347329/207968386-897aaef3-7aaa-48e8-87fb-62af31d46a9d.png)

**Comment by yichen1yu** [comment]
Hey @jgiardino @sbuenafe-rh sorry for the delay here, just be back from f2f today. I'v checked with Michael Celedonia for how to export a more clear version of small size icon and he helped me slightly adjusted to make sure the straight lines are align with the grid. However, since this is png, it will still be a little bit fuzzy. But for the final output, just like the one you used in the screenshot, it will be svg, which will be clearer than png.

 p.s I cannot upload svg since no matter the size of my export, it always auto size to your screen size. 

![Updated - processor-icon-16px](https://user-images.githubusercontent.com/108347329/207971846-3ab9533a-657e-4092-9ade-7cfe70c88220.png)
![Updated - processor-icon-24px](https://user-images.githubusercontent.com/108347329/207971853-6ee5dea7-1c5c-4b68-8bf6-d849f9253c55.png)

**Comment by jgiardino** [comment]
Thanks for the update, @yichen1yu! and thanks for working on this icon 😄
