### ISSUE TITLE
Reconsider click, select, and expand afforances for cards, lists, tiles, and tables

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1211]
The current PatternFly 4 visual affordances for indicating selection and expansion for [cards](https://www.patternfly.org/v4/components/card), [lists](https://www.patternfly.org/v4/components/data-list), [tiles](https://www.patternfly.org/v4/components/tile), and [tables](https://www.patternfly.org/v4/components/table) have been problematic. Some current issues include:

* Current designs are not always accessible to screen readers. See https://github.com/patternfly/patternfly-design/issues/1142

*  The blue border feels overused. It has been used in places to indicate selection as well as expansion. It has also been problematic when a component like a table is adjacent to another element (like navigation).

* It is unclear how to differentiate single and multiple selection for global actions vs examination of details (e.g. primary-detail views).

The PatternFly v5 release presents an opportunity to rethink these designs and come up with an approach across components that is more consistent, usable, and accessible. The solution should consider hover as well as active/selected states for all of these components.

**Comment by mcarrano** [comment]
@pankajshivpuje @tiyiprh I have opened this new issue and assigned to both of you to work together on a more consistent approach that spans components. I will close the existing issues assigned to you. Let me know if you have any questions.

**Comment by mcarrano** [comment]
@pankajshivpuje @tiyiprh I was having some conversation with @mceledonia @mmenestr and @jessiehuff to try to clarify what our next steps should be regarding this issue. We reached a few conclusions that I wanted to share with you.

* First to help clarify the difference between card actions, we should differentiate "clickable" cards from "selectable" cards. In a bit of research I've done, looks like this is what some other design systems do. See https://carbondesignsystem.com/components/tile/usage/#tile-variants and https://clarity.design/documentation/cards#top. Going forward let's refer to a card that has an associated link or action when you click it a "clickable" card and cards with selection (either single or multiple) as selectable cards. I will propose this naming change to the component library as part of our PatternFly 5 release. Does this make sense to you also? Hopefully it helps to claify some things.

* We currently have multi-selectable cards that use checkbox select, but we should also add single (radio) select cards. This will roughly give us consistency with what Carbon supports.

* You are probably noticing that tiles and cards are used interchangeably by other design systems. Perhaps to simplify things we should drop Tiles and incorporate everything into the Card component? If so, we should make sure that layout variants for Tiles are incorporated into Cards (i.e. a simple/compact card that could be used on a form, for example).

Let me know if these proposals make sense and we can proceed forward with working through some details. Hopefully this clarifies the problem a bit. Whatever we design for Cards should also be made consistent across Data Lists and Tables with clickable and selectable. Let's discuss more at our next meeting.

**Comment by tiyiprh** [comment]
@lboehling @mceledonia Wanted to get some feedback! From our discussion today, I doubled the width of the blue on the "click" state on the table row with a primary detail and I think that does help make it more apparent, especially on a full-width table. cc @mcarrano 

![Table with primary detail](https://user-images.githubusercontent.com/98424339/207953382-da0b0f04-e181-4ebf-8a73-32d534a74f7e.png)
![Full table with primary detail](https://user-images.githubusercontent.com/98424339/207953387-d804b93a-2f33-4059-8149-ebfbff1263ba.png)

**Comment by tiyiprh** [comment]
@mcarrano Per our conversation yesterday, see updates below. We can also review this in tomorrow's design share.

### Updates to the table rows behavior/interactions:

1. Selectable table rows: (same behavior/interaction as current)
There is a hover on the checkbox via mouse and keyboard. Selection is done by clicking the checkbox and the visual affordance is the checkbox appears to show the row is selected. There is no hover on the row itself.

2. Expanding table rows:
There is a hover on the caret via mouse and keyboard. Expansion is done by clicking the caret. There is no hover on the row itself. **Updates**: Once the row expands, the visual affordance will no longer be the left blue border to indicate expansion, instead it will be the removal of the bottom border of the parent row and the growing of the row into the expanded row content. The expanded row content will also be indented to be in line with the first column content. 
![Expanded Table Row](https://user-images.githubusercontent.com/98424339/211363248-97dd0289-21cf-49dc-8d04-1d0fe58f5c3f.png)

3. Clickable table rows [**primary-detail view only**]:
There is a hover on the row via mouse and keyboard (drop shadow and blue border). The row can be clicked to produce the action of opening the primary-detail drawer. **Updates**: Once the primary-detail drawer opens, the visual affordance will be updated to be a thicker left blue border (double the width of current) so it can be clearly seen in both cases where the table has content padding and where it doesn't. (same images as the above comment)
![Primary-detail no padding](https://user-images.githubusercontent.com/98424339/211367081-92855f0e-e6a1-4d26-a669-1d4443c41e84.png)
![Primary-detail w padding](https://user-images.githubusercontent.com/98424339/211367083-32f3396b-05a9-479b-bdf8-a9fcdb2c4625.png)

### Updates to the card behavior/interactions:

1. Selectable cards:
**Updates**: There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would select the card and there is now more visual affordance to the selected state of the card with the addition of the background color and blue border around the body of the card. This mirrors Carbon's interaction for tiles.
![Selectable Card](https://user-images.githubusercontent.com/98424339/211890403-6180300b-e942-467b-856e-6883cd9dc6b4.png)

2. Single-selectable cards (new):
There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would select the card and there is now more visual affordance to the selected state of the card with the addition of the background color and blue border around the body of the card.
![Single Selectable Card](https://user-images.githubusercontent.com/98424339/211891329-ba48a1b8-3e57-4c09-963d-522841d1227f.png)

3. Clickable cards:
There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would open the primary-detail drawer. **Updates**: There is now more visual affordance to the "clicked" state of the card with the addition of the background color and blue border around the body of the card.
![Clickable Card](https://user-images.githubusercontent.com/98424339/211892734-e934641f-0fa1-457f-a77f-e605b09e14ac.png)
![Clickable Card w primary detail](https://user-images.githubusercontent.com/98424339/211892745-243edd4b-1012-400d-aecc-d36363767ffa.png)

4. Selectable & clickable cards:
There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected/clicked state. Clicking anywhere on the card would open the primary-detail drawer. To select the card, you would need to click the checkbox. The clicking action would supersede the selecting action when both actions are available.
![Selectable   Clickable Card](https://user-images.githubusercontent.com/98424339/211893307-20d36dbb-4a10-4977-af5c-f22ea345ba71.png)

**Comment by mcarrano** [comment]
@jessiehuff please take a look at this latest proposal. Do you see any a11y issues with this?

**Comment by jessiehuff** [comment]
I really like the updates, particularly for the different selectable options! I think that the checkboxes and radio buttons make it clearer what the selectable interaction is. I think the only one that I have concerns with is the clickable examples. The hover styling probably makes it clear enough for sighted users, but I wonder what would tell a screen reader that it is clickable? Do we expect these cards or table rows to semantically be buttons or links? If they're buttons or links, the screen reader user will know that they're interactive/clickable. So if that's our intention, I think this will work. But if we don't want to semantically make them something like a button or link, I would just pose the question of how we'll let the users know that they can click on the item. That being said, I don't think that concern inherently holds this back (as long as we have a path forward for that question), and I really like the updates!

**Comment by mcarrano** [comment]
Based on discussion from meeting today with @tiyiprh @mceledonia @mcoker @jessiehuff @nicolethoen we will modify no.4 above (clickable and selectable cards) to require explicit and separate affordances for multiple actions, i.e. if the card is both clickable and selectable, selaction will be using a checkbox, but there must be another element on the card to fire the click action. This could be as simple as linking the card title or adding a "View more" button. Multiple actions could be added inside of a card in this way. The body of a card will only be used to trigger an action when there is a single, unambiguous action within the card.

**Comment by tiyiprh** [comment]
Updated comment with the most up-to-date info.
Sketch file: https://www.sketch.com/s/24c4707b-3dc6-49c2-b3b5-2a42718b74ba

### Updates to the table rows behavior/interactions:

1. Selectable table rows: (same behavior/interaction as current)
There is a hover on the checkbox via mouse and keyboard. Selection is done by clicking the checkbox and the visual affordance is the checkbox appears to show the row is selected. There is no hover on the row itself.

2. Expanding table rows:
There is a hover on the caret via mouse and keyboard. Expansion is done by clicking the caret. There is no hover on the row itself. **Updates**: Once the row expands, the visual affordance will no longer be the left blue border to indicate expansion, instead it will be the removal of the bottom border of the parent row and the growing of the row into the expanded row content. The expanded row content will also be indented to be in line with the first column content. 
![Expandable-3](https://user-images.githubusercontent.com/98424339/213572121-2101a8f1-3f7c-406d-99e5-7d7a07420f5f.png)

3. Clickable table rows [**primary-detail view only**]:
There is a hover on the row via mouse and keyboard (drop shadow and blue border). The row can be clicked to produce the action of opening the primary-detail drawer. **Updates**: Once the primary-detail drawer opens, the visual affordance will be updated to be a thicker left blue border (double the width of current) so it can be clearly seen in both cases where the table has content padding and where it doesn't.
![Primary-detail no padding](https://user-images.githubusercontent.com/98424339/211367081-92855f0e-e6a1-4d26-a669-1d4443c41e84.png)
![Clickable-3](https://user-images.githubusercontent.com/98424339/213572218-c7ce26bf-e628-4115-b590-61379651df09.png)


### Updates to the card behavior/interactions:

1. Selectable cards:
**Updates**: There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would select the card and there is now more visual affordance to the selected state of the card with the addition of the background color and blue border around the body of the card. This mirrors Carbon's interaction for tiles.
![Selectable Card@1x](https://user-images.githubusercontent.com/98424339/213583757-ae226d0d-f0c0-405f-9d8e-ea801f90928e.png)

2. Single-selectable cards (new):
There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would select the card and there is now more visual affordance to the selected state of the card with the addition of the background color and blue border around the body of the card.
![Single Selectable Card@1x](https://user-images.githubusercontent.com/98424339/213583777-c13fa034-bd9d-4b6a-b315-b305572a7a47.png)

3. Clickable cards:
There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would trigger the action: ex. opening the primary-detail drawer, navigating to a new page, etc. **Updates**: There is now more visual affordance to the "clicked" state of the card with the addition of the background color and blue border around the body of the card.
![Clickable Card@1x](https://user-images.githubusercontent.com/98424339/213583818-a319803f-e7ad-47e9-ad31-30d3ae1bc8aa.png)
![Clickable Card w primary detail](https://user-images.githubusercontent.com/98424339/211892745-243edd4b-1012-400d-aecc-d36363767ffa.png)

4. Selectable & clickable cards:
Moving away from nested interactions and requiring separate affordances when there are multiple actions within a card. The body of the card being a trigger to an action will be reserved for when there is a single action within the card, like the above examples. 
There is a hover on the card title and checkbox via mouse and keyboard. Clicking on the title will trigger the action of either opening a primary-detail drawer, navigating to a new page, etc. If opening a primary-detail drawer, the card will appear with a blue border to indicate that the card has been clicked. To select the card for a global action, the user would need to click the checkbox. Below are examples of the different states in a white and gray background.
![Selectable   Clickablev3 gray bg@1x](https://user-images.githubusercontent.com/98424339/213577281-d0d8c93d-9961-4cd4-82d9-eaff83d0d19e.png)
![Selectable   Clickablev3@1x](https://user-images.githubusercontent.com/98424339/213577285-2dd4dbd5-7bfc-4938-880e-4143ba032aaa.png)

### **Visual Specs:** (Selectable only & Clickable only cards)

1. Default card state uses default card component

2. Hover card state: 
- Fill: #FFFFFF
- Shadows: #000000, Alpha:18 X:0, Y:8, Blur:16; #000000, Alpha:8 X:0, Y:0, Blur:6
- Inner Shadows: #F5F5F5, Alpha:100, X:0, Y:-200, Blur:0

3. Focus card state uses PF Focus State layer

4. Select card state:
- Fill: #FFFFFF
- Borders: 18. $pf-color-blue-400, Center, Width:1
- Shadows: #000000, Alpha:18 X:0, Y:8, Blur:16; #000000, Alpha:8 X:0, Y:0, Blur:6
- Inner Shadows: #F5F5F5, Alpha:100, X:0, Y:-200, Blur:0

5. Disabled card state:
- Fill: #FAFAFA
- Borders: 5. $pf-color-black-300, Center, Width:1

### **Visual Specs:** (Selectable & Clickable cards)
1. Default card state uses default card component

2. Hover card state uses the default card component with text: 08. Link (RHT rg 16) 2.pf-global--link--Color--hover.

3. Select card state uses default card component

4. Click card state:
- Fill: #FFFFFF
- Borders: 18. $pf-color-blue-400, Center, Width:1
- Shadows: #000000, Alpha:18 X:0, Y:8, Blur:16; #000000, Alpha:8 X:0, Y:0, Blur:6
- Inner Shadows: #F5F5F5, Alpha:100, X:0, Y:-200, Blur:0

5. Disabled card state:
- Fill: #FAFAFA
- Borders: 5. $pf-color-black-300, Center, Width:1

**Comment by mcarrano** [comment]
Thanks @tiyiprh !  I've added this design detail to https://github.com/patternfly/patternfly/issues/5264 and https://github.com/patternfly/patternfly/issues/5347 to begin development.

**Comment by mmenestr** [comment]
Created this design doc issue for it: https://github.com/patternfly/patternfly-org/issues/3409

**Comment by lboehling** [comment]
Created design kit issue here: https://github.com/patternfly/patternfly-design-kit/issues/608
