### ISSUE TITLE
Colors - PF colors for severity levels

### ISSUE THREAD

**Issue by jamestalton** [patternfly/patternfly-design#1219]
Several products need colors to indicate severity levels.
Instead of the products each defining these separately PF should provide those colors. 
That way that can be used for icons, text, and charts consistently.
In addition, PF can adjust the colors for the PF dark theme.

Different use cases might have a different number of severity levels, usually 3, 4 or 5.

Examples: Lowest, Low, MediumLow, Medium, MediumHigh, High, Highest, Critical

**Comment by andrew-ronaldson** [comment]
@smckinno is picking this up. Wanted to share the progress with a  link to the [Sketch file](https://sketch.com/s/6cd8d222-b3cd-461d-b15d-d1d4ee331b48) 
<img width="704" alt="Screenshot 2023-08-22 at 10 42 44 AM" src="https://github.com/patternfly/patternfly-design/assets/28658548/1693ab57-83d7-4878-b844-691a99bd8825">
