### ISSUE TITLE
Vertical Navigation: Examples are for 2-Level nav only

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#122]
While the design page includes for 2-Level (Secondary) and 3-Level (Tertiary) navigation options, the examples on the Overview and Code pages are only for 2-Level Nav.

**Comment by mcarrano** [comment]
@LHinson Want to get you opinion on this one.  This relates to the rework we set out to do a while ago for our documentation of Vertical Nav.  There is a story that I had started to works on (https://patternfly.atlassian.net/browse/PTNFLY-2341) but I think this got pushed to the backlog in favor of other priorities.

Question is whether to revisit this now or just defer until we refactor content for the new website. Thoughts?

**Comment by LHinson** [comment]
I think that this will be addressed with the website refactor and showcases (which show variations) so think we should close. Any concerns @mcarrano?

**Comment by mcarrano** [comment]
I'm good with that.  Will close
