### ISSUE TITLE
Combine File Upload and File Upload Multiple into a single component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1223]
Currently [File Upload](https://www.patternfly.org/v4/components/file-upload) and [File Upload - Multiple](https://www.patternfly.org/v4/components/file-upload---multiple) are separate components to address distinct use cases. A more usable solution would be to combine these into one component. File Upload Multiple supports all upload use cases excepting the ability to preview a text file. Let's look at this to see if this can be added to File Upload Multiple allowing us to deprecate the single File Upload component.

Use cases:
* Upload a single text file and give users the option to edit.
* Upload a single binary file (no preview)
* Upload multiple binary files in a single operation (no preview)
* Select file to upload either by browsing the file system or drag and drop.

**Comment by mcarrano** [comment]
@yichen1yu Thanks for taking this on. I suggest starting be using the multiple file upload as a base and thinking about how to incorporate a single file text preview as an option. @megan-hall worked on this previously and should be able to provide any addition background about earlier design decisions and/or Sketch files so you don't need to start from scratch. Let me know if you have questions.

**Comment by yichen1yu** [comment]
Here is the final design flow https://www.sketch.com/s/333bbc45-e187-4e1a-8c4e-f122ceab05ed

**Comment by andrew-ronaldson** [comment]
Closing v5 issue. Will make on for v6
