### ISSUE TITLE
Define states for Stateful button

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1225]
Need states for this new button variant.

**Comment by mcarrano** [comment]
Requirements and design proposal [WIP]: https://docs.google.com/document/d/14osQnnhyLV2kW-jtwUCh31ndmfm-g3OgUxAqYujfu7k/edit?usp=sharing

**Comment by smckinno** [comment]
Here are the mocks so far: https://www.sketch.com/s/98c69153-356d-4ca0-80dd-b090aa7407ba/p/E5780C07-E53B-4AC6-9948-D5E9C4357B2F/canvas

**Comment by smckinno** [comment]
Google drive with all the file illustrations: https://drive.google.com/drive/folders/1A6cqtWnJt4iWhzLlHMO9LRZN6Y-LXZNS?usp=sharing
Design guidelines for creating illustrations in the future: https://docs.google.com/document/d/1CSvVbl9fCnVm1X4z194zoCPJFlwz0QY0OXBDjWoDBtY/edit?usp=sharing

**Comment by andrew-ronaldson** [comment]
Closed for this issue in core https://github.com/patternfly/patternfly/issues/5129
