### ISSUE TITLE
Alert icon shape update for better accessibility

### ISSUE THREAD

**Issue by heyethankim** [patternfly/patternfly-design#1227]
## Requesting new features, enhancements, or design changes to PatternFly
**Describe the use cases and requirements of the new feature or enhancement you are requesting.**

Could we afford a different shape for each alert icon container for better accessibility? 

1. "Circle" is used for OK and success. "Hexagon" is used for failure like the stop sign on the road. Wonder if this could work better in the user's mindset at a subconscious level. 
2. Could we use the square for the informational message? Basically this way, each icon gets a different shape. 
3. Using blue instead of green may be too much, but you can see the difference in the color blind vision. 
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/84546841/212420510-d74076e0-bbfc-47da-a7f0-c044af836de8.png">

**Comment by heyethankim** [comment]
FYI. @mceledonia @mcarrano, @imjoyjean

**Comment by mcarrano** [comment]
@heyethankim thanks for submitting this. You make a good point about accessibility of the alert icons. @mceledonia and I are currently working at the DPO level to come up with a consistent alert language and icons across Read Hat. This will be a good topic to take into that discussion that will influence future PatternFly directions.

**Comment by smckinno** [comment]
Wrapping up this issue - tied it to another ticket ( Colors - PF colors for severity levels #1219) 

Here is the documentation/research https://docs.google.com/document/d/1-4ocLt9Ijcu5amiX7u_U6au17N4wCqDTYGh8ZiPu7mQ/edit?usp=sharing
Here is the sketch file : https://www.sketch.com/s/6cd8d222-b3cd-461d-b15d-d1d4ee331b48

**Comment by andrew-ronaldson** [comment]
We are also working on aligning our icons with the RH branding team. I'll relay this feedback to the team
