### ISSUE TITLE
Redesign PF.org Homepage

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#1229]
As part of the website refresh, we want to redesign the homepage of pf.org. Designs should match the look and feel of PFV5 refreshed visuals and include updated copy/content provided by Erin.

If recent theme user research results suggest an overwhelming preference for dark theme, we should consider making that the emphasis with the homepage redesign.

**Comment by mcarrano** [comment]
@lboehling can you add your design links here? Then I will close this.

**Comment by mcarrano** [comment]
Looks great @lboehling I only had one question/comment that I left in the Sketch file.

@jenny-s51 let us know if you see any issues with these designs.
