### ISSUE TITLE
PF.org Homepage Content Refresh

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#1230]
As part of the website refresh, we are looking to redesign our homepage (design issue #1229). We have previously noted that the homepage could provide more useful information for our users (see #1069). We would like updated content/copy for the homepage refresh.

**Comment by edonehoo** [comment]
adding a link to [a google doc](https://docs.google.com/document/d/1I2JXqPYyMf9kLmqRyGt0koCXY7JrI4vQ42Neyi9Bxlg/edit?usp=sharing), which has initial notes, ideas, ramblings, etc. Still fiddling occasionally, but wanted to share and open it to feedback/more suggestions!

**Comment by edonehoo** [comment]
Finalized copy is on the [first page of this doc.](https://docs.google.com/document/d/1cFNqaVCfLA6aArJgZOqsfBFiftvTnyBLQ_io8QB25yk/edit?usp=sharing)

**Comment by mcarrano** [comment]
This looks good to me (just left one comment in the doc). @andrew-ronaldson perhaps also review.
