### ISSUE TITLE
Redesign PF Logo/Brand elements

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#1231]
As part of the v5 visual work and website refresh, we want to update the PF logo/brand to reflect our new visual direction. See [this deck](https://docs.google.com/presentation/d/10btvvNBXACyWTS3HjvxL2Br6Wedup2rKtqtuc94FziA/edit?usp=sharing) for more info on why we want to refresh the logo. 

This work includes
-finalizing design options
-sharing options to larger community for feedback
-updating finalized logo and brand elements
-identifying where the logo needs to be updated 
-creating final lockups/svg files to hand off to development

We may also want to consider what elements are needed for updating our social media/blog visuals.

**Comment by mcarrano** [comment]
Can we identify what follow-up is needed for this?

**Comment by lboehling** [comment]
Here is a folder with final lockups: 
[PatternFly Logos.zip](https://github.com/patternfly/patternfly-design/files/11491424/PatternFly.Logos.zip)

the folder has pngs and svgs of favicons, full horizontal logos, logos without text, and outline icon versions of logo.
