### ISSUE TITLE
Popover Triggered by Mousehover

### ISSUE THREAD

**Issue by heyethankim** [patternfly/patternfly-design#1235]
## Requesting new features, enhancements, or design changes to PatternFly

PatternFly has [Tooltip](https://www.patternfly.org/v4/components/tooltip) and [popover](https://www.patternfly.org/v4/components/popover).

If the information is short, use tooltip, which is triggered by mouse hover.
If it is long, use popover, which is triggered by a click.

In ACM Governance, we need two different interactions for a hyperlink. 

**On click**, it links to a detail page.
**On hover**, it triggers a popover with a long description of a policy.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/84546841/214381075-505291d4-86fb-45d6-a208-e527bf908a6a.png">

Try the **prototype**: https://marvelapp.com/prototype/68dcjba/screen/90255658 

There could be thousands of policies like Verizon but we don't control the policy names, which are not always easy to understand. So users should be able to scan through what individual policies are about.

We may utilize the current tooltip definition, which is rendered as white text on the black background, but it should be able to be triggered for a link.

**Comment by mcarrano** [comment]
@heyethankim why can't you use a Tooltip here? Seems like that would give you the interaction that you want. The problem with triggering a popover on hover is that they require the user to tack an action to close them, which I don't think is what you want.

**Comment by heyethankim** [comment]
Right! As I said, we could definitely utilize the current tooltip definition. Since this kind of behavior was not documented (a tooltip from a hyperlink) in the page, I wanted to address it. 

Could we add this in the page?

**Comment by mcarrano** [comment]
By page, do you mean update the design guideline? Sure, that's easy enough to do. @heyethankim would you be interested in contributing that? @mmenestr can help you get started.

**Comment by heyethankim** [comment]
Yes. I would love to do that. Thanks, @mcarrano. @mmenestr, Could you guide me?

**Comment by mmenestr** [comment]
Created this [docs issue](https://github.com/patternfly/patternfly-org/issues/3385) and slacked Ethan to discuss!

**Comment by mcarrano** [comment]
Closing in favor of the Org issue referenced above.
