### ISSUE TITLE
Add tags for Demos and Deprecated components

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1239]
For PatternFly 5, we will combine Demos and Components into a single section on the website, but want a way to tag items in the navigation and/or page heading to indicate is they are a demo. Similarly, want to be able to tag deprecated components.

See Org issues: https://github.com/patternfly/patternfly-org/issues/3370 and https://github.com/patternfly/patternfly-org/issues/3371

cc @evwilkin

**Comment by lboehling** [comment]
Designs can be found here: https://www.sketch.com/s/66bb846a-6d69-45c2-922b-e58667563549
