### ISSUE TITLE
Forms Patterns: Numerous inconsistencies between Forms design and other patterns

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#124]
The Forms pattern has numerous inconsistencies with other patterns in the library.  Some specific issues are:
 - Inconsistency between button usage in examples and other button guidelines in PatternFly.
- Inconsistency between labeling recommendations between Forms and Form Field Layout pages.

Current Forms pattern only addresses simple data entry forms focusing on modals. 

Recommendation:  Entire Forms section should be reconsidered using a top-down approach.  What are the patterns we need?  How do we leverage existing work that was done?  Where are the gaps.

**Comment by LHinson** [comment]
@mcarrano will you be addresses these concerns this sprint? If so, will you update this issue appropriately? Thanks!

**Comment by LHinson** [comment]
@mcarrano just a reminder to make sure to close issues as you address the concerns. nice to reference PR numbers on the issues as well. Thanks!

**Comment by mcarrano** [comment]
I am closing this as these issues are currently being addressed.
