### ISSUE TITLE
Create component illustrations for moved items

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1242]
For PatternFly v5, several pages that previously appeared in Demos will be moved to Components. Therefore they will require component illustrations to show on the new component catalog page (https://patternfly-org-pr-3181-v4.surge.sh/v4/components/view-all-components). New illustrations are required for the following components:

* Composable menu
* Date and time picker
* Password generator
* Password strength

The process for creating new illustrations is outlined here: https://github.com/patternfly/patternfly-org/wiki/Adding-new-components-to-the-website

**Comment by smckinno** [comment]
[Mocks
](https://www.sketch.com/s/7bec720b-7f77-4f22-99a1-a48735c0b147/p/256020A8-9189-4080-86C5-1DBD14A1A26D/canvas)

**Comment by mcarrano** [comment]
These look great @smckinno . @mceledonia @mmenestr can you also take a look at these?

**Comment by mmenestr** [comment]
Agreed, these look great! I like option 1 for the menu, without the clicking hand - though I wonder what that lighter grey line is on the top left of the expanded menu?

And my only other comment is, in some places we use line for text, but in the date picker we're using actual text. Does that matter (?) I know it's kind of a weird one but just wanted to bring it up to see what you all thought!

**Comment by smckinno** [comment]
@mmenestr That lighter gray is supposed to be the "title" of the 3 dropdown options but I can easily get rid of that line! 

I know it may seem odd but using text in this case is the best way to communicate what the component is - also we use text for just the date picker component as well. So in simple, text in this case is okay :)

**Comment by mmenestr** [comment]
@smckinno kk then I approve ;)

**Comment by mcarrano** [comment]
Thanks for your work on this @smckinno . I've opened https://github.com/patternfly/patternfly-org/issues/3465 to get these onto the website for v5.
