### ISSUE TITLE
Define "Tile" variant of the Card component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1244]
[Cards](https://www.patternfly.org/v4/components/card) and [Tiles](https://www.patternfly.org/v4/components/tile) appear to be redundant as tiles are really just more specific versions of a clickable card. To simplify this, we should deprecate the Tile component in favor of a card variant that embodies all the same properties. Specifically, tiles need to be compact, clickable, and retain state. They should not be selectable or contain embedded actions.

Need to define what a tile variant of the card should look like so examples can be added to the Card component. See https://www.patternfly.org/v4/components/tile for existing tiles and also https://github.com/patternfly/patternfly/issues/5267 which identifies some enhancements to the Tile component for more information.

**Comment by yichen1yu** [comment]
@mcarrano Sure I will. Tina has reached out to me to offer help earlier. I will keep both of them in loop for this ticket.

**Comment by tiyiprh** [comment]
Here is the [link](https://www.sketch.com/s/24c4707b-3dc6-49c2-b3b5-2a42718b74ba) to the Sketch file!

**Comment by mcarrano** [comment]
@yichen1yu I reviewed your documentation and left a couple of comments. But otherwise this is looking good. @mceledonia @andrew-ronaldson can you also take a look? I believe that based on an earlier issue, we wanted left aligned tiles also for better alignment with other Red Hat design systems. @mceledonia can you confirm? Thanks.

**Comment by andrew-ronaldson** [comment]
Designs and docs look good. This is a lead up to this core issue https://github.com/patternfly/patternfly/issues/5325
