### ISSUE TITLE
Revisit Community Page design on PF.org 

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#1247]
We are proposing to move the "flyer fundamentals" section from the [homepage](https://www.patternfly.org/v4/) to the [community](https://www.patternfly.org/v4/community) page on pf.org. Doing so will require layout changes to the existing community page. 

**Proposed changes to community page**
-Add in flyer fundamentals section
-revisit layout (there's a lot of text, anyway to consolidate?)
-refine styles (the card actions are using huge inline links, probably not the right button component to use here) 
-revisit imagery/illustrations (lower priority, but would be nice to have some more custom illustrations here)

**Comment by andrew-ronaldson** [comment]
Closed with org issue [3752](https://github.com/patternfly/patternfly-org/issues/3752)
