### ISSUE TITLE
Aligning on Patternfly buttons

### ISSUE THREAD

**Issue by kelseamann** [patternfly/patternfly-design#1250]
Requesting style guidelines on how Primary, Secondary and Tertiary buttons are grouped to create hierarchy in actions.
- Groups of buttons are used to navigate wizards, and are present in the kebab (top row) in tables as well as the bottom navigation of Wizards, as well as in other miscellaneous areas.
- The guidelines for sorted table and table on Patternfly show different types of buttons in the kebab. Seeking alignment on how groups of buttons should be displayed and creating standard hierarchy.
- A part of HMS Table audit audit, no set end date

<img width="922" alt="Screenshot 2023-03-31 at 1 55 38 PM" src="https://user-images.githubusercontent.com/91503095/229194610-f66592a6-7802-4276-8012-d22b6d5259cd.png">
<img width="815" alt="Screenshot 2023-03-31 at 1 56 12 PM" src="https://user-images.githubusercontent.com/91503095/229194726-4e149596-b7f2-474c-9eed-731e224c6228.png">

**Comment by nicolethoen** [comment]
Note: once the guidelines are updated, we should note which demos/examples in the component docs need to be updated to match these guidelines. We can open follow up issues for that

**Comment by mmenestr** [comment]
@mcarrano just closed this PR to address button usage in toolbars - https://github.com/patternfly/patternfly-org/pull/3476 
I believe this issue can be closed now
