### ISSUE TITLE
New component illustrations needed

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1259]
For the PatternFly 5 release, we are adding the new All components view that displays a card with a thumbnail illustration for each component: https://patternfly-org-pr-3512-v4.surge.sh/v4/components/all-components

In testing this view, I've found that we are missing illustrations for the following components:

* [Form select](https://www.patternfly.org/v4/components/form-select)
* [Icon](https://www.patternfly.org/v4/components/icon)
* [Time picker](https://www.patternfly.org/v4/components/time-picker)
* [Title](https://www.patternfly.org/v4/components/title)
* [Timestamp](https://www.patternfly.org/v4/components/timestamp)

**Comment by smckinno** [comment]
https://www.sketch.com/s/7bec720b-7f77-4f22-99a1-a48735c0b147/p/256020A8-9189-4080-86C5-1DBD14A1A26D/canvas 
<img width="192" alt="Time picker" src="https://github.com/patternfly/patternfly-design/assets/104632874/3701dff2-3f01-4c99-90da-aeab2debf26a">
<img width="192" alt="Time stamp" src="https://github.com/patternfly/patternfly-design/assets/104632874/e047056f-8c56-49eb-8500-439a011a695f">
<img width="192" alt="Title" src="https://github.com/patternfly/patternfly-design/assets/104632874/537b7e1d-6161-4149-946a-7db6133fcb74">
<img width="192" alt="Form select" src="https://github.com/patternfly/patternfly-design/assets/104632874/ec65bcca-278e-42c1-bfc4-9edf78490600">
<img width="192" alt="Icon" src="https://github.com/patternfly/patternfly-design/assets/104632874/142bdb4b-4cd6-465d-979c-90796ca20b22">
