### ISSUE TITLE
PF5 Logo Variant for PatternFly Extensions

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-design#1262]
A logo variant was requested for PatternFly Extensions. Either choose from existing variants or create a new one. Define a strategy as to where and how it appears in context, and consider what else qualifies for a logo variant.

Existing ideas/examples attached
![image](https://github.com/patternfly/patternfly-design/assets/30935938/7fe8c097-afcc-42de-81c0-4a8865c3c809)

![image](https://github.com/patternfly/patternfly-design/assets/30935938/c22753c3-5b82-415f-bdc9-12158c0c1b6c)
![image](https://github.com/patternfly/patternfly-design/assets/30935938/ed771a6f-a8d0-468a-a660-fc7af93ac825)

**Comment by mcarrano** [comment]
@mceledonia based on the Leads meeting today, sounds like we want to go with one of the purple variants? This should be targeted for the new Extensions landing page on the website. Can you work with @edonehoo about where to fit that in?

Landing page issue: https://github.com/patternfly/patternfly-org/issues/3486

**Comment by andrew-ronaldson** [comment]
After discussing with @jessiehuff we decided on this variation for extensions.


![Image](https://github.com/patternfly/patternfly-design/assets/28658548/23e58b20-8102-4dbb-8e5b-fb4d0c21989b)
