### ISSUE TITLE
Revisit drill down nav visual design

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1263]
In reviewing the Drill Down navigation variant for PF v5, it was noted that the current highlighting and hover effects may be confusing. See the demo here: https://patternfly-react-pr-9255.surge.sh/components/navigation/react-demos/drilldown-nav/

This is a follow-up to the discussion in this PR: https://github.com/patternfly/patternfly-react/pull/9255

**Comment by andrew-ronaldson** [comment]
Closing this issue. The same treatment exists across the rest of the v6 navigation and there is a difference between our hover and clicked states for text colours. The cursor change to the hand also indicates the hovered vs Active items
