### ISSUE TITLE
Create a recommendations for animations on PatternFly components

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1266]
## Goal
Provide a consistent implementation of animations across components. These animations should be subtle with fallbacks for users that have reduce-motion enabled in their OS.

## Definition of done

- [x] Audit all PatternFly components to determine if animations are required

**Comment by andybraren** [comment]
Very brief `.1s` transitions for the hover states of buttons and cards to start would get us pretty far. 👍

**Comment by kaylachumley** [comment]
Animation document: https://docs.google.com/document/d/1tumxUYRQqoqrrfZ1VLoNk6r7hpi3Qnc3BWUDQEXjHJw/edit?usp=sharing

**Comment by kaylachumley** [comment]
[This document](https://docs.google.com/document/d/1tumxUYRQqoqrrfZ1VLoNk6r7hpi3Qnc3BWUDQEXjHJw/edit?usp=sharing) is ready for review! Take a look and leave comments or add anything as you see fit. There is a lot of pre-existing information on micro animations in various docs and excel sheets that I tried to reference in my main doc. @andrew-ronaldson
