### ISSUE TITLE
Bug - [Switch] - [Doesn't support popover]

### ISSUE THREAD

**Issue by Misjohns** [patternfly/patternfly-design#1268]
If a popover is required for a switch element the question-circle icon doesn't wrap along with the switch label. When the label changes from a short label to a long label the question-circle icon can appear far away from the switch element.

The question-circle icon should appear roughly 8px from the last character in the label.
![image](https://user-images.githubusercontent.com/97301019/236934620-02402b18-1241-47c2-9716-77f6d1bcecb0.png)

This is how it currently appears when user reduces their screen width:
![image](https://user-images.githubusercontent.com/97301019/236934347-10b223f3-d288-4c8b-a27e-68622c7a81d8.png)

We are using this in RHTAP for Summit

**Comment by andrew-ronaldson** [comment]
Hey @Misjohns 
We talked about in a PatternFly meeting and thought this may be another option for this issue. Would either of these options work for your use case? 

![Image](https://github.com/patternfly/patternfly-design/assets/28658548/3f003aa0-a59f-436a-bb8f-a6574a51b28b)

**Comment by Misjohns** [comment]
@andrew-ronaldson Having the ? beside a label that sits above the switch or check box resolves the accessibility concern. I'm worried that it adds more text/noise to the screen. In some cases, the additional label could provide helpful context but fr other cases, the label would be very redundant with the switch/radio button text (as in your example). Maybe we need to document that this pattern would **only** be required when a popover is needed vs. every instance of a check box or switch.

**Comment by andrew-ronaldson** [comment]
Closing as stale
