### ISSUE TITLE
Toggle groups(Exploratory): Rethink the responsive behaviour

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1279]
## Enhancement objective
The current toggle group can wrap items or add a horizontal scroll bar. Stacking the items results in a long block of buttons that can take up too much vertical space. Design should look at multiple solutions to improve the experience on smaller screens.

**Comment by heyethankim** [comment]
To give more context, the screenshot below is what I found when I resized it to the smallest. But what if we have more than 4 toggles? I asked a question if we have any wrap (responsive) version of the toggle group for the smallest browser. Originally I thought it would similarly behave like a [dropdown](https://www.patternfly.org/components/menus/select) without the help text (Select…). 

Dallas Nicol suggested that we should consider "Flex." Here are the Slack discussion link: https://redhat-internal.slack.com/archives/C04JMHKSD9C/p1702912912104979  

![image](https://github.com/patternfly/patternfly-design/assets/84546841/edaffb86-4b9e-4ccf-8ace-b4f0eb41f55c)

**Comment by andrew-ronaldson** [comment]
@kaylachumley is going to be looking into this. Thanks @heyethankim!
We have an issue in [core](https://github.com/patternfly/patternfly/issues/6202) as well but we can keep design work on here.

**Comment by kaylachumley** [comment]
Alternative to stacking: turn into menu toggle

**Comment by mcoker** [comment]
@kaylachumley from core's perspective, I don't think it's a heavy lift. I think the tricky work would mostly be on the react side. From what I can tell, we would basically just swap the toggle group for a select that can support a single-select or multi-select.

Some ideas...

If it's a single-select toggle group, it seems like a default "select" menu may work well where the text in the menu toggle matches the currently selected menu toggle. And if it's a multi-select, you would pass a label of some sort to be used for the toggle text that indicates you need to select items in the menu. That label could also be used with a single-select toggle group, too, if you didn't want the toggle text to reflect the currently selected item. And an icon-only toggle group could accept a label per item/toggle, and the label is used as the text (along with the icon) in the menu as menu items. That label could work with (or come from) the `aria-label` prop we currently support on menu toggle items.

**Comment by andrew-ronaldson** [comment]
@tlabaj wanted to get your thoughts on this as well.
