### ISSUE TITLE
Missing icons in topology view of the Node Network State

### ISSUE THREAD

**Issue by yfrimanm** [patternfly/patternfly-design#1283]
## Requesting new features, enhancements, or design changes to PatternFly
- We would like to surface a new topology view of the Node Network State, and we are missing some icons to create that view.
- This view is needed to enable users understand the link between an interface with a specific IP or with LLDP enabled  in a cluster. 
- The list of the required icons is as follows: 
1. **Bridge** - a square with arrows in it, which is typically used as a switch icon
 ![Bridge](https://github.com/patternfly/patternfly-design/assets/44577420/be4425ec-e7e0-4a32-9bce-826f6a965692) 

2. **Bond** - Google for "network bonding icon" - a chain icon
![Bond](https://github.com/patternfly/patternfly-design/assets/44577420/a9a0650e-ad46-48a8-9c1f-318afcc9065d)

3. **NIC** - Google for "ethernet icon", the typical one would be a picture of ethernet cable/connector
![NIC](https://github.com/patternfly/patternfly-design/assets/44577420/525b34d5-a4e3-4e15-8988-2922d4bdf75a)

Reference:
![Uploading Petr-demo1.png…]()
![Uploading Petr-demo2.png…]()
- The topology view is an enhancement on the Node Network State feature we have now.

**Comment by andrew-ronaldson** [comment]
I found these options on FA that you could use today. You would just need to embed the svg code into your application.
Bridge https://fontawesome.com/icons/arrow-right-arrow-left?f=classic&s=solid
Link: https://fontawesome.com/icons/link?f=classic&s=solid
NIC https://fontawesome.com/icons/ethernet?f=classic&s=solid

**Comment by andrew-ronaldson** [comment]
I see ethernet and link in our react repo already https://patternfly-react.surge.sh/icons

**Comment by yfrimanm** [comment]
Hi Andrew,

The Bond (link) <https://fontawesome.com/icons/link?f=classic&s=solid> and
the NIC/ Ethernet <https://fontawesome.com/icons/ethernet?f=classic&s=solid>
icons on fontawesome look fine to me, but I don't think the Bridge
<https://fontawesome.com/icons/arrow-right-arrow-left?f=classic&s=solid> is
accurate enough. Would it be possible to create something more similar to
the original request?
FYI @Matan Schatzman ***@***.***> @Aviv Turgeman
***@***.***>

Thank you.
Yifat

**Comment by andrew-ronaldson** [comment]
<img width="802" alt="Screenshot 2024-09-19 at 12 40 32 PM" src="https://github.com/user-attachments/assets/2d72195c-f2e2-4bfd-a08c-f793ed2ff496">
made a couple versions @yfrimanm

**Comment by yfrimanm** [comment]
Hi Andrew,
The middle one is my favorite and also the Networking BE team lead
favorite, so let's go with that.
Thank you!

**Comment by andrew-ronaldson** [comment]
Closed and will make a core follow up
