### ISSUE TITLE
Animation: Grouping and prioritization of component animations

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1285]
### Goal
Many of the Components in PatternFly will share similar animation properties. Grouping our components by animation types can help break the work into smaller categories and apply consistent animation properties.

## Tasks
- [x] Group components by type of Animation (Rotations, fades, movement, expansions, etc.)
- [x] Prioritize components by library impact (Buttons, Navigation, etc.)

**Comment by kaylachumley** [comment]
Miro Discovery Board: [View Here](https://miro.com/app/board/uXjVNhTY1Rc=/?share_link_id=886077790298)

The[ Animation Master Doc](https://docs.google.com/document/d/1tumxUYRQqoqrrfZ1VLoNk6r7hpi3Qnc3BWUDQEXjHJw/edit?usp=sharing) contains a section for the animation priority and tags related to property type

**Comment by kaylachumley** [comment]
![Screenshot 2024-04-04 at 9 25 02 AM](https://github.com/patternfly/patternfly-design/assets/150823809/cdd11be1-0765-462b-ae7e-e433f957388e)
Preview of the table in the Master Doc

**Comment by andrew-ronaldson** [comment]
Thanks for adding this. I'll create some follow up issues next time the group meets to get ready for the next sprint.
