### ISSUE TITLE
Page - review sticky section designs

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-design#1286]
This is what it looks like now. cc @lboehling 

<img width="1212" alt="Screenshot 2024-02-09 at 7 06 25 PM" src="https://github.com/patternfly/patternfly/assets/35148959/04ab73c3-41b0-45ad-9a9c-8c50c4191cad">

**Comment by andrew-ronaldson** [comment]
<img width="1722" alt="Screenshot 2024-04-09 at 8 17 35 PM" src="https://github.com/patternfly/patternfly-design/assets/28658548/4bc7d31d-ee8b-4f77-b557-524ca291a9de">

This is a possible solution but looking at the code I'm not sure how to make it work. @lboehling @mcoker any feedback on this?

**Comment by mcoker** [comment]
@andrew-ronaldson off the top of my head, I'm not sure if that's possible either - to have the left/right edges of the sticky section span the full width of the content area. The content area has a white border around it now that creates the padding on the inside of the content area, and getting a section to overlap that border will be tricky. It's probably worth revisiting that part of the code and see if there is a better way to do that in a way that lets page sections bleed out to the edges of the main container though, so we could make a spike out of it.

**Comment by andrew-ronaldson** [comment]
Closing this review and created a design kit [issue](https://github.com/patternfly/patternfly-design-kit/issues/736)
