### ISSUE TITLE
pf-t--global--Zindex should be pf-t--global--z-index

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-design#1288]
Just to be consistent, it looks like the `pf-t--global--Zindex--[sizes]` tokens should use a lower-case property name with a hyphen (`pf-t--global--z-index`), similar to the `box-shadow` tokens - `pf-t--global--box-shadow` 

cc @lboehling @andrew-ronaldson

**Comment by lboehling** [comment]
fixed in figma!

**Comment by mcoker** [comment]
cc @srambach
