### ISSUE TITLE
Buttons: Add micro animations

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1294]
The buttons components need micro animations.

The goal of this issue is the define the following hover/click behaviors for:

- [x] Primary buttons
- [x] Secondary buttons
- [x] Tertiary buttons
- [x] Icon buttons

**Comment by kaylachumley** [comment]
[Figma Prototype ](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/YIxfglww1fRdQGclApv1nm/PatternFly-6%3A-Components?type=design&node-id=23613%3A1180&mode=design&t=I5K9f3BryUmAo8Kn-1)with annotations on semantic tokens

**Comment by andrew-ronaldson** [comment]
Thanks for getting this over the finish line @kaylachumley

**Comment by andrew-ronaldson** [comment]
Closed by https://github.com/patternfly/patternfly/issues/6589
