### ISSUE TITLE
Navigation items: Create motion designs and micro animations

### ISSUE THREAD

**Issue by kaylachumley** [patternfly/patternfly-design#1296]
The navigation component need micro animations. React [Demo](https://patternfly-org-pr-3958-site.surge.sh/components/navigation)

The goal of this issue is the define the following behaviors:

- [x] Define open/close expansion behavior for navigation drilldown
- [x] Define hover/click animation for navigation items
- [x] Define fade in/out animation for navigation items
- [x] Define hover/click animation for horizontal nav
- [x] Create animation concept in Figma
- [x] Define and assign semantic tokens for each property

**Comment by kaylachumley** [comment]
[Figma prototype](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/UR1JfYwpZI6MP3rLj18iJ3/PatternFly-6%3A-Components?type=design&node-id=23333%3A4960&mode=design&t=IWHIhORfsuZ4LNb5-1) with semantic token annotations

**Comment by kaylachumley** [comment]
moving this to done! @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
Closed with https://github.com/patternfly/patternfly/issues/6597
