### ISSUE TITLE
Clickable icons buttons: Create motion designs and micro animations

### ISSUE THREAD

**Issue by kaylachumley** [patternfly/patternfly-design#1298]
The Notification badge (bell), Settings (gear), Favoriting (star) icon buttons need animation. 

The goal of this issue is the define the following behaviors:

- [x] Define scale behavior for the Notification badge (bell), Settings (gear), Favoriting (star)
- [x] Define hover/click animation for the Notification badge (bell), Settings (gear), Favoriting (star)
- [x] Define fade in/out animation for the Notification badge (bell), Settings (gear), Favoriting (star)
- [x] Create animation concepts in Figma
- [x] Define and assign semantic tokens for each property

**Comment by kaylachumley** [comment]
[Figma prototype](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/1e5dyLys8Y7wBp2tPSwP1B/PatternFly-6%3A-Components?type=design&node-id=23621%3A551&mode=design&t=gsvVKRRmht1eRtPl-1) with semantic tokens annotations

**Comment by kaylachumley** [comment]
moving this to done! @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
Closing wit https://github.com/patternfly/patternfly/issues/6601
