### ISSUE TITLE
Update the "all components" page design on PF.org to support docs. 

### ISSUE THREAD

**Issue by edonehoo** [patternfly/patternfly-design#1301]
Enhance the [all components page](https://www.patternfly.org/components/all-components) design, so that it can also contain higher level guidelines and information, like details about beta and deprecated components. See if we can find a way to balance content with the components gallery.

This will allow us to strengthen and centralize information about our component system.  

### Links

- [Figma mocks](https://www.figma.com/design/qnXKjGtXlqUk4PycBot9W7/pf.org%3A-All-Components?node-id=0-1&t=9MznqXhAq5ZPru9e-1)
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-design/issues/1329
```

**Comment by andrew-ronaldson** [comment]
Closing as complete and I created a followup in org https://github.com/patternfly/patternfly-org/issues/4249
