### ISSUE TITLE
Table: 'View more' button as an alternate to Pagination

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1307]
## Requesting new feature for the table component
In a recent thread there was an ask to include a View more button with the table component that can load in addition content as needed. With pagination the page reloads to pull in the next set of data and the view more action would potentially avoid refreshing the page. 

Another benefit is being able to scroll up and down in one page vs navigating through pagination or manually adjusting the items per page menu.

This is a rough mock of the requested change. May require additional considerations.

<img width="1082" alt="Screenshot 2024-05-15 at 11 56 35 AM" src="https://github.com/patternfly/patternfly-design/assets/28658548/db0a15d4-d62e-4a73-b3f7-6d4a46a05bd2">

**Comment by jgiardino** [comment]
The issue description is inaccurate based on my understanding of the questions we have. 
> there was an ask to include a View more button with the table component

The questions we have for PF is whether this is even a valid pattern to use. 

The use of this pattern in the product today is based on a design pattern that exists in an upstream project. As we try to define guidelines around the different patterns for loading list items, the question within our team is whether the “view more” pattern is a pattern we should even recommend for other areas of the product, or is it just an artifact from pulling in the upstream project and not really a pattern we should recommend? And if the consensus is that this is a valid pattern, then our next question would be, when do we use this pattern vs pagination? 

cc'ing @nding-anges

**Comment by jgiardino** [comment]
Thanks for the update! This makes sense to me.

**Comment by nding-anges** [comment]
@jgiardino thanks for clarifying the question and @lboehling Thanks for the feedback.

**Comment by andrew-ronaldson** [comment]
Closed as resolved
