### ISSUE TITLE
Page design for Motion guidelines

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1308]
There will be a new Motion guidelines page with content provided by @edonehoo.
The goal of this issue is to provide a design mock that lays out this content with helpful examples and a CTA to promote the roadmap for future motion work.

**Comment by kaylachumley** [comment]
https://www.figma.com/design/Q5m3dAsf6hRWM4Abnglvw9/pf.org%3A-Motion-Page-Layout?node-id=0-1&t=xNz1Kog74ydGvrxL-1
