### ISSUE TITLE
Design Review: React Component groups

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1318]
Using this [doc](https://docs.google.com/document/d/12SL5EtM82YpX2ff3AB6U2T9D2GklVxdAe4L5PdhL3pM/edit#heading=h.2zu0lojzessv) as a template PF design needs to complete a design review of the v6 migration for the react component groups.

Following this design review we will create issues in the [component-groups](https://github.com/patternfly/react-component-groups) repo.

**Comment by kaylachumley** [comment]
All issues have been submitted! Though I cant seem to apply labels or milestones? Not sure why it's disabled for me. @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
I'll take a look at the permissions but I didn't know that was a thing. 🤷

**Comment by andrew-ronaldson** [comment]
Closing this now. Good job team!
