### ISSUE TITLE
Reconsider design of split check with label menu toggles

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#1320]
Follow up design issue for: https://github.com/patternfly/patternfly/pull/6886

We've added a new split check menu toggle variant with a label to v6. The original variant is set up so that the text is the target for the checkbox, and the dropdown area is separate. The new, added variant is set up so that the text is the target for the dropdown caret, and the checkbox area is a separate action. Right now, they visually present the same which makes it confusing to distinguish between the interactions. I want to revisit the design and see if we can better communicate the differences between those interactions, possibly by adding a divider like our other split action toggles. 

existing: 
<img width="165" alt="image" src="https://github.com/user-attachments/assets/e23e8a7c-08aa-4351-b51e-556b06c0b8d0">

new: 
<img width="450" alt="image" src="https://github.com/user-attachments/assets/f6b60e46-f95a-4fbf-aa58-1a70dcab9ebb">

**Comment by kaylachumley** [comment]
Adding a divider seems like the best option here to better match our other component! I made a few options in figma that we can review together @lboehling

**Comment by kaylachumley** [comment]
[view here](https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/c9mIzI9DBrdr6ud5cz3qER/PatternFly-6%3A-Components?m=auto&node-id=27730-67230&t=KpeQV2voORkx9JnM-1)

**Comment by kaylachumley** [comment]
@lboehling ready for design check #2 - I speced out how it would look if the text is attached to the dropdown caret instead of the checkbox

![Image](https://github.com/user-attachments/assets/0b1f3aee-aad3-4295-98fe-32e153783ac1)

**Comment by kaylachumley** [comment]
Hey @mcoker ! Lucia and I have been discussing making some design changes to the split check with label menu toggles across the board. I have a few questions related to this if you have a moment  🙂 

You can see above in my last comment that I speced out the divider attached to the checkbox vs attached to the drop down toggle - It could be worthwhile to have both as an option/variant. Do you envision just the default menu toggle to get the option to have the border between the different actions or alternatively anywhere that has [split button and split action](https://staging-v6.patternfly.org/components/menus/menu-toggle/html/#split-button-action) should be consistent with the divider? 

I will also be specing out the different hover/selected states for each side of the split toggle(assuming that hovering/clicking on the toggle text would just give the hover/select borders on that side of the toggle) WDYT?

**Comment by mcoker** [comment]
Hey @kaylachumley! Those look awesome - it's not super clear currently whether the text is associated with the checkbox or the caret. Apologies if I misunderstood the question, but I would probably expect any split button toggle to have a divider. This will really help with the spacing and clickable/target areas for the stuff in the toggles. The menu toggle as it is currently in v6 seems a little messy to me. Like this, for example - there is a lot of clickable space for the checkbox on the left, but not on the right

<img width="379" alt="Screenshot 2024-08-26 at 10 07 38 PM" src="https://github.com/user-attachments/assets/70679424-274c-4c4b-b896-03fa6e06a72b">

For the border changes per item in the split toggle, I'm not sure, but I can say it should be no sweat technically to make any sort of change there. FWIW here's what I mocked up in dev tools:

Hover per action:
<img width="134" alt="Screenshot 2024-08-26 at 10 12 34 PM" src="https://github.com/user-attachments/assets/254f133a-11f9-43af-9519-8bd9ad87ce6c">
<img width="124" alt="Screenshot 2024-08-26 at 10 12 54 PM" src="https://github.com/user-attachments/assets/ee55645f-2182-45ee-9662-aacbbde89734">

Expanded per action:
<img width="135" alt="Screenshot 2024-08-26 at 10 13 46 PM" src="https://github.com/user-attachments/assets/8c57a347-9a71-4678-bad3-87d48b005d43">
<img width="122" alt="Screenshot 2024-08-26 at 10 14 09 PM" src="https://github.com/user-attachments/assets/8b02c937-8231-488d-8ea8-eb8a0cbaeedc">

And maybe something like this where all of the borders change on hover, but when something is expanded (or maybe focused, too?) that action gets the super mega border:
<img width="133" alt="Screenshot 2024-08-26 at 10 14 32 PM" src="https://github.com/user-attachments/assets/c756c684-1cf4-4d09-919b-38ceccbf43ae">
<img width="132" alt="Screenshot 2024-08-26 at 10 14 45 PM" src="https://github.com/user-attachments/assets/93479786-a6a2-4d5d-b12b-a1e7dbb702be">

**Comment by kaylachumley** [comment]
closing this out since the design consideration/mock ups are done - making a new issue to start working on the bulk of the split button component changes then ill make a core issue to follow @lboehling
