### ISSUE TITLE
Pagination - bottom mobile/sticky layout bug

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-design#1321]
The default layout of bottom pagination on mobile is currently designed to span the full width of the main content area and be sticky to the bottom of the viewport. It currently looks like this, which you can see in a lot of our demos, like https://pf6.patternfly.org/components/table/html-demos/expandable/

<img width="704" alt="Screenshot 2024-07-24 at 9 43 47 AM" src="https://github.com/user-attachments/assets/f328699b-a4d2-4609-bd63-e10363a0e655">

In v5, tables/data-lists were usually put in a page section without padding, so the bottom pagination looked like this (https://www.patternfly.org/components/table/html-demos/expandable/)

<img width="632" alt="Screenshot 2024-07-24 at 9 44 43 AM" src="https://github.com/user-attachments/assets/f4b64e38-9d2c-4948-9f94-f8813bfd4a32">

**Comment by andrew-ronaldson** [comment]
Fixed in PF6 Pre-release
