### ISSUE TITLE
Component Groups - Create structure miro board

### ISSUE THREAD

**Issue by kaylachumley** [patternfly/patternfly-design#1324]
A miro board needs create to help boost and facilitate the conversation around reorganization and structure of component groups grouping

[ preview here](https://react-component-groups-pr-component-groups-200.surge.sh/extensions/component-groups/about-component-groups)

**Grouping suggestions:**

- ContentHeader
- DetailsPage
----------------------
- ErrorBoundary
- LogSnippet
----------------------
- MultiContentCard
- ServiceCard
----------------------
- SkeletonTable
- BulkSelect
----------------------
- NotAuthorized
- ErrorState
- UnavailableContent
- InvalidObject
----------------------
- ColumnManagementModal
- WarningModal
----------------------
- Ansible
- Battery
- TagCount
- CloseButton
- ShortcutGrid
- Status

**Comment by andrew-ronaldson** [comment]
Closed with this PR in Component groups repo https://github.com/patternfly/react-component-groups/pull/313
