### ISSUE TITLE
Animation: Modals & backdrop

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1325]
### Goal:
Using our new motion tokens create designs for our Modal component used in Modal, About Modal, Wizard and the User feedback extension. The Backdrop component should also be considered in this design as it is related to all modals.

**Comment by asumihasan** [comment]
[Codepen](https://codepen.io/Asumi-Hasan/pen/xxvZvgr)

[Figma annotations](https://www.figma.com/design/tnfaKqovI6z0jFSuvlOEoN/PatternFly-6%3A-Motion-Design?node-id=150-6663&t=DgprD6vY7ODJY0at-1)
