### ISSUE TITLE
Update component library illustrations (v5 Sketch > v6 Figma)

### ISSUE THREAD

**Issue by bekah-stephens** [patternfly/patternfly-design#1329]
Need to update the library of illustrated versions of our components to use on patternfly.org. The current site uses outdated graphics (v5) and the original file is no longer accessible (in Sketch).

[Figma](https://www.figma.com/design/qnXKjGtXlqUk4PycBot9W7/pf.org%3A-All-Components?node-id=0-1&t=05vYnUIE5F7kEtl2-1)

**Comment by andrew-ronaldson** [comment]
Closed as complete with org follow up
https://github.com/patternfly/patternfly-org/issues/4249
