### ISSUE TITLE
PF splash image for "Brand Strategy" page

### ISSUE THREAD

**Issue by bekah-stephens** [patternfly/patternfly-design#1338]
The Brand team reached out for an image to represent PatternFly on the new Brand Strategy page. The ask was for something other than just the PF logo, maybe a screenshot of a product interface that uses PF or a collage of PF UI elements.

Context:
![Image](https://github.com/user-attachments/assets/feb6b7f4-7aa6-4634-9f7b-3709fccc98f8)

Mocks: https://www.figma.com/design/6BEkpvTaAinsLUulMDFbWm/PF-Playground---bstephens?node-id=151-2101&t=KgzXdRKQpYDjMjpd-1

**Comment by andrew-ronaldson** [comment]
Approved by brand so good to go. Thanks Bekah!
