### ISSUE TITLE
Community: Animations

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1346]

**Comment by kaylachumley** [comment]
Create Slides for the community meeting to discuss animation updates:

- Update on results that are in development and coming soon
- Fun gifs of current animation work
- Svg animations
- Codepens?
- Favorite icon/gear icon gif
- Call out the Milestones for design handoff
- Motion principles defined collaboratively
- Defined token library for various motion attributes
- Dev handoff and collaborations for annotations 
- On going animation calls to keep things fresh and discuss work

**Comment by kaylachumley** [comment]
good to go! closing this issue
