### ISSUE TITLE
Holliday theme of PF6

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1360]
Part of our breakaway sprint activities is to make a holiday theme of PF similar to our Spooky theme.

**Comment by kaylachumley** [comment]
designs are ready to go! Figma file is [here ](https://www.figma.com/design/uB75fOolaRjJg2fIkRODze/PatternFly-6%3A-Winter-Theme?node-id=8432-2&t=PW4kfAiQ0I9HpnVo-1)

**Comment by kaylachumley** [comment]
![Image](https://github.com/user-attachments/assets/ac360248-2848-49d4-831f-d4accc260f8a)
snowflake bkg svg

**Comment by kaylachumley** [comment]
here is the [Frosty v6 Asset.zip](https://github.com/user-attachments/files/18116884/Frosty.v6.Asset.zip)  it has pf-t--global--background--color--tertiary--default applied to it

I used the free versions of the fa-snowflake, fa-snowman and fa-igloo icons from font awesome
