### ISSUE TITLE
Table View: Remove unnecessary headers

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#209]
Remove the section title called "Overview" on the overview tab. Remove the example header called "Default Table". It's not necessary and we can just show the screenshot. http://www.patternfly.org/pattern-library/content-views/table-view/#/_

**Comment by rblackbu** [comment]
Test Test

**Comment by LHinson** [comment]
@KellyMiller has offered to work on this one. Thanks Kelly!
