### ISSUE TITLE
Bar Chart: "-" should be removed 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#210]
On the design tab (http://www.patternfly.org/pattern-library/data-visualization/bar-chart/#/api), after item "5. Bar:", there is a bug because "Interaction" has a "-" before it. I think it was supposed to be a sub-bullet. 

It should look like... 

- Bar:
  - Interaction:
     - If drill down behavior is supported, clicking on a bar will navigate to the appropriate page.
     - If supported, right clicking on an bar will bring up a menu with associated actions. If you are using a grouped bar chart, right clicking on a group will bring up a menu with associated actions for that group.
  - Width: All bars should be the same width.
  - Color: For recommendations on fill colors, see the Color Palette.
  - Height: Bar height in vertical charts is the dimension that represents its value.
  - Spacing: Spacing between bars should be equal. In the case of grouped charts, increase the spacing between main categories.

**Comment by ncameronbritt** [comment]
Got it.

**Comment by maryclarke** [comment]
I'll do this one
