### ISSUE TITLE
Bar Chart: Interactive Legend should be a sub-bullet 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#211]
On this page - http://www.patternfly.org/pattern-library/data-visualization/bar-chart/#/api

Right now it looks like: 
Legend: It is recommended to include a legend to define the colors on the chart. On the bar chart, the legend may be located left aligned and underneath the chart or left aligned and to the right of the chart. - Interactive Legend (optional): Clicking on a series in the legend should toggle the visibility of the series in the chart.

and should look like... 
- Legend: It is recommended to include a legend to define the colors on the chart. On the bar chart, the legend may be located left aligned and underneath the chart or left aligned and to the right of the chart. 
  - Interactive Legend (optional): Clicking on a series in the legend should toggle the visibility of the series in the chart.

**Comment by jgiardino** [comment]
taking this one

**Comment by jgiardino** [comment]
this should be resolved by #222
