### ISSUE TITLE
Heat Map should be capitalized 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#214]
- All instances of "heat map" should be "Heat Map" on the Overview tab
- Instead of referring to "a" heat map, we want to refer specifically to our heat map. Therefore...
  - Instead of "A heat map is a visualization of objects as blocks in a grid.", change to "The Heat Map is a visualization of objects as blocks in a grid. "
  - Instead of "When heat map items become so...", change to "When the Heat Map items become...."
  - Instead of "The most common use cases for a heat map are:", change to "The most common use cases for the Heat Map are:"

http://www.patternfly.org/pattern-library/data-visualization/heat-map/#/api

**Comment by maryclarke** [comment]
I'll take this one

**Comment by maryclarke** [comment]
Resolved by #219
