### ISSUE TITLE
Broken resource links

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-design#237]
Same issue as patternfly/patternfly#607, `jquery.matchHeight-min.js` has changed location. 

However there are also some pages that pull resources from CDNs and I suppose that's not what you want. Changing those would require further synchronization with patternfly-org.

**Comment by mcarrano** [comment]
I am just cleaning up old issues. I think this was addressed @michpetrov . Can you verify?

**Comment by michpetrov** [comment]
@mcarrano yes, the jquery plugin issue was fixed with #435.
