### ISSUE TITLE
List view design doc link to Pagination incorrect

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-design#240]
The list view design documentation has the following:

"Pagination: Card view can also support pagination. See Pagination for more details."

Should say Card view instead of list view.  Link goes to github instead of the pattern on the site.

**Comment by suzannehillman** [comment]
I'm interested in working on this, but I'm a bit confused by the bug.

Looking at the code, it looks like it says "Card view" after "Pagination:" already. Is this correct or should it be list view? Given that it's the list view page, I assume that you just reversed what you meant to say, but wanted to make sure. (looking at http://www.patternfly.org/pattern-library/content-views/list-view/#/design)

And am I correct that you want the pagination link to go to: http://www.patternfly.org/pattern-library/navigation/pagination/ ?

**Comment by suzannehillman** [comment]
Also, the Card view Pagination link also goes to github: http://www.patternfly.org/pattern-library/content-views/card-view/#/design - should I go ahead and fix that as well?

**Comment by LHinson** [comment]
You got it @suzannehillman! Nice job. Checking your PR now.

**Comment by mcarrano** [comment]
Looks like this was resolved so closing out this issue.
