### ISSUE TITLE
Document capitalization recommendation for kebab menu items

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#245]
The PF kebab example (https://www.patternfly.org/pattern-library/widgets/#kebabs) shows sentence style capitalization for menu items.

In PF T&W (http://www.patternfly.org/styles/terminology-and-wording/) the section for Capitalization for Common Components - it doesn’t talk about capitalization for menu items.  But it does say to use Headline capitalization for Button labels.  My thought would be Headline would be used for menu items as well.

Could the appropriate recommendation be added to the documentation?

**Comment by LHinson** [comment]
@suzannehillman this one might interest you as well.

**Comment by suzannehillman** [comment]
This is an interesting question!

My inclination would also be to use Headline for menu items, and the style guides I looked at seem to agree with me: ([Vmware](https://code.vmware.com/web/standards/-/capitalization-of-ui-elements), [Open Stack](https://docs.openstack.org/contributor-guide/ux-ui-guidelines/ui-text-guidelines/ui-text-capitalization.html)) I also liked the second answer to the question on stackoverflow about this: https://stackoverflow.com/questions/2371226/capitalizing-texts-in-user-interface

**Comment by suzannehillman** [comment]
@LHinson, I can't find the md file for the terminology and wording section. The only thing showing up under terminology-and-wording is truncation: https://github.com/patternfly/patternfly-design/tree/master/styles/terminology-and-wording

**Comment by LHinson** [comment]
@suzannehillman: we have PR to contribute T&W as an .md https://github.com/patternfly/patternfly-design/pull/172

Are you looking to make a change to it? Or just want to reference it? If reference then refer to: http://www.patternfly.org/styles/terminology-and-wording/

**Comment by suzannehillman** [comment]
@LHinson, I was looking to add the part about menu items being Headline caps to it. I can't tell if that's already been done, or someone else was looking to do it as part of that PR?

To make sure: is it accurate that changes don't get pushed to live until a new release happens?

**Comment by suzannehillman** [comment]
As far as I can tell, I don't have access to the kebab stuff to adjust it to Headline, presumably because they aren't yet released (I see only buttons under widgets). I do see why they are sentence format though, as Bootstrap has menu items in Headline format.

**Comment by LHinson** [comment]
@suzannehillman we've merged the PR to include T&W in GitHub. You can send a PR to update the .md file. It lives here: https://github.com/patternfly/patternfly-design/tree/master/styles/terminology-and-wording

To clarify though, the website is not yet consuming this .md file. We have a to-do to swap that out.

**Comment by suzannehillman** [comment]
Hi @LHinson! Looks like the terminology and wording .md file is in github master now, or at least I can see it there when I couldn't before.

Is the website using this file now? Should I go ahead and add the bit about Menu Items being Headline style?

The kebab files still seems to be unavailable through master, though.

**Comment by LHinson** [comment]
+1 for updating the .md for T&W! I just created a note for myself to add a story next sprint to have the website consume this file so it won't be immediately reflected on the website but will be nice to have the info there when we do. 

Re kebab, this actually should be a bug against patternfly as this kebab is the implementation vs documentation. Are you interested in filing that? I can merge your PR for the .md update and could reference that for the new bug.

**Comment by suzannehillman** [comment]
@LHinson I think I've done the appropriate things for this bug? :)

**Comment by LHinson** [comment]
Sure did @suzannehillman! I just merged the PR to add headline for menu items and see the issues filed against PatternFly. Thank-you! Closing this one.
