### ISSUE TITLE
Wizard (design tab) > "Loading Screen" image

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#251]
Pink reference numbers are backwards. "Title Bar" should be 1, and "Loading Wizard State" should be 2.

http://www.patternfly.org/pattern-library/communication/wizard/#/design

Thanks for identifying this one @ryanaltvater!

**Comment by ryanaltvater** [comment]
@lhinson Hey no problem! Thanks for getting it documented under the correct repo. :)

**Comment by suzannehillman** [comment]
@LHinson:

I was going to work on this, but I do not see any pink colors here: http://www.patternfly.org/styles/color-palette/

I'd prefer to be able to use the correct color to cover the number and then make new numbers. Is there a source color that I can refer to? Or a better way to do this?

**Comment by ryanaltvater** [comment]
@suzannehillman #ff00ff is the pink being used. :)

**Comment by LHinson** [comment]
Thanks @ryanaltvater and @suzannehillman! This issue has been addressed so closing here.
