### ISSUE TITLE
Table View should be capitalized 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#252]
"Table View" should be capitalized because it is referring to a pattern. Make sure all instances of "Table View" have the correct capitalization on the Table View: design tab. For example, under the pagination item, it is listed as "Table view" and should be updated. 

Filed to be updated is here: pattern-library/content-views/table-view/design/design.md

**Comment by suzannehillman** [comment]
I'm going to try to work on this later in the week!

**Comment by suzannehillman** [comment]
@LHinson:

I've found and fixed two instances of this on the page you pointed to, one of which appears to be alt text.

Before I go ahead and submit this, should 'The table view' which starts the first sentence of the overview tab also have 'table view' be capitalized? I can see why it might go either way, but it feels like it's referring to the pattern again, and should also be capitalized.
