### ISSUE TITLE
Sort pattern table needs CSS? 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#254]
Toolbar [1] has a similar table. Look at how it's done there and apply to the table here. I' assuming it needs some CSS

[1] 
Site: http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#/design
Github: https://github.com/patternfly/patternfly-design/blob/master/pattern-library/forms-and-controls/toolbar/design/design.md

**Comment by LHinson** [comment]
FYI @mcarrano @yih-wang

**Comment by mcarrano** [comment]
@yih-wang Please compare these and update the .md file for Sort as needed.  When done, you can just open a new pull request that will update the Sort pattern on the site.  Thanks.

**Comment by mcarrano** [comment]
I believe this has been fixed.  @LHinson can you verify and close?
