### ISSUE TITLE
Numbering is not correct and does not match image 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#262]
Numbering in the list does not match that in the image. See: 
http://www.patternfly.org/pattern-library/content-views/table-view/#/design

**Comment by suzannehillman** [comment]
@LHinson am I correct in interpreting this to mean that the numbers on the first image are fine (it looks likely?), and the numbers in the relevant text are not? 

I also note that the text says to use 1-2 items max in the Inline Actions description, and there are three actually shown in the image. Which is correct?

**Comment by suzannehillman** [comment]
@LHinson: Hrm. Looking at the markdown for this page, the numbering should actually be correct. Precisely which Markdown variant does patternfly use?

**Comment by cshinn** [comment]
@suzannehillman so it looks like switching to 4 space indentation should resolve this one

**Comment by LHinson** [comment]
Thanks @suzannehillman!
