### ISSUE TITLE
Toast notifications should be top aligned under the application bar

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#276]
The toast notifications documentation shows that a toast notification should be top right aligned. I suggest that this be changed to be top aligned under the application bar, and if there is a horizontal bra, should be top aligned under that.

The toast notification covers items on the banner, and among other things blocks the user from accessing the notification drawer, in some cases. We have received feedback from multiple products on this.

You can see this problem here:

- http://www.patternfly.org/pattern-library/communication/toast-notifications/#/overview
- http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design

This issue is associated with the patternfly issue https://github.com/patternfly/patternfly/issues/643

@LHinson if you agree with this approach, i'm happy to put up a PR for this.

**Comment by mcarrano** [comment]
@kybaker Can you look at this and make a recommendation?  I am fine with @serenamarie125 's proposal put want to make sure there isn't an original rationale for this placement that we are missing.

**Comment by LHinson** [comment]
@serenamarie125 Does this change have any impact on the responsive state? When you say, send a PR, do you mean to the design repo?

**Comment by mcarrano** [comment]
A new story has been added to the PatternFly backlog to address this.  See https://patternfly.atlassian.net/browse/PTNFLY-2523

**Comment by zhutaoredhat** [comment]
Hi @serenamarie125 @mcarrano I had updated the mockups. The updates:
1.The toast notification changed to be top aligned under the application bar.
2.Added the close button on the notification bar and the button will be recommended in the user guide. When the message interrupts the user, the user could click it to close quickly!
[Uploading toast-notification-update.png…]()

The toast notification will be float on the top of notification drawer. User could close it quickly.
![Uploading toast-notification-with-drawer.png…]()

Do you think these designs make sense? Open to discuss.

There is a another design that the toast notification was put in the center of the page, but I am not sure whether it is followed the design rule of PatternFly.
![toast-notification-center](https://user-images.githubusercontent.com/13375283/30016850-5ccdf900-9189-11e7-96d1-4dc901a69ad3.png)

**Comment by mcarrano** [comment]
@zhutaoredhat Just a couple of comments:

1) I don't think we should use the center justified notification (last example). This becomes too similar to the inline notification. The idea of the toaster alert is to just have a transient alert that pokes out from the right edge of the window.

2) In the case of horizontal navigation, I'm wondering if this should be positioned below the menu or below the masthead like the notification drawer is. It also might be useful to show positioning with vertical navigation and masthead.

@matthewcarleton can you also take a look? Is this consistent with where you are going with CSS implementation?

**Comment by zhutaoredhat** [comment]
@mcarrano Thank you for your feedback. +1 for comment 1.
Matthew Carleton identified that we would not use a "variable" so have updated the story to reflect this.
Some horizontal navigations are without masthead, the drawer will be below the navigation. So I think position it below the menu will looks more consistent.

**Comment by matthewcarleton** [comment]
@mcarrano yup, I agree with this. @zhutaoredhat I think we will end up using a single variable to define the position but there won't be multiple variables defined. If it needs to be changed you can just change the single variables value.

**Comment by zhutaoredhat** [comment]
@matthewcarleton I agree with you~

**Comment by mcarrano** [comment]
@zhutaoredhat Yes, please proceed with a PR for this. I actually think that just replacing the current mockup on the Overview page with #1 will be sufficient.  Not sure what the second mockup is trying to communicate. Are we saying that the toast alert will always be on top of other content? Is that true @matthewcarleton ? If that's the case, then maybe include this with a statement that reflects that. Otherwise I'm afraid this might be misleading.

**Comment by matthewcarleton** [comment]
I agree @mcarrano I don't think we need anything but the first one. The toast will sit on top of notification drawer but I don't think that needs to be explicitly stated.

**Comment by mcarrano** [comment]
Merged #417 Verify changes on the website before closing.

**Comment by mcarrano** [comment]
Verified. Will Close.
