### ISSUE TITLE
Notification Drawer pattern clean-up 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#279]
*What happens if you have the notification drawer open, then open the navigation? Does the notification drawer auto collapse or do they layer?
* I like that addition of explaining the difference in icons (seen under responsive section). I think that need to be listed above. Not sure that we need to list twice. The callouts under the mobile section can be very specific to the responsive behavior instead of repeating.
* Toast notification image needs to be reduced down to 72px
* Drawer Title with the explanation "Drawer Title" is not all that helpful.
* Re: the blue icon when the drawer is open, it's inconsistent with the non-mobile version. Need to think through this further. 

See: http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design

**Comment by yih-wang** [comment]
@LHinson @lizsurette @mcarrano Updated the mockup as comments in #283 . See if there still any issue.

**Comment by mcarrano** [comment]
@LHinson I think all this work has been completed.  Is this still an open issue? If not, please close.

**Comment by mcarrano** [comment]
I believe this has been addressed and will close.  If there are still problems, please open a new issue.
