### ISSUE TITLE
Wrong link in pattern library

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#303]
The link to the Date Picker pattern is incorrect on the main Pattern Library page.

https://www.patternfly.org/pattern-library/ 
links to
https://www.patternfly.org/pattern-library/forms-and-controls/date-picker

but the correct URL is
http://www.patternfly.org/pattern-library/forms-and-controls/datepicker/
datepicker one word, no hyphen

**Comment by mcarrano** [comment]
@zhutaoredhat can you fix this bug since you are currently working on this page?  Thanks.

**Comment by zhutaoredhat** [comment]
@mcarrano @ajacobs21e Sure. This bug had been fixed in #417 of PatternFly.org https://github.com/patternfly/patternfly-org/pull/417/files
<img width="639" alt="2017-07-10 10 48 04" src="https://user-images.githubusercontent.com/13375283/28001219-96f9ea6a-655d-11e7-8571-2387b799805f.png">

**Comment by ajacobs21e** [comment]
Thank you @zhutaoredhat !

**Comment by mcarrano** [comment]
Looks like this has been address so I will close.
