### ISSUE TITLE
Breadcrumb Switcher

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#305]
The breadcrumb switcher is a new component that will allow the user no navigate between multiple views at the same level in the information hierarchy. This is useful, when browsing details of objects, for example, as it allows the user to navigate to a new object without the need to return first to a higher level summary view.

**Use Cases:** As a user, I want to quickly navigate to view another object at a peer level in the information hierarchy.

**References:** [JIRA Story](https://patternfly.atlassian.net/browse/OSUX-62), [Preliminary mockup](https://drive.google.com/open?id=0B5KC3vr5EkgmQlpaaE9KTC15Q3M)

**Products Needing This:** Red Hat Satellite, Red Hat Storage Console

**Scope of work:** TBD

**Stakeholders/Reviewers:** Serena Doyle, Roxanne Hoover, Matt Carrano

**Other Info:** 
- Roxanne has spoken to someone in Satellite who is going to contribute this to React PatternFly repo
- Roxanne has spoken to Walden Raines in Satellite who is going to contribute this to the Angular PatternFly repo

**Comment by mcarrano** [comment]
Need to reach agreement across UXS team about requirements before proceeding. @serenamarie125 will report back.

**Comment by Rohoover** [comment]
All -  It looks like some work has started on this.

http://wraines-sandbox.rdu.redhat.com/packages?page=1&per_page=30

admin/changeme

Please note that this is Walden's sandbox so code is influx and not all functionality is working all the time. Also -- don't break his sandbox :)

**Comment by beanh66** [comment]
Thanks for sharing @Rohoover! I just started working on documentation for the design based on your HiFi mocks. Should have something up for review soon 👍

**Comment by mcarrano** [comment]
@beanh66 I've added your name to this issue if you will be working on it.  Look forward to seeing your design proposal. @serenamarie125 did we ever have a chance to vet requirements on this at UXS level?

**Comment by beanh66** [comment]
Thanks Matt, that sounds great! My understanding was that this breadcrumb switcher was already vetted a long time ago, but I could be mistaken. I have HiFi mocks from Rox and I thought we were moving forward with getting this into some of the products. @serenamarie125 and @mcarrano let me know if that's not the case and I'll hold up on submitting a design PR.

**Comment by mcarrano** [comment]
We discussed this in the management design sharing meeting today and decided that unless there is an objection, to move ahead to a PR based around design proposal from the Satellite team.  See link posted by @Rohoover above.  @beanh66 will add this to the existing Breadcrumb pattern as an alternative to the standard breadcrumb for navigating object details.

@serenamarie125 @catrobson @maryclarke and @LHinson , let us know if you see a problem with this approach.

**Comment by catrobson** [comment]
I'm not certain where in Foreman to find this functionality.  Last time this was brought up I believe that @maryclarke and I had concerns about why we were doing a non-standard design for this functionality.  I'm not certain since I can't find it in that app where we stand today.

**Comment by Rohoover** [comment]
@catrobson 

It is not currently in Foreman. They are going to be removing two-pane view and this piece of design allows for the switch between table items that was currently possible with two-pane view.

**Comment by beanh66** [comment]
@catrobson Sorry, I just submitted a PR with the proposed design before I saw your comment above, but I didn't realize there were still design concerns around this feature. @maryclarke @mcarrano @serenamarie125 Let me know how you want to proceed! Happy to schedule a meeting if that's best 👍

**Comment by serenamarie125** [comment]
@catrobson @maryclarke I sent an email with our previous thread from July as well as some additional information around intended product usage.  I was under the impression that we were good to go with the use case & requirements around this pattern.  I think the remaining questions are clarifying why we are going with the suggested approach. Is that the case ?

**Comment by catrobson** [comment]
Yes, that's accurate @serenamarie125.  @beanh66 fine with you submitting the PR, I'll go review that and ask specific questions there if I have them.

**Comment by mcarrano** [comment]
This PR has been merged.  Verify changes correctly displaying on site before closing.

**Comment by mcarrano** [comment]
There is a pending PR #415 for updating with high res images

**Comment by mcarrano** [comment]
Merged PR #415 to updates hi-res images. Verify before closing this issue.

**Comment by LHinson** [comment]
@mcarrano I rebuilt the site. You can see changes here: http://www.patternfly.org/pattern-library/navigation/breadcrumbs/#/design

**Comment by mcarrano** [comment]
Thanks @LHinson  Will close this out then.
