### ISSUE TITLE
Add information about standard usage to the Icons page on the PatternFly website

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#308]
Want to identify and communicate standard icons that should be used for common objects and actions. Earlier work on icon standardization can be found here:

Had started this effort in 2015/2016 - check with Leslie on work that Brian did from a formatting perspective to go here: (https://www.patternfly.org/styles/icons/ )
(https://docs.google.com/spreadsheets/d/1XdcTn8OOiFjZY8txviW79rifU21Y9-s_Oiv6ZE7yJYI/)
(https://docs.google.com/spreadsheets/d/1ulZxMUoQWjRv7FKn0c_Bb-9Zv796jpGT2dFs0HpXWO8/)

**Comment by serenamarie125** [comment]
@mcarrano I think that this Issue is identifying 2 problems
1st - primary nav items
2nd - formatting the icons into a display which Brian had done previously

Could we change this issue to be regarding icon formatting?  And then I will create another issue around Navigation icons?

**Comment by mcarrano** [comment]
I have updated this issue as you requested @serenamarie125 . Please create a separate issue for Navigation icons.

**Comment by LHinson** [comment]
@serenamarie125 can we add hex values to the spreadsheet so that I can updated the table with a column with the appropriate hex values?

**Comment by mcarrano** [comment]
Merged the existing pull request #343. Further updates will be handled through a new issue.
