### ISSUE TITLE
Specify standard messaging for login errors

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#309]
We should have standard messaging for common login problems. Consider adding to Design tab of login pattern.

**Comment by junezhang** [comment]
@mcarrano, currently @zhutaoredhat  and @yih-wang are doing the Login Improvement. so we'd like to work on this issue too.

**Comment by mcarrano** [comment]
Created JiRa story https://patternfly.atlassian.net/browse/PTNFLY-2556 for this work.

**Comment by yih-wang** [comment]
@mcarrano @LHinson I summarised common error conditions and some initial recommendations can be found in this document: https://docs.google.com/a/redhat.com/document/d/1Ct6WqRhOzyBhqyT9ZNJ_bPdLUocMPDZDZlPVNqSFjoQ/edit?usp=sharing Please take a look and feel free to leave comments. Thanks.

**Comment by mcarrano** [comment]
This issue is being addressed as part of PR #501

**Comment by mcarrano** [comment]
This has been addressed as part of #501 that was just merged. Will close.
