### ISSUE TITLE
Right-Click Menu Recommendations

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#311]
PatternFly currently does not provide any guidance on use of right-click menus. 

[Right Click menu recommendations](https://docs.google.com/document/d/13d12jMaALzTuzj1WeRr0PCnbPXJnqR0PAMFPG3lv0xY/edit) - general recommendation is to not use these (do we all agree with this?); should include as an overall guideline/recommendation.  Where should this be located?

**Comment by mcarrano** [comment]
Want to proceed forward with this.  Good candidate for a PatternFly design story.  Matt C to create corresponding story.

**Comment by mcarrano** [comment]
A new story has been added to the PatternFly backlog as: https://patternfly.atlassian.net/browse/PTNFLY-2524

**Comment by yih-wang** [comment]
@mcarrano @LHinson @Mgranfie I have done some research on right-click menu and finished the first draft of the guidelines, please have a review and feel free to leave comments. Thanks! https://docs.google.com/a/redhat.com/document/d/1tv7XSQXE9HbDXyo6jhNRpWnm2C4e5cYINebVxDxpNec/edit?usp=sharing

**Comment by mcarrano** [comment]
I think that your research and recommendations make sense @yih-wang . I just had one small comment. @LHinson and @Mgranfie let us know what you think and what next steps should be.

**Comment by mcarrano** [comment]
@LHinson @Mgranfie @catrobson @serenamarie125 @jeperry @maryclarke Please see recommendations summarized by @yih-wang in the Google Doc referenced above. I'd like to get your comments and feedback on this before we proceed further.

**Comment by Mgranfie** [comment]
Great work here! I added some comments on the use cases and guidelines.. I
was not sure if this was solely research and how much would roll into the
design. Hope the feedback is useful...

-Monica

**Comment by maryclarke** [comment]
This looks great to me!

**Comment by Mgranfie** [comment]
@mcarrano @maryclarke It would be useful to consider moving some of the design information from this guideline, for context menus, to a base, standard menu component. This would include information such as the use of separators, groupings of commands, order of commands, responsive scrolling, and other general menu guidelines, leaving this variation on a menu to focus on the behaviors and rules for context menus. This would then extrapolate out to include other variations such as drop down menus, pull right menus, tab menus, menu bars, button menus, hamburger menus, task menus and this one context menus...etc...

**Comment by catrobson** [comment]
The recommendations in this doc look great to me as well!  Thanks @yih-wang!

**Comment by mcarrano** [comment]
@serenamarie125 can you look at this when you have a chance and let us know if you are OK with the recommendations?

**Comment by mcarrano** [comment]
I will create design story.

**Comment by serenamarie125** [comment]
These look great!  Thanks @yih-wang

**Comment by mcarrano** [comment]
Per discussion with @andresgalante am recommending that we put this on hold for now as there is no easy custom right-click menu solution for Chrome. If there is a product need, we will require a custom component and should revisit this pattern at that time. A story has been created in the PF backlog as https://patternfly.atlassian.net/browse/PTNFLY-2619 as a cross-reference for this.

**Comment by mcarrano** [comment]
This capability is needed in product. @serenamarie125 will follow-up with potential implementation from RHEV team for contribution.
