### ISSUE TITLE
Add Tree-List pattern (variation of List View)

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#312]
The tree-list view is a new component that will allow the user to see a list view with hierarchical relationships (parent-child relationships).

Use Cases: As a user, I want to be able to see a list of items with context of their hierarchical relationships to other items in the list.

References: [Github story](https://github.com/fabric8-ui/fabric8-ux/issues/517)

Products Needing This: OpenShift.io

Scope of work: Use cases and requirements for this pattern were defined in OpenShift.io.  The widget is already ready to be contributed to the patternfly-ng repo.  Generic design standards need to be assembled that strip out openshift.io specific fields and use cases.

Stakeholders/Reviewers: @catrobson, @mcarrano, @Mgranfie 

Other Info: _none_

**Comment by catrobson** [comment]
@mindreeper2420 is working on contributing this pattern.  Adam, feel free to also assign yourself to this issue if you'd like!

**Comment by mcarrano** [comment]
Pull Request #324 has been merged.
