### ISSUE TITLE
Support disabled rows in List View

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#313]
Want to support the ability to disable a row in a list view.  See (https://github.com/patternfly/patternfly/issues/676#issuecomment-312669489)

**JIRA Story:** https://patternfly.atlassian.net/browse/PTNFLY-2446

**Comment by mcarrano** [comment]
I did have a bit of discussion with @beanh66 around the requirements for this in Cloudforms. She writes:

"I know we needed disabled rows for Cloudforms but I can’t remember the exact use case. I want to say it was around the Inline edit pattern and how there were “disabled” rows that were unlike the rest because the item was either not configured or not in the appropriate state. The “disabled” rows didn’t get published to other areas of the UI if I recall correctly.


[1:36] 
I can understand the hesitation to add something like this to the PF listview because maybe our typical case would simply show an icon on that row to signify the disabled status. Not sure if this belongs in the general list view pattern or more of a state within the “Inline Edit” or neither, but I do like what Haley created for disabled rows. This is what I would expect to see, but I would think the checkbox and kebab would be available to allow for “enabling” or deleting the row as needed."

Given this, I propose that the checkbox should always remain active (to select it in the list), and other inline actions may or may to be available dependent on context.  To me the open question is how we should indicate that an object is unavailable. Is showing the information grayed out the right approach or perhaps we need an icon to reflect that the object is unavailable.  Thoughts? I will put on the agenda for 8/24 PF-UXS meeting.

**Comment by mcarrano** [comment]
Following the UXS-PF sync on 8/24, I looked at this again. Here is a link to the current Angular implementation http://www.patternfly.org/pattern-library/content-views/list-view/#/code/angular

If you select "Show disabled rows" you will see the current behavior.  Here everything is disabled including the expansion.  Based on the extended discussion, I propose that the only thing we change is to enable the checkbox so the row can be selected for global actions like enable or delete (would require change on the code side as well).  We should also probably say something about recommended usage of disabled rows in the design doc.

@LHinson @serenamarie125 @Mgranfie let me know if you are OK with that approach and we can move forward.

**Comment by Mgranfie** [comment]
@mcarrano @serenamarie125 @LHinson I agree with the proposal above and allowing for the selection of a disabled row and some high level guidance on how to use the disabled row, allowing flexibility and openness around the criteria that cause disabling to occur...

**Comment by mcarrano** [comment]
Confirmed that this change is live on the site. Will close.
