### ISSUE TITLE
Create common icons for general status

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#319]
Common icons for general status including : Running, Not Running, In Progress, Pending & Unknown

JIRA Story: https://patternfly.atlassian.net/browse/OSUX-8

**Comment by mcarrano** [comment]
@serenamarie125 @LHinson I have created https://patternfly.atlassian.net/browse/PTNFLY-2447 for adding these new icons to pf-icon font.

**Comment by mcarrano** [comment]
This is released in PatternFly.
