### ISSUE TITLE
Context Selector

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#321]
New design pattern 

JIRA : https://patternfly.atlassian.net/browse/OSUX-17

**Comment by mcarrano** [comment]
@jennyhaines I will pass this issue over to you for adding the high-fi images. When you are ready to send a PR, please just link it here. Thx.

**Comment by mcarrano** [comment]
Merged PR #412 .  Verify changes present on site before closing.

**Comment by mcarrano** [comment]
Verified. Will close.
