### ISSUE TITLE
Delete Confirmation

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#322]
New pattern

**Comment by serenamarie125** [comment]
We have an initial proposal too :) If people are ok with this, we can start the contribution process.  Would be nice to have a discussion as to "where" this would live and what the pattern should be called

https://docs.google.com/document/d/1UvnNPrl35osBHR0mr7ACZXhr9qN6nZ2IxI2HEgtnwwE/

**Comment by mcarrano** [comment]
@serenamarie125 I gave this a review and think it all makes sense as a basic approach. We should consider whether a warning icon is desirable here. Also, there may be situations where one want to include other object details or options. 

Here's an example of one of the Delete workflows we did for storage: https://redhat.invisionapp.com/share/729GRP1W9 You'll see that is includes some current state information, a warning message, and some options. I definitely think this is beyond what I would expect to find in PF. But it would be nice if we provided a template that is easily extensible to something like this. Thoughts?

**Comment by LHinson** [comment]
please add @matthewcarleton as a reviewer to the design PR.

**Comment by beanh66** [comment]
The detailed design doc here makes sense for basic delete/remove cases, but for more extreme detrimental actions, we way want to provide an alternative design option. Forcing the user to type the name of the thing they want to delete for example, should cover this. We have this use case in OpenShift and @catrobson mentioned it for OSIO in relation to deleting projects or spaces. This action would result in the system deleting a number of items, so we should be sure it cannot be done accidentally (similar to Github). 

@serenamarie125 Thoughts on collaborating and adding this to your delete contribution? Or would you prefer I create a separate issue to address this piece?

**Comment by mcarrano** [comment]
@serenamarie125 I have created issue #632 to address confirmation dialogs in general. I think that Delete confirmation should just be addressed as a special case of that. Do you agree?

**Comment by mcarrano** [comment]
I am going to close this one out with the assumption that it will be handled as part of #632 .
