### ISSUE TITLE
Experimental Features

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#325]
Experimental features pattern will allow users to enable UI areas that are considered "experimental" so users can try them out but know that they are still possibly volatile.  This pattern consists of a empty state showing that there is an experimental feature that can be enabled, and then the working state which highlights the page or page section as experimental while the user is working with it.

Use Cases: 
* A product version is tech preview, and we want to notate the UI with the fact that the product is in tech preview or experimental.
* A section of a product is experimental/tech preview, and the user should be able to opt into these features and have a clear visual indication always present of what areas of the UI are experimental.

References: F8UX-537 (https://github.com/fabric8-ui/fabric8-ux/issues/537)

Products: OpenShift.io, OpenShift

Scope of work:  Generalize the experimental feature capability from OSIO and document at the different levels of implementation.

Stakeholders/Reviewers: @catrobson, @mcarrano, @Mgranfie, @serenamarie125 

Other Info: <tbd>

**Comment by serenamarie125** [comment]
@catrobson @mindreeper2420 can we close this issue?  The [Experimental features PR](https://github.com/patternfly/patternfly-design/pull/338) has been merged

**Comment by catrobson** [comment]
Yes, closing.
