### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#330]
-- Overview --
Global search is a need from many products in the RH Product Portfolio

Use Cases:

References: CFUX-262 (https://patternfly.atlassian.net/browse/CFUX-262) ... need to move this to OSUX

Products: CloudForms

Scope of work:

Stakeholders/Reviewers: @serenamarie125, @mcarrano, @Mgranfie

Other Info:

**Comment by beanh66** [comment]
@serenamarie125 I agree we need a global search pattern. Would you expect this search to provide a results page? We should be sure there is a clear distinction between search and filter for this pattern. Wondering if it makes sense to contribute the search widget below (show the top 5, then link out to remaining results).
![results](https://user-images.githubusercontent.com/18057044/36874833-655b1d18-1d7b-11e8-8312-9207d56d7bbf.png)
It seems to work well in the product today and this would be a good start to a search pattern. For now consumers would have to determine where the "View All Results" link takes them until we have the more comprehensive pattern worked out with a results page. FYI @catrobson

**Comment by mcarrano** [comment]
See “Quick Add” in OpenShift http://recordit.co/USvaRZEkGg
