### ISSUE TITLE
Slider pattern

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#334]
-- Overview --
Need a slider component 

Use Cases: References: CFUX-250

Products: CloudForms

Scope of work: 

Stakeholders/Reviewers: @serenamarie125, @mcarrano, @Mgranfie

Other Info:
--

**Comment by beanh66** [comment]
Initial documentation can be found here: https://docs.google.com/document/d/1nwMNgHCgEmoFpq4gsQyhU1xwGGGlYy_JQFcglxreTZo/edit#

PR is in progress.

**Comment by mcarrano** [comment]
@jennyhaines will create hi-fi visuals and send a separate PR.

**Comment by jennyhaines** [comment]
That's right!

**Comment by mcarrano** [comment]
Confirmed changes on site. I will close. Thanks, everyone who worked on this!
