### ISSUE TITLE
Subsystem status pattern

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-design#336]
-- Overview --

Use Cases:

References:

Products: OpenShift.io, Customer Portal

Scope of work:

Stakeholders/Reviewers: @catrobson, @mcarrano, @Mgranfie, @jeperry 

Other Info:

**Comment by catrobson** [comment]
This pattern has gone through some turmoil, and might not be the right solution to make a pattern from.  Therefore, I plan to close this issue and redact this contribution.

**Comment by mcarrano** [comment]
Will go ahead and close
