### ISSUE TITLE
Sorting icons for other languages

### ISSUE THREAD

**Issue by cshinn** [patternfly/patternfly-design#337]
Sort icons for alphabetic and numeric are using A-Z and 1-9. This doesn't translate so we should consider adding an alternative for non-english languages. There are alternative sort icons with short and long bars, but I am not sure how applicable this is to text.

**Comment by mcarrano** [comment]
See font-awesome solution http://fontawesome.io/icon/sort-amount-asc/ Will move to To-Do queue for future work but not high priority per 10/5 UXS call.

**Comment by mcarrano** [comment]
Created PF story https://patternfly.atlassian.net/browse/PTNFLY-2609 to address this by adding a second variant to the Sort pattern.

**Comment by mcarrano** [comment]
A new PatternFly story, https://patternfly.atlassian.net/browse/PTNFLY-2659, has been opened to do user testing on icons for sort and determine whether there are better alternatives to the current Sort icon.

**Comment by mcarrano** [comment]
The results of usability testing can be found here: https://docs.google.com/presentation/d/19idNza_ff56YHODPLa0pdes4lnAcxFI3CJeSGtLOLVQ/edit?usp=sharing

As a result of this, the recommended path forward is to include sort-amount-asc/ and sort-amount-desc/ from the font awesome icon set as additional sort options on the Sort pattern design page (http://www.patternfly.org/pattern-library/forms-and-controls/sort/#design) with some guidance on when to use this icon vs. alpha-sort.

A new PatternFly JIRA story has been created to track this work here: https://patternfly.atlassian.net/browse/PTNFLY-2746
