### ISSUE TITLE
Errors & Validation documentation have invalid links

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#340]
There are 2 invalid links in the Errors and Validation (http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/) documentation under Forms and Controls. 

I assume that Spinner should go here: http://www.patternfly.org/pattern-library/widgets/#spinner
But unsure of Progress, possibly http://www.patternfly.org/pattern-library/widgets/#progress-bars

@mcarrano @Mgranfie @LHinson FYI

**Comment by mcarrano** [comment]
I will take this one. I do have a story in the PatternFly backlog as: https://patternfly.atlassian.net/browse/PTNFLY-2427  so I can just fold this work in there.
