### ISSUE TITLE
Table View - opposing mockups for Select All 

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#342]
Mocks in the Table View Overview & Design don’t match for Select All - one shows a Show All link, and the other shows a checkbox in the first column header

**Comment by mcarrano** [comment]
@LHinson Do we know what the recommended approach is for Select All?

**Comment by LHinson** [comment]
"Select all" needs work. We've had a number of different designs. Here's a blog post on a design that we tested... https://blog.patternfly.org/pagination-in-patternfly-second-round-cafeteria-testing/

@serenamarie125 how do you approach this in product?

**Comment by mcarrano** [comment]
Need further research and design to take place.

**Comment by mcarrano** [comment]
This issue has a dependecy on #341 . Need to resolve how Select all should work on all view types (Table view and others) and make appropriate updates to all examples.

**Comment by mcarrano** [comment]
@serenamarie125 I am going to assign this one to you with the assumption that you will address as part of the bulk selection changes currently being tracked as #341.
