### ISSUE TITLE
Need responsive guidelines for the Wizards steps panel

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#347]
Being tracked by JIRA story: https://patternfly.atlassian.net/browse/OSUX-109

**Comment by mcarrano** [comment]
@LHinson to do a final review and merge if ready.

**Comment by mcarrano** [comment]
PR #365 has been merged. Need to verify changes on site before closing.

New issue #422 has been filed to update mockups for consistency with text.

**Comment by LHinson** [comment]
@mcarrano I'm rebuilding the site.

**Comment by mcarrano** [comment]
Verified that changes are live. Will close.
