### ISSUE TITLE
PatternFly icon table update needed 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#349]
- Consolidate the font awesome and pf-icon tables 
- include the hex color as a column 

http://www.patternfly.org/styles/icons/

**Comment by mcarrano** [comment]
Content looks good but need to address why "Copy to Clipboard" on hover of all table cells.  Should apply to first 4 columns, only.

Also Delete icon is not showing up.

**Comment by LHinson** [comment]
The copy to clipboard issue should be addressed in the file on the patternfly-org repo, not the .md on patternfly-design. This is beyond my technical understanding of how to address. I've filed an issue against that repo here: https://github.com/patternfly/patternfly-org/issues/459

I do not view this as high priority therefore recommend closing the issue here and we will address the issue on patternfly-org at a later date.

**Comment by mcarrano** [comment]
Makes sense @LHinson I will close.
