### ISSUE TITLE
PatternFly.org contribution, revising and adding targeted webpages

### ISSUE THREAD

**Issue by Mgranfie** [patternfly/patternfly-design#361]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [x] This is an enhancement on an existing pattern
#### 2. If this enhancement or new pattern was made for an application, specify which one.
These are updates and additions to the current PatternFly.org pages to surface additional guidance access points and information around the contribution process.
#### 3. Title
How and where to access contributing to PatternFly
#### 4. Problem Solving
Today, a user has to either know how to contribute to PatternFly or know to look around the GutHub repository for contribution related information. This is not always easy to find and easy to remember where to find. Adding and surfacing information and pointers to information in GitHub will alleviate some of these hurdles to contributing.
###### *Does this pattern solve a common problem and has community interest?*
Yes, it solves the problem of knowing how to contribute to PatternFly
#### 5. Use Cases + Requirements

Use Cases:
1. User goes to the PatternFly.org website looking for information on how to contribute to PatternFly and wants to quickly and easily access this information.
2. User goes to PatternFly.org to find what tools and information are needed to contribute to  or get up and running with PatternFly.

Requirements:

1. Revise, update and add access points of the current UI's  "Community", "Download" and "Getting Started" web pages, as a first step to surfacing the information needed to contribute to PatternFly and improve discoverability and recall of this information.

#### 6. References 
None, at this time
#### 7. Design Concepts  
In progress

###### *Specify the approximate size of the work for this issue, SM, MD, LG, XL, by applying the relevant GitHub label to this issue.*
*This work is a MD. Accounting only for the Design work and not the implementation of the work."*

**Comment by mcarrano** [comment]
@Mgranfie and @LHinson Does this issue really belong in the design repo?  Seems like it identifies work that needs to take place on patternfly.org.  My preference is to keep website issues separate (from design contributions) and file against the 'patternfly-org' repo.  Do you guys agree?

**Comment by Mgranfie** [comment]
@mcarrano I will move this to JIRA, as I think it belongs there... not sure why I put this here

**Comment by LHinson** [comment]
@Mgranfie how is this different than the story that you have this sprint? https://patternfly.atlassian.net/browse/PTNFLY-2479
