### ISSUE TITLE
Provide design guidance for a variation of the Trend Card with the values on the right

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#366]
*This is an enhancement on an existing pattern*

Currently, our [Trend Card](http://www.patternfly.org/pattern-library/cards/trend-card/#/design) supports two variations of a card with a single trend.  What's missing, is the ability to view the values on the right side, similar to 
<img width="375" alt="screen shot 2017-08-20 at 8 17 19 pm" src="https://user-images.githubusercontent.com/12504403/29499658-9c03bc46-85e4-11e7-8bae-8ec12ba8e0e6.png">

The values shown are the card are representing the most recent data, which is shown as the rightmost point on the trend line.  This variation is requested.

**Comment by beanh66** [comment]
@Mgranfie @serenamarie125 I'll work on getting this PR up from a design perspective.

**Comment by serenamarie125** [comment]
This is being tracked by https://patternfly.atlassian.net/browse/OSUX-130

**Comment by mcarrano** [comment]
Merged this PR.  Need to validate changes on website before closing this issue.

**Comment by LHinson** [comment]
@mcarrano i've rebuilt the site and confirmed that this is on the site therefore closing the issue.
