### ISSUE TITLE
Recent changes not displaying on website

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#369]
## For Bug contributions, please provide the following information... 
- [ x] I would like to report a bug<br>

Two pulled requests were merged last week, but these changes are not showing on the website. They are:
- #338 Add Experimental Features
- #358 Remove Forms and Input Controls from Forms and Controls. Update Input Controls.

Updated files are present in the design repo

**Comment by LHinson** [comment]
Experimental features is available on the site now. See: http://www.patternfly.org/pattern-library/communication/experimental-features/

Need to figure out how to address removing items. 

FYI @mcarrano
