### ISSUE TITLE
Visual diagram of the end to end design contribution process

### ISSUE THREAD

**Issue by Mgranfie** [patternfly/patternfly-design#376]
#### 1. Choose the type of contribution for this pattern:
- [x ] This is a new work, not a pattern
- [ ] This is an enhancement on an existing pattern
#### 3. Title
Visual diagram, explaining the high level,  end to end contribution process for PatternFly designs
#### 4. Problem Solving
This diagram should assist in giving users an at a glance view of the contribution process, in it's entirety, so that they can quickly and easily digest and comprehend the full contribution process.

#### 5. Use Cases + Requirements
1. User is new to the process and wants to have an understanding of what the contribution process looks like, gaining a conceptual understanding of the process.
2. User is a new or repeat user to PatternFly and may need a refresher/cheat sheet of the high level steps to contributing.
3. The user can never remember all the steps and order of the steps needed to complete a contribution, as this is not a regular and repetitive task for them, so they would like to download this image and keep it local as a reference and cheatsheet.
4. Need to determine if and how the existing diagrams factor in to the overall diagram...
  - https://github.com/patternfly/patternfly-design/wiki/Setup-Diagram
  - https://github.com/patternfly/patternfly-design/wiki/Contribution-Diagram
  - https://github.com/patternfly/patternfly-design/wiki/Branching-Diagram

#### 6. References 

The set up steps enumerated [here](https://https://github.com/patternfly/patternfly-design/wiki/How-to-Setup-your-Contribution-Environment) in the GitHub instructions. 

The contribution steps enumerated [here](https://github.com/patternfly/patternfly-design/wiki/How-to-Submit-a-Contribution) in the GitHub instructions. 

JIRA Story: https://patternfly.atlassian.net/browse/PTNFLY-2616
###### *This is not a final document for submission, these materials will be used to help us understand the concept and problem you are solving and engage in review.*<br>

TBD via the work

**Comment by LHinson** [comment]
Same comment as previous issue seen here: https://github.com/patternfly/patternfly-design/issues/361

Think this belongs in jira vs coordinating contributions.
