### ISSUE TITLE
Need a definition for log out 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#382]
- Define "Log out" as the appropriate approach for the action in the T&W section.
- Fix the masthead pattern to say "Log out" vs "Logout" 
- Fix images http://www.patternfly.org/pattern-library/application-framework/masthead/#/design 
- File a bug with core to update implementation

**Comment by LHinson** [comment]
#380 fixes first two bullets. 

@kybaker to help out with the image updates.

**Comment by mcarrano** [comment]
Merged PR #380 to fix the text.

**Comment by mcarrano** [comment]
@LHinson I believe this issue has been resolved. If you agree, please go ahead and close.
