### ISSUE TITLE
Inline Edit on Forms

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#389]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [ x] This is an enhancement on an existing pattern
#### 5. Use Cases + Requirements
Use this pattern when you want to quickly edit a single attribute without placing the entire form in edit mode.
#### 6. Design Concepts  
Prior work on conceptual design can be found here: https://docs.google.com/a/redhat.com/document/d/1VmPLt4fgL3sSBDBFdKYv38MbLK8Uh2H9hPT0Hsgh53k/edit?usp=sharing
#### 8. Pattern Name + Location  
Propose to add this to the existing Inline Edit pattern: http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/

An existing PatternFly story exists for this here: https://patternfly.atlassian.net/browse/PTNFLY-2408

**Comment by mcarrano** [comment]
Per @catrobson this is a current need for OpenShift.io. Will move to ToDo list.

**Comment by mcarrano** [comment]
Work is currently in progress as https://patternfly.atlassian.net/browse/PTNFLY-2580

**Comment by zhutaoredhat** [comment]
Design Document:
https://docs.google.com/document/d/1Z94cNbL_8TJJZLPPWExRFkovYliID5WmEL9_-2nrjZ8/edit?ts=59e657e4#
The PR:
https://github.com/patternfly/patternfly-design/pull/452
@mcarrano The document have been pull request. Please have a review~ Great thanks.

**Comment by catrobson** [comment]
Sorry it took me so long to get to a review @zhutaoredhat - I had two items I was hoping we could add to this pattern that I added to the google doc.  Otherwise the proposal looks great!  Thanks for working through this.

**Comment by zhutaoredhat** [comment]
@catrobson Thanks for your suggestion. That's great. I had pulled a new request to update it.

**Comment by mcarrano** [comment]
PR #452  merged and verified
