### ISSUE TITLE
Notification Drawer mockups inconsistent around position of caret on accordion control

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#390]
I've noticed that the mockups on this page (http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design) and this page (http://www.patternfly.org/pattern-library/communication/notification-drawer/#/overview) inconsistently show the position of the caret within the header of each accordion panel (notification tab).

When the panel is open, the caret should always point down. But in some of the mockups, you'll see the caret pointing right when the panel is open. HTML/CSS implementation is correct.

**Comment by junezhang** [comment]
@mcarrano, @zhutaoredhat will fix this issue.

**Comment by zhutaoredhat** [comment]
@mcarrano I had fixed this bug and pulled the request. https://github.com/patternfly/patternfly-design/pull/433 Please have a review~

**Comment by mcarrano** [comment]
Verify that changes are live on the website before closing.

**Comment by zhutaoredhat** [comment]
Hi @mcarrano It looks well on PatternFly.org. Please close this task~

**Comment by mcarrano** [comment]
Thanks @zhutaoredhat . Will close.
