### ISSUE TITLE
Filter Bar 

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#397]
This is a proposal for a new Filter pattern that replaces the [existing Filter pattern](http://www.patternfly.org/pattern-library/forms-and-controls/filter/) to document generic behaviors of the filter bar that apply universally to all supported filter types.

The pattern should address the following:
* How the filter bar integrates with the overall [Toolbar](http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/) when used as a part of a content view.
* How the number of results should be reflected in the filter bar (and what happens when there are no results).
* How currently applied filters are reflected and cleared (i.e. filter chips)
* How filters can be saved and recalled.

The assumption is that the Filter Bar can embed a variety of filter types (components) and that these will be documented as separate patterns and linked from the Filter Bar pattern. Related issues include:

* Filter Panel with Faceted Filter: #348 
* Toggle Filter: #363 
* Saved Filter: #306

**Comment by mcarrano** [comment]
@cshinn I created this new issue to track the generic Filter pattern we spoke about today and assigned in to you. Let me know if this correctly summarizes the requirements or if I missed anything. I'm tentatively calling this "Filter Bar" but open to suggestions.

**Comment by mcarrano** [comment]
@cshinn I happened to be looking at the Pagination pattern this morning (http://www.patternfly.org/pattern-library/navigation/pagination/#/design) and noticed that it also talks about layout of filter bar area (not sure why).  You might want to take a look at this and let me know if we need to update this for consistency with what you are proposing. Actually I'm not sure why this is relevant to pagination at all, so maybe we would just remove. But mockups would require updating at least. Please advise.

**Comment by cshinn** [comment]
Initial documentation has been created and is available here https://docs.google.com/a/redhat.com/document/d/1Jjx0kNe6qb4lCK26w5wbDriRmObenw6CeTqwY5J4eqs/edit?usp=sharing

**Comment by mcarrano** [comment]
@cshinn I just reviewed your document and left a bunch of comments. These are mostly around various details, but I really like the overall approach. Great job pulling this together! If it would help, I'd glad to meet live to review my comments with you.

So do I understand from your document that we would have three new patterns? Filters, Textbox Filters, and Checkbox Filters? I think that makes sense.
