### ISSUE TITLE
Basic Filter

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#398]
We want to re-write the current [Filter pattern](http://www.patternfly.org/pattern-library/forms-and-controls/filter/) as a sub-component of the Filter Bar (see #397) .  Basic Filter (working title) includes a category/attribute selector and corresponding input method (text field, touchspin, datepicker, etc.) to input filter value(s).

**Comment by cshinn** [comment]
Initial documentation has been created and is available here https://docs.google.com/a/redhat.com/document/d/1Jjx0kNe6qb4lCK26w5wbDriRmObenw6CeTqwY5J4eqs/edit?usp=sharing

**Comment by cshinn** [comment]
@mcarrano works for me, I would expect that the three sections of the document went into three different pages though.
