### ISSUE TITLE
Custom filter builder

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-design#403]
We are excited to have you contribute to PatternFly!<br>
To create a GitHub issue, first determine which type of contribution you are making, a pattern or a bug, and then remove text for the contribution type, that you will not need. 

#### 1. Choose the type of contribution for this pattern:
- [x] This is a new pattern 
- [ ] This is an enhancement on an existing pattern

#### 2. If this enhancement or new pattern was made for an application, specify which one.
iPaaS, BxMS, OpenShift.io

#### 3. Title
Custom filter builder

#### 4. Problem Solving
Users want to create a fairly advanced, custom filter based on many criteria and booleans.

#### 5. Use Cases + Requirements
The custom filter builder will allow users to create a custom filter based on a combination of values and booleans that is more advanced than a normal filtering pattern would provide.

#### 6. References 
https://patternfly.atlassian.net/browse/PTNFLY-2568

#### 7. Design Concepts  
<img width="360" alt="createfilterdropdown-2_720" src="https://user-images.githubusercontent.com/3739227/29892616-36839c68-8d9d-11e7-9fdc-d7e38fdf1838.png">

#### 8. Scope  
This pattern would focus on the interaction of these rows of selections, adding the rows, and removing the rows as you build out these queries.  It would not focus on the placement on the screen (whether this lives in a filter panel on the right, a modal, a full page like this, or a filter overlay).  We could just allude to and linked off to other patterns that talk about filtering placement.
  
#### 9. Assign  
SJ Cox will contribute this pattern.

**Comment by mcarrano** [comment]
@sjcox-rh can you please be sure to attach the requirements you are gathering here?  Thx.

**Comment by sjcox-rh** [comment]
Here is the link for the requirements doc for the custom filter builder. Please review and let me know if you have any questions.

Thanks!

https://docs.google.com/a/redhat.com/document/d/1bbPI_jPig3PrvfrVTQUoKB36BkYd0PEie2ylURysXUg/edit?usp=sharing 

@mcarrano @maryclarke @serenamarie125 @LHinson @catrobson @lizsurette

**Comment by mcarrano** [comment]
@sjcox-rh I think we are good to move forward with a preliminary design based on feedback. Please also consider how this will integrate with the filter framework that @cshinn is working on.

**Comment by sjcox-rh** [comment]
@mcarrano perfect! Should I go ahead and create a story in PatternFly's backlog? and sorry for the delay, just got back from PTO

**Comment by mcarrano** [comment]
Yes, go ahead and create a story in the PatternFly backlog @sjcox-rh and you can link it here.

**Comment by sjcox-rh** [comment]
Here is the conceptual design story in Jira: 

https://patternfly.atlassian.net/browse/PTNFLY-2649
