### ISSUE TITLE
Inline Components for Tabs

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#404]
- [ ] This is a new pattern 
- [ x] This is an enhancement on an existing pattern
#### 6. References 
Existing Tabs pattern (on Widgets page) http://www.patternfly.org/pattern-library/widgets/#tabs

#### 7. Design Concepts  
Webcomponents implementation: https://rawgit.com/priley86/patternfly-webcomponents/pf-tabs-updates-dist/app/app.html?dir=pf-tabs&file=index.html

###### *Once the design issue has been reviewed, the name and location, within the PatternFly.org website, will be determined and posted here, on this issue, by a PatternFly team member.*

Note that Tabs is currently presented on Widgets page but we should consider whether a new Tabs pattern page is needed under Forms and Controls.

**Comment by mcarrano** [comment]
This topic was discussed in the biweekly CSS meeting on 9/6 and it was noted that placing buttons or other components inline with the tab bar leads to difficulties with responsive behavior. Perhaps there are other solutions to this use case. @maryclarke and @jgiardino an alternate approach supported by PatternFly can be seen here in the context of Canvas View (http://www.patternfly.org/pattern-library/content-views/canvas-view/#/overview) Would this meet your requirements? If so, maybe what we should do from a PatternFly perspective is to generalize this approach to be applicable to a variety of detail view types.

**Comment by maryclarke** [comment]
We have decided to go a different direction, so closing this issue.
