### ISSUE TITLE
Login Enhancements 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#406]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [X] This is an enhancement on an existing pattern
#### 2. If this enhancement or new pattern was made for an application, specify which one.
Keycloak
Identity Management
#### 3. Title
Login Screen
#### Problem 
The existing login design issues causing it to be inflexible are: 

- The two column layout 
- Everything positioned at the bottom 

#### 5. Use Cases + Requirements
Design requirements: 

- Ensure that it's responsive 
- Ensure that it can have more than two fields or just one if password is not needed based on type of user 
- Ensure layout is flexible in order to add other element such as social badges
- Flexible logo position 
- Identify what is mandatory vs. optional. 

See examples here: 
https://docs.google.com/document/d/1CdxlqxskfpjMW_i5AS8KfdcH7Sr2cNutMAThw_Sj_n0/edit#

**Comment by LHinson** [comment]
@maryclarke identified that Identity management has similar requirements and will dig those up and surface them here.

**Comment by junezhang** [comment]
@mcarrano, @zhutaoredhat and @yih-wang would like to work on this task.

**Comment by mcarrano** [comment]
Research and preliminary recommendations are summarized here. https://docs.google.com/a/redhat.com/document/d/1cqfOsR9iw3rw9bB1etj-svMmil_HvVg4Z1oPIFvJlS0/edit?usp=sharing

Please review @serenamarie125 @catrobson @maryclarke @jeperry @kybaker

**Comment by mcarrano** [comment]
@mcarrano will follow up with proposed next steps.  Consider if there are additional requirements we should consider.

**Comment by mcarrano** [comment]
Design recommendations for a variety of login page templates are summarized in an InVision document here: https://redhat.invisionapp.com/share/59DNSUUZT#/255230613_1 @serenamarie125 @catrobson @maryclarke @jeperry please review and comment. 

https://patternfly.atlassian.net/browse/PTNFLY-2559 created to track feedback and next steps.

**Comment by mcarrano** [comment]
Today a meeting was held with @mcarrano, @LHinson , @catrobson , Amy Glass, and Stian Thorgerson, and Stan Silvert (KeyCloak project) to discuss next steps.  The following action items were captured:

* Keycloak needs Way to log into corporate Single Sign-On login. This is use case where the user signs on once to gain access to multiple applications within an organization. Need to communicate hierarchy Company -> Product Name.  Create an additional login page template and add to existing InVision doc. @mcarrano will create a PF story. Once this is complete, Stian will send to Keycloak community for further comments.

* Want to proceed forward with visual design work for new login templates. @mcarrano will create a PF story.

* KeyCloak needs guidance on for to integrate custom actions into login workflow, e,g,  things user must do before logging in? (i.e. you must update your password). Stian/Stan will send screenshots of existing functionality to @catrobson who will determine best path forward for UXD support.

* @mcarrano and @LHinson will assess effort and priority and follow up with Stian for estimated availability of new login templates.

**Comment by mcarrano** [comment]
New PatternFly stories created:
* Add single-sign on: https://patternfly.atlassian.net/browse/PTNFLY-2602
* Visual design for new login screens: https://patternfly.atlassian.net/browse/PTNFLY-2603

**Comment by yih-wang** [comment]
Thanks @mcarrano, I will take the single-sign on task. Will we be responsible for the visual design, or the brand team will work on it?

**Comment by guillaumevincent** [comment]
Hello, 
this feature will be really useful for us too.

Here the actual login screen we use:

![screenshot-2017-10-23 distributed ci](https://user-images.githubusercontent.com/943762/31901171-fb4203f2-b820-11e7-8055-0a21b7dedf5e.png)

There is some issue on the mobile experience also:

![screen shot 2017-10-23 at 18 37 41](https://user-images.githubusercontent.com/943762/31901282-45c73ad2-b821-11e7-807d-30b97c00037b.png)

with red body to see the wrong padding on `.login-pf #badge`

**Comment by mcarrano** [comment]
Someone from the Visual team will handle the visual design story, so we just need the SSO template from you, @yih-wang . Thanks for taking this on!

**Comment by mcarrano** [comment]
Interaction design has been reviewed and is summarized here: https://redhat.invisionapp.com/share/2DE6FA656#/screens/255230615. Need guidance on next steps.

**Comment by yih-wang** [comment]
@mcarrano @LHinson I have sent a PR #501 to fix this issue. Please have a review. Thanks.

**Comment by mcarrano** [comment]
Three PR's have been merged and new patterns are now live on website. Needs to be updated with hi-res mockups.

**Comment by mcarrano** [comment]
There are three open PRs to further update the visual designs: #509 , #510 , #511 . To reduce redundancy, I am going to close this issue out and track further comments per these PRs.
