### ISSUE TITLE
Modeless Overlay

### ISSUE THREAD

**Issue by lwrigh** [patternfly/patternfly-design#409]
#### 1. Choose the type of contribution for this pattern:
- [X] This is a new pattern 
- [ ] This is an enhancement on an existing pattern
#### 2. If this enhancement or new pattern was made for an application, specify which one.

This is not an enhancement.  

#### 3. Title
Modeless Overlay
#### 4. Problem Solving
An overlay panel that displays more detailed information while still allowing the user to access and interact with the information behind the panel.  
#### 5. Use Cases + Requirements
Use Cases

General

* If the user needs to access more detailed information from a list or dashboard. 
* If the user needs more detailed information while still needing access to the underlying UI. 
* Quick access to details without leaving a main page. 
* A substitute for a modal when the underlying UI directly affects the surfaced details. 

More Detailed 

* This pattern should be used only for detailed or secondary information, primary information should not live on this panel. 
* The underlying information should be directly related to the detailed information that is presented on the panel. 
* This pattern could be used to add, view, edit, and remove detailed information on an individual item. 

#### 6. References 

https://github.com/fabric8-ui/fabric8-ux/issues/632

#### 7. Design Concepts  
![osio- overlay panel](https://user-images.githubusercontent.com/20227374/30170952-8a4ad254-93be-11e7-9f78-c99c87af9dce.png)
![osio- overlay panel empty state](https://user-images.githubusercontent.com/20227374/30170953-8a4b8b9a-93be-11e7-9b03-2ddc2e517bec.png)

#### 8. Scope  

MD

###### *Once the design issue has been reviewed, the name and location, within the PatternFly.org website, will be determined and posted here, on this issue, by a PatternFly team member.*

@Mgranfie @catrobson

**Comment by beanh66** [comment]
@lwrigh I thought we decided this would actually be a separate pattern rather than an enhancement to an existing pattern. For my submission the pattern is called "Modal Overlay" and exists in the Forms and Controls folder. My understanding was that your submission would be "Modaless Overlay" and would be located in the same folder in PF but a separate pattern. @Mgranfie @mcarrano Do you agree?

**Comment by Mgranfie** [comment]
@chart yes, this makes sense and was how I understood it.

One question that comes to mind, when I read this.... is... are the
position and modality dependent?

-Monica

**Comment by mcarrano** [comment]
Yes, this should be submitted as a new pattern and located in Forms and Controls. Title should be Modeless Overlay.

@lwrigh there was already an issue opened for this here: https://github.com/patternfly/patternfly-design/issues/402 If this has more complete information, I will close the old one. Let me know what you prefer, but would rather not keep both open.

**Comment by lwrigh** [comment]
@mcarrano That works for me. I can update this one accordingly and submit it as a new pattern.

**Comment by lwrigh** [comment]
@mcarrano Am I still in need of a review before I continue onto submitting the final design documentation?

**Comment by mcarrano** [comment]
@lwrigh there are a couple of ways we can approach this. Do you feel like there are significant open issues of questions that we should address before you proceed too far? If so, I would recommend pulling together a few folks and walking through your design proposal with them to get some feedback. If you feel more confident and/or you've done the due diligence to vet your proposal with other, you can always jump right into creating the PR with the understanding that changes might be requested at that stage. What's your preference?

I do recall that @Mgranfie had some questions about this so have you and her had a chance to sync up?

**Comment by lwrigh** [comment]
@mcarrano I think I'm going to go down the path of asking for more feedback on the design and content before I start working on the final design submission. 

I had a chance to catch up with Monica today and she was able to give me more direction with the next steps in the contribution process.

**Comment by Mgranfie** [comment]
@lwrigh can you please place a link to the Google Doc in the References in the Issue above...

**Comment by mcarrano** [comment]
Looks like this is now live on the website so will close.

**Comment by Mgranfie** [comment]
Fantastic PatternFly addition!! Thanks everyone!
