### ISSUE TITLE
Full product logotype should be displayed in responsive states on mobile devices

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#411]
## For Pattern contribution proposal, tell us about your idea... 
(delete section if filing a bug)
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [ x] This is an enhancement on an existing pattern

#### 6. Design Concepts  
TBD
#### 7. Scope  
TBD

**Comment by mcarrano** [comment]
PatternFly story https://patternfly.atlassian.net/browse/PTNFLY-2547 has been created to further investigate options and make some recommendations.

**Comment by deernano** [comment]
@mcarrano 
Product logotype responsive state research
https://docs.google.com/document/d/1EYC705bk65wyl-ZFKTDa9_iC3JkD1X2KikvXik2Psl0/edit#

**Comment by mcarrano** [comment]
The document above contains some research and options for this ^^^

Please review and comment @serenamarie125 @maryclarke @catrobson @jeperry @kybaker

**Comment by mcarrano** [comment]
Let's hold on this until we have more info on future direction of RH product branding.

**Comment by mcarrano** [comment]
After discussions with @deernano @matthewcarleton and @kybaker we arrived at a proposal to go to a 2 line header where the first line with the logotype collapses on scroll. You can see a demo of that here: https://codepen.io/matthewcarleton/pen/bogyKg  See this JIRA story for the complete discussion: https://patternfly.atlassian.net/browse/PTNFLY-2547

@serenamarie125 @catrobson @maryclarke @jeperry @LHinson Thoughts?

**Comment by mcarrano** [comment]
Per 10/5 UXS mtg lets move forward. I will create needed stories.

**Comment by mcarrano** [comment]
Work to make these changes to the library in progress as https://patternfly.atlassian.net/browse/PTNFLY-2581

**Comment by deernano** [comment]
@mcarrano  Please review the PR of responsive state. Thank you !
https://github.com/patternfly/patternfly-design/pull/476

**Comment by deernano** [comment]
@mcarrano Updated, please review again~

**Comment by mcarrano** [comment]
Merged #476 . Verify changes on website.

**Comment by mcarrano** [comment]
Verified.
