### ISSUE TITLE
The `url-js-extra` front matter attribute in empty-state site.md file needs to be an array

### ISSUE THREAD

**Issue by bleathem** [patternfly/patternfly-design#416]
In PR #385 a `url-js-extra` attribute was added to the `pattern-library/communication/empty-state/site.md` file needs to be an array, as in the file referenced in the comments of the PR:
https://github.com/patternfly/patternfly-design/blob/master/pattern-library/content-views/card-view/site.md

**Comment by dabeng** [comment]
The related PR has been submitted. Please review https://github.com/patternfly/patternfly-design/pull/419
