### ISSUE TITLE
Fix Typo in Image in Language Selector pattern

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#420]
The image on the design tab of the Language Selector pattern has a typo.  "Logout" should be updated to "Log Out"

![image](https://user-images.githubusercontent.com/12504403/30464032-2120ddac-999d-11e7-8adc-cf5ca5210471.png)

**Comment by kybaker** [comment]
@serenamarie125 Added a story in the visual backlog for this.

**Comment by kybaker** [comment]
@LHinson This was fixed, merged, and can be closed - Convert Language Selector to High Fidelity #427.

**Comment by mcarrano** [comment]
Will close.
