### ISSUE TITLE
Comments pattern hi-fi visuals

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#421]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [x ] This is an enhancement on an existing pattern

Comments pattern hi-fi visuals: http://www.patternfly.org/pattern-library/communication/comments/#/overview

FYI @kybaker @mcarrano

**Comment by kybaker** [comment]
@LHinson Added a story in the visual UXVDN backlog for this.

**Comment by kybaker** [comment]
@LHinson This was merged and can be closed - Convert comment images to high fidelity #428
