### ISSUE TITLE
Images for Responsive wizard do not match docs

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#422]
Images for responsive wizard do not match the actual behavior. 

>  **Button Bar:** Wizard actions are available on the button bar, which is fixed at the bottom of the page for embedded wizards and modals wizards except for in smaller screen sizes, which requires the user to scroll the page for the button bar.

...however the images show the button bar fixed.

**Comment by mcarrano** [comment]
@kybaker How should we handle this? Is this something you or someone else on the visual team can update or should I put in "help wanted" list?

**Comment by kybaker** [comment]
@mcarrano I will add it to the visual design backlog.

**Comment by mcarrano** [comment]
@LHinson will follow up with @matthewcarleton to confirm behavior of the buttons whether modal or embedded.

**Comment by mcarrano** [comment]
@LHinson @matthewcarleton Can you comment on this issue? Is it still pending?
