### ISSUE TITLE
Clarification about Toast Notification behavior 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#423]
The toast notification pattern states: 

> Toast Notifications should remain on the screen when the user is hovering on them.

It's not clear whether or not just the toast being hovered should remain or if all toasts should remain if one is hovered. For that reason, we've had a bit of discrepancy in implementation between repos.

The pf-react implementation (in progress and not yet merged), leaves all toasts on the screen when one is hovered. The angular-pf implementation, leave only the toast that is hovered on the screen. Which approach is recommended?  

- [React impl - not merged yet](https://rawgit.com/priley86/patternfly-react/toast-notification/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Header=Great%20job%21&knob-Message=By%20default%2C%20a%20toast%20notification%27s%20timer%20expires%20after%20eight%20seconds.&knob-Type=success&knob-Dismiss=true&knob-Menu=true&knob-Action=true&selectedKind=ToastNotification&selectedStory=Toast%20Notification%20List&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)
- [Angular impl](http://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfToastNotificationList)

@mcarrano thought we could review in the design lead meeting. Also looping in @priley86 @jgiardino since this is a result of the react repo team meeting.

**Comment by mcarrano** [comment]
Per UXS review, want all to remain if any is hovered on.

**Comment by mcarrano** [comment]
A PatternFly Story has be created to make these updates. Ref https://patternfly.atlassian.net/browse/PTNFLY-2555
