### ISSUE TITLE
Mockup on Errors and Validation not consistent with latest guidance

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#436]
- [x ] I would like to report a bug on, design documentation, visual or interaction design inconsistencies, feedback or suggestions<br>

The mockup on [Errors and Validations page](http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/) is not consistent with latest guidance on displaying buttons on forms. Should be Save and Cancel rather than Save changes and Close.  See http://www.patternfly.org/pattern-library/forms-and-controls/buttons-on-forms/ for up to date guidance.

**Comment by mcarrano** [comment]
@yih-wang Since you are working on the Errors and Validation page, I wanted to assign this small issue to you also. It just requires that we make sure that the mockups on this page are consistent with our button labeling standards.

**Comment by yih-wang** [comment]
@mcarrano This issue has been solved in #465 . I think it can be closed. Thanks.

**Comment by mcarrano** [comment]
Merged pr #465 Validate changes to site before closing.

**Comment by mcarrano** [comment]
Verified on website.
