### ISSUE TITLE
'Field Level Help' and 'Help on Forms' are inconsistent and redundant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#437]
## For Bug contributions, please provide the following information... 
(delete section if proposing a design)
- [x ] I would like to report a bug on, design documentation, visual or interaction design inconsistencies, feedback or suggestions<br>

The new [Help on Forms](http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/) pattern contains redundant information with [Field Level Help](http://www.patternfly.org/pattern-library/forms-and-controls/field-level-help/) and uses incorrect info icon in mockups.

**Comment by mcarrano** [comment]
@LHinson I just noticed this today while reviewing some of the Forms and Controls content. I think our intent was to remove Field Level Help when we added Help on Forms, but want to verify. There was a recent update to the hi-fi mockups for Field Level Help that did not make it to the new pattern so this should also be updated.

**Comment by LHinson** [comment]
+1 @mcarrano for both issues. We need work with @bleathem to understand how to address these types of things so that we know what to do in the future.

**Comment by mcarrano** [comment]
I have added the 'Help Wanted' tag and we will see if this is something we can get in during the next sprint to make the needed corrections.

**Comment by junezhang** [comment]
@mcarrano @LHinson please help to review this PR.

**Comment by mcarrano** [comment]
Looks like this is complete, so will close. Thanks @junezhang !
