### ISSUE TITLE
Two-Column List Layout

### ISSUE THREAD

**Issue by maryclarke** [patternfly/patternfly-design#439]
We are excited to have you contribute to PatternFly!<br>
To create a GitHub issue, first determine which type of contribution you are making, a pattern or a bug, and then remove text for the contribution type, that you will not need. 

#### 1. Choose the type of contribution for this pattern:
- [X] This is a new pattern 
- [ ] This is an enhancement on an existing pattern
#### 2. If this enhancement or new pattern was made for an application, specify which one.
RHEL Composer, possibly RHEL8 Installer, and investigating with Cockpit team
#### 3. Title
Two-Column List Layout

#### 4. Use Cases + Requirements
Allows users to scroll two independent lists side by side and give them the ability to move items from the left hand list into the right hand list.  Also provides the ability to drill into each specific item and see more details.

#### 5. Design Concepts  
<img width="743" alt="screen shot 2017-10-06 at 10 20 43 am" src="https://user-images.githubusercontent.com/20341028/31284591-00b68a44-aa87-11e7-96a4-655d09b20308.png">

#### 6. Scope  
Probably SM to MD in size depending on exactly how the concept is contributed.  It could be one large pattern or broken down into several.

#### 7. Assign  
Jenn Giardino and Matt Carleton will work on this contribution

**Comment by mcarrano** [comment]
After further discussions with @andresgalante and CSS team, will close for now
