### ISSUE TITLE
Shuttle Selector/Dual Pane Selector - New Design Pattern

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#443]
#### 1. Choose the type of contribution for this pattern:
- [x] This is a new pattern 
#### 2. If this enhancement or new pattern was made for an application, specify which one.
Satellite is using this pattern, and this can be used in other Management products.
#### 3. Title
"Shuttle Selector" Or "Dual Pane Selector" were original thoughts, although unsure if this is recognizable by all
#### 4. Use Cases + Requirements
User needs to visually compare available and selected items and move items between those states. #### 5. Design Concepts  
Initial PR https://github.com/patternfly/patternfly-design/pull/160
###### *Once the design issue has been reviewed, the name and location, within the PatternFly.org website, will be determined and posted here, on this issue, by a PatternFly team member.*

@mcarrano, there was a couple of PRs initially put up by @Rohoover before we had the contribution process nailed down.  I'd like to get this back on the agenda, so we can see if we have consensus for this to be worked on again.

**Comment by serenamarie125** [comment]
Assigning to myself, since this will be contributing back from the Mgmt side

**Comment by mcarrano** [comment]
Let's move forward with use case any discovery work.

**Comment by serenamarie125** [comment]
Here's an initial document written by @Rohoover .  @mcarrano @maryclarke @catrobson @jeperry please take a look.

**Comment by mcarrano** [comment]
Thanks for moving this along @Rohoover . Overall is looking good. Left a few comments in your document.

**Comment by Rohoover** [comment]
Thanks @mcarrano.

I've updated the document/design to answer questions and resolve issues.

**Comment by mcarrano** [comment]
@serenamarie125 @Rohoover I took another look at the Google doc and I think we are ready to move ahead with this. I'll just look forward to seeing a PR when you are ready to submit. I would add this to Forms and Controls. Note that there are still files present from the old PR you submitted over a year ago that never got published @Rohoover . Would can just replace those with this new version. Should have an overview.md, design.md, site.md and associated images. Let me know if you have any questions.
