### ISSUE TITLE
Need better guidance on selecting date and time

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#459]
#### 1. Choose the type of contribution for this pattern:
- [ x] This is a new pattern 
- [ ] This is an enhancement on an existing pattern
#### 4. Use Cases + Requirements
* User wants to set a date, time, or date and time.
* User wants to set a date range for filtering.
We currently have Datepicker and Timepicker widgets but no guidance on how to use these in common use cases.
#### 5. References 
None
#### 6. Design Concepts  
None
#### 7. Scope  
Research and design
#### 9. Pattern Name + Location  
Propose "Date and Time" to be added to forms and controls.

**Comment by mcarrano** [comment]
@serenamarie125 will consider if we have a resource to work on this.

**Comment by jeperry** [comment]
Sam Linville worked on a date range picker, so when this is picked up we should look at this. https://redhat.invisionapp.com/share/ZBCBL4UP6#/screens/256225779

**Comment by mcarrano** [comment]
@serenamarie125 will look at whether there is an available resource.

**Comment by mcarrano** [comment]
Thanks for offering to take this on @nding-anges  When you are ready, please just attach your proposal for review.

**Comment by nding-anges** [comment]
@mcarrano Please find the first version of " Selecting date and time - Concept Design " with this link:
https://docs.google.com/document/d/1evHUQwFY7KaVg0xgltUdqX92jMKgS71YjQCZu6yBLIk/edit?usp=sharing

**Comment by mcarrano** [comment]
@jeperry @serenamarie125 @catrobson @maryclarke @kybaker @LHinson please review. @matthewcarleton would also like you to take a look. This implies extending what we currently support now for our date and time picker so want to make sure that we can integrate these suggestions into our existing component set.

**Comment by nding-anges** [comment]
@mcarrano  I made a new design proposal in Invision and put all component for completeness. It was based on the reference of Bootstrap , which is suggested by Liz Clayton, see detail here: https://redhat.invisionapp.com/share/TZGSUJZXG9A#/290220418_Date_-time_Selector_Proposal_A
We could comment on that and after I go back to finalize the design guidance.

**Comment by nding-anges** [comment]
Hi, Dear all, @mcarrano @jeperry @serenamarie125 @catrobson @maryclarke @kybaker @LHinson please review. @matthewcarleton  I put the image of design proposal of date time picker here and also you could check it and comment on Invision with the link https://redhat.invisionapp.com/share/TZGSUJZXG9A#/290220418_Date_-time_Selector_Proposal_A   
![2018-04-16 5 50 42](https://user-images.githubusercontent.com/34368385/38802341-c6d97872-419e-11e8-871f-bd8f90957553.png)

**Comment by nding-anges** [comment]
![2018-04-16 5 57 49](https://user-images.githubusercontent.com/34368385/38802735-d957c7fa-419f-11e8-9c3b-bc02f736b8f5.png)

**Comment by nding-anges** [comment]
![2018-04-16 5 58 02](https://user-images.githubusercontent.com/34368385/38802754-e89d8b64-419f-11e8-977e-5a6663d9b84d.png)

**Comment by nding-anges** [comment]
![2018-04-16 5 58 21](https://user-images.githubusercontent.com/34368385/38802775-f36c2186-419f-11e8-89a2-6322a3ebffa6.png)

**Comment by maryclarke** [comment]
Added some comments to the Invision doc.

**Comment by nding-anges** [comment]
Hi Matt, @mcarrano 
After internal discussion of our UX team , I made a new alternative design - proposal C. 
The differences compared with previous design are basically focus on date-time picker and  date-time range picker. These two components in Proposal A  are using a picker associated  time picker and calendar, and in Proposal C, time picker and calendar  are separately.

The improving points of Proposal C are summarized below :
1.  Better for responsive design
2. Make the picker  more simple and separate task for user.(e.g: On using date-time range picker, if user just want to just modify minute or hour , they don’t need to open a complete picker for changing it.)
3.  Easy for development 

Please have a look and compare with them. I am looking forward to gathering  more opinion from our team.

The Proposal link:

Proposal C: https://redhat.invisionapp.com/share/TZGSUJZXG9A#/293134549_Date_-time_Selector_Proposal_C

Proposal A:  https://redhat.invisionapp.com/share/TZGSUJZXG9A#/290220418_Date_-time_Selector_Proposal_A

**Comment by mcarrano** [comment]
@nding-anges Thanks for providing this additional proposal. Agree that separating date and time makes this easier. I left a few questions/comments on your InVision project.

As for next steps with this, now that we are beginning work on PatternFly-next, I'm reluctant to make any major changes to our existing date and time picker approach. I do think that this research is useful for informing our next generation designs, however. Perhaps we can think about testing some of these alternatives using an interactive prototype?

The only exception to the above is that I would like to have better guidance on selecting a date range. We do not have a good solution to that today. Please take a look at what's on this test page: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-datepicker.html  and look specifically at the date range example. Perhaps we can look at updating that based on your recommendations. What would you suggest that we change?

**Comment by nding-anges** [comment]
@mcarrano OK.I get your point. So to thinking about PF next , the first priority task for now is time range design by making less changes and providing better guidance for it. I will work on this firstly. And I just saw The issue #336, that is a good use case. We could thinks about how could be a appropriate design and relative guidance based on that .

**Comment by nding-anges** [comment]
@mcarrano Hi Matt, Please find the first version of " Date Range Design and Guidance " with this link:https://docs.google.com/document/d/1pOMxt6rqJgH0_jc0dDWQhH0IfMwjvSWCMRNxl-TMhZA/edit?pli=1

**Comment by mcarrano** [comment]
@nding-anges Looks good, but just a question. I see two proposals and not sure how to evaluate them. Is proposal A the one that is more aligned with the current Datepicker we are using? If so, see my questions/comments. @matthewcarleton can you also take a look. Do you see anything that would be problematic from an implementation standpoint?

@jeperry @maryclarke @serenamarie125 @catrobson would also like some input on requirements here for date range filtering. Besides selecting events taking place within a range of dates, do we need to consider situations where either start or end date is unbounded, i.e. show me all events before <start-date> or show me all events after <end-date> ? Do we have those use cases in product?

**Comment by jeperry** [comment]
> situations where either start or end date is unbounded, i.e. show me all events before or show me all events after

I'm sure that we do, but I don't think a single control needs to also handle all of these cases. Instead, I'd expect this to be handled as by combining existing controls. For example, a picker to select the input I want to provide (days before, exact day, days after, or specific range.)

**Comment by nding-anges** [comment]
@mcarrano The Proposal A is the one that is more aligned with the date range example on this test page: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-datepicker.html and I have made some little changes. The proposal B is more improved in term of usability that some of our products are using a date range pattern like this. Since it is a completely a new pattern from an implementation standpoint, I am not sure if it will be better for the next phrase on considering  of PatternFly Next. What are your thoughts?

**Comment by mcarrano** [comment]
@nding-anges Before we commit to a design approach, I'd like to see us create a working prototype of this. If possible we'd like you to work with @dabeng to create a new test page that demonstrates the following use cases:

- Picking a single date or time.
- Picking a date range
- Picking a date and time in combination.

We'd like you to begin with trying to utilize the existing Bootstrap Datepicker since we already have that in the library, but you may explore other approaches if they will lead to a more usable solution. What I want to ensure is that we have a recommendation for implementation that goes along with our design advise.  Let me know if you have any questions. Would be glad to set up a time to meet if we need to discuss live.

@LHinson FYI

**Comment by nding-anges** [comment]
@mcarrano  It will be great that we could arrange a short discuss live. I'm available from this Wednesday to Friday between 20:00-22:00 (Beijing time) I think 30 mins should be okay .  Please let me know which time should be suitable for you ? Thanks.

**Comment by dabeng** [comment]
Additional Info:
1. I think it's better to use two standalone input boxes to host begin date and end date for date range picker rather than single input box. As far as I know, in practical development, backend developers like using two columns of database table to store begin date value and end date value.

2. There is no need to include many similar bootstrap date picker components in patternfly-core repo. IMO, bootstrap datetimepicker is good enough to fulfill current requirements

**Comment by mcarrano** [comment]
Thanks for posting this @dabeng . I am OK with using separate fields for start and end date/time as you have implemented this. It seems like a very clear way to handle ranges. @nding-anges what do you think? One question I have is what if we want to specify "any time before x" or "any time after y"? would it make sense to be able to just clear either the start of end date to get this result?

I think that there are some further refinements that can be made. Looks like we lost the Today button from the bottom of the calendar. Was that intentional? I'd like to consider how we combine date & time when the user needs to select both. I see two different approaches. Let's continue to iterate.

**Comment by mcarrano** [comment]
@nding-anges @dabeng and I met today to further discuss next steps. For PatternFly 3, we will continue to explore an approach as demonstrated by @dabeng above that uses separate Bootstrap Datepickers for selecting a range. We can explore a more elegant approach for pf-next. The is an open feature issue for pf-next here: https://github.com/patternfly/patternfly-next/issues/180 @nding-anges feel free to post ideas there for longer term implementation.

A few things that need to be considered are:
- How can I select a date range filter that includes time, i.e. date/time start - date/time end ?
- How can we include predefined ranges, e.g. last 30 days, last 12 hours, etc.
- Can we support open ended date/time ranges, i.e. all items before endDate or all items after startDate? (Note this if nice to have but not critical).

The attached wireframe sketch shows a potential approach. @nding-anges and @dabeng will continue to work together on a prototype.

![date range picker](https://user-images.githubusercontent.com/6619860/39834518-3a6fc6a2-539b-11e8-8a6d-2e669271316b.png)

**Comment by dabeng** [comment]
Hi @mcarrano . The following is updated demo page of prototypes :blush: 
https://rawgit.com/dabeng/patternfly/date-range-dist/dist/tests/time-picker2.html

**Comment by mcarrano** [comment]
This looks good @dabeng But I just have a few questions.

* It seems like for the single date picker we lost the Today button at the bottom. See http://www.patternfly.org/pattern-library/forms-and-controls/datepicker/#code

* For Date & Time, I'm not sure about the calendar and the time picker side by side. Why should this be different from the way we toggle between date and time in the Range picker? @nding-anges what do you think? Do you prefer one approach vs. the other?

* Not sure if Time Range is needed as this can be accomplished with the combined date/time range picker.

* If we go with the kebob approach, we need to decide of standard options. @nding-anges thoughts here?

**Comment by dabeng** [comment]
Hi @mcarrano @nding-anges 
1. The whole page of time-picker2 is built up based on ["bootstrap datetimepicker"](https://eonasdan.github.io/bootstrap-datetimepicker/). IMO, this plugin can fulfill all the demands we described in design doc of date picker.
"today" button is the feature ["bootstrap datepicker"](https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=true&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox) provided. 
2.

**Comment by dabeng** [comment]
Hi @nding-anges , I have enable toadybutton of bootstrap datetimepicker - https://rawgit.com/dabeng/patternfly/date-range-dist/dist/tests/time-picker2.html

**Comment by dabeng** [comment]
Hi @mcarrano I added custom code to replace all icons of action buttons with text as shown below:

<img width="512" alt="screen shot 2018-05-16 at 8 40 15 am" src="https://user-images.githubusercontent.com/5689075/40091023-fe5d13de-58e7-11e8-810a-f04a2418c521.png">

**Comment by dabeng** [comment]
Additional Info:

1. bootstrap datetimepicker itself can not provide ["select range in one input" feature  ](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/2163).

2. bootstrap datetmepicker can not allow users to select range in one calendar.

3. But above two demands have practical significance. 

4. With the help of[ a huge mount of custom code](https://github.com/dabeng/patternfly/blob/b211655ed4ec211c171174e34daa484c866feb9d/tests/pages/_includes/widgets/forms/date-range-with-single-calendar.html), the example "Date Range with single Calendar" fulfill these demands.

<img width="366" alt="screen shot 2018-05-16 at 9 39 21 am" src="https://user-images.githubusercontent.com/5689075/40093074-1343a1ea-58f3-11e8-88d1-d35d50e5c165.png">

**Comment by matthewcarleton** [comment]
I would say that we should stay away from it for core. We wouldn't introduce this with custom JS for PF-next so core should be the same.

**Comment by mcarrano** [comment]
Thanks @matthewcarleton . 

@nding-anges can you please proceed with finalizing the design and creating a new Date and Time pattern to replace the current Datepicker in Forms and Controls? I think that the design page can show these various options with a note that the single date range picker will not be available in PatternFly core, but can be an alternative approach for JS implementations. Let me know if you have questions.

**Comment by dabeng** [comment]
Hi @matthewcarleton Is it our explicit convention to exclude the patterns or demos which contain custom js code snippets ?

**Comment by nding-anges** [comment]
Hi Matt

I just want to confirm 3 small  issues with you that summary as below:

1. Design of Today and Time Button need to be reviewed. 

2. The  Single Date picker  on currently  patternFly will replaced  by components  based on Bootstrap date time picker that @dabeng  did as prototype, I will also make all components using a same UI design .  

3. After I discuss with @dabeng  , we recommend that do not add the single calendar design in design note , as it is not completely design solution and we have some unsure implement issues , Any thought?

**Comment by mcarrano** [comment]
@nding-anges See my responses to your questions:

1. I'm not sure that either option works for me completely. I definitely would avoid Option B because it does not seem right that one action is a link style and the other is a button. So option A seems closer, but I'm not sure that the "v" is right. It indicates that this is a dropdown to me which I know is not the case.  Maybe something like "Time ->" to indicate navigation to a new panel? Don't know. Perhaps you can try some other options. And it would be good to see what the Timepicker looks like then. How do I get back to Date?

2. Yes, that's what I expect.

3. If you and @dabeng think it's best to leave the single calendar date range picker out for now, I'm OK with that. It keeps things simpler.

**Comment by nding-anges** [comment]
Thanks! @mcarrano 
Regarding Time button , I also think that using a symbol to indicate navigation will be better.But since the new panel will get in from bottom to top, something like " ^ "  maybe indicate clearly the direction.
Otherwise, I think that Option A is more clear to inform which panel user will enter and which they will come back to. What do you think?  
See more detail 
![today - time](https://user-images.githubusercontent.com/34368385/40351798-d82074d4-5ddf-11e8-858a-79c870940ea4.jpg)

**Comment by dabeng** [comment]
Hi @nding-anges @mcarrano bootstrap datetimepicker doesn't provide the APIs to switch action buttons' caption between calendar view and clock view. If necessary, I can try to add trick code to fulfill this demand: 

> 'Today' button should change to 'Now' button in case I want to set the time to the current time

**Comment by nding-anges** [comment]
That makes sense. "Now" is better. We just need to confirm with @dabeng to see whether it could be customized separately. And I did the first version of Design note, https://docs.google.com/document/d/1kVAhNzSB-szucfeGgq815dB6e214WavZ-gqRR0Sydj0/edit?usp=sharing @mcarrano please have a review.

**Comment by mcarrano** [comment]
@nding-anges Thanks for posting the design document. I did not have a chance today, but will try to review by the end of this week and give you some feedback.

**Comment by mcarrano** [comment]
@nding-anges I reviewed and adding some comments. Please make one more round of edits and then I will circulate this for review with the other UX leads before we proceed with sending a PR.

**Comment by nding-anges** [comment]
@mcarrano Thanks so much for all suggestions. I just did some modifications, please have a look.

**Comment by mcarrano** [comment]
Looks much better @nding-anges . I will submit this for review and comment by the UX Leads this week. Assuming they are in agreement with the approach, we can then go forward with sending a PR. Thanks.

**Comment by mcarrano** [comment]
@nding-anges So I think we are good to move forward with taking what you've done so far and creating a PR to add this to the Forms and Controls section of the design library. Please replace the existing Datepicker with this. Let mw know if you have questions.

**Comment by vconzola** [comment]
@mcarrano Is this ready to be used? I have an application for a date/time picker in VM Migration.  Also, this is going into pf-core, correct?

**Comment by mcarrano** [comment]
@vconzola Yes, the plan is to put this into PF Core. It leverages the current Bootstrap widget, so there is minimal dev work to be done. You should feel free to use this approach and let @nding-anges and I know if you see any issues with applying this.

**Comment by nding-anges** [comment]
@mcarrano Ok, I'll send the PR A.S.A.P

**Comment by dabeng** [comment]
Hi @mcarrano  Is there any other comments before sending PR ?

**Comment by mcarrano** [comment]
I think we are good to go @dabeng . I created a new issue in PF Core and assigned to you for tracking: https://github.com/patternfly/patternfly/issues/1078
