### ISSUE TITLE
Typo in Filter Mockup

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#460]
- [x] I would like to report a bug on design documentation

Two images on the Filter Design page : http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design  "Status has ben mispelled (Stauts)
![image](https://user-images.githubusercontent.com/12504403/31801305-365ff232-b515-11e7-8b2b-09b839ffa90c.png)
]

**Comment by LHinson** [comment]
Hey @zhutaoredhat Would you be able to fix this one? FYI @mcarrano

**Comment by zhutaoredhat** [comment]
@LHinson No problem. I had fixed it and pulled a new request. https://github.com/patternfly/patternfly-design/pull/463/files
Please have a review~

**Comment by zhutaoredhat** [comment]
@serenamarie125 This bug had been fixed. could you help me close this task please?

**Comment by mcarrano** [comment]
@zhutaoredhat @serenamarie125 @LHinson I have verified and merged #480 I will close this.

**Comment by zhutaoredhat** [comment]
@mcarrano Thank you~
