### ISSUE TITLE
Inconsistent menu (vertical nav) behavior 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#461]
[Issue](https://github.com/patternfly/patternfly/issues/790#issuecomment-337901644) filed with patternfly stating: 

> I find the inconsistency between vertical nav and other menus unexpected. Where some menus appear just after hovering (vert nav) the rest must be clicked first. One can observe that at https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html

**Comment by LHinson** [comment]
Red Hat QE also noted an issue with hover to open vertical nav menus. See https://bugzilla.redhat.com/show_bug.cgi?id=1491622

**Comment by rhamilto** [comment]
*If* hover is going to persist, I recommend it only be used on non-touch devices since browsers like mobile Safari convert the first "click" to hover.

**Comment by mcarrano** [comment]
Investigate what the accessibility issues are here.

**Comment by mcarrano** [comment]
@Mgranfie will follow-up to determine:
- What are current accessibility issues?
- Are short term fixes we should pursue?
- Is there an opportunity to better document?

**Comment by LHinson** [comment]
to clarify, follow up with Jenn

**Comment by mcarrano** [comment]
This issue is further complicated by discussion of https://github.com/patternfly/patternfly-react/pull/88. This raises issues about desired behavior of selecting parent nodes when there are multi-level menus present. Per [Repo Leads mtg on Jan 26](https://docs.google.com/document/d/19GFkbc25C9OEOTI9W4NUoyF2dvNJAvwYQDADPT42wWY/edit?usp=sharing), a detailed analysis and recommendations are needed that account for accessibility, mobile, and usability concerns as they relate to user behaviors.

**Comment by mturley** [comment]
To clarify one detail from the discussion above, we agreed on changing the behavior in patternfly-react such that a click will skip the delay for the hover. i.e., if you just hover, you'll have to wait 500ms, but if you click after 100ms it will go ahead and enter the hovered state immediately. That click would not also navigate the application unless the item clicked is a leaf node, or has its own href or onClick to use.

Does that sound consistent with pf core? If not, I think it should be added, if we continue to support hover. It's a very nice way around the delay if you want to be moving a bit faster.

**Comment by mcarrano** [comment]
@matthewcarleton @andresgalante Can you reply to @mturley 's comment above? Not sure if we currently have these delays build into the core implementation.

**Comment by matthewcarleton** [comment]
This may need to wait for @andresgalante as I haven't done much work on the nav, but from what I can see there is only a 100ms delay in vertical nav in core.

**Comment by mcarrano** [comment]
Will close this in favor of considering specific issues as they arise per UXS-PF call on Feb 1
