### ISSUE TITLE
Standard Menu UI's

### ISSUE THREAD

**Issue by Mgranfie** [patternfly/patternfly-design#464]
UI specifications for standard menu designs, are needed, so that designers and developers can implement consistent menu solutions in our applications.

#### 1. Choose the type of contribution for this pattern:
- [X] This is an enhancement on an existing pattern
#### 2. If this enhancement or new pattern was made for an application, specify which one.
Capturing current implementations of menus and establishing standards for them.

#### 4. Use Cases + Requirements
Designers and developers utilize and implement menus in various ways throughout our applications. Without some guidance with standards and recommendations of use, for various menus, designers and developers are left to create and implement menus on their own, and this can create inconsistent use of menus.

#### 5. References 
GitHub Stories:
https://github.com/patternfly/patternfly-design/issues/461
https://github.com/patternfly/patternfly-design/issues/410#issuecomment-338024237

Existing PatternFly Components:
Kebab Menus: http://www.patternfly.org/pattern-library/widgets/#kebabs
Launcher: http://www.patternfly.org/pattern-library/application-framework/launcher/
Masthead: http://www.patternfly.org/pattern-library/application-framework/masthead/#/design
Card View: http://www.patternfly.org/pattern-library/content-views/card-view/#/design
List View: http://www.patternfly.org/pattern-library/content-views/list-view/#/design
Table View: http://www.patternfly.org/pattern-library/content-views/table-view/#/design
TreeList View: http://www.patternfly.org/pattern-library/content-views/tree-list-view/#/design
Data Input: http://www.patternfly.org/pattern-library/forms-and-controls/data-input/
Language Selector: http://www.patternfly.org/pattern-library/forms-and-controls/language-selector/#/design
BootStrap ComboBox: http://www.patternfly.org/pattern-library/widgets/#bootstrap-combobox
BootStrap Select: http://www.patternfly.org/pattern-library/widgets/#bootstrap-select
BoostStrap DropDowns: http://www.patternfly.org/pattern-library/widgets/#dropdowns

**Comment by suzannehillman** [comment]
Hi all! I'm attaching the existing information I collected around the masthead user dropdown, and there's a few things to be aware of based on conversation with @Mgranfie:

* The correct wording and capitalization for logging out is "Log Out".
* OpenShift is still in progress - there's a section for 'now' and a section for 'in progress'. The former only has a single item in the menu (see Catherine Robson's line for the former, and Serena Doyle for the latter).
* When a menu is selected, there needs to be highlighting on the top-level of menu to make it clear which menu is open. (eg, for user dropdown, highlight the user name/icon). This may exist in in an existing story already.

**Comment by suzannehillman** [comment]
[Masthead user dropdown - Sheet1.pdf](https://github.com/patternfly/patternfly-design/files/1506865/Masthead.user.dropdown.-.Sheet1.pdf)

**Comment by suzannehillman** [comment]
I've done some additional research, to better understand the contexts within which dropdown menu/lists are likely to appear, as well as other types of menus. (dropdown lists and dropdown menus seem to be used interchangeably, and it is unclear if context or content matters)

Overall, it seems like menus are typically are used for navigation (including search) and filtering of data. Dropdown menus seem to be a subset of these, most often used for selection. 

Two links that I have found useful: 
* https://semantic-ui.com/collections/menu.html and https://semantic-ui.com/modules/dropdown.html - these include many examples of UI patterns that relate to menus and dropdowns.
* https://www.nngroup.com/articles/drop-down-menus/ - good guidance from the Nielsen Norman Group on dropdown menus.

My next step is to gather examples of how people are currently using menus and dropdowns in Patternfly within and outside of Redhat.
