### ISSUE TITLE
Add a loading state to the base dashboard card pattern

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-design#466]
This is an enhancement to an existing pattern to add a loading state to the base dashboard card.

- The pattern is needed for MIQ and the Angular implementation is in progress [here](https://github.com/patternfly/angular-patternfly/issues/658)
- Users have to wait for dashboards to load when there is a lot of data to present and a loading state would distinguish which cards needed time to load
- Working with visuals on design but something similar to this:
<img width="144" alt="screen shot 2017-10-23 at 9 52 33 am" src="https://user-images.githubusercontent.com/12504403/31893389-6c11d082-b7d9-11e7-9893-64d8429b5b2e.png">
- Stakeholders @serenamarie125 @jennyhaines 

@patternfly/patternfly-design-maintainers Please assign me!

**Comment by serenamarie125** [comment]
@beanh66 I think we need a Loading label here ... let's chat
