### ISSUE TITLE
Add guidance for a loading state to the Card View

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#467]
This is an enhancement to an existing pattern to add a loading state note to the card view.

When there are performance issues, users have to wait for the view to load.  We should give guidance around using a loading state ( which would likely be a Large Spinner control with the "Loading" text below it).

Note that on the design page of this pattern, we are already giving guidance around if the view is empty http://www.patternfly.org/pattern-library/content-views/card-view/#/design.

- Stakeholders @serenamarie125 @jennyhaines

@mcarrano @maryclarke @catrobson do you support this suggestion?

Associated Issues: 
https://github.com/patternfly/patternfly-design/issues/468
https://github.com/patternfly/patternfly-design/issues/469

**Comment by serenamarie125** [comment]
@mcarrano the proposed design is to use the same solutions we give for the base card.  Display a Large Spinner control with the "Loading" text below it.  Loading would be the default text ( with no ellipses ), but should be customizable from an implementation perspective.

Note that this suggestion is consistent with the loading state of the card shown here: http://www.patternfly.org/pattern-library/content-views/card-view/#/design

**Comment by serenamarie125** [comment]
![pageloading](https://user-images.githubusercontent.com/12504403/36209645-3fe85bda-116a-11e8-940a-4f6c38610b44.jpg)
FYI - here are some examples of how inconsistent we are between products and within products now
<img width="1440" alt="screen shot 2018-02-14 at 7 52 30 am" src="https://user-images.githubusercontent.com/12504403/36209454-c5f19436-1169-11e8-93f3-345ee04a4f92.png">
<img width="1440" alt="screen shot 2018-02-14 at 7 52 49 am" src="https://user-images.githubusercontent.com/12504403/36209455-c6066ab4-1169-11e8-85aa-8b5df85df620.png">
<img width="1440" alt="screen shot 2018-02-14 at 7 52 25 am" src="https://user-images.githubusercontent.com/12504403/36209456-c6186b24-1169-11e8-9110-ac68188a723d.png">
![screen shot 2018-02-14 at 7 48 39 am 2](https://user-images.githubusercontent.com/12504403/36209457-c7472ca6-1169-11e8-8a60-2806576c9851.png)

**Comment by mcarrano** [comment]
I think one of the questions might be whether the toolbar controls appear while the view is loaded and what state they are in, i.e. everything disabled?

**Comment by serenamarie125** [comment]
Good point @mcarrano
IMO, the toolbar should be displayed
I'm not sure if things should be disabled, as if someone wants to change the filter criteria during load time, I'd imagine they should be able to ...

**Comment by terezanovotna** [comment]
[Work in Progress](https://docs.google.com/presentation/d/1-nqhbY5QcI7SNEsXOM1C0EO9vGkGAnyDFGDYmtjkCdc/edit?usp=sharing)

**Comment by terezanovotna** [comment]
@serenamarie125 had a great comment that Load state is a very similar pattern as Empty state.

Can we remove Loading from [Cards - > Base Card], and add it to [Communication -> Loading State]?

**Loading state**
_description of loading state_
![loading-state-html](https://user-images.githubusercontent.com/36040135/36326908-bd5e09d6-132a-11e8-9cbe-93d02a762dc6.png)

The loading state pattern is most often used in conjunction with one of the content views (e.g. [List View](http://www.patternfly.org/pattern-library/content-views/list-view/), [Table View](http://www.patternfly.org/pattern-library/content-views/table-view/), and [Card View](http://www.patternfly.org/pattern-library/content-views/card-view/)).

![card-view-load](https://user-images.githubusercontent.com/36040135/36327009-1cf85306-132b-11e8-9fad-4b4ee4829b34.png)

[Spinner Size](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/spinner.html)
If spinner is `<h1>` then text “Loading” is `<h1>` as well.

**Comment by terezanovotna** [comment]
This makes it straightforward and we don't need to specify visuals for all List, Table and Card View. 

@serenamarie125 @mcarrano Thoughts?

**Comment by mcarrano** [comment]
I like this idea, @terezanovotna . Always looking for opportunities to not duplicate materials. If we do that, we should include examples of what this would look like in a card vs. a table or list.

@serenamarie125 @LHinson what do you think?

**Comment by terezanovotna** [comment]
@mcarrano please [review this doc,](https://docs.google.com/document/d/1Q1cLSJ9dFbRJDT9954NLvNmFqP5eEoqtFHDHfpGbsFU/edit?usp=sharing) thanks!
