### ISSUE TITLE
Add loading state guidance to the Table View

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#469]
This is an enhancement to an existing pattern to add a loading state note to the table view.

When there are performance issues, users have to wait for the view to load.  We should give guidance around using a loading state ( which would likely be a Large Spinner control with the "Loading" text below it).

Note that on the design page of this pattern, we are already giving guidance around if the view is empty http://www.patternfly.org/pattern-library/content-views/table-view/#/design.

- Stakeholders @serenamarie125 @jennyhaines

@mcarrano @maryclarke @catrobson do you support this suggestion?

Associated Issues: 
https://github.com/patternfly/patternfly-design/issues/468
https://github.com/patternfly/patternfly-design/issues/467

**Comment by catrobson** [comment]
@serenamarie125 Agree for first load.  In some of our implementations, we're also seeing lazy load taking time, and in this case I think clearing out the table doesn't make sense.  Do you think a lazy load solution for spinners is another separate issue/contribution?

**Comment by mcarrano** [comment]
@serenamarie125 is there someone assigned to work on this? (and also #467)

**Comment by serenamarie125** [comment]
@mcarrano the proposed design is to use the same solutions we give for the base card.  Display a Large Spinner control with the "Loading" text below it.  Loading would be the default text ( with no ellipses ), but should be customizable from an implementation perspective.

Note that this suggestion is consistent with the loading state of the card shown here: http://www.patternfly.org/pattern-library/content-views/card-view/#/design
