### ISSUE TITLE
Saved Filter

### ISSUE THREAD

**Issue by sdash-redhat** [patternfly/patternfly-design#472]
I have created a PR regarding this: 
https://github.com/patternfly/patternfly-design/pull/471

## For Pattern contribution proposal, tell us about your idea... 
Many times while using a filter component, the user applies a set of filters and get the result. Later on he wishes to filter the data set using the same criteria, he has to again select those criteria again. Current proposal helps the user to save any filter criteria combination the user has applied on any data set to filter the results and give it a custom name. Later whenever he wants to apply the same filter criteria, he can select it from the list of saved filters and apply using a click. 
#### 1. Choose the type of contribution for this pattern:
- [x] This is a new pattern 
#### 2. If this enhancement or new pattern was made for an application, specify which one.
This is a solution to be implemented in OSIO Planner 
#### 3. Title
Custom Filter
#### 4. Use Cases + Requirements
Many times while using a filter component, the user applies a set of filters and get the result. Later on he wishes to filter the data set using the same criteria, he has to again select those criteria again. Current proposal helps the user to save any filter criteria combination the user has applied on any data set to filter the results and give it a custom name. Later whenever he wants to apply the same filter criteria, he can select it from the list of saved filters and apply using a click. 

###### *Specify the use case, requirements and what problems do we believe users have, that we intend to solve? ANd, does this problem have a community interest?*
This also helps in reusability of applying a filter combination. 

#### 5. References 
[https://github.com/sdash-redhat/patternfly-design/blob/master/pattern-library/forms-and-controls/custom-filter/design/overview.md](https://github.com/sdash-redhat/patternfly-design/blob/master/pattern-library/forms-and-controls/custom-filter/design/overview.md)

[https://github.com/sdash-redhat/patternfly-design/blob/master/pattern-library/forms-and-controls/custom-filter/design/design.md](https://github.com/sdash-redhat/patternfly-design/blob/master/pattern-library/forms-and-controls/custom-filter/design/design.md)

The Usage in Planner 

Option 1/3 in the deck 
[https://redhat.invisionapp.com/share/KRDF4GH8V#/252687304_Slide04](https://redhat.invisionapp.com/share/KRDF4GH8V#/252687304_Slide04)

Option 1/2 in this deck 
[https://redhat.invisionapp.com/share/DUDF5ZA7J#/252909294_00_Custom_Filters_Copy](https://redhat.invisionapp.com/share/DUDF5ZA7J#/252909294_00_Custom_Filters_Copy)

###### *If you know of any other PatternFly designs that will be impacted or depend on the design you are contributing, enter those here.*

Filter

###### *Attach any rough sketches, undocumented wireframes or workflows that will help the PatternFly Team understand and review, the pattern you would like to submit.*

[https://github.com/sdash-redhat/patternfly-design/blob/master/pattern-library/forms-and-controls/custom-filter/design/overview.md](https://github.com/sdash-redhat/patternfly-design/blob/master/pattern-library/forms-and-controls/custom-filter/design/overview.md)

[https://github.com/sdash-redhat/patternfly-design/blob/master/pattern-library/forms-and-controls/custom-filter/design/design.md](https://github.com/sdash-redhat/patternfly-design/blob/master/pattern-library/forms-and-controls/custom-filter/design/design.md)

###### *Once the design issue has been reviewed, the name and location, within the PatternFly.org website, will be determined and posted here, on this issue, by a PatternFly team member.*
 #471

**Comment by catrobson** [comment]
This is a duplicate issue with https://github.com/patternfly/patternfly-design/issues/306.  This issue has some more detail so I'll let you handle which issue you want to keep around @mcarrano

**Comment by mcarrano** [comment]
@sdash-redhat @catrobson Because we are currently working on revising our overall filter framework (see #397 ), I'd like to hold off on doing a final review of #471 until that is in. I think the best approach here will be to specify how the save and recall actions should integrate with the overall Filter pattern that @cshinn is working on and them document the details of the Save interactions in a new pattern. We can discuss further if you have questions.

**Comment by mcarrano** [comment]
@sdash-redhat we would like to get this moving again now that base filter pattern has been updated. @catrobson will be in touch about next steps on revising your proposal. I am updating title to Saved Filter to better reflect the expected functionality and not confuse with #403

**Comment by mcarrano** [comment]
@sdash-redhat per discussion with @catrobson I understand that you will move forward with this by making changes to [Filter](http://www.patternfly.org/pattern-library/forms-and-controls/filter/) to indicate integration points and add a new pattern called Saved Filter to the Forms and Controls section of the library by updating your existing PR.

Let me know if you have any questions or if this does not accurately describe your next steps.
