### ISSUE TITLE
Visual inconsistencies with the empty state shown on the Filter pattern

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-design#473]
### Bug: Visual inconsistencies with the empty state shown on the **Filter** pattern.
- The Filter pattern should remove empty state examples and just link to the Empty State pattern. 
- A Filter example should be added to the Empty State pattern so there is only one place to maintain empty state visuals. 
- All Content View patterns currently do this effectively.

### Empty State:
<img width="1025" alt="screen shot 2017-10-26 at 5 27 26 pm" src="https://user-images.githubusercontent.com/18057044/32078199-105e7626-ba74-11e7-9a4c-c2b94ccce996.png">

### Current empty state in Filter Pattern: 
<img width="1023" alt="screen shot 2017-10-26 at 5 26 54 pm" src="https://user-images.githubusercontent.com/18057044/32078209-193c649c-ba74-11e7-8b16-f5db79e41775.png">
(different font size and treatment)

**Comment by beanh66** [comment]
FYI @LHinson @serenamarie125

**Comment by mcarrano** [comment]
Discussed with @beanh66 and we agreed to keep documentation of null filter result empty state with the filter pattern as this is directly related to Filter behavior. We should still review visual look & feel for consistency and determine if changes should be made. Specific questions concern font treatment, background colors, and use of buttons vs. links.

@kybaker can you take a look at this and give us an opinion?

**Comment by beanh66** [comment]
@kybaker FYI @jennyhaines may have started some work on empty state patterns in the context of OpenShift last sprint. FWIW, I think the main concern was the inconsistency between the font size/ weights and not really related to the link/button. Both look fine to me, just a question of which we should be using. It might be as simple as showing the filter empty state as an alternative example (links instead of buttons) inside the empty state pattern so it is clear what the visual treatment should be when an empty state is the product of filtering everything out. Curious your thoughts!

**Comment by jennyhaines** [comment]
@beanh66 I like the idea of using the font sizes/weights from the PatternFly Empty State pattern, and just including a link rather than a button at the bottom, since the action doesn't seem imperative.

**Comment by mcarrano** [comment]
@kybaker please take a look and let me know next steps.

**Comment by kybaker** [comment]
@mcarrano Please make a story for this and we can work with @serenamarie125  to prioritize it against the other stories.

**Comment by mcarrano** [comment]
A story where @kybaker ?

**Comment by serenamarie125** [comment]
@mcarrano I can create a story on the OSUX board and get it contributed from management side 
FYI @kybaker

**Comment by mcarrano** [comment]
I would be fine with that @serenamarie125 . I was going to create a PatternFly story but I'm good either way. I guess it depends on who will do the work. Thoughts @kybaker ?

**Comment by kybaker** [comment]
@mcarrano I think it would be better to have Serena do it. It can then get prioritized against MGMT work since it was Colleen who created this.

**Comment by mcarrano** [comment]
I'm good with that. @serenamarie125 when you create the story, just link it here.

**Comment by mcarrano** [comment]
@zhutaoredhat Thanks for offering to take this on. Please review your proposal with folks on this issue.

**Comment by zhutaoredhat** [comment]
@mcarrano I have pulled a new PR to fix this bug, please help me have a review https://github.com/patternfly/patternfly-design/pull/567 Thank you~

**Comment by kybaker** [comment]
@zhutaoredhat @mcarrano These changes look great. Thanks for making the update.

**Comment by zhutaoredhat** [comment]
@kybaker Thank you too.

**Comment by mcarrano** [comment]
PR has been merged. I will close.
