### ISSUE TITLE
Remove masthead details from Vertical Nav and link to the Masthead pattern instead

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-design#475]
### Bug: Remove masthead details from **Vertical Nav** design tab and link to the Masthead pattern instead
- On the Vertical Navigation pattern's "Design" tab, there is a "Masthead Design" section with an image and details. This should be removed and simply provide one sentence with a link to the dedicated **Masthead** pattern.
- The image on the overview tab can likely be removed as well and just link to the Masthead pattern there too.
- Keeping the masthead documentation in two places may lead to inconsistencies.

**Comment by mcarrano** [comment]
After discussing with @beanh66 I agree that it's redundant to have this documentation in two places and we should just update this to point to Masthead pattern where complete documentation exists.

**Comment by mcarrano** [comment]
@LHinson Do you agree with making this change? If so I will add to our backlog.

**Comment by LHinson** [comment]
+1 Thanks @mcarrano @beanh66

**Comment by mcarrano** [comment]
https://patternfly.atlassian.net/browse/PTNFLY-2618 has been created to make this update.
