### ISSUE TITLE
Visual design + review of PatternFly.org Contribution web pages

### ISSUE THREAD

**Issue by Mgranfie** [patternfly/patternfly-design#478]
We are excited to have you contribute to PatternFly!<br>
To create a GitHub issue, first determine which type of contribution you are making, a pattern or a bug, and then remove text for the contribution type, that you will not need. 

## For Pattern contribution proposal, tell us about your idea... 
(delete section if filing a bug)
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a visual review of some webpages for PatternFly.org and should follow the visual language for this established website.
#### 4. Use Cases + Requirements
To provided feedback, guidance, recommendations and possibly some small visual assets for these web pages.
#### 5. References 
www.patternfly.org
JIRA Story: https://patternfly.atlassian.net/browse/PTNFLY-2615
JIRA Story for Wireframes: https://patternfly.atlassian.net/browse/PTNFLY-2546
#### 6. Design Concepts  
Wireframes in InVision
https://redhat.invisionapp.com/share/PGE5KM0WZ#/screens/258726916_PF-Contribute
#### 7. Scope  
SMALL

**Comment by gdoyle1** [comment]
Here's the [InVision project](https://redhat.invisionapp.com/share/HUFTGHCWKRG#/281288915_TOC) with the most recent wireframes. We are at the end of our process, making final decisions on the community and downloads pages, as well as some content tweaks.
