### ISSUE TITLE
Ensure consistent use of hand vs. pointer across patterns

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#485]
Hand and pointer cursor are used inconsistently relative to list or card actions, selection, and drill down. These differences can be seen in the sample implementations for the following patterns:

List View: http://www.patternfly.org/pattern-library/content-views/list-view/#/code
Card View: http://www.patternfly.org/pattern-library/content-views/card-view/#/code
Notification Drawer: http://www.patternfly.org/pattern-library/communication/notification-drawer/#/code/html-css

A related issue on Notification Drawer was filed here: https://github.com/patternfly/patternfly-org/issues/487

Should define a set of common practices for use of the cursor and update all affected patterns accordingly.

**Comment by jeperry** [comment]
There are two concerns
- Guidance for when to change cursors from pointer (default) to hand
- Guidance for when to (or not to) use styling to change the appearance of objects on hover

I think it is ok for this issue to focus on the former and not the latter, but both need to be addressed.

I think we should define a general rule that we should always change the cursor to hand if over an item that is interactive ('can be clicked') I see two instances where this is not followed from the examples you shared. 

List View: http://www.patternfly.org/pattern-library/content-views/list-view/#/code
- Hovering on select box in the list does not change the cursor, however I see that this appears to be standard behavior for this control in HTML.

Notification Drawer: http://www.patternfly.org/pattern-library/communication/notification-drawer/#/code/html-css
- drawer-pf-notification-content has no cursor or styling change to indicate interactivity, but it is an active click area.

**Comment by beanh66** [comment]
@jeperry I'm not sure I'm following. Why wouldn't we want to change the cursor for the check box?

**Comment by jeperry** [comment]
@beanh66 it seems that intuitively we would, but from best I can tell, its 'normal' to not change the cursor for checkboxes. Can you find examples anywhere that have cursor changes on checkboxes?

**Comment by beanh66** [comment]
@mcarrano I do think the clickable items should have the cursor change to the pointer, but to me that is an implementation issue, not design. It sounds like we need an issue in the PF core repo to address each of these. I brought up the issue specifically around the notification drawer needing the cursor change when hovering over a row in the drawer (because clicking a row will mark a message as read).

**Comment by mcarrano** [comment]
@andresgalante @matthewcarleton wanted to get your opinion on this. Do you feel you need design guidance here or is it fair to say that hover over any interactive element should always produce a hand cursor? If the later, then I will just file bugs for the instances called out by @beanh66 . There are a number of inconsistencies in this regard in our HTML/CSS examples.

Regarding the checkbox question, from what I can tell @beanh66 , it does seem like the default behavior for HTML checkboxes and radio buttons is to not change the cursor, so that may be the exception. I think we would need to customize these elements to do differently. My guess is that the thought is that the appearance of the element in itself provides enough affordance that it is clickable.

**Comment by beanh66** [comment]
Gotcha, thanks @mcarrano!

**Comment by matthewcarleton** [comment]
@mcarrano I agree, there should be no reason why an interactive element doesn't have the hand cursor on hover.

**Comment by mcarrano** [comment]
Per PF-UXS meeting on Jan 25, all agree that interactive elements, excepting core HTML controls like radio buttons and checkboxes, should show the hand cursor on hover. I have reassigned this to myself and will enter appropriate issues against PF core repo.

**Comment by mcarrano** [comment]
I have entered a new issue (https://github.com/patternfly/patternfly/issues/942) to address the Notification Drawer.

@beanh66 Based on my review, I believe the list view example code is correct. By default I would not expect the hand cursor on hover over a list item unless that item is linked to a drill-down page for drill down. Card View does seem inconsistent between single and multi-select views. While I agree that's incorrect, would like to know what you think the behavior should be. Do you think that hovering over the card body should show the hand cursor in both cases? If so, would clicking the card select it or drill down? Maybe card selection should be more like in list view where you always have check boxes when the cards are selectable. Thoughts?

**Comment by beanh66** [comment]
@mcarrano The card view is a tough one. Something I notice is the checkboxes are not visible all the time, they only appear on hover which is not the case for list view so the selection process is less obvious. Card views are also sometimes used with a single select option for performing actions so I like the idea of not requiring checkboxes. I think it is fair to allow each use case to determine (A) if they need checkboxes for multi select and (B) if clicking a single card will drill down or just select a card (highlight in blue). IMO the main functionality missing is the hand cursor over the checkboxes.

**Comment by mcarrano** [comment]
That's fair @beanh66 . There is currently a related issue (#110) about reconciling selection and drill-down for different view types that I'd like to get to at some point. So these issues are probably more appropriate to consider in that context. As for the checkbox, as mentioned about, it's not standard to display the hand-cursor for checkboxes. I can see why that might be debatable, but I don't see the need to do custom work here.

Given that we now have an open issue to fix inconsistencies with the Notification Drawer, I am going to close this one out as sounds like there are no further actions at this time.
