### ISSUE TITLE
Update Masthead Utility Icons with Hover

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#486]
Update the images (seen on the bottom of the page) for the masthead [1] to include the light gray hover background (as seen on the horizontal example [2]). Update the text to specify this hover behavior. So instead of: 
*It should be visually indicated when a user hovers or selects an icon from the Masthead.

It should read: 
* The icon color changes to white and has a light gray background to visually indicate when a user hovers or selects an icon from the Masthead.

There is also a bug [3] against patternfly to update the implementation to update the tall masthead

[1] http://www.patternfly.org/pattern-library/application-framework/masthead/#/design
[2] https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/horizontal-navigation.html
[3] https://github.com/patternfly/patternfly/issues/828

**Comment by junezhang** [comment]
@LHinson, Haley @yih-wang  would like to take this issue.

**Comment by yih-wang** [comment]
@LHinson I found the style of user icon is not the latest version in PatternFly. So I replaced all user icons in the images. Also, I think the icon should be grey when not selected but it used to be white, modified too. Please have a review in #489 , thanks.

**Comment by junezhang** [comment]
@LHinson @yih-wang For https://github.com/patternfly/patternfly/issues/828, we also need to update the designs in Notification Drawer.
http://www.patternfly.org/pattern-library/communication/notification-drawer/

**Comment by yih-wang** [comment]
@LHinson @junezhang @mcarrano I went over all the patterns with masthead in PatternFly and found we don't have a general rule for icon appearance in different states (default/hover/selected). So the mockups are not consistent in different patterns.

- Horizontal Navigation page: Default to be grey, have a grey background when hovering, have a ground and highlighted when selected.
![horizontal navigation](https://user-images.githubusercontent.com/23331885/32715328-791f5760-c817-11e7-8f63-f9f730c7c2b3.png)

- Vertical Navigation page: Default to be grey, highlighted when hovering
![vertical navigation](https://user-images.githubusercontent.com/23331885/32715398-d12f488e-c817-11e7-8a26-9e741c7a5f0f.png)

- Breadcrumb page: Default to be white
![breadcrumb](https://user-images.githubusercontent.com/23331885/32715420-e7fb222c-c817-11e7-8ab9-6b1388f29ee7.png)

- Icons in different mockups are in different style:
<img width="159" alt="screen shot 2017-11-13 at 16 14 46" src="https://user-images.githubusercontent.com/23331885/32715630-bdffa06e-c818-11e7-97f3-f8e4a8877499.png"> <img width="126" alt="screen shot 2017-11-13 at 16 14 54" src="https://user-images.githubusercontent.com/23331885/32715632-bf5d6554-c818-11e7-86b3-e198af3be75b.png">


I think we should generate a unique rule for masthead and update all the patterns to keep consistency. What's your thoughts?

**Comment by mcarrano** [comment]
@yih-wang We certainly should make sure we are being consistent wherever the masthead appears. Let's get your first PR reviewed and merged and then we can look at some of these other cases. I've asked @kybaker to just take a look at your visuals. Thanks for raising this.
