### ISSUE TITLE
Add icon and recommendation for external links

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#487]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [ x] This is an enhancement on an existing pattern

**Comment by serenamarie125** [comment]
Suggestion ... this is what is used in OpenShift
<img width="137" alt="screen shot 2017-11-09 at 9 09 19 pm" src="https://user-images.githubusercontent.com/12504403/32660539-4ef1f4f2-c5f1-11e7-90ca-a75aecc2eddd.png">

I'd also suggest that we recommend that external links are brought up in a new browser/tab, based on the browser preference

**Comment by mcarrano** [comment]
Agree @serenamarie125 I was thinking the same.

**Comment by cshinn** [comment]
I would sort of expect this documentation to exist in the terminology and wording section along with the other link documentation. Does that make sense?

**Comment by mcarrano** [comment]
@cshinn  Yes. If you look at the Terminology and Wording page, there is already mention of of this, but the icon is not called out. I think this issue just requires to small updates:

1- the text on Terminology and Wording.
2- Add this icon to the recommended list of 'fa' icons in the Icons table here: http://www.patternfly.org/styles/icons/
