### ISSUE TITLE
Inline Alert

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#493]
This is a pattern that started rolling into OpenShift.io designs because the existing patterns were not quite doing the job for our use cases.  The idea is to use a vertical line on rows or cards that have issues associated with them as an aggregate status designating some issue, to help guide the user's eyes towards that row/card.  I'm not sure if this should be an extension of the existing patterns, or a new pattern that we could use on other elements of PatternFly.

Examples:  
  Row:  https://redhat.invisionapp.com/share/SCEEUYDUP 
  Card:  https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/262786733

**Comment by mcarrano** [comment]
Need recommendation from visual design on best way to proceed.

**Comment by kybaker** [comment]
@mcarrano - I can see the potential value in highlighting a row in a list which calls the users attention. The issues I see in the examples above on each row there is 3 different ways of highlighting a single issue. This creates so much visual noise that it makes it difficult to scan the list defeating the purpose. 

Additionally the row highlight itself relies only on color to differentiate between the highlights which creates issues with accessibility. So by definition the row highlight will require an additional visualization showing status.

**Comment by mcarrano** [comment]
Per Dec 14 PF-UXS meeting, @kybaker will work thru design issues with OpenShift team and we will revisit this at a later date for next steps (i.e. do we see a pattern contribution here).
