### ISSUE TITLE
Pinned rows in List View

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#494]
This is a pattern that was identified for Openshift.io as well, where they wanted the ability to allow users to pin a few results to the top of the returned results list so they could also quickly find those objects.  This would be an added capability to the List View pattern.

**Comment by catrobson** [comment]
Patternfly-ng implementation demo: https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/list

**Comment by catrobson** [comment]
@bdellasc - I'll create an issue for you to contribute this design change into PatternFly in our fabric8 backlog

**Comment by bdellasc** [comment]
@mcarrano Here is the [draft](https://docs.google.com/a/redhat.com/document/d/1kJBAW8MibLjBzA12ocjFisLLMlUbQUgUuGuQAhuVrkY/edit?usp=sharing) of what I've written so far for the pinned items. I haven't added any images to the document yet. I figured once I knew what aspects I was writing about, I could add some images based on where the text content lands.

**Comment by mcarrano** [comment]
@bdellasc I reviewed your document and left a couple of comments. I think it would be good to have a bit more detail before doing a complete review. For example, what does the pin look like in the context of our current list (and table?) views. It looks like this is adding another potential icon at the front of the row. What does this look like if both selection and expansion are also supported? It may not be a problem, but it would be good to see those mockups.

I think once you do that, this would be ready for a full review with the PF-UXS team and we can decide what the best approach is for documentation. Does that make sense?

**Comment by mcarrano** [comment]
@catrobson @serenamarie125 @maryclarke @jeperry Please review the preliminary design concept here and provide feedback: https://docs.google.com/a/redhat.com/document/d/1kJBAW8MibLjBzA12ocjFisLLMlUbQUgUuGuQAhuVrkY/edit?usp=sharing

Note that this is still a work in progress but it would be good to get more feedback on the overall concept before further detailing the design.

**Comment by catrobson** [comment]
Looks good to me

**Comment by maryclarke** [comment]
LGTM

**Comment by jeperry** [comment]
made a minor comment but also LGTM

**Comment by mcarrano** [comment]
@serenamarie125 have you had a chance to look at this?

**Comment by serenamarie125** [comment]
I see a need for the pattern.  I have questions as to if this is a Pin or a Freeze as well as if things that are "pinned" should remain in the order that the user set, or sorted as well.

**Comment by catrobson** [comment]
I think the way that this pinning works you just mark and item as "pinned" or "unpinned" in the data set - you have no way to really control its order in the pinned set.  Therefore keeping the same sort as the data set, with pinned items shown first, makes sense.

If we were discussing something like freezing cells in a datasheet where I can choose a set of cells, then I agree that the order shouldn't change on sort, but I think this is a different use case since you can't select the order or grouping of the items you are pinning.

**Comment by Mgranfie** [comment]
The pinning I have been using with email is close to what you are
describing Cat. With the exception that it does keep an order within the
pin items, in this case they have deemed date as the priority for ordering.
Ours could be generic, as you suggested, which would be order added, or we
could allow them to choose one of their data attributes.

So would our default order just be as added and they would be removed from
the greater list?

**Comment by catrobson** [comment]
@Mgranfie As Brian's document attempted to capture, they are ordered by the same sort order applied to the list in the filter bar.  So if the whole table is ordered by date, the pinned items would be too.  If you change the order to name A->Z, they would both be ordered by name.  In this case you would get Pinned items A->Z, then non pinned items A->Z in your list.
