### ISSUE TITLE
Inconsistent terminology used in Notification Drawer

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#496]
The existing [Notification Drawer pattern](http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design) has inconsistencies with the pattern.

In the accordion, there is italicized text indicating the number of "new" events.  The pattern also has a "Mark All Read" link.  These two terms are conflicting.  The italicized text should read "unread" rather than "new".  The concept of "new" doesn't make sense here.

**Comment by mcarrano** [comment]
Thanks for taking this one, @zhutaoredhat Just send a PR when ready.

**Comment by zhutaoredhat** [comment]
Thanks @mcarrano I have pulled a new PR to fix this bug, please have a check https://github.com/patternfly/patternfly-design/pull/566
