### ISSUE TITLE
Some content view images need minor updates to use "Active Filters" rather than "Active filters"

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#497]
A few of the content view patterns include images which use inconsistent labels.  "Active filters:" should be changed to "Active Filters:" in the following images:
- http://www.patternfly.org/pattern-library/content-views/list-view/img/standard-list-view.png
- http://www.patternfly.org/pattern-library/content-views/card-view/img/single-select-card-view.png
- http://www.patternfly.org/pattern-library/content-views/card-view/img/multi-select-card-view.png
- http://www.patternfly.org/pattern-library/content-views/card-view/img/card-view-callout.png
- http://www.patternfly.org/pattern-library/content-views/table-view/img/table-callout2.png

**Comment by mcarrano** [comment]
We should review and update all content view patterns to reflect updated filter bar design.
