### ISSUE TITLE
Need icon enahancements

### ISSUE THREAD

**Issue by ssilvert** [patternfly/patternfly-design#500]
As I understand it, there is currently a very limited set of icons that are known to work well with PatternFly.
https://www.patternfly.org/styles/icons/

Keycloak needs to allow administrators to select and/or upload icons that will eventually be displayed in PatternFly templates.  The very limited icon set and even more limited color use will make for a poor user experience.

The use case for this is that a Keycloak administrator would assign an icon to each application managed by Keycloak.  These icons would show up on the SSO login screen and in the account management console.  If you want an idea of what I'm talking about, check out Google's login screen where they show an icon for every app that you can have access to: https://ps.w.org/google-apps-login/assets/screenshot-2.png?rev=1629984

At the very least, a detailed tutorial on how to create PatternFly-compatible  icons would be extremely helpful.

To make this really shine, PatternFly needs to allow more icons than it currently accepts.

**Comment by mcarrano** [comment]
@catrobson to follow up and get more info.

**Comment by mcarrano** [comment]
@catrobson any update on this? Would like to discuss at Thursday's meeting and close out if we have no intent to address.

**Comment by catrobson** [comment]
Stan, 

Sorry, it was on my list to follow up with you.  Leslie and I discussed, and we both had different understandings of the need.  I know you've talked us through this a few times, so I'm sorry that we still are not on the same page.  Can you clarify if you are looking for:

A.  A **definition** of what the standards are for building a custom icon that can be used in PatternFly applications - possibly a template file with instructions for creating icons that fit our style standards.  These could then be added to KeyCloak in their use cases as PNG or SVG uploads. 

and/or

B.  A way to contribute icons to PatternFly font family for yourself and any other PatternFly consumer to use

and/or

C.  A way to request custom icons from the PatternFly team, whether we give them as PNG/SVGs for your team's use only, or as font family through PatternFly.

Thanks!
Catherine

**Comment by ssilvert** [comment]
We need "A" as a bare minimum.  That way, our customers can create their own icons and upload them to KeyClocak/SSO.  "B" and "C" would be very helpful as well.

I would also add "D", which would be helpful for PatternFly generally:

D. PatternFly should provide a larger set of approved icons.  Perhaps the full set of FontAwesome icons could be rebuilt to fit the PatternFly style standards.

**Comment by amysueg** [comment]
@ssilvert - We met with the Patternfly team today and @kybaker provided updates to two documents that describe how to create custom icons and how to contribute them to Patternfly:

This document describes how you would design the icon
https://docs.google.com/document/d/1ErSqzD1lgMTyRVEuFNvNUfbIQipTx078EohBhPcuv_M/edit

This document describes how you would add the new icon to the existing library
https://github.com/patternfly/patternfly/blob/master/PFICONS.md

FYI @catrobson @mcarrano
