### ISSUE TITLE
Help on Forms: Using the "i" information icon looks cluttered on the page

### ISSUE THREAD

**Issue by amysueg** [patternfly/patternfly-design#502]
The UX team working on Fuse Ignite Online has a question about appropriate usage and design intent related to the "Help on Forms" "i" information icon on field labels on a page. Referencing this page in Patternfly: http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/

The attachment is a design we are currently working on. Working with the writer, we've determined that each field on the page needs additional information explaining what is needed per field. However, the page appears cluttered with the numerous "i" icons. We like that the "i" icon provides a visual cue that more information is available, but the overall look is somewhat disruptive.

Is there a workaround or way we can minimize the impact when multiple fields require additional information? 

![multipleinfoicons](https://user-images.githubusercontent.com/31700119/33635493-2813faac-d9e6-11e7-8f16-390be2e9b4d9.png)

@sjcox-rh @seanforyou23 @dongniwang

**Comment by mcarrano** [comment]
Discussed this issue during UXS-PF review meeting. Several issues questions were raised:
* Do field-level help (info) icons need to be blue in their default state? This may draw undue attention to them and makes the page feel visually cluttered. Consider changing default icon color to drak-gray and only change to blue on hover (like other tool icons in PF).
* Do we need better guidance on when to use field-level help vs. help text below the field. It may be that having Info on every field is not necessary.

Agreed that we should add this to the agenda for Dec 12 meeting to consider use of field level help and required fields on forms.

**Comment by mcarrano** [comment]
This issue will be considered together with #505.

**Comment by mcarrano** [comment]
@amysueg See recommendations made against #505 Does this address your concerns?

**Comment by mcarrano** [comment]
I am going to close this issue out as I believe it has been addressed by #505
