### ISSUE TITLE
Improve Recommendations for Form Field Labeling (Required fields and info tips)

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#505]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [x ] This is an enhancement on an existing pattern ([Field Labeling](http://www.patternfly.org/pattern-library/forms-and-controls/field-labeling/))

Current recommendations for designating required fields on forms specify that a red asterisk should be placed to the right of the field label. However it is unclear how this may coexist with info tip icons that are also to be placed to the right of form labels (see [Help on Forms](http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/)). The current pattern should be updated to provide clearer guidance on this issue that can be supported by research and industry best practices. Any change in design approach should result in updates to design docs and related code examples. Some specific needs include:

* Determine proper placement of required field indicator for different labeling options (left, right, and top aligned fields.
* Ensuring that recommended approach works responsively at mobile viewport sizes.
* Creating additional examples that show how required field indicators and field help (info tips) should coexist.
* Update all examples to use consistent label capitalization. See http://www.patternfly.org/styles/terminology-and-wording/

There is a related issue here: https://github.com/patternfly/patternfly-design/issues/502 that should be considered. Consider whether Field Labeling and Help on Forms should be combined to ensure a more hollistic approach as both deal with labeling topics.

**Comment by mcarrano** [comment]
@nlcwong I have created this new issue and assigned to you. I did a bit of research on prior work. There are two Jira stories from last year: 

* https://patternfly.atlassian.net/browse/PTNFLY-1688 is the design story
* https://patternfly.atlassian.net/browse/PTNFLY-1829 is the implementation story

Seems that there were issues with how to indicate optional fields so that was dropped. You should consider when/if optional vs required field indicators are useful. Also, it does look like required field indicators (red asterisk) moved from left to right at some point. Perhaps due to responsive considerations? Here is the current test page that represents our implementation example: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/forms.html. If you shrink the page you will notice that labels jump from the left to top at some point.

Let me know if you have questions or need any help as you work through this.

**Comment by mcarrano** [comment]
Related OpenShift story can be found here: https://patternfly.atlassian.net/browse/OSUX-373

**Comment by nlcwong** [comment]
@mcarrano  @serenamarie125  @LHinson @beanh66 
Can folks please review my findings and recommendations?
https://docs.google.com/a/redhat.com/document/d/1PcxszZ1S53Oacf7XZddnvba42RjMGr5R_QtQHZUqq98/edit?usp=sharing

**Comment by mcarrano** [comment]
@nlcwong Thanks for posting this. I have reviewed your document and left comments. In general I think that you recommendations make sense. @serenamarie125 @catrobson @maryclarke @jeperry please also review. One question I have is whether we should concern ourselves with left-aligned labels at all. As far as I know, all PatternFly forms use right-aligned labels. Are there instances where we would want to use left alignment?

@andresgalante It would be good if you can also take a look and see if you have any issues from an implementation standpoint. This approach would mean switching our required field indicators (red asterisk) from the right to the left of the field label.

**Comment by jeperry** [comment]
LGTM. I am ok if left aligned is kept in this pattern JIC an app author is needs to use that alignment for some reason.

**Comment by maryclarke** [comment]
LGTM too

**Comment by beanh66** [comment]
Thanks @nlcwong, the document LGTM 👍

**Comment by andresgalante** [comment]
Hi @nlcwong at first glance there are several problems aI see on moving the * to the left and even more if we want it to be fixed and generate a gap on non required fields.

The result on the browser in most scenarios and viewports would not be close to what the drawings show.

If this was tested and proves to be a big UX improvement I would suggest building it out to spot the implementation challenges it presents.

**Comment by nlcwong** [comment]
After talking with various UX team members about the feasibility of things, I've updated the recommendations of the required field as well as include some more design explanation of the field level help's interactive behavior since I'm also proposing a change to how it visually looks as well. 
 Also included is a section on research potential.

[Form Field Labeling - Enhancement ](https://docs.google.com/a/redhat.com/document/d/1PcxszZ1S53Oacf7XZddnvba42RjMGr5R_QtQHZUqq98/edit?usp=sharing)

**Comment by nlcwong** [comment]
I have closed out the [related OpenShift design recommendation story](https://patternfly.atlassian.net/browse/OSUX-373) and created a new one that will track the [research of the recommendation](https://patternfly.atlassian.net/browse/OSUX-435)

**Comment by jeperry** [comment]
I'm skeptical that any test of web forms as designed here is going to provide actionable data or even be a good use of time/resources. Imagine you are a test subject, and we ask you to fill out a short form. You're just going to fill out the entire form, right? People skip fields when it is convenient or the form is long. The test environment is artificial, and test subjects generally want to do what is 'right.'

My main point is I don't think there is anything novel here that warrants testing. Web forms are incredibly familiar to any computer user and the recommendations that Natalie put together are well thought out and follow best practices that have been around for quite a long time.

**Comment by serenamarie125** [comment]
@jeperry the reason we wanted to perform testing was because some of our designs expressed concern with the suggestions.  We thought that cafeteria testing would be helpful to show that the proposed designs doesn't raise any concerns with the participants.

**Comment by jeperry** [comment]
Understood - cafeteria testing is easy and quick so won't burn too many precious valuable cycles. I'm not trying to cause trouble, it's just that neither the problem or the solution are novel so it is not clear to me what our concerns or test questions are. Anyhow, I look forward to the results and hope the design here holds up well.

**Comment by nlcwong** [comment]
After receiving feedback from UXR on a study proposal, it was determined that the proposal was insufficient in helping us properly test the design.  UXR provided suggestions on alternative approaches, but due to limited availability, I had to close out the [Recommendation Research Story](https://patternfly.atlassian.net/browse/OSUX-435) for the previous sprint. 

Conversations can be found in the comments section of the [design document](https://docs.google.com/document/d/1PcxszZ1S53Oacf7XZddnvba42RjMGr5R_QtQHZUqq98/edit?usp=sharing).

**Comment by mcarrano** [comment]
After discussing with @nlcwong and @serenamarie125 we like to make the following recommendations:
(1) Abandon test/research plan as it's likely to become an expensive effort and may still not yield conclusive results.
(2) Move forward with Natalie's proposed changes which include:
* Moving the required field asterisk from right to left for all label alignments.
* Keeping info tip icon to right of the label, but changing the static color from blue to dark gray (blue on_hover).

This will solve the problem of the asterisk and info tip icon competing for space to the right of the label, which was the primary concern.

@maryclarke @catrobson @jeperry do you approve of moving forward with this approach? If so, I will work with @LHinson and @nlcwong to figure out next steps to get the docs and code examples updated.

**Comment by catrobson** [comment]
I'm happy to move forward with this approach.  However, the only thing that I'm concerned about is left-aligned labels and the required asterisk.  The use case for Left aligned labels is usually that you want easy scanability down the left hand side for the word that matters for changing that field value.  By bumping in the words when the asterisk is present, it degrades from the value of this use case.  Is there any chance we could investigate having the asterisk off in the 'gutter' from the start of the left labels for this situation?

**Comment by maryclarke** [comment]
The approach is fine with me too, but I second @catrobson's proposal for the placement of the asterisk with left-aligned labels.

**Comment by mcarrano** [comment]
Unfortunately I'm told this presents a technical challenge for responsive forms.

**Comment by mcarrano** [comment]
Per 2/26 PF-UXS meeting, we'd like to proceed with this recommendation by first doing some technical feasibility investigation to explore form layout in various permutations. I will create a PF core dev story and link here.

**Comment by nlcwong** [comment]
@mcarrano @serenamarie125 
I've taken what is already described in PatternFly (for both Field Labeling &  Help On Forms) and started to edit it to what I think it would look like with the recommendation. (The areas where I changed content is highlighted in yellow.): [https://docs.google.com/document/d/1bheM2861fcemrlCe1AcUffPGE0M2sT0GN7Q1drMdNt8/edit?usp=sharing](https://docs.google.com/document/d/1bheM2861fcemrlCe1AcUffPGE0M2sT0GN7Q1drMdNt8/edit?usp=sharing)

What I also found out in the Help On Forms section is that in the design tab, the description of the Syntax Hint Error Handling needed to be condensed a bit and also would like some more guidance on how to handle Syntax Hint & Validating/Error Handling together as it doesn't give clear guidance on how they both can co-exist.

Please review my proposed changes to the PatternFly documentation.

**Comment by mcarrano** [comment]
@nlcwong I just reviewed your document and left some comments. I'd like to hold on making actual updates to the site until @matthewcarleton is able to review and prototype these forms. There is a story in the PatternFly backlog here: https://patternfly.atlassian.net/browse/PTNFLY-2775

Another thing I'd like to consider is whether these two patterns should be combined into one since they both address field labeling in one form or other. I like the idea of seeing all this information in one place. @LHinson thoughts?

**Comment by mcarrano** [comment]
@matthewcarleton has sent a PR to update the core implementations. @nlcwong @serenamarie125 @maryclarke @catrobson @jeperry @LHinson see https://github.com/patternfly/patternfly/pull/991. I think this is a good solution and we should update the design docs to be in sync. Thoughts?

**Comment by jeperry** [comment]
LGTM

**Comment by LHinson** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/eb1a2ea1-7c1f-4a92-abdb-e89cdc52edfd-15206079-98a4-479e-bb46-baa63bbd1a81-v1.png?transparent=1&palette=1&width=246)

**Comment by catrobson** [comment]
The implementation looks good.  Are we going to update the design docs to follow this implementation as well?

**Comment by mcarrano** [comment]
Yes, that's the plan.

**Comment by mcarrano** [comment]
Per the PF-UXS meeting on 3/22 we'd like to go ahead with the current implementation as modeled in https://github.com/patternfly/patternfly/pull/991. The assessment is that we can live with the mis-alignment of right aligned labels when some have info tips until a better approach can be found for pf-next.

@matthewcarleton and @nlcwong please proceed with making changes to the code examples and design docs.
