### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#506]
- [x ] This is a new pattern 
- [ ] This is an enhancement on an existing pattern

This is a proposal for a new pattern to support file upload.

#### 4. Use Cases + Requirements
* Browse to select a file to upload
* Allow the user to select a file on their desktop and drag & drop it onto the web app for upload.

**Comment by mcarrano** [comment]
@catrobson I have created this new issue, as requested. Please feel free to add further requirements or details, as needed.

**Comment by mcarrano** [comment]
@gdoyle1 is currently working on a design proposal and will post here for review when ready. The following PatternFly stories have been created to track this work:
* Requirements and conceptual design: https://patternfly.atlassian.net/browse/PTNFLY-2757
* Final design and documentation: https://patternfly.atlassian.net/browse/PTNFLY-2781

Propose that this will be added as a new pattern to Forms and Controls. @LHinson do you agree?

**Comment by gdoyle1** [comment]
Here is the [Google Doc](https://docs.google.com/document/d/1yMv-GIWML3UYgN-koJnp21L4ASwr4gHcQzojLF0nHG0/edit?usp=sharing) with Requirements, Use Cases, Best/Common Practices and the [Proposed Design link](https://redhat.invisionapp.com/share/4AG2N43N5WH). If anyone has any feedback on the current wireframes provided, that'd be great to hear!

**Comment by mcarrano** [comment]
@gdoyle1 Thanks for posting. I think this is a good start. Left a couple of comments on your InVision deck to think about. Let me know if we need to discuss live. Also, just a general question. This design assumes that drag and drop to upload would always be supported. Do we know if there are instances where we might just want a simple textbox and browse button approach either to save space or otherwise?

@serenamarie125 @catrobson @maryclarke @jeperry would be good to also get your thoughts.

**Comment by johnnyNcsu** [comment]
@mcarrano I am new to PatternFly but also have this use case (file input). I have been integrating the design pattern for file input created by krajee to my project (in addition to PatternFly elements) - in particular I am using the file input pattern he defines in his [example 9](http://plugins.krajee.com/file-basic-usage-demo#basic-example-9). His code is already in npm registry as a bootstrap styled plugin which is nice. (This particular modal dialog appears to favor BSv4 styling however - I am working on fixing the styling for BSv3 which is better for my work). I am currently adding this file input modal as part of a PatternFly drop-menu list which differs from the proposal put forth by @gdoyle1.

In any case, I was considering contributing this (integrating really) to PF as it really would be more appropriate there (also npm is not handling install deps well separately) but don't want to step on any toes or run afoul of any license incompatibilities; nor am I particularly experienced at OSS contribution; nor can it turn into my full-time job :) Suggestions?

**Comment by johnnyNcsu** [comment]
@mcarrano will do - Thanks.

**Comment by mcarrano** [comment]
@gdoyle1 Any updates on this?

**Comment by gdoyle1** [comment]
@mcarrano I uploaded the newest wireframes a couple weeks ago! They begin at "Initial Screen V2." https://redhat.invisionapp.com/share/N5G2SX76QDZ It's the same InVision project as posted above. I would love to hear what you/others think about these.

**Comment by mcarrano** [comment]
@gdoyle1 the revised design looks great. @catrobson @serenamarie125 @maryclarke @jeperry @kybaker @LHinson please take a look. It's the screens labeled "V2" that you should be looking at.

@gdoyle1 for future reference, it's good to post a comment here when changes are made, that way I'll be sure not to miss updates! Thanks.

**Comment by mcarrano** [comment]
Per 4/5 PF-UXS Meeting - Let's create a draft in the form of a Google Doc that includes Overview and Design pages. Want to consider use cases and variations that may be needed. @catrobson to follow up with @gdoyle1 . Also should get Visual Design involved to create hi-fi mockups.

**Comment by gdoyle1** [comment]
Here is the [Google Doc](https://docs.google.com/document/d/1CM1BZdMFUUWXttI9oRaNb518TFpDP8LX_hA9OIjYXUU/edit?usp=sharing) with:
1. Overview
2. Use Cases
3. Design Pages
4. Design Write-ups
For reference, here is the [previous Doc](https://docs.google.com/document/d/1yMv-GIWML3UYgN-koJnp21L4ASwr4gHcQzojLF0nHG0/edit?usp=sharing) I was using to gather requirements and use cases as well as the [InVision Project](https://redhat.invisionapp.com/share/4AG2N43N5WH#/281862883_Initial_Screen) I put all of the design pages in.

**Comment by bmignano** [comment]
@dongniwang do you happen to have the source files for the images? I think you may have been working on this with Gina but I'm not sure. Thanks!

**Comment by dongniwang** [comment]
@bmignano - I don't have the source files, unfortunately, but I think you might be able to find some files in Google drive.

**Comment by catrobson** [comment]
@bmignano - You can find the files in this folder:
https://drive.google.com/drive/folders/18dWjrkS-rtvUz7PMimLt-16tBIYKbDBr

**Comment by beanh66** [comment]
@serenamarie125 @catrobson @maryclarke @mcarrano Please review the latest [File Upload Design document.](https://docs.google.com/document/d/1hT0snitJwyDN9Wz2nzbzA0-AyzS8GJbds3v6rJ-UOqo/edit?ts=5b3244f6) @bmignano has updated this doc to reflect what she would be looking to contribute for the overview and design pages in PF. Note: the design is based on the initial work done by @gdoyle1 and @dongniwang! We wanted to get a final review before opening a PR.
