### ISSUE TITLE
Row expansion for tables

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#507]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [ x] This is an enhancement on an existing pattern
#### 2. If this enhancement or new pattern was made for an application, specify which one.
Table View

**Comment by mcarrano** [comment]
@catrobson I've added this new issue as you requested. Please feel free to add more detail or design proposals and we can discuss further.

**Comment by mcarrano** [comment]
@Mgranfie This issue has been sitting in our backlog for a while. As you are looking at functional requirements for data tables, can you consider this in the mix? Is it something we have support for today? Should it be added to out design library as a supported feature?

**Comment by Mgranfie** [comment]
@mcarrano we have this in the PF_NG Angular 4 implementation. Is this asking for this functionality for a specific implementation of the table?

**Comment by mcarrano** [comment]
@catrobson perhaps you can comment here. 

@Mgranfie I think the request is to add this to our design documentation as we already have an implementation for it. But the bigger question in my mind is whether this is something that should be supported across any table implementation.

**Comment by Rohoover** [comment]
@mcarrano 
This is helpful as I also need a table with row expansion. As a note, in my use case, only some rows are expandable.
