### ISSUE TITLE
DataTable - sort state clarification

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-design#516]
Hello PatternFly Design ;)

I noted during the development of the data tables pattern in React that our language on data table column sorting could be a bit further detailed. Currently the documentation [here](https://github.com/patternfly/patternfly-design/blob/master/pattern-library/content-views/table-view/design/design.md) states:

> Organize data by sorting columns. All columns are sortable, simply click on the column header to sort via info found in that column.

> Active column will be highlighted with a blue line above the column and blue text. The carat indicates the direction of the sort, in this case from ascending order alphabetically.

I think we could probably further enhance this language after reviewing some implementation details in Reactabular. The default sort mechanism there is to allow the "unsorted state", however it appears PatternFly only allows sort ascending/sort descending. 

See example here (at bottom of page):
https://reactabular.js.org/#/data/sorting

I've built the default functionality to mimic what exists currently in PatternFly, (see this functioning [here](https://rawgit.com/priley86/patternfly-react/reactabular-storybook/index.html?knob-Label=Well%20done%21%20You%20successfully%20read%20this%20important%20alert%20message.&selectedKind=DataTable&selectedStory=Sortable%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) ) and removed the "unsorted" state.

I would propose that would we modify or append to existing sort state language for the table view, such as:

> All columns are sortable by ascending or descending sort order. By default, columns will only support ascending or descending sort, and are typically sorted by the first column in ascending order.

Reactabular also supports multicolumn sort so we may be able to revisit this in the future 😸

**Comment by priley86** [comment]
@serenamarie125 @mcarrano do you agree with these language updates?

**Comment by mcarrano** [comment]
@priley86 It looks like the "unsorted" state is necessary in Rectabular because they support multicolumn sort. The current Table View pattern was modeled on the Datatables jQuery plugin here which looks like it does not support multi-column sorting (https://datatables.net/). Maybe the first question is whether we should support multi-column sorting for implementations that can support it or take the least common denominator approach and stick with simple sorting as it's currently implemented.

@serenamarie125 will be interested to hear your thoughts.

**Comment by michpetrov** [comment]
@mcarrano FYI the current implementation of table view supports [multiSort](https://datatables.net/reference/option/orderMulti) and has it enabled by default

**Comment by mcarrano** [comment]
I actually did not realize that, so thanks for pointing it out @michpetrov . I do note however that the method used in the Datatables component differs from the Rectabular approach. Right now there is no mention in the design documentation about this capability so it is somewhat hidden.

Let me get further input on this to identify the path forward. It may be that we just update the documentation as @priley86 suggests in the short term. But in the longer term we should identify an approach for multi-column sort that can be consistent across implementations.

**Comment by mcarrano** [comment]
A new issue #543 has been created to look at data tables consistency across repo implementations and how to address from a design perspective. The resolution of this question will be dependent on that outcome.

**Comment by mcarrano** [comment]
@Mgranfie Just an FYI. Here's a specific issue about data tables that relates to the story you will be taking on. It's a good example of the types of questions that are coming up.
