### ISSUE TITLE
Mobile design for Login Screen

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#521]
## For Pattern contribution proposal, tell us about your idea... 
(delete section if filing a bug)
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [x ] This is an enhancement on an existing pattern

We have recently published new designs for our standard PF login screens here: http://www.patternfly.org/pattern-library/application-framework/login-page/ This includes a responsive approach that allows the same code to work across multiple devices.

We have feedback from the KeyCloak team that this approach may not be optimal for mobile usage and that we should consider a more simplified design that removes background images and is further compressed. Before making further changes, some investigation is needed around how we want to represent product identity on mobile apps (i.e. use of branded backgrounds and logotypes). This should result in recommendations for further design/code changes.

**Comment by amysueg** [comment]
thank you @mcarrano

**Comment by matthewcarleton** [comment]
👍 @mcarrano

**Comment by mcarrano** [comment]
@catrobson will follow up with @amysueg to recommend path forward.

**Comment by mcarrano** [comment]
@amysueg @catrobson Any update on this one? Do we need to keep this issue open/active?

**Comment by catrobson** [comment]
This issue can be closed.  I believe the KeyCloak team has adopted the latest PatternFly designs in their most recent sprint.

**Comment by mcarrano** [comment]
Great. Thanks for the follow-up @catrobson . I will close.
