### ISSUE TITLE
Update the Checkbox Filter design pattern to include transparency on the filter panel

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-design#530]
- This could be considered an enhancement or a bug on an existing pattern
- Angular Pattern made a change due to an issue that surfaced in OpenShift:
 https://github.com/patternfly/angular-patternfly/pull/701
- The style of the current checkbox filter panel was preventing users from seeing results in cases where there was a single result hidden behind the panel. Making the panel slightly transparent will prevent this case from misleading users.
- This update may be required in both the [Filter Pattern](http://www.patternfly.org/pattern-library/forms-and-controls/filter/) and the [Checkbox Filter Pattern](http://www.patternfly.org/pattern-library/forms-and-controls/checkbox-filter/).

@patternfly-design-maintainers, I can work on this issue.

**Comment by mcarrano** [comment]
I understand the problem, @beanh66 , but before we make this update I'd like to get some additional opinions here. Right now, I'm not aware the we have semi-transparent panels anywhere in PatternFly so this would be a styling add. @andresgalante and @kybaker I would be interested in getting your thoughts about this.

Did you also consider other alternatives? I agree that it's a problem that the panel blocks content and probably did not think of this when I reviewed the original design. Maybe there should be an Apply button that closes the panel before displaying the results. @cshinn thoughts?

**Comment by mcarrano** [comment]
@beanh66 can you send a screen shot so we can see what this looks like? Thnx.

**Comment by beanh66** [comment]
@mcarrano the OpenShift issue I provided a link to has some relevant conversation as well as a screenshot of the suggested change. Please check it out: https://github.com/patternfly/angular-patternfly/pull/701

I am attaching the image from that issue here as well:
<img width="301" alt="screen shot 2018-01-29 at 8 12 47 am" src="https://user-images.githubusercontent.com/18057044/35512025-450843c8-04cc-11e8-8657-4d8d5ff901c1.png">

**Comment by mcarrano** [comment]
@beanh66 Thanks for posting. @kybaker can you take a look and let us know what you think?

**Comment by kybaker** [comment]
@mcarrano @beanh66 I am concerned about how introducing this new styling will affect the rest of the library. This dropdown background is used in many other places in the library, do we make them all transparent? I am also concerned that it adds visual noise that takes away from the readability of the content. I also have concerns about levels of contrast. 

My question is, does the complexity of adding this element outweigh the benefit of this single usecase?

**Comment by beanh66** [comment]
No problem @kybaker just wanted to contribute back the change we made in OpenShift if it made sense. I wasn't aware this filter panel was being used anywhere else yet, but that's good if it is! I understand your concerns for changing it across the board and it's a minor difference so happy to close this issue if everyone agrees @mcarrano?

**Comment by mcarrano** [comment]
Let me just run past the strategists this week and confirm that we can close, @beanh66 . I think the approach taken was reasonable for OpenShift, but not sure I want to apply this in general to the design given @kybaker 's concerns.

**Comment by mcarrano** [comment]
@LHinson @catrobson @serenamarie125 @maryclarke @jeperry 
I somehow skipped over this one in yesterday's PF-UXS call. I'd like to recommend that we close this issue and not make this change to the Checkbox filter pattern. I concur with @kybaker 's comments above. I'm fine to consider this a reasonable customization for OpenShift to adopt, but would like to avoid introducing semi-transparent panels as a new PF core design element at this time.

Any objections?

**Comment by jeperry** [comment]
+1

**Comment by maryclarke** [comment]
sounds good to me @mcarrano

**Comment by Mgranfie** [comment]
+1

**Comment by mcarrano** [comment]
Sounds like there are no objections, so I am going to close this one out.
