### ISSUE TITLE
Embedded Wizard - Issues with responsive implementation of current design

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#532]
The current [embedded wizard design](http://www.patternfly.org/pattern-library/communication/wizard/#) does not support responsive layout. The layout assumes a fixed height in order to correctly place the left-hand sub-step navigation and the button bar. Given that the absolute height of a user's browser window is variable, it is not clear how to calculate that height.

Request is to reconsider need for an embedded wizard and/or adjust the design to address these concerns.

**Comment by mcarrano** [comment]
@matthewcarleton and @LHinson I have filed this new issue to take up the embedded wizard design and ask whether we should eliminate or rework this option. Feel free to add comments or further background.

**Comment by mcarrano** [comment]
Per @maryclarke , Cockpit has a need for this design. I will coordinate meeting with Mary and @matthewcarleton to discuss possible design modifications that will satisfy user case requirements as well as being addressing implementation concerns.

**Comment by mcarrano** [comment]
Per meeting on Feb 5 with @LHinson @matthewcarleton @maryclarke ... For now, we will remove the embedded wizard documentation on the wizard pattern because of issues we were having with implementation (current design does not allow for a flexible enough implementation). see: patternfly/patternfly#899

this documentation will just be commented out in the markdown with references to associated issues for further evaluation at a later date.

**Comment by mcarrano** [comment]
@matthewcarleton Can you briefly summarize the issue(s) with the embedded design so I can add these to the comment? Thx.

**Comment by matthewcarleton** [comment]
hey @mcarrano sure. The main issue with this design is the full height. This can only be done if we can know the height of all the other elements on the page with the wizard. 
So for example: wizard height = (100 % of viewport height - combined height of other elements). 
If we build the example and another element is added it will break.

**Comment by mcarrano** [comment]
A PR has been sent to address this. See #554
