### ISSUE TITLE
Use genderless descriptions in utilization bar chart 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#535]
http://www.patternfly.org/pattern-library/data-visualization/utilization-bar-chart/
Should use genderless descriptions when it isn't necessary. 

> For example, it would be appropriate to use a Utilization Bar Chart to show the user how much storage he has used in context of the total amount of storage he has purchased." 

Should be: 

> For example, you may use a Utilization Bar Chart to show a user how much storage has been used in context of the total amount of storage available."

**Comment by michael-coker** [comment]
PR submitted - https://github.com/patternfly/patternfly-design/pull/556
