### ISSUE TITLE
Utilization Bar Chart Edits 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#536]
http://www.patternfly.org/pattern-library/data-visualization/utilization-bar-chart/#/design

- fix formatting, nesting, and random hyphens in the first list
- Change "with the exact percentage value of the used value." to "with the exact used value percentage." or "with the exact percentage used."
- Change "provides for an warning" to "provides for a warning"
- Change "When a warning threshold is active, the chart fill is blue until it reaches the warning threshold." This should say green, not blue.
- Change "the warning threshold the chart fill is orange" to "the warning threshold, the chart fill is orange"
- Remove the bullet point "The warning threshold fill is orange (#ec7a08)" and put the hex value in the sentence before it after the word "orange" - and do the same for the "error threshold" section
- Update the language under the error and warning threshold sections to be more similar. Currently they say basically the same thing using different words that could be the same.

**Comment by michael-coker** [comment]
PR submitted - https://github.com/patternfly/patternfly-design/pull/556
