### ISSUE TITLE
Unclear wording in Wizard design panel 

### ISSUE THREAD

**Issue by michael-coker** [patternfly/patternfly-design#542]
https://github.com/patternfly/patternfly-design/blob/master/pattern-library/communication/wizard/design/design.md

Under [First Step](https://github.com/patternfly/patternfly-design/blob/master/pattern-library/communication/wizard/design/design.md#first-step), this text is unclear.

> In some cases the completion action button will close the dialog, and in others it views progress in the wizard and ends up changing the label of that button.

Can anyone explain what "it views progress in the wizard and ends up changing the label of that button" means? I _think_ it's referring to the 2nd bullet under [Final Step - Progress](https://github.com/patternfly/patternfly-design/blob/master/pattern-library/communication/wizard/design/design.md#final-step--progress) where it says:

> For wizards that do not remain open while the particular task is being processed, the completion button would close the wizard.

Also the 2nd bullet under [Completion Page](https://github.com/patternfly/patternfly-design/blob/master/pattern-library/communication/wizard/design/design.md#completion-page) where it says:

> The wording on the completion button can change once processing of the content in the wizard is complete. This may be Close or some other word that makes sense for the particular use case. 

Assuming so, should "it views progress in the wizard and ends up changing the label of that button" change to something more clear, like "the button text changes to indicate that the wizard is processing or finishing, and upon finishing, it changes again to "Close" (or whatever word makes sense for your application), allowing the user to close the dialog"?

**Comment by mcarrano** [comment]
@LHinson Do you know who originally wrote this and can give more explanation? If not, I'm fine to let @michael-coker revise the wording. I agree this could be made more clear. Thoughts?

**Comment by LHinson** [comment]
@cshinn I believe you worked on this one? If so, will you please review the issue and provide your input? Thanks!

**Comment by cshinn** [comment]
@LHinson I believe this is one of the patterns that I uploaded, but did not write the original content for, but I'm happy to weigh in on it.

I agree with @michael-coker that the "button bar" section is pretty unclear, and should at least be broken into sub-bullets or something. It looks like the other sections called out in the issue are what it refers to, and I wonder if maybe some of that description could be moved down to the sections where it's relevant and the button bar text could be more like "this is where the actions go, and this is the order that they should be placed in".

**Comment by LHinson** [comment]
Thanks for weighing in @cshinn! Agreed @mcarrano @michael-coker that we should clean it up. 

Looping in @serenamarie125 just in case she might have any other insight or comments on the intent.

**Comment by mcarrano** [comment]
@nlcwong has filed a related issue. See #578 . We should definitely clean this up. @michael-coker and @nlcwong can you coordinate? I'm happy to have whoever has bandwidth take this and resolve both issues. Thanks.
