### ISSUE TITLE
Add Type-Ahead Input Pattern

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#546]
## For Pattern contribution proposal, tell us about your idea... 
(delete section if filing a bug)
#### 1. Choose the type of contribution for this pattern:
- [x ] This is a new pattern 

#### 4. Use Cases + Requirements
As a user, I want the system to make suggestions or recall  previously entered search or filter terms as I type.  Suggestions are listed in a drop-down menu that is filtered as the user types.

#### 5. References 

There is an open PR to add this component to PatternFlt React. See https://github.com/patternfly/patternfly-react/pull/190 (also https://github.com/patternfly/patternfly-react/issues/189)

#### 6. Design Concepts  
See https://github.com/patternfly/patternfly-react/issues/189

**Comment by priley86** [comment]
Hi @mcarrano - thanks for the issue. 

Here is a few things I think that have been mentioned that would be possible nice additions when we have time:

*Select Multiple*:
http://ericgio.github.io/react-bootstrap-typeahead/  (controlling selections example)
Implementation pattern:
http://downshift.netlify.com/?selectedKind=Examples&selectedStory=multiple&full=0&addons=1&stories=1&panelRight=0

*Custom Menu Contents*:
http://ericgio.github.io/react-bootstrap-typeahead/  (see Rendering example)

*Custom Icons*:
https://jedwatson.github.io/react-select/ (see Custom Placeholder, Option, Value, and Arrow Components)
* generally i have seen these used to just give context around the selection (maybe a user's profile icon like this [one](http://twitter.github.io/typeahead.js/)). Some more examples of this [here too](http://react-autosuggest.js.org/).

**Comment by danseethaler** [comment]
@priley86 thanks for the thoughts on the component!

I did want to bring up one thing that may help the discussion. In my mind this component should remain fairly simple since it's goal is to provide suggestions as a user is typing. When a dropdown item is selected the user can continue typing and more options may appear. I think this differs quite a bit from other types of dropdowns like filtering a list, picking a user, or multi-select.

The recently released downshift library provides so much flexibility for these types of components that I think it makes more sense to support specific more narrow implementations rather than trying to address many uses cases in one component. If we allow lots of flexibility the user may as well just use Downshift directly.

Let me know your thoughts or if I'm off base here. Thanks!

**Comment by serenamarie125** [comment]
We have something in OpenShift take a look at the design here, http://openshift.github.io/openshift-origin-design/web-console/homepage/search-filter#search-catalog.  This is similar, yet different :) Do people think this would be a variation of the design?

**Comment by priley86** [comment]
yep - i think Downshift would support the OpenShift example noted above (with icons). 

To @danseethaler 's question - I'm not sure how to best group and and name the React components  (but they'd all be using Downshift). My vote would be have `AutoComplete` support profile icons and create an additional component (`TypeaheadSelect`) in a subsequent PR to support multiple typeahead selections (if this is a design pattern we like).

**Comment by dabeng** [comment]
Hi @danseethaler . I used jquery version of autocomplete. I think [Bootstrap-3-Typeahead](https://github.com/bassjobsen/Bootstrap-3-Typeahead) and [typeahead.js](https://github.com/corejavascript/typeahead.js) will give you inspirations if you want to add interesting features.

**Comment by yih-wang** [comment]
@danseethaler @priley86 @mcarrano I have a similar design for OpenShift.io and here's the wireframe, https://redhat.invisionapp.com/share/MECYL572D. Do you think this design can fit the needs?

**Comment by mcarrano** [comment]
I think this is an interesting design @yih-wang . Does the OpenShift team have an implementation for this?

**Comment by yih-wang** [comment]
@mcarrano I think it hasn't been implemented yet. @catrobson Can you confirm the status please? The original issue of the design is #516 .

**Comment by catrobson** [comment]
Correct, this hasn't been implemented in patternfly-ng - this is something that we wanted to do but haven't been able to prioritize since we already have something different that technically works, but isn't ideal, in the product.

**Comment by yih-wang** [comment]
@mcarrano I'd like to take this issue cuz it's similar as what I did before. 

When I take another look at the autocomplete component in PatternFly React, I found the type-ahead results will just show one word until beginning to input the next word. But I prefer to show the whole sentence. For example, if I input "ora", the dropdown shows "orange", but I think directly showing "orange is agreeable/calm/..." as suggestions makes more sense.

What's your thoughts? Should we align the design with the implemented component? In this case, we can directly link the code to PatternFly website.

**Comment by mcarrano** [comment]
Thanks for volunteering to take this on @yih-wang . I think that we need more discussion about that with a larger team. For now, I recommend documenting your design proposal as you think best. We do currently have a multi-select and single select drop down list based on Bootstrap http://www.patternfly.org/pattern-library/widgets/#bootstrap-select  How do you feel this fits with those? Is this an additional/new option? Would it replace Booststrap Select?

@LHinson this is a requirement to consider as we work on dropdowns and select lists for pf-next, also.

**Comment by yih-wang** [comment]
@mcarrano I think the use case of auto-complete is not only when selecting from dropdown list. It should also include [Filter](http://www.patternfly.org/pattern-library/forms-and-controls/filter/) and [Search](http://www.patternfly.org/pattern-library/widgets/#search). That means the auto-complete component is individual and can combine with current Dropdowns/Filter/Search patterns.

According to the previous discussion, basic features of the auto-complete component should be:

- Allow users to type in the input fields/drop downs.
- Custom menu contents, including dividers, headers, etc.
- Support keyboard interaction and a11y.
- Support icons.

The extensions include:

- Support multi-selections

And there are also some points need further discussion/research:

- Behaviour when hitting the `tab` key. When hitting the key, It will select the item and update the text input in current implementation. But in Bootstrap, it will switch to the next item, which is same as the Up arrow key.
- Drop down menu contents to show -- single word at a time or the whole item.

I'll draft a document for the first step, then it will be easier for us to move on.

**Comment by yih-wang** [comment]
@mcarrano I have did some research on this issue, and proposed a design. Have a look at this document: https://docs.google.com/document/d/1ZrtUMibkC_6oqjwTi6vx_xmFZMXk4SmJBC1VjjtiFII/edit?usp=sharing

**Comment by mcarrano** [comment]
@yih-wang Thanks for posting your proposal. It is thoughtful and well researched, as usual. @serenamarie125 and @lizsurette have been working on a similar proposal based on the React implementation and their product needs. Serena will post a copy by the end of this week. I'd like to make sure your proposal here is aligned with that and then I think we can move forward with turning this into a PatternFly contribution.

Hope that makes sense, but let me know if you have any questions.

**Comment by yih-wang** [comment]
@mcarrano Got it, thanks.

**Comment by dabeng** [comment]
Hi @mcarrano , is it necessary to reopen this [task](https://github.com/patternfly/patternfly/issues/332) to put jquery autocomplete into patternfly-core repo ?

**Comment by mcarrano** [comment]
Just wanted to give everyone an update on this based on recent discussions this week.

First, I have renamed this to "Type-Ahead Input" and reassigned to @serenamarie125 to better align with the contribution that is being made directly to React (https://github.com/patternfly/patternfly-react/pull/374). @dabeng we can reconsider where to add to Core at a later date, but for now will focus on React as that's where there is an immediate need.

@yih-wang Thanks for your prior work on this and hopefully this can be leveraged in writing up the final design. But since this is being contributed to React directly from product, I think it makes sense for @serenamarie125 and her team to pick it up from here and sync the design and implementation.
