### ISSUE TITLE
Change Request: Vertical Navigation: add integrated search for nav items.

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-design#551]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [x] This is an enhancement on an existing pattern
#### 2. If this enhancement or new pattern was made for an application, specify which one.

No specific application, it is just something I thought may be useful when testing my React implementation of this pattern.

#### 3. Title

Vertical Navigation: add integrated search for nav items.

###### *Specify the use case, requirements and what problems do we believe users have, that we intend to solve? ANd, does this problem have a community interest?*
Capture cross product requirements in this Google doc file.
Make a duplicate of this file and include a link to this file here: https://docs.google.com/document/d/1LQ_MxtsFgvxi8-ssXVHLcSaCUy0xQR_npqsBfyJH2Hw/edit?usp=sharing

I can follow up with a doc if there is any interest here. This is a shot-in-the-dark suggestion. When testing the hover delays and click behavior of the React VerticalNav, I found myself realizing it would be faster to type 2 or 3 keystrokes than to navigate to some of the deeper items with the mouse.

###### *Have you checked this GitHub backlog, to see if there is any work, in progress, that may impact your work?*

I have given it a quick search, but I apologize if this is not a new idea.

###### *Attach any rough sketches, undocumented wireframes or workflows that will help the PatternFly Team understand and review, the pattern you would like to submit.*

What I am imagining is this: Somewhere either in or near the Vertical Nav, or maybe as an extra item at the end of the primary list, we could have a Search icon/item, maybe even accessible via hotkey, that could make a temporary search bar and results pane appear. The search bar could have a placeholder text of something to the effect of "Find a page", or that could be customizable from app to app/context, e.g. "Find a pattern" or what have you.

The icon that triggers this search behavior would be easy to add to the existing design, but some new design resources would be required to determine how best to present this search bar and results area to the user. It should be focused immediately, so the user can click the icon/item and begin typing. Pressing enter should navigate to the first result. Ideally, arrow keys could select the others. It could be displayed as an expanded form of that final "Search" nav item in the list, but this would mean we couldn't implement my "highlight suggestion" behavior below. Perhaps instead it could be a pane that appears to the right of the deepest shown nav depth-- i.e., if you just clicked Search, it would appear in place of the Secondary nav pane. As you type, if your hovered suggestion is in the Secondary nav pane, primary and secondary navs are shown, and the search pane appears in place of the tertiary nav pane. Or, it could be a pane that slides in from the right. Not sure if that would work on all screen sizes. I'm no designer!

On mobile, the search pane would probably need to just replace the entire nav, and you wouldn't be able to get the highlighted suggestions I don't think. That would have to be some quite clever mobile design.

For extra-cool future-points, I am imagining that the selected search suggestion's ancestors are opened and the suggested item is highlighted/focused in the navigation tree as if you are hovering it, while you are hovering the suggestion. Maybe we could even fade out / darken the other items, or add extra border around the suggested item, something like that to draw the user's attention to the location of the suggested item. The JavaScript side of this would be easy to achieve in the patternfly-react implementation, by passing down an alternate `hoverPath` prop and adding a new `highlightSuggestion` prop, or maybe instead adding a new `suggestedPath` prop that renders similarly to the `hoverPath`.

For inspiration: The macOS application help search feature is a perfect example of the kind of experience that I'm going for: "here's what you're looking for, now you'll know where to find it next time."

<img width="755" alt="screen shot 2018-02-05 at 12 12 36 pm" src="https://user-images.githubusercontent.com/811963/35818461-20f5f816-0a6e-11e8-9548-52ec756e91df.png">

###### *Approximate the overall effort of the work for this issue, SM, MD, LG, XL, by applying the relevant GitHub label to this issue.*

MD, I think. 

###### *If you are going to be the person working on this pattern, use the tag '@patternfly-design-maintainers' in the comments, to let us know you want to work on this issue, and we will assign you to it.*

I would be happy to implement this in the JavaScript repos, but I would need help with the design side of it, and maybe some of the CSS.

###### *Once the design issue has been reviewed, the name and location, within the PatternFly.org website, will be determined and posted here, on this issue, by a PatternFly team member.*

http://www.patternfly.org/pattern-library/navigation/vertical-navigation/

This could probably also apply to Horizontal Navigation.

**Comment by mturley** [comment]
I don't have the permissions to add the MD size label.

@patternfly-design-maintainers as mentioned above, I would be happy to implement this in the JavaScript repos, but I would need help with the design side of it, and maybe some of the CSS.

**Comment by mcarrano** [comment]
I think this is an interesting idea @mturley . As well as making navigation more accessible, it could benefit accessibility, I think. Since this would not be trivial to design and develop, it will be a question of whether there is a product priority for this. Welcome other thoughts. @serenamarie125 @catrobson @maryclarke @jeperry @andresgalante

**Comment by mturley** [comment]
I agree on all counts. I think it would be very nice for a11y to have a simple function that turns a user's search string (or even the first letter or two) into a page navigation.

**Comment by mturley** [comment]
If I find free time, I might make a rough prototype of it in pf-react, and then if a designer wants to come along and make it pretty they are welcome to. :) we don't have to merge it until there is product priority. It can stay in my fork.

**Comment by mcarrano** [comment]
This sounds like a good approach @mturley . If anyone has a product priority for this we can move on it faster. But right ow, I would consider it a "nice to have."

**Comment by mcarrano** [comment]
Consider for PatternFly Next navigation.
