### ISSUE TITLE
Mega menu

### ISSUE THREAD

**Issue by lclay2** [patternfly/patternfly-design#553]
Mega menu: expandable dropdown navigation that presents high level IA categories and links to lower level sections at a glance. 

#### 1. Choose the type of contribution for this pattern:
- [X] This is a new pattern 
- [ ] This is an enhancement on an existing pattern

#### 2. If this enhancement or new pattern was made for an application, specify which one.
KIE http://www.kiegroup.org/, jBPM (http://jbpm.jboss.org/)

#### 4. Use Cases + Requirements:
- Allow users to easily navigate to respective functional areas to perform tasks - while also providing global access to related areas, to perform integrated end to end tasks (e.g. process deployment.) 
- Users of this system can easily: Identify and work within key functional areas of the application to perform specific tasks.
- Navigate between functional areas in the suite, to perform end to end tasks, using global navigation.
- Understand the context and purpose of functional areas -  to support users who might use some areas of the suite infrequently. 

#### 5. References 
https://docs.google.com/document/d/1W1wrH-jF5dwqwgkfRxZyAJfxfAl9HMIgsPqC-gGYaOo/edit?usp=sharing

#### 6. Design Concepts  
Doc attached, will send. 

#### 7. Scope  
Unknown, project specific documentation and implementation exists.

**Comment by mcarrano** [comment]
Thanks @lclay2 for submitting this well considered and detailed proposal!

@serenamarie125 @catrobson @maryclarke @jeperry @LHinson 
This is a proposal to add a "mega-menu" pattern to PatternFly as an alternative navigation. See the Google doc referenced above for more details about what this is, how it will work, and usage in the KIE/jBPM product.

Would like to get thoughts about cross-product applicability and whether we should document and add to PatternFly.

**Comment by catrobson** [comment]
@lclay2 @mcarrano looks good to me, I'd be happy to see this added to PatternFly.  We might also want to sync up with Jeremy and Tiffany since I think there are Mega menus used on the websites today.  If our pattern can generally cover all those use cases it would be a good thing.

**Comment by mcarrano** [comment]
Per 2/16 PF-UXS meeting, we approve this to move forward to create a first draft of this pattern. Primary concern is to make it clear when to use vs existing vertical or horizontal nav. [Navigation Guidelines](http://www.patternfly.org/pattern-library/navigation/guidelines/) documentation should be updated as part of this process.

@lclay2 I have assigned to you and glad to answer questions about next steps. We should also have visual design involved so please coordinate with @kybaker on creating more generic PatternFly versions of your designs.

**Comment by lclay2** [comment]
@mcarrano That's great Matt, thanks for the update. I'll followup with you and Kyle.

**Comment by amysueg** [comment]
woo-hoo @lclay2 ![bitmoji](https://render.bitstrips.com/v2/cpanel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-cc737c0e-145d-4d97-aea9-1fdd38b44e0a-v1.png?transparent=1&palette=1&width=246)

**Comment by matthewcarleton** [comment]
I've closed an issue that was in core that was related to this. We should consider it as this moves forward. Thanks!

**Comment by lclay2** [comment]
@mcarrano @LHinson @amysueg @catrobson 
Hi Matt, I have a draft for the mega menu pattern that I believe is ready for review:
https://docs.google.com/document/d/1y1BCRxCo5ofIdinV0eenHZwSPbA1EwPtQcI73pXFlJE/edit#
Thanks, Liz

**Comment by catrobson** [comment]
Thanks @lclay2!  I left a few comments in the document for you.

**Comment by mcarrano** [comment]
@lclay2 Thanks for posting this. Overall your document looks great. There were just a few comments/questions I left in the document.

Want to add @kybaker @serenamarie125 @jeperry @maryclarke and @matthewcarleton to the list of reviewers. Besides reading the Google doc, you can see a sample implementation here: https://cdn.rawgit.com/srambach/BxMS-frontend/master/bpm-home.html#

One question for @kybaker , is this something that will fit into our navigational approach for PatternFly-Next? I think we're at the point where we should start to consider that for anything new we add.

**Comment by maryclarke** [comment]
+1 to Cat's comments/questions regarding responsive design, but overall looks good.
