### ISSUE TITLE
Update Context Selector design docs for consistency with core implementation

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#569]
During the process of implementing Context Selector, the design needed to be modified to consider responsive behaviors when shrinking viewport. The final implementation can be seen here: https://rawgit.com/matthewcarleton/patternfly/context-selector-dist/dist/tests/context-selector-vertical-nav.html

Overview.md and design.md pages should be updated for consistency.

**Comment by mcarrano** [comment]
Thanks for taking this one @zhutaoredhat !

**Comment by zhutaoredhat** [comment]
@mcarrano Hi matt, I have updated the all mockups, please help me have a review. https://github.com/patternfly/patternfly-design/pull/615
