### ISSUE TITLE
Inconsistent story for masthead icons, pop-ups, dropdowns

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-design#570]
I would like to report a bug on consistent use of a pattern in our design documentation and visuals in the masthead.

Today, we show a caret next to the help dropdown, but not the launcher popup.  The fact that these two icons in the masthead act differently, one as a dropdown and one as a pop-up, seems inconsistent as well.  

In discussion with @kybaker we felt that none of the icons in the masthead should use a caret next to them, and they should all behave as pop-ups rather than drop downs.  Also not clear on whether a background selected state is necessary for the pop-up, as that is normally used to indicate selection for a dropdown area instead, such as is used for the user dropdown or context selector dropdown.

![image](https://user-images.githubusercontent.com/3739227/36328991-452916b0-1332-11e8-95d6-df833cb9e02a.png)

@mcarrano - please review and provide your insights as well

**Comment by mcarrano** [comment]
@catrobson Thanks for filing this issue. I think this inconsistency was intentional, but I can see where it wouldn't make sense and feels more like a bug. Let's discuss at the next meeting. I would not have a problem updating this to be more consistent.

**Comment by mcarrano** [comment]
Per 3/2 UXS-PF mtg:
* Update masthead to remove dropdown arrow from Help.
* Make sure we differentiate what uses pop-up vs. drop-down style. What are general rules. (add to General Considerations).

**Comment by mcarrano** [comment]
@deernano Thanks for taking on this issue. Please create a Google doc and/or InVision prototype with you proposed mockups so we may review them before updating the library.

**Comment by deernano** [comment]
@mcarrano before the mockup, I would like to research a little bit on this use case. I will create a google doc and maybe put some draft design in it and review with you. If we are agree with the direction I will develop the draft design. What do you think?

**Comment by mcarrano** [comment]
That's fine @deernano . Just keep in mind that we are not looking to make substantial changes here. But will be interested to see what you come back with.

**Comment by deernano** [comment]
@mcarrano Here is the research doc https://docs.google.com/document/d/1zsoGeBPbfr67VsUHbadzmzLs2f2sDS6XMp_flr9-xIs/edit?usp=sharing
I expained the general rules concept only. If we agree with, I will write a more comrehansive description of the rules with images.

**Comment by mcarrano** [comment]
@deernano I reviewed your document. Your recommendations seem reasonable based on the research. What I would like to see next would be some mockups or detailing of specific changes that you are proposing that we make.

@catrobson @serenamarie125 @maryclarke @jeperry @kybaker @LHinson your feedback is also welcome.

**Comment by deernano** [comment]
@mcarrano ok, I will continue work on this

**Comment by deernano** [comment]
@mcarrano Here is the proposed changes of the masthead menu. Please take a look. Thank you~
https://docs.google.com/document/d/1J4VNRPCmpHsoPaJro_LgvKblgW4D7-cz21rPjxO_JMM/edit?usp=sharing

**Comment by mcarrano** [comment]
Your recommendations look good @deernano . Please also review @catrobson @serenamarie125 @maryclarke @jeperry @LHinson @kybaker @matthewcarleton . I think this would mean updating our current masthead design pages and implementation to be consistent with this.

**Comment by matthewcarleton** [comment]
LGTM, thanks @deernano :)

**Comment by maryclarke** [comment]
LGTM

**Comment by deernano** [comment]
@mcarrano @catrobson @matthewcarleton @maryclarke  Thanks for the comment:)
I will submit a pr.
