### ISSUE TITLE
pf-react component updates on status page

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-design#571]
The following components have been recently merged and should be added to the [patternfly status page](http://www.patternfly.org/patternfly-design/status/):

- [content views: table-view](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Show%20Modal=true&knob-content=Enter%20the%20hostname%20in%20a%20valid%20format%20%3Cbr%3E%20%20%3Ca%20target%3D%22_blank%22%20href%3D%22http%3A%2F%2Fwww.test.example.com%22%3EClick%20here%20for%20examples%20of%20valid%20hostnames%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Labels=false&knob-Show%20Help=true&knob-Stacked=false&knob-Show%20Loading=false&knob-Disabled=false&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Field%20Label=Hostname&selectedKind=Table&selectedStory=Client%20Paginated%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
    @priley86 or @jeff-phillips-18 Do you agree with linking to this pf-react example for table-view?
- [forms and controls](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Show%20Modal=true&knob-content=Enter%20the%20hostname%20in%20a%20valid%20format%20%3Cbr%3E%20%20%3Ca%20target%3D%22_blank%22%20href%3D%22http%3A%2F%2Fwww.test.example.com%22%3EClick%20here%20for%20examples%20of%20valid%20hostnames%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Labels=false&knob-Show%20Help=true&knob-Stacked=false&knob-Show%20Loading=false&knob-Disabled=false&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Field%20Label=Hostname&selectedKind=Forms&selectedStory=Horizontal%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
This link provides examples of the following:
  - Buttons on Forms
  - Errors and validation
  - Field Labeling
  - Help on Forms
  - Syntax Hints
- [forms and controls: data input](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Show%20Modal=true&knob-content=Enter%20the%20hostname%20in%20a%20valid%20format%20%3Cbr%3E%20%20%3Ca%20target%3D%22_blank%22%20href%3D%22http%3A%2F%2Fwww.test.example.com%22%3EClick%20here%20for%20examples%20of%20valid%20hostnames%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Labels=false&knob-Show%20Help=true&knob-Stacked=false&knob-Show%20Loading=false&knob-Disabled=false&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Field%20Label=Hostname&selectedKind=Forms&selectedStory=Supported%20Controls&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
- [forms and controls: filter](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Show%20Modal=true&knob-content=Enter%20the%20hostname%20in%20a%20valid%20format%20%3Cbr%3E%20%20%3Ca%20target%3D%22_blank%22%20href%3D%22http%3A%2F%2Fwww.test.example.com%22%3EClick%20here%20for%20examples%20of%20valid%20hostnames%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Labels=false&knob-Show%20Help=true&knob-Stacked=false&knob-Show%20Loading=false&knob-Disabled=false&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Field%20Label=Hostname&selectedKind=Filter&selectedStory=Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
- [navigation: vertical navigation](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Show%20Modal=true&knob-content=Enter%20the%20hostname%20in%20a%20valid%20format%20%3Cbr%3E%20%20%3Ca%20target%3D%22_blank%22%20href%3D%22http%3A%2F%2Fwww.test.example.com%22%3EClick%20here%20for%20examples%20of%20valid%20hostnames%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Labels=false&knob-Show%20Help=true&knob-Stacked=false&knob-Show%20Loading=false&knob-Disabled=false&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Field%20Label=Hostname&selectedKind=Vertical%20Navigation&selectedStory=Items%20as%20JSX&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by amarie401** [comment]
Thanks! @jgiardino

**Comment by priley86** [comment]
re: table-view. works for me @jgiardino . I guess eventually it would be nice to have an example with filters as well (but right now we don't have the integrated example). I believe @Mgranfie will reach out to you and @jeff-phillips-18  on this (around table terminology/organization).

**Comment by amarie401** [comment]
@jgiardino @priley86 I already have the react example for forms and controls: filter under the textbox filter example, not plain "filter". Is this okay? The react example seemed specific to the textbox filter design pattern.

**Comment by jgiardino** [comment]
@amarie401 I would put that under both, since the design documents seem to overlap. So if they navigate to the [Filter](http://www.patternfly.org/pattern-library/forms-and-controls/filter/) page, it would be nice for them to be able to find the pf-react Filter component.

**Comment by amarie401** [comment]
@jgiardino @LHinson I have currently only linked textbox filter and checkbox filter and other filter specific patterns to their implementations. Currently there is nothing linked under filter along with no pf core example. I am a bit confused on what is considered filter or if filter is made up of the specific kinds of filter? 

I have no issue with linking the pf-react filter example, just want to clarify on what is considered filter. I have also discussed this with @mcarrano and @dtaylor113 in a past [issue](https://github.com/patternfly/patternfly-org/issues/518) Just want to make sure I'm linking the right filter examples for their framework implementations.

**Comment by mcarrano** [comment]
@amarie401 I can see how this is confusing! The [Filter pattern](http://www.patternfly.org/pattern-library/forms-and-controls/filter/) is more like a general design specification for how all filters should work. We did not want to repeat specifications of specific behaviors within the design page for each filter instance. There can potentially be many different filter types that can plug into this filter pattern.

The Filter component I'm seeing in the React storybook is really what we're calling a [Textbox Filter](http://www.patternfly.org/pattern-library/forms-and-controls/textbox-filter/). We should have a separate component for a [Checkbox Filter](http://www.patternfly.org/pattern-library/forms-and-controls/checkbox-filter/).

@LHinson perhaps this is a good topic for the next Repo Leads mtg. I think we need to clarify naming of what we are calling these things across repos otherwise these will continue to be confusion.

**Comment by Mgranfie** [comment]
+1 on the naming. It really has a big impact.

**Comment by LHinson** [comment]
@mcarrano I've added it to the agenda for Friday :) 

Thanks!
