### ISSUE TITLE
Improve documentation on error resolution

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-design#572]
In our pattern "Validation and Errors" for Forms and Controls, we provide some guidance on when validation should occur.  After confusion from developers, I'd suggest adding "and the widget loses focus" on the description of when validation disappears after a user fixes the field entry.

> When to perform validation
> For server-side validation, the error message always appears after user submitted and the entire page was reloaded. For client-side validation, there are several scenarios:
> * When possible, it’s best to perform inline validation as the widget loses focus so that the user is immediately informed of invalid information. The validation will disappear after user modifies the content within the field **and the widget loses focus**. However, inline validation shouldn’t be overused as the user may feel frustrated.
> * When a required field is not filled or input data is in the incorrect format, we recommend showing a validation as the widget loses focus. If users are asked to provide unfamiliar data or a specific format is needed, we recommend provide syntax hints to preventing users from making mistakes. See Syntax Hints for more information.
> * Some use cases might require validation as the user types, where the syntax for each character is checked. For example: Checking IP address fields where the only valid characters are numbers and periods.

**Comment by catrobson** [comment]
Sorry, I'd submit a PR if my system was set up!  Hope this small change can be added by someone who is already in making changes. :)

**Comment by mcarrano** [comment]
@catrobson This makes total sense. I will queue this up as a small fix that someone can take when they have some time. Would be a great training exercise if we have someone new who is needing to learn the contribution process.
