### ISSUE TITLE
Notification drawer wastes space by showing up at fixed height

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-design#573]
This is reference to this [issue](https://github.com/patternfly/patternfly/issues/959) filed in core.

**Comment by gregsheremeta** [comment]
This is an interesting design issue. On a 1920x1080 PC, I like when the drawer opens all the way. https://github.com/patternfly/patternfly/issues/959 is a screenshot from a screen in vertical orientation, and it does look weird. But the whole thing looks weird to me -- it's 2k tall :) Does PatternFly design for vertical and or high dpi screens?
