### ISSUE TITLE
View selector icons and order are inconsistent throughout PF documentation

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#575]
There are visual & design inconsistencies throughout the PF documentation

Note that we will be talking to @mcarrano on 3/1 to go over this issue

View types which we should make sure are captured:
- Card View
- Dashboard View / Overview
- List View
- Object / Summary View
- Table View
- Topology View

@terezanovotna will be including additional information today ...

**Comment by terezanovotna** [comment]
It is not very clear what the icon order and name are. Should they be called Grid, Tile and List View?
<img width="1324" alt="screen shot 2018-02-22 at 11 10 51" src="https://user-images.githubusercontent.com/36040135/36616850-4811729c-18b3-11e8-9b2b-6fdcb2863e16.png">

Because Drag and Drop section shows different icons. 
<img width="1324" alt="screen shot 2018-02-22 at 11 18 37" src="https://user-images.githubusercontent.com/36040135/36616888-706fae34-18b3-11e8-836e-f8a35b658375.png">

as well as Inline edits for List View
![screen shot 2018-02-22 at 11 23 40](https://user-images.githubusercontent.com/36040135/36616913-8610f4be-18b3-11e8-912a-74b1540bea33.png)

PatternFly icons should have consistent name and look as the View Selector Icons.
<img width="1323" alt="screen shot 2018-02-22 at 11 27 40" src="https://user-images.githubusercontent.com/36040135/36616960-b602d03e-18b3-11e8-981c-5fa534eb7adc.png">

**Comment by terezanovotna** [comment]
<img width="612" alt="view selector" src="https://user-images.githubusercontent.com/36040135/37035296-61e34ae6-214c-11e8-91b8-c3aaa5396423.png">
Which view do we want to use for View Selector? I think we should use the one in Card View

**Comment by terezanovotna** [comment]
I suggest this order and naming of these icons.
<img width="590" alt="table card list view" src="https://user-images.githubusercontent.com/36040135/37035783-e955f310-214d-11e8-9668-35401129b370.png">

**Comment by terezanovotna** [comment]
@mcarrano @serenamarie125

**Comment by mcarrano** [comment]
@serenamarie125 @catrobson @maryclarke @jeperry  Please take a look at @terezanovotna 's proposal. I wasn't sure about the desired order of these. I think that we also discussed replacing the Table icon with something better. @kybaker @jennyhaines do you have a suggestion?

**Comment by terezanovotna** [comment]
Serena confirmed that Toolbar shows a correct order of the icons (1) List (2) Card (3) Table
<img width="884" alt="screen shot 2018-03-07 at 11 19 56" src="https://user-images.githubusercontent.com/36040135/37087093-972d25d4-21f9-11e8-939d-914d1642ae85.png">

**Comment by terezanovotna** [comment]
We need one consistent icon for List, Card, and Table
<img width="877" alt="screen shot 2018-03-07 at 11 21 42" src="https://user-images.githubusercontent.com/36040135/37087247-0c660e38-21fa-11e8-8845-72ebe7c1308e.png">

**Comment by mcarrano** [comment]
@jennyhaines and I just went through a review of icon usage. I think that we want 'fa-table' for Table View, 'fa-th-large' for Card View. @jennyhaines can you confirm.

The icon shown in the mockups for List View is correct but I can't find that on our Icons page. Anyone know what this is? We should explicitly call this out is the pattern.

**Comment by jennyhaines** [comment]
@mcarrano - yes, I agree that we should be using 'fa-table' for table view,and  'fa-th-large' for card view. 'fa-th-list" is what we should be using for list view. (Not in that table- that's being updated in the upcoming PR!) @terezanovotna

**Comment by terezanovotna** [comment]
Thanks for your input! I am adding more info about [View Selectors](https://docs.google.com/document/d/1avSfEJevRKA6oI-q3AIJU1bpoHaWYq5yWn88jER9kVs/edit?usp=sharing) into Toolbar. As we introduce consistent order and look of the icons, images have to be updated throughout PF.

@serenamarie125 @mcarrano please comment, so I can put PR

**Comment by serenamarie125** [comment]
@jennyhaines does 'fa-th-list' make sense?  it has a dot with line on it (looks like radio button list), which really doesn't depict our list views.  I thought that we were moving towards something similar to the hamburger menu, but with four lines?

**Comment by terezanovotna** [comment]
[This is the latest](https://fontawesome.com/v4.7.0/icon/th-list/) fa-th-list @jennyhaines shared with me

**Comment by jennyhaines** [comment]
@serenamarie125 @terezanovotna - [fa-th-list](https://fontawesome.com/v4.7.0/icon/th-list/) and [fa-list](https://fontawesome.com/v4.7.0/icon/list/) are the only list-related icon that FontAwesome supplies, though they do have a [fa-align-justify](https://fontawesome.com/v4.7.0/icon/align-justify/) that isn't  intended for list views, but we could use it if it A) visually depicts our list view more accurately - which I agree that it does, and B) we will not need to use justification icons in our Red Hat products - don't think we do currently.

@mcarrano , thoughts? I can change our recommendation in the PF icon table if we find that 'fa-align-justify' works better to show a list view.

**Comment by mcarrano** [comment]
@jennyhaines I would be OK to use fa-align-justify or do you this we should just create a unique Pf icon for this? I don't really anticipate that we will use text justification in anything we design at RH, although one could argue that if PF is an open design system, there's no restriction on what someone might build. Mainly, I'm a bit uneasy that the icon is called "align-justify" but we are using it to represent a list. But maybe that's just me. @serenamarie125 @terezanovotna  thoughts?

**Comment by terezanovotna** [comment]
I agree that [fa-align-justify](https://fontawesome.com/v4.7.0/icon/align-justify/) depicts the list view more accurately.

**Comment by jennyhaines** [comment]
Okay, I'll change our recommendation to fa-align-justify for the list view icon!

**Comment by jennyhaines** [comment]
I'm fine with creating a new icon for the PF icon set based on fa-align-justify. We could could add that icon in at the same time as the new sort icons that are going in this PF sprint.

**Comment by mcarrano** [comment]
@terezanovotna Please move forward with this by creating a new pattern in Forms and Controls called "View Selector" that contains guidance on icons as you describe. Existing content views and Toolbar pattern should also be updated reflect this and link to the new pattern.

You may also want to consider the effect of switching between views. Does the view get re-paginated? For example, what happens if the same number of objects don't fit in the view when it is switched (i.e. switch between a table and a card view). Or will the number of items in view always be the same?

Let me know if you have questions.

**Comment by terezanovotna** [comment]
[Mockup](https://docs.google.com/document/d/19YRgDY1FeSm72zYDyNg4E5daWyjMAh5XJGBb_SSUpiM/edit?usp=sharing) for View Selector

**Comment by terezanovotna** [comment]
@mcarrano let me know what you think. Then I will go ahead and adjust the images throughout PF for consistency

**Comment by mcarrano** [comment]
@terezanovotna In looking at your PR's I think you may have mixed these changes with prior work on the Loading States. Perhaps we should do a Bluejeans call to sort this out. I can discuss how to do this with multiple branches to isolate you changes. I will try to set something up for us.

**Comment by terezanovotna** [comment]
Matt and Tereza reviewed changes - it looks 👍. 

As approved, Tereza starts working on updating mockups for

- CARD VIEW OVERVIEW
- CARD VIEW DESIGN
- LIST VIEW OVERVIEW
- LIST VIEW DESIGN
- TREE LIST VIEW OVERVIEW
- TREE LIST VIEW DESIGN
- PAGINATION OVERVIEW
- PAGINATION DESIGN
