### ISSUE TITLE
Wizard button bar should span width of wizard

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#577]
There are visual & design inconsistencies throughout the PF documentation

Note that we will be talking to @mcarrano on 3/1 to go over this issue

@nlcwong will be including additional information today ...

**Comment by nlcwong** [comment]
**Description:** The design documentation for the Wizard's button bar is inconsistent with what has been implemented.  The screenshots on the overview & design tabs of the Wizard designs show that the wizard's button bar does not take up the entire width of the wizard and instead only spans up to the sub-steps panel (see example image below):

<img width="677" alt="screen shot 2018-02-22 at 11 23 41 am" src="https://user-images.githubusercontent.com/31672086/36621061-31c66acc-18c4-11e8-953d-7c2e4be603c4.png">

**Steps to reproduce:** Screenshots found on the following pages: 
[PatternFly Library > Communication > Wizard > Overview Tab](http://www.patternfly.org/pattern-library/communication/wizard/#overview)
and...
[PatternFly Library > Communication > Wizard > Design Tab](http://www.patternfly.org/pattern-library/communication/wizard/#design)
do not properly reflect what has been implemented:
[PatternFly Library > Communication > Wizard > Code](http://www.patternfly.org/pattern-library/communication/wizard/#code) . -- click on "Launch wizard" button to view what has been implemented.

**Solution:** Update screenshots to match what has been implemented as what has been implemented demonstrates what the desired design should look like (see image below):

<img width="923" alt="screen shot 2018-02-22 at 11 30 10 am" src="https://user-images.githubusercontent.com/31672086/36621099-5896e1f4-18c4-11e8-8d89-5b757c666709.png">

**Comment by nlcwong** [comment]
This issue will be taken care of by Pull Request #601
