### ISSUE TITLE
Inconsistent Documentation of Interaction Behavior with Wizard

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#578]
There are visual & design inconsistencies throughout the PF documentation

Note that we will be talking to @mcarrano on 3/1 to go over this issue

@nlcwong will be including additional information today ...

**Comment by nlcwong** [comment]
**Description:** The documentation of the wizard pattern, mentions in the main steps and Button Bar, that the user cannot advance to the next step (either through the steps panel buttons or through the wizard's button bar) without satisfying requirements, yet there is no indication that is the same case with the wizard's sub-steps.  In addition, the desired interaction behavior is not properly enforced in the PatternFly Core Implementation of the wizard.

**Steps to reproduce:** Descriptions found on the following pages:
1. Open [PatternFly Library > Communication > Wizard > Design Tab](http://www.patternfly.org/pattern-library/communication/wizard/#design)
2. On that page, scroll down to First Step > 2. Sub-steps for the Selected Main Step
==> That paragraph of description does not contain any wording on how the wizard should behave when there are required inputs w/in the sub-steps.

1. Open [PatternFly Library > Communication > Wizard > PatternFly Core Example](http://www.patternfly.org/pattern-library/communication/wizard/#code)
2. Click on the "Launch wizard" button
3. Hover over the "Next" button of the wizard
==> should reveal that it is disabled (a circle with a strikeout appears and everything is greyed out)
4. Click on the "Next" button
==> it advances the wizard to the next sub-step.

**Solution:** 


- Update wording in the "2. Sub-steps for the Selected Main Step" section to include:
_" The sub-step labels can be used to jump between sub-steps in a non-sequential manner as long as previous sub-steps have been completed. This should also be enabled for next sub-steps as long as all required information has been completed on the current sub-step and there are no dependencies between the sub-steps."_

- Update PF Core implementation to not allow the system to take action on when a user tries and clicks on a disabled Next button (or do not have that Next button look disabled).

**Comment by michael-coker** [comment]
Some more issues with the Wizard demo code.

1. Even when "back" and "next" are greyed out, and the cursor indicates the buttons are disabled, you can click either button and it will take you to the previous/next step. You can even click "next" during the loading screen and it will load the first step in the wizard in the loading screen.
2. At any point, you can advance to next steps even though you haven't filled out required fields in both the top and left navigation.

**Comment by michael-coker** [comment]
The disabled "back" button also allows you to go back when you click it.

Also clicking on the steps in the top and left navigation allow you to advance through the wizard without filling out required fields.

**Comment by nlcwong** [comment]
@michael-coker so about the code portion, when reviewing this issue with @serenamarie125 & @mcarrano they noted that the code is perhaps purposely that way because there is no real backend to it, so the logic might not be there to enforce the intended behavior.  I've corrected this issue to state that the goal is to address the textual design documentation for this pattern and not the demo portion.
