### ISSUE TITLE
Update PF images to use correct badge visuals

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#579]
The Overview page of the vertical navigation pattern has 2 out of date visuals
- change the flag to the bell
- badge should be blue and on top right corner
- add the user name

be sure to be consistent with what's defined here: http://www.patternfly.org/pattern-library/application-framework/masthead/

**Comment by mcarrano** [comment]
@serenamarie125 @kendraMar I am aware that there are many inconsistencies in the library, but can you list specific items that this issue refers to for clarity? Thanks.

**Comment by KendraMar** [comment]
Hey, Matt! Definitely...we are putting together our detailed list of issues and will give you the reveal (HGTV speak) tomorrow when we meet.

**Comment by KendraMar** [comment]
Badges should look like this:

![badge1](https://user-images.githubusercontent.com/32581146/36871766-44331a3c-1d71-11e8-95d8-3fc1b6b27c5d.png)



Images that are showing the wrong badges are below:

- Notification icon on horizontal navigation image currently looks like this:
![badge2](https://user-images.githubusercontent.com/32581146/36871288-cb665980-1d6f-11e8-89da-d5b751d98042.png)

Image location: http://www.patternfly.org/pattern-library/communication/notification-drawer/#code 
	
- Notification icon on vertical navigation image currently looks like this:
![wrongbadge](https://user-images.githubusercontent.com/32581146/36871543-90abaad8-1d70-11e8-9550-a897885a795f.png)

Image location: http://www.patternfly.org/pattern-library/navigation/vertical-navigation/
