### ISSUE TITLE
Selectpicker with placeholder indistinguishable from disabled selectpicker

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-design#587]
This is related to [this](https://github.com/patternfly/patternfly/issues/888) issue that was filed in core.

**Comment by mcarrano** [comment]
I agree that there is not enough visual differentiation between the "nothing selected" state and the disabled state. @kybaker can you take a look at this? My opinion would be to keep the same visual styling but perhaps italicize the text as an instruction.

**Comment by kybaker** [comment]
@matthewcarleton Good catch. I agree with @mcarrano here.

**Comment by mcarrano** [comment]
So sounds like we all agree. Then what are the next steps here? @matthewcarleton wouldn't this just require a CSS change? I don't think there anything else for us to do from a design standpoint. Thoughts?

**Comment by matthewcarleton** [comment]
@mcarrano yes I believe so.

**Comment by mcarrano** [comment]
@matthewcarleton Do you want me to open a new issue against Core then, or can you just reopen the original issue?

**Comment by matthewcarleton** [comment]
@mcarrano I'll just reopen, thanks! :)

**Comment by mcarrano** [comment]
Great. Thanks @matthewcarleton . I will close this as a design issue then.
