### ISSUE TITLE
Design for Data not Applicable

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-design#588]
Looking for guidance around cases where data is not applicable. 
- Not sure if this would enhance an existing pattern or stand on its own.
- Applies to tables, list views, card views, etc. 
- Use cases exist today in both Foreman and OpenShift where we are looking to distinguish between data not applicable/not provided and data not available or not loading at the moment. 
- Foreman uses "NA" for this today
- Currently PF has a loading state, but the case where a column in a table does not apply to certain provider types would warrant this type of NA notation. 

@Rohoover @ncameronbritt @serenamarie125 FYI

**Comment by ncameronbritt** [comment]
FWIW, I'm more accustomed to seeing "N/A", as opposed to "NA" for not applicable.

**Comment by Rohoover** [comment]
Would this be a good opportunity to involve Stacy McAuliffe? I don't know her github handle off-hand.

**Comment by beanh66** [comment]
@stacymcauliffe Can you take a look at the issue above? Thanks!

**Comment by mcarrano** [comment]
@beanh66 Is there a distinction in your mind between "not applicable" and "not available?" Agree that "loading" is different since the data is available, but it hasn't been loaded yet. Maybe it's a matter of where the data is permanently unavailable (i.e. an error condition) or the field is not applicable in this instance. Is there a screenshot that illustrates the case you are describing?

**Comment by beanh66** [comment]
@mcarrano I think it is a matter of data not available because it does not apply. It is not an error case since the data just does not apply for the specific instance. Does that make sense?  @ncameronbritt and @Rohoover can you share the examples you have?

**Comment by Rohoover** [comment]
@mcarrano 
For example: Satellite has both custom subscriptions and Red Hat subscriptions. Both are housed in the same table. Custom subs do not have a sku or contract number but Red Hat subs do. In the table, NA is listed for sku/contract for those custom subs. 

They are both subscriptions and the interactions with them are the same so they do belong in the same table despite a few pieces of information not being relevant to both.

**Comment by ncameronbritt** [comment]
It's possible to have both cases in OpenShift. For example, we will have a table that shows (among other things) the amount of storage consumed. Not all of the storage types will support this metric, so we need to show that that metric does not apply for that storage type--there will never be data.

But it is also possible for the storage types that do support the metric that those data are not available at the moment for some reason. Currently in the console they use `--` in this scenario.

**Comment by mcarrano** [comment]
Thanks for all the clarification @beanh66 @Rohoover and @ncameronbritt . This makes more sense to me now. Yes, I agree this is something that calls for more guidance. I'm not sure whether this is a pattern or part of our overall terminology and wording guidelines. I will queue this up for more discussion with the strategists.

**Comment by stacymcauliffe** [comment]
Just getting caught up on this! I haven't seen this case before, so off the top of my head I got nothing. Let me dig into this a little with of our various Red Hat writing standards this afternoon and see what I can find. Stay tuned...

**Comment by mcarrano** [comment]
There was an earlier story to address this topic, the details of which can be see here: https://patternfly.atlassian.net/browse/PTNFLY-2181 This resulted in an update to the Table View pattern to use "--" to indicate not applicable or unavailable data. See http://www.patternfly.org/pattern-library/content-views/table-view/#design (item #8).

@beanh66 do you think this addresses the problem? If so, this approach should be carried over to other view types and perhaps further clarification made between "Unavailable" vs. "not applicable". Thoughts? @LHinson FYI

**Comment by beanh66** [comment]
@mcarrano I thought the issue here was that we wanted to distinguish between the data is not available at this moment (system issue) and the data does not apply for this object.  Sounds like we have a solution for the former but not the latter.

**Comment by mcarrano** [comment]
@beanh66  If you see "--" what does that reflect to you? Not available? Not Applicable? Neither? To me it's more like "not applicable" and maybe we need to do something different for "not available?" Not sure. @stacymcauliffe let us know if you find anything in your research.

I'm willing to queue this up for further exploration and discovery. Does someone want to take this on? After giving it more thought, I think this should be a global guideline that exists on the [Terminology and Wording page](http://www.patternfly.org/styles/terminology-and-wording/), just as we handle truncation.

**Comment by stacymcauliffe** [comment]
I haven't been able to find any solid recommendations on this anywhere. 
A few options - 
1. Use "--" to represent any missing value
2. Use "n/a" to represent any missing value
3. Use "--" to represent a value that is not available and "n/a" for data that is not applicable
4. Use "--" for everything and assign a tool tip of "Not applicable" or "Not available" depending on the context

I think the amount of time we spend on it depends on how important it is for users to understand the distinction.

**Comment by mcarrano** [comment]
I did have an opportunity to discuss with the UX Strategists today and based on that, I'm proposing that we use "--" to reflect Data not Applicable and "N/A" for Data not Available. The difference being that the first one would indicate that the data in question would never be available for the object in question.

@beanh66 @ncameronbritt @Rohoover @serenamarie125 does that work for you?

**Comment by Rohoover** [comment]
If that is the consensus then I'm good with it!

**Comment by beanh66** [comment]
That works @mcarrano!

**Comment by mcarrano** [comment]
@yih-wang If you will be updating Terminology and Wording for #626 , can you take this one too and roll into one PR?

**Comment by yih-wang** [comment]
Sure, I'll take this.

**Comment by mcarrano** [comment]
This was address by #631 . Will close.
