### ISSUE TITLE
Arrow button not always visible in 2nd level pinnable menu

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-design#591]
This is related to [this](https://github.com/patternfly/patternfly/issues/837) issue that was filed in core.

**Comment by mcarrano** [comment]
Right now I think this is functioning as designed. @serenamarie125 can you look at the original issue and let me know if you think there is a problem? As far as I know this is only implemented in the Angular version here: https://www.patternfly.org/angular-patternfly/#/api/patternfly.navigation.component:pfVerticalNavigation%20-%20Basic
