### ISSUE TITLE
Need guidance on action button location for toolbars and breadcrumbs

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-design#593]
Update Toolbar and Breadcrumbs patterns to provide explicit guidance on where primary and secondary actions belong. For example in the toolbar, two actions are shown, but it is not clear if the primary action is the right-most or left-most action. In the breadcrumbs pattern, can actions be placed on right side when there is no toolbar below? Seems like a better use of space then adding another horizontal row just for actions. 

This is a pattern enhancement. Use cases were discussed with @catrobson @serenamarie125 and @amysueg as we are not currently consistent across products in this area. 

I am happy to contribute these updates. Open to suggestions on where the primary action belongs. Note the various layouts: 
<img width="950" alt="screen shot 2018-03-01 at 6 29 51 pm" src="https://user-images.githubusercontent.com/18057044/36875585-90aa3294-1d7e-11e8-9690-a635a0fba9ab.png">

**Comment by beanh66** [comment]
Here are some examples where actions are not consistent when used in conjunction with a breadcrumbs bar and without a toolbar. 
<img width="451" alt="screen shot 2018-03-01 at 6 31 55 pm" src="https://user-images.githubusercontent.com/18057044/36875669-fe0dd4ee-1d7e-11e8-981e-d930bc6cbc43.png">
<img width="942" alt="screen shot 2018-03-01 at 6 32 12 pm" src="https://user-images.githubusercontent.com/18057044/36875672-ff52178e-1d7e-11e8-99b3-fc1cbce1ace4.png">

**Comment by mcarrano** [comment]
@beanh66 Agree that more guidance on placement of primary actions in the Toolbar will be helpful. @cshinn has been working on an Actions pattern so I want to involve him in this discussion. See #508 . As for including actions as part of a "breadcrumbs bar" I think this is potentially a different pattern that is useful for drill-down or object detail pages but not really part of the breadcrumb IMO.

**Comment by mcarrano** [comment]
Per 3/2 PF-UXS mtg we should address the "breadcrumb header" case as either a new pattern of guideline to cover common cases. Consider how this plays within the page.
