### ISSUE TITLE
Need guidance around actions and the use of icons, buttons, links

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-design#594]
Looking for guidance around the visual appearance of actions. Can we provide details around when actions can or should have an icon associated with them and where those icons belong? Can we provide details around when actions should be links vs buttons? 

This is a pattern enhancement. Use cases were discussed with @catrobson @serenamarie125 and @amysueg as we are not currently consistent across products in this area.

See examples below. 

OpenShift: 
<img width="531" alt="screen shot 2018-03-01 at 6 35 17 pm" src="https://user-images.githubusercontent.com/18057044/36875909-58421f82-1d80-11e8-845c-16fd5566cd4b.png">
<img width="785" alt="screen shot 2018-03-01 at 6 35 39 pm" src="https://user-images.githubusercontent.com/18057044/36875910-5853930c-1d80-11e8-99b7-8abd73b28132.png">

OSIO
<img width="728" alt="screen shot 2018-03-01 at 6 36 33 pm" src="https://user-images.githubusercontent.com/18057044/36875911-5865caea-1d80-11e8-94c3-5744cadbec1f.png">

**Comment by mcarrano** [comment]
@cshinn FYI. This relates to the Actions pattern you are working on See #508
