### ISSUE TITLE
Unclear guidance on the Notification Drawer Design Tab re: Toast Notification

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#597]
<img width="961" alt="screen shot 2018-03-02 at 11 07 47 am" src="https://user-images.githubusercontent.com/12504403/36908688-fd52f544-1e09-11e8-9fc9-4d3025591e5e.png">

**Comment by mcarrano** [comment]
What exactly do you feel is unclear @serenamarie125 ? Technically toast notifications are not part of the drawer, so maybe the issue is whether we need more guidance around alerts in general?

**Comment by KendraMar** [comment]
Hey, Matt -- Serena can give more detail, but I didn't understand what "the drawer should utilize the current toast notification" means. In what way is it utilizing them? repeating the same text? inserting the visual into the drawer (I know that's not the case, but I couldn't understand the description.)

If I recall what Serena said correctly, I think it means that designers will want to consider whether or not the event/job/error is important enough to be in the drawer and appear as a toast over the top of the drawer. All events/jobs don't require both a drawer entry AND a toast appearing.

**Comment by mcarrano** [comment]
@serenamarie125 @KendraMar I agree that this should be better explained. I will add this to the backlog. @KendraMar is this something that you'd be willing to take on?

**Comment by KendraMar** [comment]
Happy to take it on (will just double check with Serena). Thanks @mcarrano.

**Comment by serenamarie125** [comment]
@mcarrano at this point, there is upcoming product work, and there's not current bandwidth to take on additional PatternFly work this sprint.
