### ISSUE TITLE
Notification Drawer pattern has some inconsistencies

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#598]
[Notification Drawer pattern](http://www.patternfly.org/pattern-library/communication/notification-drawer/) has some inconsistencies

- On Overview tab, the image is missing "Clear All"
- The drawer title should be consistent, suggest that it is "Notifications".  Images in the pattern show "Title of Drawer", "Notifications" and "Notification Drawer" right now

**Comment by zhutaoredhat** [comment]
@mcarrano No problem, I have pulled a new PR to fix them, please have a check~ PR link: :https://github.com/patternfly/patternfly-design/pull/600
