### ISSUE TITLE
Pattern enhancement - Cards with no data available

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-design#604]
The need for a card with no data available came up in the following PR: 
https://github.com/patternfly/patternfly-react/pull/212

For now, we're using the empty state pattern inside the card, with some style changes for the context of the card. See examples pasted below.

A design should address the following use cases:

- A card has no data and the user can add data (i.e. empty state with an action)
- A card has no data and the user cannot add data (i.e. empty state without an action)

![image](https://user-images.githubusercontent.com/21063328/37096774-b91b6a50-21e7-11e8-9f11-5c017bbeec7e.png)

**Comment by mcarrano** [comment]
There is a related issue here: #588

**Comment by mcarrano** [comment]
@jgiardino did you see this pattern? http://www.patternfly.org/pattern-library/cards/base-card/#design

Looks like the No Data Available state is covered, but we still may need to address the first use case.

**Comment by jgiardino** [comment]
Oh. Thanks!

I'll close this issue then and open on in patternfly to have css added, because I couldn't find html/css examples for these patterns.
