### ISSUE TITLE
About Modal should provide guidance on build information

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#606]
This is an enhancement to the existing [About Modal design pattern](http://www.patternfly.org/pattern-library/communication/about-modal/#design)

The call out image should have 6 callouts:
1. Modal
2. Close Button
3. Title ** new
4. Content ** new
5. Trademark & Copyright info ** new
6. Corner Graphic

As an interim design, we are utilizing the following:
When version and build information are both shown:
Version 6.3 (Build 5)
When version only:
Version 6.3
When build only:
Build 5

**Comment by serenamarie125** [comment]
@mcarrano FYI - just spoke about this with a few folks, and added a new issue to capture our current thoughts on an interim solution

**Comment by mcarrano** [comment]
@serenamarie125 I agree that we should be more specific about the content that goes here. I will move this to the backlog as a good small issue for someone to pick up. @LHinson FYI.

**Comment by LHinson** [comment]
make sense. thanks @mcarrano!

**Comment by mcarrano** [comment]
@zhutaoredhat Thanks for taking this issue. Please share a revised mockup so we may review it before making changes to the library.

**Comment by zhutaoredhat** [comment]
Hi @mcarrano I had pulled a PR about this issue. Please help me have a review. Great thanks~ https://github.com/patternfly/patternfly-design/pull/613
