### ISSUE TITLE
Stacked or Accordion Navigation

### ISSUE THREAD

**Issue by deernano** [patternfly/patternfly-design#609]
Catalog pattern:  Display the sub content to avoid users losing focus when reading.

#### 1. Choose the type of contribution for this pattern:
- [X] This is a new pattern 
- [ ] This is an enhancement on an existing pattern

#### 2. If this enhancement or new pattern was made for an application, specify which one.
Patternfly.org, Patternfly showcases

#### 3. Use Cases + Requirements:
- Use Case 1: Documentation
When we design the contribue page for current patternfly website, we find that we do not have an appropriate catalog pattern for better displaying the long content of design contribution. Users will lose their focus when reading the long doc if we place all the content in one page. Currently patternfly only provide two level of navigations. Although we have a tree list widget based on bootstrap, it is not fit enough for the requirement.
So we decided to place every sub content in separte pages. Users can find the sub content title on the left navigation, which is not convinient enough.
<img width="1383" alt="1" src="https://user-images.githubusercontent.com/5396309/37325207-d562f590-26c7-11e8-8f7e-94e28c6a99d4.png">
Also, when there are less content, the page may feel empty.
<img width="1379" alt="2" src="https://user-images.githubusercontent.com/5396309/37325220-e2ae993e-26c7-11e8-97f4-117ad46fe650.png">
If we have a ‘catalog’ pattern as ([bootstrap](https://getbootstrap.com/docs/3.3/javascript/#tooltips)), we can place the relavent sub content in one single page without jumping pages. The reading experience will be more fluently. The content is closely relevant to the navigation. Users only need to scroll down and will not lose their focus. When users scroll down the page, the relevant catalog will be highlighted. If users click the catalog, they will get to the right content as well. 
<img width="1085" alt="3" src="https://user-images.githubusercontent.com/5396309/37325300-4affacd0-26c8-11e8-8f18-38698f797001.png">

- Use Case 2: Patternfly pattern library 
‘Catalog’ pattern can be used in pattern library. For example, in List View overview page, Currently we use links to display the catalog: ‘Jump to Standard Tree List View, Tree List View with Single Child Expansion or Tree List View with Multiple Child Expansion’. If we have a ‘catalog’ pattern, we can use it to display content in a more organized and extensible way.
<img width="801" alt="4" src="https://user-images.githubusercontent.com/5396309/37325326-678136e4-26c8-11e8-952f-76b2d255af12.png">

- Use Case 3: Showcases
‘Catalog’ pattern can be used in showcases. We can add indent and highlight for showcase navigation.
<img width="1420" alt="2018-03-05 5 34 05" src="https://user-images.githubusercontent.com/5396309/37325360-8fc855e2-26c8-11e8-8d80-a00966707b82.png">

#### 4. References 
https://docs.google.com/document/d/1V423n9Y6BGVQ11JoPAIjHjD2ynbEO0AVDNITsUt7V0Y/edit?usp=sharing

**Comment by mcarrano** [comment]
@deernano Thanks for entering this. This is what Boostrap calls ScrollSpy navigation. https://getbootstrap.com/docs/4.0/components/scrollspy/

I think that we already have code for something like this in the website to support the widgets section navigation (http://www.patternfly.org/pattern-library/widgets/). @amarie401 @LHinson can you confirm that? I definitely think this is useful for the website but am less sure if it's something we have a product need for. But I can float this to the Ux Strategists to see if there is interest.

**Comment by deernano** [comment]
@mcarrano Just want to mension:
 When we were doing designs for Keycloak, we found that we would like to have sub nav with indentation as the following pic:
<img width="275" alt="2018-03-05 5 44 24" src="https://user-images.githubusercontent.com/5396309/37385703-27b58790-2790-11e8-9cdc-5a2e8acd99dc.png">
Sometimes we prefer the second level nav to be displayed automatically without flying out another window when:
there are not much content in the second level nav.
second level nav need to be obvious and make sure that users can notice it in the navigation.
demonstrate the information architecture clearly.
find the right information quickly.
Here is another example:
<img width="1381" alt="2018-03-05 5 50 24" src="https://user-images.githubusercontent.com/5396309/37385725-437a27f6-2790-11e8-944a-bb78991e4a24.png">
These kind of navigation has similar UI as catalog, but its part of the navigation. The code might be different. Will we consider to have an extention style of vertical navigation so that we can use these kind of navigation in Keycloak or maybe showcases?

**Comment by LHinson** [comment]
@mcarrano our old site used it but our current site does not.

**Comment by mcarrano** [comment]
@deernano I discussed this with the UX Strategists and we agreed to move forward with a proposal for a stack/accordion style navigation pattern as you referenced in your last comment regarding KeyCloak navigation. Please work on this and post a proposal for review when ready. Some considerations include:
* How to ensure appropriate visual hierarchy between the primary and secondary items.
* When to use this vs. the fly-out vertical navigation.
* How this works in responsive/mobile states.

I have renamed this issue accordingly to Stacked/Accordion Navigation.

**Comment by deernano** [comment]
@mcarrano  sounds great~ I will continue work on this task.

**Comment by deernano** [comment]
@mcarrano Here is the draft design proposal of the stacked / accordion navigation
https://docs.google.com/document/d/1CL6Cl5MH4_rvzqfFUz0KRr9eK0jnUzM6rhVQVTF2kjI/edit?usp=sharing
Please take a look. Thank you:)

**Comment by mcarrano** [comment]
Good start on this @deernano . See my comments/questions.

**Comment by mcarrano** [comment]
Per the UXS-PF review meeting on 4/5, let's put this one on hold. We are concerned about introducing new navigation patterns at this time but can reassess this one we better understand our navigation strategy for PatternFly next.

@deernano thanks for your efforts on this. Your design provides a good basis for this pattern should we decide to move forward in the future.

**Comment by deernano** [comment]
@mcarrano ok, thank you ~
