### ISSUE TITLE
Bootstrap Select width guidance

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-design#614]
Documentation -- I need guidance, and perhaps better documentation, around how we should deal with select boxes that have options longer than the select box itself.

Example below. Note that the third option is currently selected, and the text is truncated in the current selection part (the top, don't know exactly what to call that). [It's not a great example because here we could probably increase the width of those select boxes and it would look fine. Unfortunately on that screen we can't increase those widths because there is content that sometimes appears next to them, in a 4 column design at the top of the dialog.]

Other than increasing width, I can only think of
1. simply truncate
2. add an ellipsis

In either case, could/should a tooltip containing the not-truncated value be added to the select box when a truncated value is selected?

![vm_import](https://user-images.githubusercontent.com/2248293/37401810-beb4f2d8-275f-11e8-8c97-98bb4776e495.png)

**Comment by mcarrano** [comment]
@gregsheremeta I discussed with the UX Strategists and the consensus seemed to be that truncation should be applied whenever a label is too long to fit it's container. Pls see the truncation rules here: http://www.patternfly.org/styles/terminology-and-wording/  Do you feel this will resolve the issue?

**Comment by gregsheremeta** [comment]
Yes, thanks!
