### ISSUE TITLE
Add "create card" to Card View

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#623]
Want to update the [Card View](http://www.patternfly.org/pattern-library/content-views/card-view/) pattern to include a Create/Empty card that can fall at the end of a list of cards. This card should include an Add/Create button and appropriate messaging that will allow users to launch an action to create new objects that will add to the view.

Ref https://github.com/patternfly/patternfly-design/issues/619 for further details

**Comment by mcarrano** [comment]
@sjcox-rh This is a new issue created out of today's UXS-PF to cover the iPaaS use case you raised for card empty states. We were hoping you can help out here with a design contribution. @catrobson will follow up with more details.

**Comment by sjcox-rh** [comment]
@mcarrano Sounds good, thanks for creating this! I'll be on the lookout for deets from @catrobson

**Comment by catrobson** [comment]
@sjcox-rh basically the card pattern you were proposing for card views when you want to show an "empty card" to add another card to the view should go against this issue.  Can you start by creating a document that captures your PatternFly proposal that we can share across strategists to see if there are any other products doing something similar?

**Comment by sjcox-rh** [comment]
@catrobson Sure thing, I'll try and finish that up today.

**Comment by sjcox-rh** [comment]
@mcarrano @catrobson @serenamarie125 @jeperry @maryclarke @LHinson 

Please review the design document for a potential new update to the card view pattern. This doc goes over the requirements/uses/considerations of a Create/Empty State card.

https://docs.google.com/document/d/1K0CJWuYoUxOe2H-pzkQSPLACEEc9oEnDUvK3ZOIjaDI/edit?usp=sharing

Thanks!
