### ISSUE TITLE
Provide guidance on using "Select" in Terminology & Wording

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#626]
Enhancement to [Terminology & Wording](http://www.patternfly.org/styles/terminology-and-wording/)

Let's add some general guidance for wording in the UI when prompting the user to choose/select from a list ?  It sounds like "select" is the correct verb to use:

- Microsoft Manual of Style prefers "select" 
- [IBM's editorial style guide](https://www.ibm.com/developerworks/library/styleguidelines/) -- states "don't use choose for actions on interface elements ... use Select"

Both SJ Clark & Stacy McAuliffe were included in discussion re: the above

**Comment by yih-wang** [comment]
@mcarrano I'll take this issue. How about insert a row into [the "Terminology and Wording for Action Labels" table](http://www.patternfly.org/styles/terminology-and-wording/#common-terms-and-words). 


Label | Action | Complement | Notes
-- | -- | -- | --
Select | Select an item from a list, group, view, or other container element. |   | “Choose” is not recommended for this use case.

**Comment by mcarrano** [comment]
@yih-wang I don't think this belongs in the Actions table since it is more like instructional text usage. Maybe just add to "Common Words and Terms?" @LHinson what do you think?
