### ISSUE TITLE
About Modal: add description section

### ISSUE THREAD

**Issue by akieling** [patternfly/patternfly-design#627]
A good enhancement to the About modal would be the addition of a description section under the title and above the label/value items.

**Comment by catrobson** [comment]
Hi @akieling!  Thanks for submitting a PatternFly design issue for this.  I don't think we would want to have a description of the product in the About Modal for any of our product situations.  Here's why:

* The description that marketing and others use for our product do evolve and change over time.  This is an occurrence that is likely to get out of date with those.
* Usually the purpose of the about modal is to help users understand version numbers if they are working with the Red Hat support team.  The user should understand what the product is and what it does for them way before they would ever see this Modal.  If you need a way to describe your product to users, consider using the PatternFly [Tour Pattern](http://www.patternfly.org/pattern-library/communication/tour/).

**Comment by akieling** [comment]
HI @catrobson . Thanks for the explanation.
