### ISSUE TITLE
pficon-service is missing from website

### ISSUE THREAD

**Issue by abonas** [patternfly/patternfly-design#628]
The icon for service that is used in openshift, manageiq, kiali, etc is missing from patternfly website.
Not sure what is the reason for that, it used to be there for sure.
Any dev going to explore the icons available from pf will not know about it if it's missing

This is the icon:
![serviceicon](https://user-images.githubusercontent.com/6277245/38048665-a6417a58-32ce-11e8-98a3-0cf961af69ff.png)
.

**Comment by mcarrano** [comment]
@jennyhaines can we add this one back and in the description note that it is specifically for a Kubernetes service? Thx.

**Comment by abonas** [comment]
:cake:
