### ISSUE TITLE
Add Confirmation Dialog pattern

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#632]
Add a standard pattern for confirmation dialogs. This can include a generic confirmation dialog together with specific instances (i.e. delete confirmation) as part of one pattern.

Requirements:
* Address use of alert types
* Address standards/guideline for writing confirmation messages.
* Address standard buttons and button placement.

Prior work was done here: https://www.dropbox.com/s/ix1zl4hpwl3qb07/MessageDialog-PatternProposal.pdf?dl=0

**Comment by deernano** [comment]
@mcarrano The prior work link can not be opened. Can I have a update link?

**Comment by mcarrano** [comment]
@deernano I'm attaching acopy here.

[MessageDialog-PatternProposal.pdf](https://github.com/patternfly/patternfly-design/files/1894612/MessageDialog-PatternProposal.pdf)

**Comment by mcarrano** [comment]
Per UXS-PF meeting on 4/12 - Please move forward with this @deernano .  There is another issue specifically for Delete Confirmation which you should also address as part of this work. That's #322 . The new pattern should:

1- Provide a standard template for modal confirmation dialogs.
2- Call out specific instances for common use cases requiring confirmation like Delete (and others?).
3- Provide some guidance on writing confirmation message text and labeling buttons.

Next steps should be to create a proposal in the form of a Google Doc that addresses these issues for initial review with @serenamarie125 and I. Let me know if you have questions. Thanks for volunteering to take this on!

**Comment by deernano** [comment]
@mcarrano @serenamarie125  Ok I get it, keep working, thank you~

**Comment by deernano** [comment]
A reference doc from #322 https://docs.google.com/document/d/1UvnNPrl35osBHR0mr7ACZXhr9qN6nZ2IxI2HEgtnwwE/

**Comment by deernano** [comment]
@mcarrano @serenamarie125 
https://docs.google.com/document/d/1SSv4YPU1b2qlLGJSBnLxsI2BboFdJlWySqIwA0T7nfE/edit?usp=sharing
Here is the draft confirmation dialog design and pattern description. It may not be the same as our current pattern design description, as I'm trying to include all the use cases. Please help to review it and leave comments for further refinement. Thank you!

**Comment by serenamarie125** [comment]
@deernano you've done a great job here!  I'm adding comments to the doc, but in general, I'm wondering if we have the pattern be "Message Dialog", and then have an example of each type below.  For example, a Delete Confirmation Dialog, etc.

@mcarrano fyi

**Comment by deernano** [comment]
@mcarrano @serenamarie125  Thank you for the comments:) 
The doc has been updated, please take another look.
https://docs.google.com/document/d/1SSv4YPU1b2qlLGJSBnLxsI2BboFdJlWySqIwA0T7nfE/edit?usp=sharing

**Comment by mcarrano** [comment]
This is looking good @deernano . Agree with changing this to Message Dialog to me more general and like the suggestion about including examples of some specific dialogs to address common use cases like Delete.

@serenamarie125 can you think of other common dialogs we need besides delete? Maybe a situation where the user makes some changes on an item and then tries to navigate away?

**Comment by deernano** [comment]
@mcarrano @serenamarie125  
I added a title for each use case
Warning Confirmation:
Acknowledgement Confirmation:
Complete Confirmation:
Error Confirmation:
Maybe we should add another example in warning confiratmation other than delete?
There is a use case in Keycloak. Keycloak request access privileges to user's account, it will show a list of consents in the dialog:
https://redhat.invisionapp.com/share/2RGJZNJUBSZ#/289976989_v1-4-falt-category
I think this belongs to acknowledgement confirmation.

**Comment by mcarrano** [comment]
I'm wondering whether we should include any guidance on writing messages or text for standard messages that go with some of these use cases. We might even want to create templates for these standard dialogs. @serenamarie125 what do you think? I could request some help with crafting the message content.

**Comment by stacymcauliffe** [comment]
@mcarrano - I put together an outline that includes most of the content from @deernano and added in additional message dialog types - error and passive. I had to reorganize some of the content to make it work for all of the different dialog types.

Let me know what you guys think. We could probably include more prescriptive content guidelines for each dialog, but I'd like to hear your feedback on this approach before I go any further. 

https://docs.google.com/document/d/1mw2zdbkdgIXxpvS2oY5JfsD9j3dLTnmC8769pdKg3e0/edit?usp=sharing

Thanks!

**Comment by mcarrano** [comment]
@stacymcauliffe Thanks for putting this together. I like the direction. My only question is how we should organize this in the context of our current design documentation. I am going to schedule a meeting for you, @deernano , and myself to review and talk about next steps.

**Comment by stacymcauliffe** [comment]
Thanks @mcarrano! I'm happy to meet earlier if it works better for @deernano

**Comment by deernano** [comment]
@mcarrano @stacymcauliffe  ok~

**Comment by deernano** [comment]
@mcarrano @stacymcauliffe  I think the overall content is accurate and clear now. We could just add some button description for users to know how to use the correct button. As we can see from https://github.com/patternfly/patternfly/issues/1038#issuecomment-392787000, it may not easy for developers to understand the design doc.
Thus, we can introduce the dialog usage, the style, the button& icon usage in Overview page, and decribe the 3 different msg dialog details in design deciption. Mark the most differences between each dialog and add some real examples to help them understand. What do you think?

**Comment by mcarrano** [comment]
On 6/1 @deernano @serenamarie125 @stacymcauliffe @jennyhaines @michaelkro met to sync with React repo team. Some relevant take aways for design:

- Message dialogs should be build on top of a standard PatternFly modal. That means they will always have a title and a close button in the header.

- They many just include a simple message (i.e. just a block of text) or a complex message that includes a Primary Message (short) and a Secondary Message (detailed). Michael will implement this to allow for both possibilities. Stacy will consider guidelines for usage and examples of when you might need to use the more complex format. As always, simpler is better, so we should make a point that a simple primary message should be the default unless sharing a lot of detail is needed for making a good decision.

- Jenny will rework the visual design to consider the alignment of the icon given that the Primary (short) message is optional and also consider a minimum height for the dialog.

- We need to consider types of dialogs we need to support and include those in the implementation examples so the design doc and examples align. Stacy will follow up.
Something we did not get to was the use of Yes/No dialogs. Melody, while your original recommendation was not to use these, I think we may need them in limited cases as we saw with the inline edit example (i.e. "Are you sure you want to exit without saving your changes?"). But agree we should only use these when there is no positive affirmative action.

**Comment by jennyhaines** [comment]
@mcarrano @stacymcauliffe 

The minimum total height that a modal should ever be is 150px. (40px title bar+20px spacing+9px minimum text+40px spacing+26px buttons+15px spacing=150px) I don't even know that this needs to be specified in the code, though, as long as there is always exactly 40px of space between the secondary message text and the buttons. (See "Minimum Height Dialog" mockup below for example of the shortest possible modal.) Any modal status icon should be 20 px below the header bar, just as the text is.

![modal_designs](https://user-images.githubusercontent.com/24898297/41259517-e5be341a-6da1-11e8-9ac2-6ecf57b04560.png)

*You'll notice in these examples that I've included both instances in which we will have/not have the primary message text displayed in the modal window. We had discussed, for example, that this primary message text may be necessary/recommended for error dialogs.

**Comment by mcarrano** [comment]
Thanks @jennyhaines 

@deernano perhaps we should include the basic template with pixel spacing on the Design page?

**Comment by deernano** [comment]
@mcarrano Yes, I agree.

**Comment by deernano** [comment]
@mcarrano @stacymcauliffe 
Updated the PR, please help to review it.
Thank you ~
https://github.com/patternfly/patternfly-design/pull/686

**Comment by mcarrano** [comment]
This work is complete and the new pattern can be found here. https://www.patternfly.org/pattern-library/communication/message-dialog/ Will close.
