### ISSUE TITLE
Appearance of expanded row in list view differs between design and implementation

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#633]
There is currently a difference between the design and implementation of an expanded row in List view.

Design specifies that row should be light gray when expanded (http://www.patternfly.org/pattern-library/content-views/list-view/#design). Core implementation shows expanded row as light blue (http://www.patternfly.org/pattern-library/content-views/list-view/#code).

This is further complicated by changes made recently to change hover color from gray to light blue and the interaction of hover and selection. What is the expected result is a row is both open and selected? Need to consider how all of these states work together: hover, selection, and open.

**Comment by mcarrano** [comment]
@kybaker @jennyhaines Just a heads up on this one. I will try to set up a meeting with the three of us and @matthewcarleton to discuss. I think this is more complicated than just changing the Core implementation to reflect the design since this the gray may not play well with what is now a blue hover and selection state.

**Comment by jennyhaines** [comment]
@kybaker , @mcarrano , @matthewcarleton , and I just met about this, and the consensus was to have the [previously determined](https://github.com/patternfly/patternfly-design/issues/314#issuecomment-338284058) #edf8ff blue be the color we use for the list view row color for both hover and selected states. (No grey used whatsoever for list view rows.)

**Comment by mcarrano** [comment]
Just to clarify @jennyhaines . I think that when you say selected state you mean expanded/open, right? According to my notes, we will remove the blue background color for selected rows and use only the checkbox to signify selection. So the target will be equivalent to the current React implementation here: https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=ListView&selectedStory=List%20of%20expandable%20items

Do we all agree with that?

**Comment by jennyhaines** [comment]
@mcarrano - yes, correct! I just edited my above comment so there is no confusion. It should be equivalent to the link you provided (except the "fa-angle-down" caret should continue to stay that default dark gray/black color)

**Comment by mcarrano** [comment]
Thanks, @jennyhaines . Also, would you be able to update the mockups on the Overview and Design pages in the pattern doc here to reflect that? http://www.patternfly.org/pattern-library/content-views/list-view/  ?  @matthewcarleton I will open a separate issue in the core repo for updating the CSS.

**Comment by jennyhaines** [comment]
@mcarrano - yes- working on that now!
