### ISSUE TITLE
Update contributing.md file with new text

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#634]
Want to update https://github.com/patternfly/patternfly-design/blob/master/.github/CONTRIBUTING.md to be the primary point of reference for design contributors. Proposed changes:

Some preliminary work will happen up front from Matt Carrano and Leslie Hinson including:

* Review document and identify what needs to be included in the contributing.md (will also loop in Stacy for edit review) https://docs.google.com/document/d/1esLbHNEhOah5iYNgGi86kFSgCRijcXEgiQhyQs1TQZA/edit?usp=sharing
* Note that instructions on "How to Contribute" using SourceTree and GitHub can remain in place, but may be updated to improve or clarify how to contribute changes.

The action items for this story include:

* Consolidate wiki and contributing.md
* Identify stories to update Community page on the website to point to this as the primary source of information about making design contributions.
* Point to this page (rather than the Wiki) for contribution instructions from patternfly.org as well as on the readme on patternfly-design repo.

**Comment by mcarrano** [comment]
@LHinson I created an issue to track this work. Just let me know when you have added "How to become a maintainer" and I will bundle this into a PR.

**Comment by LHinson** [comment]
Thanks @mcarrano. It's added now!
