### ISSUE TITLE
Existing PatternFly Color Swatches is unfriendly to Color-Blind Users

### ISSUE THREAD

**Issue by yih-wang** [patternfly/patternfly-design#638]
I was asked to help a local team today to improve the color accessibility for red/green colorblind users. When I view PatternFly labels like the color blind, I found our Red and Green colors are difficult to distinguish. (See the image below)
![slice](https://user-images.githubusercontent.com/23331885/38543689-d3123410-3cd7-11e8-8751-399fb8785dd6.png)

I just read [a blog from Tableau](https://www.tableau.com/about/blog/2016/7/colors-upgrade-tableau-10-56782), talking about their color palettes design. So I try to view their color swatches like the color blind as well, and it's easier to distinguish between red and green.
![slice 2](https://user-images.githubusercontent.com/23331885/38544215-6abdea38-3cd9-11e8-8504-27b6b2c63171.png)

As we are researching a11y, I think we could make some improvements to this issue. So submit this for more conversations.

**Comment by mcarrano** [comment]
@yih-wang Thanks for raising this issue. You are correct that we do not provide much existing design guidance here for PatternFly. In practice, I would advise that color should never be used alone to communicate severity level of a warning, but there should always be some type of redundant coding - an icon, for example along with the color.

I'm copying in @kybaker and @jgiardino in case they would like to comment further. For PatternFly Next, I'd like to offer more design guidance in this area. But I don't expect we will be adding further documentation about this to the current website.

If you have specific designs you want to have reviewed, I'd recommend getting the visual design team involved.

**Comment by yih-wang** [comment]
@mcarrano I agree that it's enough for the current website. It will be nice if we could consider this area for PatternFly Next.
