### ISSUE TITLE
Sort icon and guidance on Toolbar design page are inconsistent 

### ISSUE THREAD

**Issue by nding-anges** [patternfly/patternfly-design#642]
## Bug Contributions: 
- Currently, the sort icon displayed and guidance are inconsistent on " Form and control"- Toolbar, design page 
- Sort image need to be changed.
-see more detail here:http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#design

![issue of toolbar](https://user-images.githubusercontent.com/34368385/38663300-0a8b1c80-3e69-11e8-9153-757284448d87.png)

**Comment by mcarrano** [comment]
@nding-anges Thanks for raising this issue. If you want to send a PR for this, I will review and merge.
