### ISSUE TITLE
Review/Update Contributor's Guide on Design Wiki

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#645]
Review and update the Contributor's Guide text here: https://github.com/patternfly/patternfly-design/wiki  in order to bring detailed contribution instructions up to date and position this as one-stop shopping for on-boarding new designers. 

* Integrate useful content from https://docs.google.com/document/d/1esLbHNEhOah5iYNgGi86kFSgCRijcXEgiQhyQs1TQZA/edit?usp=sharing 

*Reference use of the new PatternFly Design Kit as a tool for creating hi-fidelity mockups when creating new patterns.

**Comment by mcarrano** [comment]
@LHinson I have made some updates to the Wiki in the Design repo when the detailed contribution instructions live.  https://github.com/patternfly/patternfly-design/wiki What's changed?

* Removed any redundant text about contributions that is already present on Contributing.md page. 
* Added a new Understanding GitHub Concepts page and diagram.
* Highlighted the importance of branching for working with multiple features.

Please take a look when you have a chance and let me know if this makes sense or if there are any additional changes we should make. Hopefully this provides a coherent story starting from https://github.com/patternfly/patternfly-design/blob/master/CONTRIBUTING.md

**Comment by LHinson** [comment]
Hey Matt, this looks good. I went back through and did the following: 

- Removed some redundancy at the beginning
- Remove unnecessary sentences (for example, I didn't think it necessary to state "You don't need to have years of expertise to make a contribution, just a desire to learn about design and become part of a community of designers and developers working to create a better experience for enterprise users."  
- The [Common Terminology](https://github.com/patternfly/patternfly-design/wiki/Terminology ) guide does not exist. How are they supposed to "Start by familiarizing yourself with some basic GitHub concepts and terminology by checking out." 
- Question, shouldn't we link to the contributing.md? 

You can compare the revisions here: https://github.com/patternfly/patternfly-design/wiki/Home/_compare/266b542a8178ed555ac33b4402530db4f7a880d9...0db36c1606d8f901e6afbf48f4ce2d361a3aa5e2

**Comment by mcarrano** [comment]
Thanks for your comments @LHinson. Agree that the revised copy reads better and removes lots of redundant text left from earlier revisions. I made a few small updates here: https://github.com/patternfly/patternfly-design/wiki  I think we are in good shape to close this out.
