### ISSUE TITLE
Update patternfly library screenshots with latest pattern for required field labeling.

### ISSUE THREAD

**Issue by nlcwong** [patternfly/patternfly-design#647]
This issue deals with documentation inconsistencies due to the recent update of the required field labels pattern.  The following patternfly library pages contain screenshots that shows an outdated pattern for required field labels.  Either the required symbol is located in the wrong location (left of label), or it is not the correct color (red), or both and also in the case of top-aligned labels, the symbol is not positioned outside of the form's margin.

[Communication > Wizard > #overview](http://www.patternfly.org/pattern-library/communication/wizard/#overview)

![screen shot 2018-04-18 at 2 58 36 pm](https://user-images.githubusercontent.com/31672086/38952454-bc1bf078-4319-11e8-8f34-a272836a07e9.png)

[Communication > Wizard > #design ](http://www.patternfly.org/pattern-library/communication/wizard/#design)

![screen shot 2018-04-18 at 2 58 53 pm](https://user-images.githubusercontent.com/31672086/38952460-c200b500-4319-11e8-91ea-a90cd0a907f8.png)

![screen shot 2018-04-18 at 2 59 52 pm](https://user-images.githubusercontent.com/31672086/38952552-1721a2ec-431a-11e8-829a-7ba6b85c84d3.png)

![screen shot 2018-04-18 at 3 00 19 pm](https://user-images.githubusercontent.com/31672086/38952564-2010ced2-431a-11e8-83cb-9063a0166637.png)

![screen shot 2018-04-18 at 3 00 31 pm](https://user-images.githubusercontent.com/31672086/38952572-244e1626-431a-11e8-8b47-c04928ee604a.png)

[Content Views > Canvas View > #overview](http://www.patternfly.org/pattern-library/content-views/canvas-view/#overview)

![screen shot 2018-04-18 at 3 00 47 pm](https://user-images.githubusercontent.com/31672086/38952582-2e76763e-431a-11e8-8100-a7886c199945.png)

[Forms and Controls > Modal Overlay > #overview](http://www.patternfly.org/pattern-library/forms-and-controls/modal-overlay/#overview)

![screen shot 2018-04-18 at 3 01 10 pm](https://user-images.githubusercontent.com/31672086/38952591-379d60a6-431a-11e8-8b01-82ec1ed6184d.png)

[Forms and Controls > Modal Overlay > #design ](http://www.patternfly.org/pattern-library/forms-and-controls/modal-overlay/#design)

![screen shot 2018-04-18 at 3 01 22 pm](https://user-images.githubusercontent.com/31672086/38952615-481a5a06-431a-11e8-9c7d-b4928da6c8b3.png)

![screen shot 2018-04-18 at 3 01 29 pm](https://user-images.githubusercontent.com/31672086/38952618-4b7b9c64-431a-11e8-96a6-d72fde143b0b.png)

**Comment by deernano** [comment]
@nlcwong @mcarrano 
Please help to review the updated images. Thank you!
https://github.com/patternfly/patternfly-design/pull/657
