### ISSUE TITLE
Determine whether Table View should be included in View Selector

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-design#658]
View Selector does not include Table View. Is Table View a common view? How do you switch in and out of table view if it is used together with a list or card? Do we have that use case in the product? How was it handled?

issue came from #656

**Comment by mcarrano** [comment]
@serenamarie125 @LHinson  would be interested in your thoughts about this. During the course of making View Selector updates, we realized that none of your Table View designs actually include a View Selector. See @terezanovotna 's questions. Wondering if this needs to be added to the Table View examples here: http://www.patternfly.org/pattern-library/content-views/table-view/#overview
