### ISSUE TITLE
Visuals for Bullet Charts have changed

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#662]
While implementing the [Bullet Chart](http://www.patternfly.org/pattern-library/data-visualization/bullet-chart/) pattern, additional work was done with the visual designers which needs to be incorporate back into the design documentation

cc @mcarrano @jennyhaines

**Comment by mcarrano** [comment]
@serenamarie125 Are those visuals available somewhere? Is this just a matter of replacing existing mockups or do new mockups need to be created?

**Comment by serenamarie125** [comment]
@mcarrano plan is to have the PR up by Tuesday 5/29 morning at the latest. I've got a few things queued up for @jennyhaines to help me on.  I think there may be some text changes as well
