### ISSUE TITLE
Consider interaction between Notification Drawer and other masthead menus

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#663]
In testing some recent changes to the masthead utility items (see https://github.com/patternfly/patternfly/pull/1055) I noticed that when the Notification Drawer was opened, it remained open when other items, i.e., the Help or User menu, were clicked such that both menus were opened at the same time and overlap. See attached screenshot.

![screen shot 2018-05-18 at 10 47 37 am](https://user-images.githubusercontent.com/6619860/40255890-ac70de40-5ab6-11e8-943f-9bba150076e9.png)

I found this behavior unexpected as it seems like there should never be more than one utility item open at a time.

**Comment by serenamarie125** [comment]
> I found this behavior unexpected as it seems like there should never be more than one utility item open at a time.

IMO ... there should never be more than one utility menu open at a time.  The notification drawer is something totally different to me.  @mcarrano, if the notification drawer is open, you should still be able to access the help menu items.  For example, you may want to pull up documentation to look up notification text.

The error to me seems to be that there is some kind of selection state on the notification drawer at the same time as the hover state of the help menu.

**Comment by mcarrano** [comment]
@serenamarie125 Given your comments, I will close this out. It struck me as odd that it worked this way, but I do see your argument. And since it's already implemented this way, I feel no need to change it. The selection state is the result of the last PR we processed which addressed the inconsistency in behavior of masthead items.

**Comment by jeff-phillips-18** [comment]
@mcarrano The selection state on the notification toggle seems to be something new. It is not applied in angular-patternfly, patternfly-ng, or patternfly-react.

**Comment by mcarrano** [comment]
Yes, this is a recent design change @jeff-phillips-18 that was made so that all masthead items would behave consistently. It is a result of https://github.com/patternfly/patternfly/pull/1055.
