### ISSUE TITLE
Error Message for Radio Buttons

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-design#665]
There is no documentation on Error State of [Radio Button in PatternFly. ](https://www.patternfly.org/pattern-library/forms-and-controls/data-input/)

![data-input-radio-buttons 1](https://user-images.githubusercontent.com/36040135/40298026-f2fe3312-5ce1-11e8-80e0-9e43a472c014.png)

Here is a suggestion how that could be implemented, and it would be great to see it in PF as an example.
![data-input-radio-buttons](https://user-images.githubusercontent.com/36040135/40298100-31409ca0-5ce2-11e8-94b0-4ed542aa0954.png)

**Comment by mcarrano** [comment]
Yes, I agree with you @serenamarie125 . There should always be one radio button selected in a group. The user should not be able to deselect an option by clicking on it like a checkbox. That's the definition of a radio button group. It's a way to select between two or more mutually exclusive options.

**Comment by terezanovotna** [comment]
I was asked this question by UI devs, and they had this use case when no default selection and asked for help how to show that. @serenamarie125 @mcarrano I agree it should have a default state. I just asked for an example in a UI and we can't find it now. So we can close this issue. Thanks for your help!

**Comment by mcarrano** [comment]
OK. I will close it then. If this comes up again and we need to reconsider, you can always reopen @terezanovotna .
