### ISSUE TITLE
Update App Launcher design pages to reflect Masthead updates

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#668]
The [Launcher pattern](http://www.patternfly.org/pattern-library/application-framework/launcher/) design pages are now out of date following the updates to the [Masthead](http://www.patternfly.org/pattern-library/application-framework/masthead/).  Note that the Launcher menu, when open, should no longer use the infotip style and the Help icon should no longer have the down arrow. The Application Launcher core code example has been updated and has the correct design. You can reference that here: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/application-launcher.html

**Comment by mcarrano** [comment]
@junezhang @deernano @zhutaoredhat This is a small issue that came up this week and I wonder if it's something one of you can take? It just requires an update to the mockups, I think. Thanks in advance.

**Comment by deernano** [comment]
@mcarrano Updated the images
Please take a look, if no problems, I will make a PR, Thank you.
![launcher1 2x](https://user-images.githubusercontent.com/5396309/40602626-e4baa3bc-628b-11e8-92d9-d7fa9b456f1c.png)
![launcher2 2x](https://user-images.githubusercontent.com/5396309/40602629-e8288c30-628b-11e8-8ac9-8c6b2270e4b9.png)
![launcher3 2x](https://user-images.githubusercontent.com/5396309/40602632-e98d7176-628b-11e8-9fb2-71bf2e3395e0.png)

**Comment by mcarrano** [comment]
@deernano Just two comments...

First, the image for the Overview page seems off. There is a gap between the menu and the masthead bar. The Design page images are correct.

You raise a good question about the tooltip. Let's change the design document to say that the tooltip is optional and should only be used if more information is needed about the app that will be launched. In most cases I don't think they are needed. Do you agree?

**Comment by serenamarie125** [comment]
@mcarrano i agree that the tooltip should be optional

**Comment by deernano** [comment]
@mcarrano @serenamarie125 I agree.
Updated as following, only remain one tooltip in design description:
![launcher1 2x](https://user-images.githubusercontent.com/5396309/40706643-121ecb76-6421-11e8-8b2d-2ccf0555e0a2.png)
![launcher2 2x](https://user-images.githubusercontent.com/5396309/40706653-173c651e-6421-11e8-9e4d-4db0ebaee3db.png)
![launcher3 2x](https://user-images.githubusercontent.com/5396309/40706654-193038fa-6421-11e8-9566-05da54ac7b0c.png)

**Comment by deernano** [comment]
@mcarrano https://github.com/patternfly/patternfly-design/pull/673
Updated to pf-design, please review it. Thank you.
