### ISSUE TITLE
Suspend x Resume - Terminology and Wording

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-design#670]
In MIQ, Compute - Containers - Providers, we have a new functionality about Suspending and Resuming a Provider. @romanblanco is asking for help.

![image](https://user-images.githubusercontent.com/36040135/40657666-f56dd69e-6348-11e8-99b3-fdf6bbfefac6.png)

What wording is better?
**a. Pause - Resume
b. Suspend - Resume**

What icons should we used for these?
@jeperry @serenamarie125 Thanks for the guidance!

**Comment by terezanovotna** [comment]
Pause and Suspend explained here https://wiki.openstack.org/wiki/Kvm-Pause-Suspend

**Comment by romanblanco** [comment]
related to BZ https://bugzilla.redhat.com/show_bug.cgi?id=1455145#c12

**Comment by serenamarie125** [comment]
I'm wondering if Suspend = Pause
and Resume = Play 

@jennyhaines can you take a look at this ? I don't see those 2 icons in the PF Icons setup anymore.  Would you agree that these are correct suggestions, and do you know the icons?

**Comment by terezanovotna** [comment]
I like the Pause and Play concept @serenamarie125

**Comment by slemrmartin** [comment]
@terezanovotna can be closed? (can you?)

**Comment by terezanovotna** [comment]
close #670
