### ISSUE TITLE
Select Multi Group - Form

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-design#679]
This is a component that was originally created for miq ui classic, and it would be great if we could contribute this pattern to PF as well. 

<img width="784" alt="screen shot 2018-06-12 at 13 45 59" src="https://user-images.githubusercontent.com/36040135/41288594-27765f72-6e47-11e8-80f1-a5e1900adaf2.png">
<img width="787" alt="screen shot 2018-06-12 at 13 46 08" src="https://user-images.githubusercontent.com/36040135/41288595-2b604206-6e47-11e8-903b-1d9b6d32b6d9.png">
<img width="770" alt="screen shot 2018-06-12 at 13 46 24" src="https://user-images.githubusercontent.com/36040135/41288598-2e8ad180-6e47-11e8-9798-5981a816ea79.png">

[Storybook link
](https://5b1f8eacc9659226588a0774--confident-banach-ee0a7a.netlify.com/?selectedKind=Rbac%20forms&selectedStory=Rbac%20add%20user%20form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) by @Hyperkid123

I've done my UX review, could we get PF review?
Should we move it to [react mono repo right here?](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Show%20Help=true&selectedKind=patternfly-react%2FForms%20and%20Controls%2FForms&selectedStory=Supported%20Controls&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

In terms of PF, I think it could go to the Forms area. Would that be a good area @mcarrano? If so, I will create overview and design proposal.

**Comment by terezanovotna** [comment]
chatted with @serenamarie125 and it looks like there [is already an implementation](https://github.com/patternfly/patternfly-react/pull/374) that has just few differences with this one:

- different chip color
- alphabetical order

**Comment by terezanovotna** [comment]
@mcarrano I am not really sure what to do here. Do we want to add this design to PF (as it's really similar to labeling)? or we don't want to have it?

**Comment by serenamarie125** [comment]
@terezanovotna I think we need to understand the use cases of this component.  Can you elaborate on those?

**Comment by mcarrano** [comment]
@terezanovotna Agree that it would be helpful to understand use cases. My first take is that this is pretty similar to the Auto-Complete/Type-Ahead control that we are already adding. Would that serve your needs or perhaps we can consider your use cases as part of that contribution? I don't really want to have two separate components that do almost the same thing.

**Comment by serenamarie125** [comment]
@Hyperkid123 I spoke with Ron ( that PR contributor ) and he said that you can override the visual representation of the chip, so I think you should be able to utilize what he's contributing.

From what i understand, the use case for ManageIQ is that they are selecting tags, which have a unique visualization, thus they want them displayed differently.  To me, that's just a variation of what's been contributed.

**Comment by Hyperkid123** [comment]
@serenamarie125 yes i am ok with using your implementation, we just needed it a bit sooner and if we can customize the visuals, there should ne no problem using it when its finished.

But i was wrong about saying it may be exactly the same. After i've checked the code i think that the type ahead is a bit different from implementation stand point. Specifically the options data structure. We need array of objects, each having some value and label properties, not just array of strings or numbers.
