### ISSUE TITLE
Add/Modify Tag & Assigned Tags

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-design#680]
**Background:**
This component was created for MIQ and will be available in miq ui classic. Compute - Infrastructure - Hosts/Nodes. Policy - Edit Tags. 

**Original solution for tagging.** 
<img width="1198" alt="screen shot 2018-06-13 at 13 55 54" src="https://user-images.githubusercontent.com/36040135/41349916-abdcb8cc-6f11-11e8-9833-5b7d921c6af0.png">
<img width="1197" alt="screen shot 2018-06-13 at 13 56 05" src="https://user-images.githubusercontent.com/36040135/41349919-ad592474-6f11-11e8-8760-103f58e47976.png">
<img width="1194" alt="screen shot 2018-06-13 at 13 56 16" src="https://user-images.githubusercontent.com/36040135/41349921-af26935e-6f11-11e8-9d2a-273d04082a2e.png">
<img width="1197" alt="screen shot 2018-06-13 at 13 56 24" src="https://user-images.githubusercontent.com/36040135/41349928-b1d5c75a-6f11-11e8-841b-20b6832a4dce.png">

**New Component.**
The component has two parts:

1. add/modify tag
2. assigned tags

This pattern meets PatternFly design standard, and it would be great if we could contribute it to either react mono repo and pf core. We realize that this pattern is consisted of two parts and only together they make one functional piece. We know that only second part (assigned tags) can be generalized and then added as a component. 

[Storybook](https://panspagetka.github.io/patternfly-react/?selectedKind=%40patternfly%2Freact-tagging%2FTagging&selectedStory=TaggingStoryComponent&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

<img width="659" alt="screen shot 2018-06-13 at 13 20 59" src="https://user-images.githubusercontent.com/36040135/41348923-7eeed1c2-6f0e-11e8-8fa4-8db080cabf38.png">
<img width="662" alt="screen shot 2018-06-13 at 13 21 15" src="https://user-images.githubusercontent.com/36040135/41348928-82ce74d2-6f0e-11e8-9cd6-635cd768591b.png">
<img width="657" alt="screen shot 2018-06-13 at 13 21 24" src="https://user-images.githubusercontent.com/36040135/41348931-85e60540-6f0e-11e8-98c2-7b5a7be426c9.png">
<img width="850" alt="screen shot 2018-06-13 at 13 21 32" src="https://user-images.githubusercontent.com/36040135/41348935-88ab5ef6-6f0e-11e8-987a-65ed7516cff8.png">
<img width="654" alt="screen shot 2018-06-13 at 13 21 42" src="https://user-images.githubusercontent.com/36040135/41348945-90af28c6-6f0e-11e8-98da-26ebcf92d581.png">
<img width="648" alt="screen shot 2018-06-13 at 13 21 50" src="https://user-images.githubusercontent.com/36040135/41348947-928b8d4c-6f0e-11e8-948b-0790274b03f1.png">
<img width="843" alt="screen shot 2018-06-13 at 13 21 55" src="https://user-images.githubusercontent.com/36040135/41348951-9497399c-6f0e-11e8-8a64-9afa67459f55.png">

Thank you for some guidance! @mcarrano

**Comment by mcarrano** [comment]
@terezanovotna I brought this up today at the weekly PF Design leads meeting and there is general agreement that adding a new Tagging pattern would be useful. Is this something you have the bandwidth to work on? It was suggested that we should get input from some other folks to make sure this gets cross-project input. But I wanted to check with you first. If you are to move forward with this, it might make sense to put your proposal in the form of a Google Doc to make it easier for people to comment.

I also want to draw your attention to some earlier work done by Liz Clayton around the same use cases. It was being called Labels at the time. Here's a link: https://docs.google.com/document/d/1QXdmBVJRPlPqYq0dhRE-Yhk9g_vuUwbvverHA-ju79g/edit?usp=sharing  Would be interested in how similar this is to your proposal. Perhaps there is some reuse opportunity.

Let me know what you think and glad to do a BJ call if you want to discuss further.

**Comment by terezanovotna** [comment]
@mcarrano Thank you so much for bringing this up:)

@serenamarie125 @jeperry @nlcwong @KendraMar did quite a research on unified tagging experience across RH Management products. [Here is a doc about it,](https://docs.google.com/presentation/d/1CblISYqdZ0EBPDxa8HD7EP5aqG5O4mv9Vf0TzxqTsDM/edit?usp=sharing) slide 3 includes even more links. 

I'll be adding shared Google doc soon.

**Comment by terezanovotna** [comment]
@mcarrano and I discussed the tagging component and [here is a design proposal](https://docs.google.com/document/d/19Vu9Q_lfCQDkwO3LQuwsImSH0rH9i0o9AF24Uer6WqA/edit?usp=sharing)

Feel free to comment!

**Comment by terezanovotna** [comment]
Tagging people for visibility @nlcwong @KendraMar @jeperry @kybaker @Rohoover @lclay2

**Comment by terezanovotna** [comment]
[Updated the doc](https://docs.google.com/document/d/19Vu9Q_lfCQDkwO3LQuwsImSH0rH9i0o9AF24Uer6WqA/edit?usp=sharing). Can you think of more use cases for a compound label?

**Comment by terezanovotna** [comment]
A storybook can be found here.
https://github.com/patternfly/patternfly-react/pull/464

**Comment by mcarrano** [comment]
@terezanovotna Any update on this? I believe that the next steps we agreed on were to send a PR top add this to Forms and Controls. Is that right?

**Comment by terezanovotna** [comment]
Correct! We had Provider meetup in Brno, and then I was on PTO. Back in the office, it's on my to do list!

**Comment by mcarrano** [comment]
Welcome back @terezanovotna .  Just an FYI that today I met with @jgiardino @kybaker and @jeff-phillips-18 on this topic. We decided to base the core implementation for this on your design as shown above that is being implemented in React. We will retrofit this to of [Filter pattern](https://www.patternfly.org/pattern-library/forms-and-controls/filter) which shows a different color treatment. 

Please just be sure to coordinate with @jgiardino who will work on the core CSS for this to make sure your design page is in sync. Let me know if you have any questions.

**Comment by mcarrano** [comment]
@terezanovotna has created a draft proposal that is documented here: https://docs.google.com/document/d/19Vu9Q_lfCQDkwO3LQuwsImSH0rH9i0o9AF24Uer6WqA/edit?usp=sharing  This looks good to me, but @jgiardino can you also review? The only issue I see is that if we also apply this to the Filter pattern, it changes the way we represent a filter chip when there is only a single attribute:value pair. If we change this, does this potentially result in a breaking change?

**Comment by jgiardino** [comment]
After reviewing visual designs for both Filters and Assigned Tags, the main questions I have are how similar do we want these designs? Functionally they're similar, and can be achieved with a single react component, but we can still have different styles applied for the different variations (Filters vs Assigned Tags). Even if we do consolidate on the color palette, there are differences between font styling and spacing. The styles defined currently in pf-react are based on the Assigned Tags visual designs that were provided. To be able to use this same component for Filters, we would need to implement a Filter Chip variation of this component that uses different styles. I'm not opposed to applying the same styles if that's what we want. I'm also not opposed to creating these as separate react components either, if that makes the most sense.

@jeff-phillips-18 Please correct me if I'm way off on this one.

I'm not sure if it was clear during out conversation that we will need to have different styles for each variation anyway. And so knowing that, I do want to confirm what color palette we should use for the Filter Chip variation of this component: 

- For the single attribute value chip, do we still want that to be a solid color like the original design? 
- Knowing that we will need different styles for Filter Chips vs Assigned Tags anyway, do we want to stick with the original color combination (i.e. dark blue on light blue) shown in the example below? 

Example of filter chips from [PF design document](https://www.patternfly.org/pattern-library/forms-and-controls/filter/)
![image](https://user-images.githubusercontent.com/21063328/43803635-66ca5a88-9a67-11e8-93d5-fc70dc52192d.png)

Example of single attribute value from @terezanovotna's [design document](https://docs.google.com/document/d/19Vu9Q_lfCQDkwO3LQuwsImSH0rH9i0o9AF24Uer6WqA/edit)
![image](https://user-images.githubusercontent.com/21063328/43804058-c081cdb2-9a68-11e8-92ff-518b4e1c3b66.png)


> The only issue I see is that if we also apply this to the Filter pattern, it changes the way we represent a filter chip when there is only a single attribute:value pair. If we change this, does this potentially result in a breaking change?

Regarding implementation, I think any consumers that would want to utilize the compound label would need to make updates to their project anyway to handle the logic required to create the relationship of the single attribute to many values. Maybe @jeff-phillips-18 could comment on this, but ideally, we would incorporate this new component in a way that doesn't break existing implementations, but also allows consumers to add this new feature to existing implementations. Just handling the layout of filter chips when there is a mix of single and multiple values per chip will probably require some updates to the underlying html of the single value chip. But I think that change can be made without breaking the existing pf-react implementations.

**Comment by mcarrano** [comment]
Closing with merge of #712
