### ISSUE TITLE
Need guidance on entering time zone when selecting a "time"

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#681]
When a user selects "time", often they need to provide an associate time zone as part of their user flow.  It would be helpful to include this use case as part of the Time Picker design documentation.

**Comment by serenamarie125** [comment]
@vconzola @nlcwong created this issue based on our slack discussion

**Comment by mcarrano** [comment]
Makes sense. @serenamarie125 @vconzola @nlcwong do any of you have examples of how this is done in product today?

**Comment by nlcwong** [comment]
Quick scan of CloudForms yielded this...
![screen shot 2018-06-19 at 2 19 45 pm](https://user-images.githubusercontent.com/31672086/41616422-fb0b0dd6-73cb-11e8-87a7-fad1d6d5c8bd.png)

**Comment by serenamarie125** [comment]
thanks @nlcwong !

**Comment by LHinson** [comment]
This has been added to the PF4 issue and list of requirements seen here: https://github.com/patternfly/patternfly-next/issues/180

Removing this from the PF4 feature board as you can track progress via the above issue.
