### ISSUE TITLE
Remove Background Color & Border from Empty State

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-design#682]
Per a discussion in the uxd-visual Slack channel with @serenamarie125 and @jennyhaines, the empty state pattern should not have a set background color or border. As such, the background should be set as transparent and the border removed.

http://www.patternfly.org/pattern-library/communication/empty-state/#code

The code needs to be updated as well, as that shows a background with color and a border. Issue created here for that update: https://github.com/patternfly/patternfly/issues/1079

**Comment by lizsurette** [comment]
@mcarrano Looking closer at this for oVirt with dev, just the two CSS properties 'background-color' and 'border' would need to be removed from the blank-slate-pf class. The current workaround is to override these PatternFly values with project-specific CSS.

**Comment by LHinson** [comment]
Since this is not a large effort to override on product side, I'm closing this issue due to the risk it presents to breaking change on core. That said, we will add dev notes to the empty state code page to identify/ack this as an option. See: patternfly/patternfly-org#615
