### ISSUE TITLE
Copy to Clipboard [New Pattern]

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#689]
This is a request for a new pattern around copying to clipboard:

This [doc](https://docs.google.com/document/d/1KXTWC6-J7-dKDXFdzX_5v28fUu9dKDwM7pGzareTZ0g/edit) is a starter for a new design pattern

**Comment by serenamarie125** [comment]
here are some screenshots of different patterns being used in our products/in industry:
Tectonic:
<img width="487" alt="screen shot 2018-06-27 at 4 37 40 pm" src="https://user-images.githubusercontent.com/12504403/41998320-77f1af14-7a28-11e8-99a7-3486ea61c1a1.png">
GitHub:
<img width="488" alt="screen shot 2018-06-27 at 4 37 25 pm" src="https://user-images.githubusercontent.com/12504403/41998321-7801388a-7a28-11e8-8370-4b48ac4bb652.png">
<img width="540" alt="screen shot 2018-06-27 at 4 37 16 pm" src="https://user-images.githubusercontent.com/12504403/41998322-780f6d9c-7a28-11e8-92c7-52391a78b69f.png">
PatternFly NG (includes toast notification):
<img width="655" alt="screen shot 2018-06-27 at 4 41 14 pm" src="https://user-images.githubusercontent.com/12504403/41998518-f764117e-7a28-11e8-9488-411744bd0f46.png">
<img width="651" alt="screen shot 2018-06-27 at 4 41 19 pm" src="https://user-images.githubusercontent.com/12504403/41998517-f753f046-7a28-11e8-9e62-65666a6bf5ed.png">

**Comment by serenamarie125** [comment]
@catrobson @bmignano @beanh66 @cdcabrera FYI

**Comment by bmignano** [comment]
Please review the [design proposal](https://docs.google.com/document/d/1tieVwiPeReAQVE-pcu8wf-O2ZSxgV78CIBVhzj466dU/edit?usp=sharing) for this pattern including competitive research and a proposed solution. I would love to get some feedback before starting MD files. Thanks!

**Comment by sjcox-rh** [comment]
Fyi - @seanforyou23 just worked on a copy to clipboard component for PatternFly-ng. Possibly something you can use!

https://github.com/patternfly/patternfly-ng/pull/351

**Comment by beanh66** [comment]
sjcox-rh Can you review the [design proposal](https://docs.google.com/document/d/1tieVwiPeReAQVE-pcu8wf-O2ZSxgV78CIBVhzj466dU/edit#) from @bmignano if you haven't already? @catrobson mentioned you are using something similar and we want to be sure you have seen this before we put up a PR. Thanks!

**Comment by sjcox-rh** [comment]
Thanks for the heads up! Left a couple comments, looking good! @beanh66
