### ISSUE TITLE
Add new Drag/Drop Handle to PF icon set

### ISSUE THREAD

**Issue by jennyhaines** [patternfly/patternfly-design#691]
We have a new drag and drop handle icon that should be added to our PF icon library (located [here](https://patternfly.atlassian.net/browse/PTNFLY-2861)). Mary Shakshober did a great job creating it, (design reviews documented [here](https://patternfly.atlassian.net/browse/OSUX-628))… Please let me know whether you need anything else or other guidance to add the icon in! Thank you!

FYI: @LHinson @andresgalante

**Comment by jennyhaines** [comment]
Okay that sounds good to me @mcarrano ... there is no code for that drag and drop pattern in PatternFly, so I doubt that it is highly used at the moment.

**Comment by mcarrano** [comment]
@catrobson showed a current implementation in OpenShift.io that follows the approach outlined in the pattern referenced above. Would like to hold on this until we can arrive at a consistent cross-product approach that we will use moving forward.

**Comment by serenamarie125** [comment]
@catrobson let's see if we can update OSIO to use this new icon as well.  As long as that's ok, @mcarrano I'd suggest we change the D&D documentation to use the new icon and get this in.  Let me comment here again once Catherine & I have had the chance to talk

**Comment by serenamarie125** [comment]
@beanh66 can you provide some guidance here ? I think last we talked, you mentioned that the pattern documentation included low fidelity mockups, not high.  Am i remembering correctly ?

**Comment by beanh66** [comment]
@serenamarie125 correct, I created those in sketch awhile back but I think we planned on having a high fidelity follow-up to get an actual drag and drop icon created since this may apply to tables, cards, lists, forms, etc. @jennyhaines and @maryshak1996 created an icon recently for this so Mary may have the latest info!

**Comment by maryshak1996** [comment]
@serenamarie125  @beanh66  yes! here's the issue that this was getting tracked on with JIRA 
https://patternfly.atlassian.net/browse/OSUX-628
I can also add any design files you need directly here if you'd like

**Comment by mcarrano** [comment]
Per our discussion at the Aug 16 PatternFly Design Sync, I am splitting this into two separate issues. Let's let this request to add the new Drag/Drop Handle to the PatternFly 3 icon set proceed. I have also opened a new issue to consider inconsistencies in current implementations and recommend a path forward for defining a consistent approach to be applied across-products and for PatternFly 4. See https://github.com/patternfly/patternfly-design/issues/708

@LHinson can you remind me of the process for adding this icon? Should an issue be opened against PF core?

**Comment by LHinson** [comment]
That's correct @mcarrano

**Comment by mcarrano** [comment]
A new issue https://github.com/patternfly/patternfly/issues/1131 has been filed in patternfly-core to add the new icon. This issue will be closed.
