### ISSUE TITLE
Standard ListView mockup on Design page needs updating

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#694]
On this page http://www.patternfly.org/pattern-library/content-views/list-view/#design there is a mockup of a standard list view with rows selected. This image does not agree with the specification below for background colors of selected rows.

**Comment by yih-wang** [comment]
@mcarrano I'd like to take this task and here is the pr #699 . Also modified a typo when I go over the List View documents. Please have a review.

**Comment by mcarrano** [comment]
Just merged your PR @yih-wang . Will close.
