### ISSUE TITLE
Placeholder is added as option in drop-downs

### ISSUE THREAD

**Issue by akaRem** [patternfly/patternfly-design#695]
There is a bug in ansible galaxy https://github.com/ansible/galaxy/issues/818

The problem is that dropdown placeholder is added as first option in dropdown list.
This looks strange. And there is no such behaviour in most of frameworks.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/1472728/42218885-ad742758-7ed2-11e8-951c-f0072f4e23f4.png">

Team says that they can't fix this in galaxy ui and it should be fixed in framework instead

**Comment by LHinson** [comment]
@akaRem Given this seems like an implementation concern, I'm going to open this again our patternfly-core repo. Before doing so, I'd like to to confirm, you are using patternfly-core vs one of our js implementations (e.g PF-React), correct?

**Comment by akaRem** [comment]
@LHinson 
Hmm.. Well, I found defect in AnsibleGalaxy by RedHat (on screenshot). They use Angular-based patternfly framework. So.. This is **correct**, but I'm not 100% sure. 🙂 

This is what mentioned in package.json:
```
    "patternfly": "^3.48.4",
    "patternfly-ng": "^3.3.4",
```

I'm not insider. I just trying to help them with launching new version of Ansible Galaxy because I like this site. 
So it's better to ask someone from Galaxy team directly.  I suppose, @chouseknecht and @newswangerd are the best candidates for discussion.

**Comment by LHinson** [comment]
@akaRem Assuming they use patternfly-ng, I'm not able to see this same bug on our end. You can see the patternfly-ng implementation of this component, here: http://www.patternfly.org/patternfly-ng/#/filters

I'd suggest filing a bug against Ansible Galaxy to investigate how it's implemented there. We (PatternFly) are happy to follow up though if they find there is an issue with a specific component.

**Comment by akaRem** [comment]
@LHinson I can confirm the same behaviour on demo site:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/1472728/42732130-c2b37aec-8823-11e8-9552-1ebea1df4d92.png">

Here are the problems I see with this weekday filter.
First I choose Monday -> drop-down does not change it's state, but tag is appended 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/1472728/42732226-3e39c5ac-8826-11e8-81de-e05b1339c07b.png">
Does it mean that I can add another weekday? It looks like yes, but If I add tuesday the tag is replaced.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1472728/42732239-6f2881bc-8826-11e8-8928-4006b5f82d8a.png">
Ok, I can't add another day. So this control acts like radio group / single-select dropdown / combobox.
What if I want to remove my selection? I click again and choose that initial option 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1472728/42732260-c23e4a30-8826-11e8-8d44-b3e543b86ed3.png">
And nothing happens..
The only way to remove selected filter is to click on `x` in "Active filters" list.

**So the question: Why this default option even there? It does nothing.**

This component looks like classic combobox with placeholder but acts like button group where first button does not have any action.

It probably should look like this (when it does not remember it's state)
```
 +------------------------------------------------------+
 |  Week Day | V | Filter by week day...            | V |
 +------------------------------------------------------+
```
or like this (when it can remember)
```
 +------------------------------------------------------+
 |  Week Day | V | No filter                        | V |
 +------------------------------------------------------+
```
while not interactive.

And like this when drop-down is activated
```
 +------------------------------------------------------+
 |  Week Day | V |                                  | V |
 +------------------------------------------------------+
                 | No filter                            |
                 | Sunday                               |
                 | Monday                               |
                 | Tuesday                              |
                 | Wednesday                            |
                 | Thursday                             |
                 | Friday                               |
                 | Saturday                             |
                 +--------------------------------------+
```
If user chooses "No filter" option, then filter should be removed. 
If user clisks on something else, then crsp filter is added/replaced.

After user chosed anything, it should look like this (when it does not remember it's state)
```
 +------------------------------------------------------+
 |  Week Day | V | Filter by week day...            | V |
 +------------------------------------------------------+
```
or like this (when it can remember)
```
 +------------------------------------------------------+
 |  Week Day | V | No filter                        | V |
 +------------------------------------------------------+
```
```
 +------------------------------------------------------+
 |  Week Day | V | Monday                           | V |
 +------------------------------------------------------+
```
If you don't want to allow user to remove filters from dropdown, then you may remove "No filter option".

_____________

So, one more time..

If it's combobox, it's legal to add default value (placeholder) as first option, but it __must__ display currently selected option and if user selects default option it __must__ be applied

If it's drop-down button group or "menu", than it __must__ __not__ display menu placeholder, it __must__ __not__ contain any buttons that don't do anything.

**Comment by LHinson** [comment]
@akaRem yes you are right. Thanks for taking the time to clarify the bug/concern. I've filed an issue against patternfly-ng with your description of the bug. You can see that here: https://github.com/patternfly/patternfly-ng/issues/418

@mcarrano neither the checkbox filter or filter patterns describes what the behavior of the filter should be when only one can be selected. I'm leaving this issue open against patternfly-design as well so we can address that on the site and with future filter work.

**Comment by dlabrecq** [comment]
Is the issue here that the component needs to show the current selection?

Other than showing the current selection (I agree that is a bug), it appears to behave similarly to the Angular Patternfly implementation, which this was ported from. http://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilter

I'm a little confused by the terminology (i.e., what is referred to as "combox" Vs "dropdown button group" Vs "menu"). Can you please clarify what you mean by "If it's drop-down button group or menu"?

FYI, the component's filter filed currently uses either an input field or a dropdown. (We haven't implemented any checkbox groups, yet.) While the developer implements how the filter is applied and the available filter options.

**Comment by mcarrano** [comment]
@akaRem @LHinson I looked into this issue a bit more. The conclusion I've drawn is that none of our PatternFly implementations exactly match the design intent. This should work as a Select list (either single or multiple) with placeholder text. You can see that behavior if you go to this page and scroll down to Placeholder. You'll see that the placeholder text does not appear in the menu. Agree that it is currently a bug as implemented.

As for clearing the filter, the design intent was that this is done by clicking the "X" on the filter chip. You could add a "no filter" item into the list, but that is unnecessary IMO. When removing the filter, the placeholder text should be restored.

Perhaps we should start by fixing the core implementation and then propagate this through the other repos. I suspect others copied what Core had done. Thoughts @LHinson ?

**Comment by LHinson** [comment]
I agree that we should address this in core first. There is an issue created here: https://github.com/patternfly/patternfly/issues/1116

Once this is complete, we'll proceed with fixing the pf-ng example. 

Closing this issue here since it's not a design doc bug.
