### ISSUE TITLE
Refine Empty State design to allow more secondary button options

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#696]
There is a proposal to allow alternate options for displaying secondary actions in an [Empty State](http://www.patternfly.org/pattern-library/communication/empty-state/) pattern. These are summarized in this issue filed against patternfly-core (https://github.com/patternfly/patternfly/issues/907).

The Design page should be updated to add these alternate designs.

**Comment by nding-anges** [comment]
@mcarrano Definitely ;-)  I will updated the Design page with relative design.

**Comment by nding-anges** [comment]
Hi @mcarrano, please find the updated Design guidance related @dabeng demo page of multiple secondary action. https://docs.google.com/document/d/12kSla-sTocg-mNQTgZ2NHNs58BsX4PxisEfl8vJvg5M/edit?usp=sharing . Thanks;-)

**Comment by mcarrano** [comment]
This has been fixed with PR #702.
