### ISSUE TITLE
Inconsistency in breadcrumbs design

### ISSUE THREAD

**Issue by bmignano** [patternfly/patternfly-design#700]
There is a design inconsistency with breadcrumbs documentation.

On the breadcrumbs [design page](https://www.patternfly.org/pattern-library/navigation/breadcrumbs/#design), screenshots show the "fa-angle-right" icon being used. In the callout text, however, the "fa-angle-double-right" icon is listed as the recommended icon. I'm happy to update this to be consistent but I'm not sure which icon is the correct one.

@kybaker Do you know which icon we are recommending for breadcrumbs?

**Comment by mcarrano** [comment]
@bmignano Thanks for flagging this. We updated the mockups a while ago to consistently use the single arrow (fa-angle-right) but must have missed this text. @kybaker please confirm. If you can make this update and send a PR @bmignano, that would be much appreciated!

**Comment by kybaker** [comment]
@mcarrano @bmignano Yes the single angle right is perfect. Thanks for catching this!
