### ISSUE TITLE
PF3 Expandable row for table 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#701]
PatternFly-ng has the expandable row for table. https://www.patternfly.org/patternfly-ng/#/table
@vconzola would like to add this to PF-React. 

We just need to update our documentation to show how this optional feature should look/behave.

**Comment by gdoyle1** [comment]
To stay consistent with expandable rows in list view, I decided to highlight the table row that is expanded in the hover color (as seen [here](https://www.patternfly.org/pattern-library/content-views/list-view/#code)). Other than that, the design matches that of PatternFly-ng expandable row.
