### ISSUE TITLE
Add Pagnination control as an optional component of Toolbar

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#721]
The [pagination pattern](https://www.patternfly.org/pattern-library/navigation/pagination/) was recently updated to include the pagination control in the toolbar above any content view as well as in a footer below the bar. The [Toolbar pattern](https://www.patternfly.org/pattern-library/forms-and-controls/toolbar/) documentation should be updated to include this as an optional component.

**Comment by mcarrano** [comment]
@gdoyle1 Thanks for taking this issue. Let me know if you have any questions. @LHinson FYI

**Comment by gdoyle1** [comment]
@mcarrano Just uploaded some updates/changes here!
