### ISSUE TITLE
Patternfly Login encourage SSO login

### ISSUE THREAD

**Issue by guillaumevincent** [patternfly/patternfly-design#734]
Hello,
in my product I would like to encourage my user to login using the SSO.
I tried different login page:

this one

![screenshot_2018-11-30 pf next](https://user-images.githubusercontent.com/943762/49301073-12bddc00-f4c4-11e8-9251-01af3a04b185.png)

and this one
![screenshot_2018-11-30 distributed ci](https://user-images.githubusercontent.com/943762/49301075-13567280-f4c4-11e8-9f30-7d311eddd2ce.png)
![screenshot_2018-11-30 distributed ci 1](https://user-images.githubusercontent.com/943762/49301074-12bddc00-f4c4-11e8-8fcf-c9e08e378105.png)

The second one with the toggle form works really well. 
Users stop reaching us to get an account for example.

The page works very well but is not very pretty. How can we encourage the connection with a social button with the current design?

**Comment by mcarrano** [comment]
Closing in favor of the active patternfly-next issue referenced above.
