### ISSUE TITLE
Reevaluate "Running" icon

### ISSUE THREAD

**Issue by bmignano** [patternfly/patternfly-design#740]
The current icon PF recommends using for 'On' or 'Running' (pficon-on-running) is the same as the OLM logo. For this reason, OpenShift (and potentially other products) is not able to use it. We should reevaluate the 'Running' icon to determine if there's a better icon to represent this status.

cc @mcarrano @kybaker @serenamarie125 @cshinn

**Comment by serenamarie125** [comment]
OLM is the Kubernetes operator framework. I agree with @bmignano point that we should re-evaluate the current running icon.

Here's a screenshot of the operator framework logo - 
<img width="444" alt="screen shot 2019-01-18 at 8 40 00 pm" src="https://user-images.githubusercontent.com/12504403/51420573-44b4fb80-1b61-11e9-93c7-bdb806cff304.png">
and a couple of resources where you see the image referenced:
https://www.redhat.com/en/blog/introducing-operator-framework-building-apps-kubernetes
https://github.com/operator-framework

@bmignano it may be worth sharing what the team ended up using for OpenShift, the various icons that were considered and the rationale around the final choice. This input may be helpful in solving this issue.

**Comment by bmignano** [comment]
While deciding on an appropriate icon to represent 'Running' in the OpenShift console, we considered a number of different icons, including pficon-on-running, fa-arrow-circle-o-up, pficon-in-progress, and fa-refresh. We needed this icon to represent the 'Running' status of several Kubernetes resources, such as pods or builds.

![running-options](https://user-images.githubusercontent.com/40238481/51559524-221c2e80-1e50-11e9-90ec-658eb6c00918.png)

**pficon-on-running**: We did not use this icon for the aforementioned reasons of it conflicting with OLM.
**fa-arrow-circle-o-up**: We did not use this because we felt it did not accurately represent the status of 'Running.'
**pficon-in-progress**: We chose not to use this as it represents something running with an end goal, such as an object updating, which was not appropriate for our use case. It would also create a conflict for resources that might have both the 'Running' and 'Updating' statuses.

We ultimately decided to go with **fa-refresh** for a few reasons:
1. It did not conflict with any other status icons we use in the console.
2. We used it in the old console and received positive feedback from users.
3. Visually, we agreed that it effectively represented 'Running.'
4. It is currently listed in PF as only an Action, but could potentially be added as a Status as well.

Hopefully this helps shed some light on the background and some of the thought that went into this icon selection!

**Comment by mcarrano** [comment]
I think that the proposal to re-use 'fa-refresh' is fine as an interim fix for PF3. I have opened a new issue in the PF4 repo requesting that this icon be re-evaluated. https://github.com/patternfly/patternfly-next/issues/1533  Will close this one.
