### ISSUE TITLE
Classification Banners [New Pattern]

### ISSUE THREAD

**Issue by kavinmc** [patternfly/patternfly-design#742]
Hello Patternfly contributors and administrators – RedHat’s Office of the Public Sector CTO and Cornell University’s Information Science Graduate program have partnered to give students the ability to flex their classroom skills by applying them to real-world applications.

For our project this semester, we are aiming to contribute a pattern to the library at Patternfly. The below information should give more clarity on the pattern itself.

Note: We (the four students in the project team) are fairly new to GitHub, and very new to the contribution style for Patternfly. While we have reviewed the contribution guides, we are prone to errors that come as part of the learning curve, so please bear with us!

1.	State whether this is a new pattern or an enhancement on an existing pattern

**This is a New Pattern**

2.	If this is for specific applications, list them here

This pattern is to be (potentially) made available for use in the Pattern Library at https://patternfly.org

3.	Describe the use cases and requirements
**Requirements**:
•	Classification banner elements should span entire screen
•	Classification banners should have the data classification on the top and bottom banners.
•	Classification banner elements should have background colors based off of a set of standardized colors
•	Classification banner elements should have options to be able to easily customize text on the banners
•	Banners should be able to have different background colors based on the data classification
•	The user name should be in the top right part of the banner, and what host the user logged into in the top left corner of the banner. 
**Use Case(s):**
•	When deploying an information system into the U.S. Government, data classification of the information system must be performed based on what type of data the information system is approved to process. This means that all display screens and web pages need to display the classification level (Proprietary Level I, Proprietary Level II, Unclassified, etc) on the top and bottom parts of the display screens/webpages so that users are aware of what type of data they are working with.

4.	Link any detailed design documents (template available here):
 
Design documentation is being worked on and will be added shortly

5.	List any existing PF patterns this may impact or depend on:

Patternfly **Masthead** and **Navigation** elements should be extended to use these new classification banners if enabled

6.	Attach any rough sketches, wireframes or workflows 

The below screenshot is taken from the ‘Security Central’ RedHat project. The new classification banner patterns are to be made in a similar manner whilst adhering to the requirements mentioned in this issue.

![image](https://user-images.githubusercontent.com/47615277/54432463-a7f58100-46ff-11e9-8304-db6563d55906.png)
 

7.	Tag '@patternfly-design-maintainers' if you will be working on this issue we will assign it to you.
Hi @patternfly-design-maintainers, the four users who are working on this issue are
•	Kavinmc – Kavin M Chinnasamy
•	Zeyap – Zeya Peng
•	Alinarobin – Alina Robin
•	Lesleycl – Li Chai

**Comment by shawndwells** [comment]
Additional examples include:

* How Drupal-based sites have implemented classification banners:
(ref: https://www.drupal.org/files/project-images/screen_shot_1.png)

![image](https://user-images.githubusercontent.com/5713754/54468440-f25c1980-4762-11e9-9979-cee5956103c4.png)

* Same thing for SharePoint:
(ref: https://i.stack.imgur.com/qVJkE.png)
![image](https://user-images.githubusercontent.com/5713754/54468450-0142cc00-4763-11e9-9b99-56ae42267830.png)

**Comment by shawndwells** [comment]
Looks like original callouts didn't format correctly, so +cc 
@kavinmc, @zeyap, @Zeyap, @Alinarobin, @Lesleycl

**Comment by mcarrano** [comment]
I believe this work is completed. Closing out for housekeeping purposes. Let me know if this should still be active for any reason.

**Comment by shawndwells** [comment]
Banners were merged upstream. Will open new tickets for PatternFly v4 work.
