### ISSUE TITLE
Beta or Experimental Features Pattern

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-design#748]
## For Pattern Contributions: 
- State whether this is a new pattern or an enhancement on an existing pattern 
New Pattern
- If this is for specific applications, list them here
Insights, CSfRM
- Describe the use cases and requirements
The application would like to indicate to users that they are in a beta environment. In the Insights use case, it would be the entire application. The pattern illustrates use cases for the entire application, content area, and by feature.
- List any existing PF patterns this may impact or depend on
https://www.patternfly.org/v3/pattern-library/communication/experimental-features/
- Attach any rough sketches, wireframes or workflows 
https://marvelapp.com/451jc24

**Comment by mcarrano** [comment]
@Rohoover There is already an open issue for creating an experimental or beta features demo in the PatternFly 4 repo here: https://github.com/patternfly/patternfly-next/issues/294  There is also a related issue to create a Banner component similar to you mocks: https://github.com/patternfly/patternfly-next/issues/1964

These still need to be planned on our PF4 Roadmap. I recommend adding your requirements and product timelines there and bringing @LHinson into the loop for prioritization.

**Comment by mcarrano** [comment]
Closing this out in favor of the issue referenced above.
