### ISSUE TITLE
Broken link in main Readme file

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly-design#749]
Documentation bug:
The link to http://www.patternfly.org/patternfly-design/status/ in the main repo [README.md](https://github.com/patternfly/patternfly-design/blob/master/README.md) file opens up a 404 page (`https://www.patternfly.org/v4/404.html`)

[sorry if duplicate -- searched for it but didn't find an open issue]

**Comment by mcarrano** [comment]
This content is all pretty stale at this point as we are no longer actively updating the patternfly-design repo. @rachael-phillips @LHinson do you think we need to update this readme to reflect our current approach?

**Comment by rachael-phillips** [comment]
Hi @mcarrano could you tell me more about what this page is?

**Comment by mcarrano** [comment]
It's here: https://github.com/patternfly/patternfly-design @rachael-phillips
