### ISSUE TITLE
Dashboard demo 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#752]
In this issue (which might be broken up to separate issues later), visuals will begin by providing hi-fi examples of various dashboards with our components. After this, we will determine which make sense to add as demos. 

Design Folder: https://drive.google.com/open?id=1kRZClTWey5ZtDPK81Yrk2ZozRugoZyPx

Consider both full page dashboards and "dashbars."

Component lifecycle: 
- [x] Interaction design requirements 
- [ ] Visuals 
- [ ] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual 
- CSS

**Comment by mcarrano** [comment]
Going to get this one back into the plan. Here's some documentation that @mceledonia created to go along with this: https://docs.google.com/document/d/1VYTC2VrjdlwWPwEF7oVcCT-ict16bb3kDUmfHf9lpQA/edit?usp=sharing

**Comment by mcarrano** [comment]
@doruskova I'd like you to work on this in conjunction with looking at the Dashbar issue (#913). I think it would be great to end up with a set of Dashboard demos that included both full page dashboards and dashbars. I have been working on design guidelines for dashboards. There is a PR up here: https://github.com/patternfly/patternfly-org/pull/2702 You may want to start by reviewing that to get a sense of general guidelines.

One issue that is not addressed in the guidelines, but would be good to consider in a live demo, is how to make dashboards responsive. Not sure what we currently do, but I believe we should have a consistent approach on this.

**Comment by doruskova** [comment]
@mcarrano I'm adding my updates on this issue. I created a guide for responsive layout - [link](https://docs.google.com/document/d/1_6wNCRzfmh16sMCLCCG66DrzO28xdTJkI168-9JlVDk/edit?usp=sharing)

And here's the marvel that shows examples of responsive dashboard https://marvelapp.com/prototype/d642i6g/section/1537267

And then I was trying to figure out the example for a demo. However, I think we should use what we already created and it's mentioned almost everywhere (dashboard guideline, examples, card examples). It'd be the most consistent approach IMHO. I've changed a couple of little things. But, here's the example for demo https://marvelapp.com/prototype/d642i6g/screen/84550919

These components exist in Sketch, Cards implementation and it's being described in Dashboard guidelines. I just need to add the screen for expanded cards. Let me know what you think.

**Comment by mcarrano** [comment]
@doruskova just to follow up/summarize what we covered in the meeting today, sounds like next steps are to create mocks of responsive versions of the existing dashboard example and to work out the scrolling technique for the dashbar. Once that is complete, we should be in good shape to review with dev. Thanks!

**Comment by doruskova** [comment]
@mcarrano Adding examples of responsive dashboards https://marvelapp.com/prototype/d642i6g/screen/84702324

The next thing, I'll explore is the scrolling technique. Current implementation wraps up the content. I think it should be an optional choice for everyone who needs to show more cards, columns, etc.

**Comment by mcarrano** [comment]
@mcoker please take a look at the mockups above. I'd like to create core and React dashboard demos from these. If there are any issues I can set up some time for us all to meet. Thanks.

**Comment by mcoker** [comment]
Hey @mcarrano @doruskova, looks good - a few questions:

* Events list looks like notification drawer items, which are tied to the notification drawer. Can we use inline alerts there instead?
* In the row of pathway cards at top:
  * Confirm there is no border between cards on mobile
  * Text in each card (on desktop) shouldn't fill the available space
* In status card - is the "notifications" section a nested expandable card in the status card footer?

**Comment by mcarrano** [comment]
@doruskova @mcoker I have opened core issue https://github.com/patternfly/patternfly/issues/4659 and added to milestone 2021.03 in the hopes that we can work out the remaining design questions before starting the next sprint.

**Comment by doruskova** [comment]
@mcoker I'll try to answer here :) 

- I don't know what's used in this existing React component https://www.patternfly.org/v4/components/card/react-demos#event-view
- Yep, you're right. There is no border between columns on mobile. It comes from this demo https://www.patternfly.org/v4/components/card/react-demos#horizontal-card-grid
- Ooh, it should fill the space. My bad. The implementation looks like this
<img width="1354" alt="Snímek obrazovky 2022-02-04 v 10 16 39" src="https://user-images.githubusercontent.com/32618096/152503297-c774400b-e0a6-4519-a13c-f3f21602d9df.png">

-  Status card - it comes from this demo and yeah it looks like a nested expandable card in a footer.  https://www.patternfly.org/v4/components/card/react-demos#status
