### ISSUE TITLE
Labels Demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#753]
Provide examples and guidelines for using tags and labels including:
- Common CRUD use cases
- Tags and labels in context

**Comment by mcarrano** [comment]
Tagging mockups from Insights team: https://marvelapp.com/ddc6724/screen/65624340

**Comment by maryshak1996** [comment]
@mcarrano here is what I've come up with so far - I'd be interested to hear your thoughts on how we structure these demos since there are several different ways that we could categorize them.
https://marvelapp.com/prototype/bd077ag

**Comment by mcarrano** [comment]
Good question @maryshak1996 . I think the question becomes what are the major use cases for applying labels and then how do the demos illustrate those. I'd like to bring @bmignano into this conversation as she is working on design guidelines for labels and label groups. I think the demos should be closely coupled with the design guidelines documentation so perhaps you can collaborate. Thoughts?

**Comment by bmignano** [comment]
Thanks for adding me to the conversation @mcarrano ! The labels [design guidelines](https://www.patternfly.org/v4/components/label/design-guidelines/) are actually up already if those would be helpful for you @maryshak1996 ! I think the demos you linked are looking great. One thing I'd mention is that they don't seem to include dismissible labels which is a feature we highlight in the design guidelines.
I'd be more than happy to collaborate with you further on this @maryshak1996 :)

**Comment by maryshak1996** [comment]
thanks @bmignano and @mcarrano :) I just chatted with Brie a bit and tweaked things a bit to align this more closely to what's happening in the documentation

**Comment by mcarrano** [comment]
This is looking great @maryshak1996 . It would be good to get some more eyes on this. Perhaps present at the next PF design share. I'm wondering if this covers common tagging use cases. Also, I don't see anything about label groups. Should we also consider label group usage (e.g. label groups with category labels)? I believe these were being used extensively in Ansible. @trahman73 I believe you had some examples?

**Comment by trahman73** [comment]
Thanks @mcarrano We are using the PF Label Group component below for some use cases in Ansible.

https://www.patternfly.org/v4/components/label-group

**Comment by mcarrano** [comment]
Do you have any screen shots or mockups to reflect that usage @trahman73 ?

**Comment by trahman73** [comment]
@mcarrano One case for us is using a label group to show selected items on a list.

![image](https://user-images.githubusercontent.com/13351591/99005766-6722c080-250f-11eb-93cd-737aa31145d2.png)

**Comment by maryshak1996** [comment]
@mcarrano I was curious about this 'label group' peice as well, but I wasn't sure if this should be covered in this demo or not (since the 'label group' is it's own navigation item on the site)

**Comment by mcarrano** [comment]
Yeah, that's a fair question @maryshak1996 . I'd say let's cover everything here and then we can figure out how to divide this up within the website.

**Comment by maryshak1996** [comment]
@mcarrano I added two label group examples to the marvel :)

**Comment by mcarrano** [comment]
@mcoker When you get a chance, please take a look at Mary's designs and let us know if you see any issues: https://marvelapp.com/prototype/bd077ag

**Comment by mcoker** [comment]
@mcarrano this mostly looks OK to me. As custom demos, it should be fine, it's just worth noting that labels are taller than regular text line-height, so they may change the space of the element they're placed in. For example, when used in a card title:

Title is 64px tall without a label:
<img width="325" alt="Screen Shot 2020-12-07 at 1 10 25 PM" src="https://user-images.githubusercontent.com/35148959/101394078-a255ac80-388d-11eb-8302-88fc3184cc4f.png">

69px tall with a label:
<img width="309" alt="Screen Shot 2020-12-07 at 1 10 38 PM" src="https://user-images.githubusercontent.com/35148959/101394084-a4b80680-388d-11eb-84b1-87326fcbc3eb.png">

Also by default a label may not align with other things around it. Like a title:

<img width="341" alt="Screen Shot 2020-12-07 at 1 07 59 PM" src="https://user-images.githubusercontent.com/35148959/101394205-cb763d00-388d-11eb-8216-2708ca0abc05.png">
<img width="254" alt="Screen Shot 2020-12-07 at 1 08 06 PM" src="https://user-images.githubusercontent.com/35148959/101394177-c3b69880-388d-11eb-8415-ba10bd73cb35.png">

When used with a custom layout, the spacing and alignment can be fixed.

One problem I see is you can't place a label (or HTML at all) inside of a textarea:

<img width="886" alt="Screen Shot 2020-12-07 at 1 03 31 PM" src="https://user-images.githubusercontent.com/35148959/101394300-e8ab0b80-388d-11eb-87ac-e3efdc007178.png">

And the theme support (grey background, black background) - if the labels change appearance depending on the background they're used, we'll need something that serves as a trigger for the label's colors to change. This could be like the work we're doing with dark theme, or something like a modifier class (similar to tabs or cards) that have modifiers that change the appearance based on what kind of background they're placed on top of.

**Comment by mcarrano** [comment]
> One problem I see is you can't place a label (or HTML at all) inside of a textarea

That's a good catch @mcoker . Is there any reason for the labels to be inside a text area? Could we just have a Label Group here and add or remove labels from the group?

**Comment by bmignano** [comment]
@mcarrano we included labels inside a text area because that's a use case in OpenShift that we have today. We haven't moved over to PF labels yet which is probably why I hadn't run into this issue before :). This is how we allow users to add and delete labels. @mcoker what would be the best way to try to replicate this interaction given this constraint?
![edit-labels](https://user-images.githubusercontent.com/40238481/101409188-8bbe4e00-38ab-11eb-86b4-478d9002c52c.gif)

**Comment by mcoker** [comment]
@bmignano from your screenshot above, one way to do it would be to create a fake "textarea" form control component variation, using a regular `<div>` with `contenteditable` and `resize` properties to mimic the HTML native `textarea`. From there, you can put whatever you want in it.

Using that, I created this demo using the label group component and placing a custom text input in the label group as an item that would allow a user to type and hit enter to add an extra label to the group.

![Dec-07-2020 17-52-30](https://user-images.githubusercontent.com/35148959/101419289-50288180-38b5-11eb-9a6b-ae5ae3c5e4d3.gif)

We don't support this custom textarea variation currently but it might be something we could add.

**Comment by mcarrano** [comment]
@mcoker I'm wondering if we should extend the Label Group component to encapsulate this functionality. What do you think?

**Comment by mcoker** [comment]
@mcarrano like an editable label group? I think that would work. We could also see if it makes sense to support in the inline edit component.

**Comment by mcarrano** [comment]
Yes, I think an editable Label Group would make sense. @maryshak1996 @bmignano perhaps you can spec that out as a new component in the design mocks? I think this is pretty straight forward, but there may be some design considerations I'm not thinking of.  Thanks.

**Comment by mcarrano** [comment]
I am going to mark this as complete and have opened the following new issues:

* https://github.com/patternfly/patternfly/issues/3741 to introduce an editable Label Group.
* https://github.com/patternfly/patternfly/issues/3742 to introduce a Labels demo per these designs.
* https://github.com/patternfly/patternfly-design/issues/967 to update filled label designs to work against a gray background.
