### ISSUE TITLE
Dark Theme 

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#754]
An epic to collect issues related to a PF dark theme.

**Comment by serenamarie125** [comment]
@rachael-phillips we now have an Epic around provided a dark mode https://issues.redhat.com/browse/CONSOLE-2140

**Comment by ajacobs21e** [comment]
Designs from @coreyvickery https://xd.adobe.com/view/f329a7a4-b030-4bb8-ab3f-58b17830d1e2-a67a/

**Comment by mceledonia** [comment]
Update on the dark theme effort:

@mcoker and I did an initial test of a hands-off dark theme approach where we adjusted the global variables to the dark color palette. This was successful so we're working now on applying it to the rest of the system where we can check and audit each component. 

Open/ongoing design tasks: 

- Refine new gray palette with colorbox
- Solve new input styling per @ajacobs21e example*

*Note on this - input fields are the only component I "changed" the styling of for dark theme, rather than just switching the colors, so issues of this nature should be isolated to this instance.

**Comment by mcarrano** [comment]
Thanks for posting this update @mceledonia . I have opened this issue in the core repo that may also require some design support to help audit current variable usage: https://github.com/patternfly/patternfly/issues/3211

**Comment by ajacobs21e** [comment]
Dark theme buttons needed for Web https://sketch.cloud/s/3WK1w/a/w0bEb9

**Comment by mcarrano** [comment]
Adding links to component audit results: https://docs.google.com/document/d/1FFI4b0YIDcjgkX8sameeAHzkHuxYkIGWtgQFN3tgv9s/edit?usp=sharing and dark theme conversion spreadsheet: https://docs.google.com/spreadsheets/d/1nIXNC-4CJfEWYPMYpgQl3rr_aMRPOdx_Vjs-t08GjQk/edit?usp=sharing

**Comment by christianvogt** [comment]
@mcarrano when can we expect to have dark theme support?

**Comment by mcarrano** [comment]
@christianvogt we have been working on this in the background and are almost complete with the design work. I don't currently have a firm target date for delivery, but do you have I time frame that you will need this for product? That might give us something more concrete to work towards. It is something I'm hoping that we can deliver in a Q2-Q3 timeframe.

**Comment by serenamarie125** [comment]
@mcarrano OpenShift Console and Che/CRW are both eager to use the dark theme! I'm tagging @beaumorley here as well

**Comment by mcarrano** [comment]
All design issues are complete so I am going to close this epic. Thanks for all your efforts on this @doruskova @mceledonia

**Comment by septatrix** [comment]
Could someone please explain how to use the dark theme? I do not find any reference to it in the docs...

**Comment by mcarrano** [comment]
@septatrix dark theme is not yet available for general use. We currently have an alpha version that we are testing with selected projects and don't have any firm date on when this might be fully supported. If you can provide us with more information about your project and need for dark theme, that would be helpful. Thanks.

cc @evwilkin

**Comment by septatrix** [comment]
I am investigating alternative ui frameworks (to our current in-house solution) for the management and status dashboard of a new product. At this stage PF as well as IBM's framework look very promising for our vision of the look and seem to provide most required components/features.

A feature which would be very welcome is if it were possible to select the dark mode without js (so no switch via a mandatory `.dark` on the body) by e.g. using `prefers-color-scheme` media query in the css to set variables. JS override (or people who only want one theme) should then be possible by setting a class on the body/html element.

Regardless as long as this is not in the released version I would propose to reopen this issue to prevent any confusion.

**Comment by mcarrano** [comment]
@evwilkin @mcoker ^^^
