### ISSUE TITLE
Accordion box-shadow

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-design#757]
From https://github.com/patternfly/patternfly-next/issues/2375, we added a variation to the accordion component that removes the CSS `box-shadow`. After chatting with @mceledonia about it, we came to the conclusion that the shadow is not necessary and could be removed.

In this issue, I would like to determine if we should:

1. Leave the component as it is with the `box-shadow` enabled, and offer a variation to remove it.
2. Remove the existing `box-shadow` (since this is the most likely use case), and offer a variation to add it back as it is now.
3. Remove the `box-shadow`, and if a user would like a shadow around the accordion, they can place it inside a card component.
4. Something else?

Re: patternfly/patternfly-next#3, it's worth noting that the existing `box-shadow` on the accordion is `--pf-global--BoxShadow--md`, and the card's `box-shadow` is `--pf-global--BoxShadow--sm`.

cc @mcarrano

**Comment by mcarrano** [comment]
@lboehling @mceledonia Is this something that will be addressed as part of the effort to reduce usage of box shadows throughout the library?

**Comment by mcoker** [comment]
> Leave the component as it is with the box-shadow enabled, and offer a variation to remove it.

We ended up adding that variation to opt-out, but from what I remember, it should have never been implemented in the first place. It was added because the shadow existed in the design just to separate the component from the background in the design.

I'll go ahead and remove it as part of https://github.com/patternfly/patternfly-next/issues/2653 since it's not part of @lboehling's designs in https://marvelapp.com/dge08b4/screen/66345389. Let me know if we want to keep it - though if so, there was also a top and bottom padding above/below the accordion between the items and the outer box shadow that we'll need to adjust since that padding was set to `--pf-global--spacer--xl`

**Comment by mcarrano** [comment]
Thanks @mcoker . Yes, this makes sense. Should I just close this design issue out in that case?

**Comment by mcoker** [comment]
@mcarrano yep as long as we're all in agreement the component shouldn't have a box-shadow by default or as an opt-in. If a user wants a box shadow around the accordion, they should use it in a card or add a box shadow themselves either using our utility classes or add one manually.

**Comment by mcoker** [comment]
@mcarrano I think you can close this, these changes were merged in core http://patternfly-v4.surge.sh/documentation/core/components/accordion/
