### ISSUE TITLE
Add item counts to the select dropdown

### ISSUE THREAD

**Issue by bmignano** [patternfly/patternfly-design#759]
Add the option to provide the number of items that match a certain value in a select dropdown. For example "Running (0)". Example screenshot attached.
![nodes-future](https://user-images.githubusercontent.com/40238481/68043540-e7cba180-fcab-11e9-9064-a246af861785.png)

**Comment by mmenestr** [comment]
Possible other idea on how to present this --
![image.png](https://images.zenhubusercontent.com/5e750f70a086dc7bdce718bd/d369c85d-8d73-46ad-a8d3-dccec5c2a691)

**Comment by mcarrano** [comment]
@bmignano Is this still something that's needed?

**Comment by bmignano** [comment]
@mcarrano We have this today in OpenShift so it would be great if it could be added to PatternFly! Here's what we have implemented today:
<img width="1792" alt="Screen Shot 2020-09-09 at 12 56 41 PM" src="https://user-images.githubusercontent.com/40238481/92629167-e986ce00-f29b-11ea-8daa-00492d52f1b4.png">

**Comment by mcarrano** [comment]
OK. I will get this onto the PatternFly roadmap @bmignano

**Comment by mcarrano** [comment]
@mcoker See the screenshot above. Would it be straight forward to add an optional badge to menu items in the checkbox select? Would you require anything from design?

**Comment by mcoker** [comment]
Just from testing it, looks like the read background color is the same as the hover/focus background on the menu item. Is that OK?

<img width="286" alt="Screen Shot 2020-09-09 at 3 12 40 PM" src="https://user-images.githubusercontent.com/35148959/92648364-ec3eee80-f2ae-11ea-978e-5f73b03635e8.png">

**Comment by mcarrano** [comment]
Good catch @mcoker . In that case we may need to consider this more in design. @bmignano did you encounter that in the OS implementation? If so, how did you work around it?

**Comment by jcaianirh** [comment]
@mcoker @mcarrano for openshift we don't have a hover state over selections in the dropdown. The below state doesn't change when selections are hovered. 

![Screen Shot 2020-09-10 at 10 57 50 AM](https://user-images.githubusercontent.com/35978579/92749848-8147f300-f354-11ea-83f9-dfae30fa46a2.png)

**Comment by mmenestr** [comment]
I'm wondering if we could do what was proposed above, but change the badge color to a darker grey, just like was done for tree view and dual list to take the hover state into account!
I think the only proposal I'd make is potentially right aligning the badges so they are all ultimately vertically aligned with each other? But I don't feel too strongly, and I know that for tree view they're placed right after the text ends so maybe we should just keep it consistent.

![image](https://user-images.githubusercontent.com/51165119/100143876-f7dc9300-2e63-11eb-8565-9e3df35aca76.png)

**Comment by mcarrano** [comment]
I think that your proposal makes sense @mmenestr . Sorry it took so long to reply! I think that having the badges left-aligned after the label makes more sense because it reinforces the association. @mceledonia can you also take a look and let us know what you think?

**Comment by mceledonia** [comment]
I am in favor of the right-aligned approach, it makes the list easier to scan and would avoid any issues with wrapping. As far as badges or just a regular text count, I think either could work, but I like the look of the first screenshot @mmenestr posted where it uses secondary text color. 

I could see an oversized menu width causing some awkwardness, but that would be a result of a larger issue (fix the menu width, or shift the count column closer) and I think our hover/focus states would quickly alleviate any issues there. The difficulty of scanning a list of misaligned counts would also outweigh the fixable issues of the oversized menu widths.

The only hesitation I have with badges is having a list full of badges and then badges in a filter or chip group all in the same page, it could possibly get a little convoluted or imply some relationship between the counts. That might not be an issue either, but probably worth mocking it up to test as I could see it being a common occurrence.  

@mcarrano @bmignano @mmenestr

**Comment by mmenestr** [comment]
Here is a new proposal, after talking to @mceledonia and @maryshak1996 who both like this suggestion.
I've added it to the [ppt I had presented](https://docs.google.com/presentation/d/1mT-lRbd5RrF2xfD4xBd77k09XGUmTzu_eqLTdSeB_Lw/edit#slide=id.gbadec78527_0_31) at the PF design share - but here's a screenshot with the gist. @mcarrano let me know what you think!

![image](https://user-images.githubusercontent.com/51165119/107274354-3e329e80-6a1e-11eb-94e3-89d5794e2077.png)

**Comment by mcarrano** [comment]
I think this looks great @mmenestr . We will just need a spec for implementation.

@mcoker can you take a look at this to see if there are any issues? One question - can this be implemented so it can either be used in a dropdown as shown or within a drawer if we want to use the same approach in a Catalog view?

**Comment by mcoker** [comment]
This looks good to me. Thinking forward, just want to note we may consider how this count lives with other parts of a menu item. https://pf4.patternfly.org/components/menu#with-actions

> One question - can this be implemented so it can either be used in a dropdown as shown or within a drawer if we want to use the same approach in a Catalog view?

Are you referring to the filter side panel items here? https://patternfly-react.surge.sh/extensions/catalog-view-filter-side-panel

**Comment by mmenestr** [comment]
Yes @mcoker that's what he's referring to! Would want something like this: 
![image](https://user-images.githubusercontent.com/51165119/108272963-f5c36100-7140-11eb-9f1c-00fed137dde5.png)

**Comment by mmenestr** [comment]
@mcoker in terms of how this count would live with other menus types, I don't envision there being a need for a count for dropdown action menus, do you? I see this more in select lists that wouldn't have actions or favorites - ie: in filtering situations.

If you do though, I would probably space it the same way you have menus with favorites + an action:
![image](https://user-images.githubusercontent.com/51165119/108273580-b77a7180-7141-11eb-9a2f-0c9206b8169d.png)

**Comment by mmenestr** [comment]
Finally, here's the final idea with specs:
https://marvelapp.com/prototype/c18hjf1/screen/76910983

**Comment by mcoker** [comment]
@mmenestr thanks! 

> can this be implemented so it can either be used in a dropdown as shown or within a drawer if we want to use the same approach in a Catalog view

They would need to be separate enhancements. Off the top of my head, I'm not sure of the best way to to implement the catalog view filter panel items from core. Since that's a react extension, there are styles associated with the catalog view filter panel, but they don't come from core. And the check component is the core component used for the filter items (checkbox + text), and this count doesn't seem like an enhancement we would make to the checkbox component itself.

> I don't envision there being a need for a count for dropdown action menus, do you? I see this more in select lists that wouldn't have actions or favorites - ie: in filtering situations.

I agree, and the design you included looks good to me in the case that the count is used with a more complex menu. Since it's right-aligned, it just comes with the caveat that if used with menu items that have other right-aligned things, if one of the items doesn't have one of those things it no longer aligns properly. He's an exaggerated example.

<img width="331" alt="Screen Shot 2021-02-17 at 4 59 47 PM" src="https://user-images.githubusercontent.com/35148959/108279034-931e9500-7141-11eb-847d-4eb1341a8f23.png">

**Comment by mcarrano** [comment]
> They would need to be separate enhancements. Off the top of my head, I'm not sure of the best way to to implement the catalog view filter panel items from core. Since that's a react extension, there are styles associated with the catalog view filter panel, but they don't come from core. And the check component is the core component used for the filter items (checkbox + text), and this count doesn't seem like an enhancement we would make to the checkbox component itself.

Good points @mcoker . I guess that we need more discussion about how to build the filter panel. @mmenestr can you also add your design proposal to the issue here so we are sure to consider that when it comes time to implement the panel? https://github.com/patternfly/patternfly/issues/3472 Thanks.

**Comment by mmenestr** [comment]
Oh yeah that would be a problem. I did my mock assuming all items would have an action/favorite, or none of them, not a mix of having and not having haha. Well hopefully that won't be an issue since I don't see anyone doing this sort of combo.

Here is the mock/spec for the catalog view: https://marvelapp.com/prototype/c18hjf1/screen/76941197

**Comment by mcarrano** [comment]
I have opened https://github.com/patternfly/patternfly/issues/3902 to track core implementation as applied to the existing Select component.

**Comment by doruskova** [comment]
@mmenestr @mcarrano Do we need to include this feature also for toggles? Catalog view example is using "toggle with text" symbols and this issue requires adding this feature to a "dropdown menu item" symbol. There is different spacing. Thank you!

**Comment by mmenestr** [comment]
@doruskova ideally we want to use it in both dropdown menu items AND catalog view, since the use cases are the same (ie: showing matches for that filtering option)
