### ISSUE TITLE
Revisit shadow on drawer component overlay

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-design#762]
After talking with the OpenShift team, the request was made to distinguish between side panel push vs. overlay. Right now the shadow on the drawer component isn't consistent with the UI needs on OpenShift.

cc @mceledonia @maryshak1996

**Comment by mcarrano** [comment]
We do have an issue open here in Core to remove the drop shadow from the "push" panel as this issue suggests as part of the work needed to address Master-Detail: https://github.com/patternfly/patternfly-next/issues/2467 I will therefore close this one out.
