### ISSUE TITLE
Horizontal and vertical splitter bars

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-design#763]
The dev console would like to implement a design with horizontal  and vertical splitter bars which provides the ability to resize the window as seen in this design. 

<img width="909" alt="Screen Shot 2019-12-11 at 11 23 39 AM" src="https://user-images.githubusercontent.com/40275806/70639604-b4642700-1c08-11ea-8d36-c3342e7301d4.png">

Here is the functionality of splitter bars for reference:
https://www.fmsinc.com/MicrosoftAccess/controls/components/splliter-bar/index.html

cc @sunilmalagi @maryshak1996 @serenamarie125

**Comment by itsptk** [comment]
I am working on a design for the OpenShift admin console that is also interested in making use of a vertical splitter in the future:
https://docs.google.com/document/d/1n5_aeJVvuvvXw_1q1v_00slxzksslkgY3CfEK1TAvHE/edit

**Comment by mcarrano** [comment]
@doruskova I have assigned this issue to you per our discussion about creating a resizable panel for a tree browser. Please review other requirements here to be sure that your approach can satisfy these different use cases as well.

**Comment by doruskova** [comment]
@mcarrano I'm adding [mocks](https://marvelapp.com/8cdg211/screen/69469192) and [code preview](https://codepen.io/mdorusko/pen/BaoEWvy) for a splitter component. I tried to be minimalistic as much as possible. Appreciate every feedback about it :)

**Comment by mcarrano** [comment]
These look great @doruskova . Personally I like the with the icon that provides some visual affordance. I am going to set up some time to review with @mcoker and @mceledonia , also.

**Comment by doruskova** [comment]
@mcarrano I changed the color of the line for a better contrast [here](https://marvelapp.com/8cdg211/screen/69932685)
And the [next screen](https://marvelapp.com/8cdg211/screen/69941311) shows some examples of where we can or we shouldn't apply the splitter.

**Comment by mcarrano** [comment]
This definitely looks better IMO @doruskova . @mceledonia can you confirm? It will be helpful to identify the gray values to be used here for implementation.

Regarding the usage, I don't agree about the drawer. We have two types of drawers, one the splits the space and pushes the content and another that overlays content. In either case, I could see a case for resizing the drawer . In the overlay case, the user might want to make the drawer temporarily bigger to see more, even if it covers other content on the page. Does that make sense?

**Comment by doruskova** [comment]
@mcarrano oooh it makes sense. Thanks for this clarification! I'll change the guide.
