### ISSUE TITLE
Sticky header (and footer)

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design#768]
We would like an option for a sticky header. This sticky header would remain, well, sticky, while the user scrolls. 
This would likely be useful on mobile as well as desktop.

cc @KendraMar 
cc @ajacobs21e - wondering if you would also need this in designs

**Comment by KendraMar** [comment]
@katierik @mcarrano Thinking that this could be a good assignment for Maria Svirikova.

@katierik let's talk tomorrow?

**Comment by mcarrano** [comment]
I'm feeling like this needs more definition before assigning a designer. What exactly are we trying to make sticky? I see a couple of unrelated things mentioned in this issue. One looks like a request for a sticky page header. The other request looks to address column headers in tables. Are there others? These would result in changes to separate components and can be mutually exclusive.

**Comment by KendraMar** [comment]
agreed. That's why I think we could have Maria Svirikova research this. She would need Katie's guidance, tho, so it's dependent on Katie's time.

**Comment by mcarrano** [comment]
@katierik @KendraMar That's fine. Just let me know how you want to proceed.

**Comment by mcarrano** [comment]
This article includes some interesting findings on the usability and accessibility of sticky elements: https://technology.blog.gov.uk/2018/05/21/sticky-elements-functionality-and-accessibility-testing/

**Comment by KendraMar** [comment]
Appreciate that, Matt. 

@katierik know you're flat out currently, but wondering if you could work with Maria S (have her run with it) to pursue it?

**Comment by katierik** [comment]
Looping around on this - @MariSvirik and I are meeting to kick off this research Tues Feb 18

**Comment by gdoyle1** [comment]
Related to #834 - I'll take a look at the research provided and then add mocks for sticky headers and footers for tables, data lists, and card views

**Comment by gdoyle1** [comment]
Here's what I've come up with so far! https://marvelapp.com/prototype/79affd0 - feel free to comment on the marvel. I will be gathering more feedback today at the PF weekly stakeholder meeting as well

cc: @mcarrano @katierik @KendraMar

**Comment by katierik** [comment]
This looks good! 
I wonder how it would work with a situation like this, with tabs? (This is one of the *exact* screens that we are considering adding a sticky header to)
![Xnip2020-07-30_10-03-47](https://user-images.githubusercontent.com/23172038/88932375-fb606480-d24b-11ea-833f-5832a6f99dc4.jpg)

**Comment by gdoyle1** [comment]
@katierik thanks for adding that use case! I'll add an example of that to the marvel project too
