### ISSUE TITLE
* List View: Data Toolbar should be Toolbar 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#77]
On the list view page [1], replace all instances of "Data Toolbar" with "Toolbar" and link them over to the Toolbar pattern here: http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/

[1] http://www.patternfly.org/pattern-library/content-views/list-view/#/api

**Comment by catrobson** [comment]
I'm working on this issue.

**Comment by LHinson** [comment]
can still be seen here: https://github.com/patternfly/patternfly-design/blob/master/pattern-library/content-views/list-view/design/design.md
