### ISSUE TITLE
Introduce multi-select search with attribute-value pairs

### ISSUE THREAD

**Issue by yih-wang** [patternfly/patternfly-design#771]
Keycloak needs a filter pattern that supports multiple criteria. There are some reasons that the current Faceted filter and Multiple filters don't fit our use case.

- There can be more than 5 criteria, so there aren't enough spaces for multiple filters.
- For each attribute, there can be thousands of options so a faceted filter cannot cover that.

I have also considered applying multiple attribute-value filters. But it is unpractical due to the technical limitation. Iterated filtering needs too much effort on the server-side to be implemented.

An assumed pattern for us is, there will be a search box allowing the free search. A dropdown with a form will be attached to it. Users can fill in the form to limit all the criteria. And the search will be conducted by the Search button in the form.

What's more, the filter will support the search operator. That is, users can directly input "username:hwang firstname:haley" instead of filling the form.

I'm not sure if the Expression Builder would fit our use case. As there isn't a guideline for it.

**Comment by mcarrano** [comment]
I'd like to consider how this can be addressed be modifying the current type-ahead select component by specifying an attribute-value pair in the form 'attribute:value' vs. just a single value. I've transferred this to design and will queue for roadmap consideration.

@yih-wang if you have design ideas given the above, I'd be happy to work with you on this.

**Comment by yih-wang** [comment]
@mcarrano I have talked with developers about the type-ahead technic. In our use case, it may not be able to be implemented. Because in Keycloak, the data is very large and there can be multiple servers to be searched in. The querying cost of type-ahead is too expensive.

**Comment by mcarrano** [comment]
@yih-wang Thanks for clarifying that. I've updated the issue to remove the reference for type-ahead. Do you have a design for this in mind? What I think would be helpful would be to see a conceptual design for this. I can then share that to see if this is something we would add to PatternFly. It may too product specific. If it seems like KeyCloak should implement a custom component, we do have a dropdown that exposes an empty panel where you can add necessary controls. See https://www.patternfly.org/v4/documentation/react/components/dropdown#basic-panel

**Comment by yih-wang** [comment]
@mcarrano I drew a simple sketch based on the quick idea from my mind. Hope it helps!

![Filter sketch](https://user-images.githubusercontent.com/23331885/71164460-10beea80-228a-11ea-872d-8d433fe4d398.png)

**Comment by mcarrano** [comment]
@mcoker Could this be built using an Input Group? My thinking is to combine a text field with a button to toggle the search form. The form can be contained in a popover, I think. Would that work or do you have another idea?

**Comment by mcoker** [comment]
@mcarrano I think you could. Here is an input group with 2 buttons (search and arrow for toggle). From there, clicking the arrow button could trigger a popover.

<img width="439" alt="Screen Shot 2019-12-20 at 10 36 03 AM" src="https://user-images.githubusercontent.com/35148959/71269282-98e9d200-2314-11ea-8edc-6331e00278f5.png">

You could also get close by using a dropdown component in place of the down arrow.

<img width="442" alt="Screen Shot 2019-12-20 at 10 35 43 AM" src="https://user-images.githubusercontent.com/35148959/71269371-c2a2f900-2314-11ea-85ac-64ec8f5badb1.png">

**Comment by mcarrano** [comment]
Thanks for looking into this @mcoker . I'm not even sure the Search button is needed as the way I understand this, one would either just type into the field or open the popup panel.

@yih-wang can you run this past the KeyCloak team for consideration? If this works, we may not need a new component.

**Comment by yih-wang** [comment]
@mcarrano Sure. I'll do that. Thanks @mcarrano and @mcoker !

**Comment by yih-wang** [comment]
@mcarrano After discussed with the Keycloak team, we're wondering whether we can contribute the pattern/code to PatternFly. This kind of filter is frequently used in many places (Google, Github, etc.).

I drafted several options for the concept design - https://marvelapp.com/7gb4j6h/screen/65584421   Please have a look and tell me your idea, thanks.

**Comment by mcarrano** [comment]
Thanks for providing your designs for this @yih-wang . I do think that this is something that is needed in PatternFly as I have gotten similar requests from other teams that are looking for something that functions more like a search against a large set of possible values vs. what we are currently calling a multi-select filter. I've renamed the issue to change 'filter' to 'search' to better describe what this is.

But before I say yes to contributing this, I wanted to compare it with other approaches to make sure we have a common design that would work across products. @KendraMar @katierik @terezanovotna can you take a look at what is being proposed here? Will this work for your use cases? Can you share any similar designs you are working on for the Management platform to support attribute-value searches?

**Comment by mcarrano** [comment]
@yih-wang It's been a while since we connected on this. We have since introduced a new [Search input component](https://www.patternfly.org/v4/components/search-input). This does not have all of the features you requested, but I think it would make sense to extend that component.

Is this still something that is needed or have your requirements changed? I currently have this on our roadmap for December, but need to define better what this should be. Will be happy to chat further about this.

**Comment by yih-wang** [comment]
Hi @mcarrano, I just had a discussion with the engineering team. We still need this component and it's better to have that before February 2021. As we'll apply this search feature in the release next year.

The Search input component is not suitable for our use cases because we cannot support real-time searching. And we do need multiple attributes as limitations in one search.

**Comment by mcarrano** [comment]
@yih-wang I took another look at your designs. We can modify the Search Input to only trigger the search when you click the search button (not real-time searching), and drop down a panel when you can construct any search form you want for advanced searching. Parsing the contents of a search string in the form of an attribute-value pair would be the responsibility of the application using this, I think, since that becomes pretty application specific. 

I will work on some designs and run then by you. At this point, getting this into a release before February is not possible. I can target to have this available as a React component by mid-February. Will that work?

**Comment by yih-wang** [comment]
@mcarrano That sounds great! Thanks! The timeline makes sense as that I meant before Feb ends. If you need any f2f discussion, feel free to find a time in my calendar :)

**Comment by mcarrano** [comment]
@yih-wang I've done some work on the design with the goal of getting this into our January milestone to begin work on implementation. I would like to extend the existing Search input component to cover your use case as I think this is the natural placement of this. Here is a link to my preliminary design: https://marvelapp.com/prototype/276i4086/screen/75410726 

Let me know if this works, If we need to discuss, I'll be glad to set up some time next week. It is similar to your design, but uses a popover in place of a dropdown to expose the search form. Feel free to leave comments directly in the Marvel document.

**Comment by mcarrano** [comment]
Preliminary design options for review and comment: https://marvelapp.com/prototype/276i4086

**Comment by mcarrano** [comment]
@yih-wang I made some updates to accommodate feedback from the meeting today. Here is the latest set of designs: https://marvelapp.com/prototype/276i4086  Let me know if this will work for you. Next steps will be to review with our technical team. I'd like to get this into the development sprint that starts after the US shutdown.

@mceledonia it would be good if you can also take a look. The only thing that is new/unique from a visual standpoint is that I added an optional auto-complete to the text box. We currently don't have text styling for this so any advise on specific text colors to use would be helpful.

**Comment by yih-wang** [comment]
@mcarrano Thanks for the updates! The designs look great! I left some comments on the wireframe. The timeline sounds good to me, thanks!

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/3771 to begin core implementation.
