### ISSUE TITLE
Definition List - Create underline link variation

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-design#772]
On the OpenShift side we've added an option for field level help to have an underline option for the field level help indicator. This is useful when there are a lot of these popovers on a single page, it avoids having an overload of help icons. 
It could be a useful option to provide through PatternFly to have consistency across products.
@mcarrano we could possibly just document this if we don't want to provide the modifier. 
![image](https://user-images.githubusercontent.com/287880/67289887-b38b0080-f4b5-11e9-8ba7-17c468a52d3b.png)

**Comment by andybraren** [comment]
I've created [this (internal) doc](https://docs.google.com/document/d/1t_ojtWYwjhT6Vu0MzHrsArsqwQ2UpXlufLNzUIpZ9cE/edit#) that covers some of the product use cases we've bumped into. I wonder if it'd be worth doing some user research to solidify a recommendation around when to use which patterns. FYI @mcarrano @rachael-phillips

**Comment by mcarrano** [comment]
@andybraren I read through your document. Thank you for pulling this together! It is an excellent overview of the problem and possible solutions. I'd be in favor of talking further about how to move this forward. Right now we do not have the ability to add an underline link to a text label so that would require a component enhancement. @LHinson is this something we should get on our roadmap?

**Comment by mcarrano** [comment]
Let's consider this as an enhancement for description lists.

**Comment by maryshak1996** [comment]
@mcarrano @matthewcarleton @andybraren hey friends :) based on the conversations that I saw above, it *seems* like there has been a lot of thought put into the proposed design (grey dashed underline), so I mocked up that design and just provided accessible colors, if you guys want to take a look here: https://marvelapp.com/prototype/7j26ab6

**Comment by kevinhatchoua** [comment]
Hi @maryshak1996, what was the solution to address Jenn's point regarding the 'link' states?

**Comment by mcarrano** [comment]
Looks good @maryshak1996 . I'd also like to add @mcoker and @mattnolting to this review. The proposal is to apply this optional label styling to the definition list component, only.

**Comment by mattnolting** [comment]
@mcarrano @maryshak1996 This looks pretty straightforward to me, the approach being attaching a modifier to `.pf-c-description-list__term` and/or `pf-c-description-list__text` (which could be reused in, say body text if needed) to apply the underline. 

Pertinent CSS properties:
```
text-decoration: underline;
text-decoration-style: dashed;
text-underline-offset: 8px; (works across FF, Safari, Chrome)
```

**Comment by maryshak1996** [comment]
> Hi @maryshak1996, what was the solution to address Jenn's point regarding the 'link' states?

Hey @kevinhatchoua what comment are you referring to? Maybe I'm missing it somewhere haha

**Comment by maryshak1996** [comment]
@mattnolting that approach definitely makes sense to me (assuming that the color be included in the css declarations as well as recommended in the marvel doc)

**Comment by andybraren** [comment]
Your design spec is looking great @maryshak1996!

I think Kevin is referring to this bit from Jenn:

> I would say the example of the default state (dotted underline) is sufficient to pass WCAG requirements, and that the color shown is fine. I would also suggest there is an additional visual style change on hover/focus. That can be a change in color, underline, border, background, etc...

Right now OpenShift's UI changes the dotted underline's color to an almost imperceptibly darker shade of grey on hover (the middle one seen below) and that's it. Probably not clear enough. 🙂

Either a much darker color or maybe transforming into a non-dotted underline on hover seems like a viable solution to that accessibility issue. Either one should probably be codified into the component.

> Ultimately I'd say that whatever we end up with should probably be evaluated with user testing to catch any potential issues.

+1, this seems like a good candidate for some unmoderated research.

![image](https://user-images.githubusercontent.com/9122899/104963842-55dfaf80-59a9-11eb-9745-0f976dd1a5f5.png)

**Comment by kevinhatchoua** [comment]
> I feel like this is one of the hardest challenges with a11y, both in understanding requirements and meeting them.
> 
> Here are some links that touch on these topics:
> 
> * The default state should be distinct from the hover/focus styles. This is noted in [WCAG technique C15](https://www.w3.org/WAI/WCAG21/Techniques/css/C15)
> * There are some resources that talk about the visual presentation of the default state. This first link leads me to believe that there is flexibility in how we decide to style elements (e.g. buttons don't need to look like buttons), and the other links talks about interactive elements that are embedded with other contents being visually distinct.
>   
>   * [Understanding Success Criterion 1.4.11: Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) - I think one of key statements in this guide is the following about Buttons under the section **Active User Interface Component Examples**
>     > A button which has a distinguishing indicator such as **position**, **text style**, or **context** does not need a contrasting visual indicator to show that it is a button, although some users are likely to identify a button with an outline that meets contrast requirements more easily.
>   * [Using a contrast ratio of 3:1 with surrounding text and providing additional visual cues on focus for links or controls where color alone is used to identify them](https://www.w3.org/WAI/WCAG21/Techniques/general/G183)
>   * [Ensuring that additional visual cues are available when text color differences are used to convey information](https://www.w3.org/WAI/WCAG21/Techniques/general/G182)
> 
> My take-away from these resources is that there should be some distinguishing factor visually to identify elements as interactive. But it's open to interpretation on what that factor is.
> 
> I would say the example of the default state (dotted underline) is sufficient to pass WCAG requirements, and that the color shown is fine. I would also suggest there is an additional visual style change on hover/focus. That can be a change in color, underline, border, background, etc...
> 
> Ultimately I'd say that whatever we end up with should probably be evaluated with user testing to catch any potential issues.

@maryshak1996 This is the comment I was referring to. It dates back to 2019, so I was wondering if it was already addressed. :)

**Comment by maryshak1996** [comment]
@andybraren @kevinhatchoua ahhhhhhh thank you for clarifying! Ya I'll take a look at hover and focus states here too -- totally didn't consider those yet, so thank you!!

**Comment by maryshak1996** [comment]
@andybraren @kevinhatchoua @mcarrano I updated this in the Marvel as well, but here's what I had in mind for hover and focus:

![image](https://user-images.githubusercontent.com/19824574/105089886-b20b0800-5a6b-11eb-9dd6-0666be984b69.png)

**Comment by kevinhatchoua** [comment]
Thanks @maryshak1996 ! I think this is definitely a step in the right direction. Can you mock it up with a popover open within a form? just for context. Otherwise it LGTM.

**Comment by mcarrano** [comment]
@kevinhatchoua just to clarify, we will not use this in a form. We decided to restrict this pattern to the definition list, only. Forms will still use the popover help triggered by the (?) icon.

**Comment by mcarrano** [comment]
@maryshak1996 regarding the hover and focus states, I think that they are fine. Should be enough contrast. @mceledonia can you also take a look?

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/3808 to begin core implementation.
