### ISSUE TITLE
add context menu component

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-design#774]
**Describe the issue. What is the expected and unexpected behavior?**
Topology component has a need to bring up a context menu:
![image](https://user-images.githubusercontent.com/14068621/69552737-fafd2480-0f6c-11ea-833f-22e9582305d2.png)

- Ability to open a context menu popover a specific x, y coordinate identified by the mouse click event.
- Popover should open to the bottom right of the specified coordinate.
- Popver should flip and orient itself accordingly to open and remain visible on screen.
- Menu should receive focus on open.
- Menu should support keyboard navigation through the list of menu actions.
- Menu should trap focus.
- Popover should request close on escape, click outside, or action selected.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Our workaround has been very involved. We first created a `Popper` component to handle positioning much like tippy.js. Then we had to mimic the dropdown structure and override some styles to make it work. The end result works great however it would be nice to see a standard popover component in patternfly that's generic for these situations as well as a generic menu component that doesn't require hacking around the dropdown menu.

```
<Popper
      {...other}
      closeOnEsc
      closeOnOutsideClick
      open={isOpen}
      onRequestClose={handleOnRequestClose}
    >
      <DropdownContext.Provider
        value={{
          onSelect: handleOnRequestClose,
          toggleTextClass: styles.dropdownToggleText,
          toggleIconClass: styles.dropdownToggleIcon,
          menuClass: styles.dropdownMenu,
          itemClass: styles.dropdownMenuItem,
          toggleClass: styles.dropdownToggle,
          baseClass: styles.dropdown,
          baseComponent: 'div',
          sectionClass: styles.dropdownGroup,
          sectionTitleClass: styles.dropdownGroupTitle,
          sectionComponent: 'section',
          disabledClass: styles.modifiers.disabled,
          hoverClass: styles.modifiers.hover,
          separatorClass: styles.dropdownSeparator,
        }}
      >
        <div className="pf-c-dropdown pf-m-expanded">
          <DropdownMenu className="pf-c-dropdown__menu topology-context-menu" autoFocus>
            {children}
          </DropdownMenu>
        </div>
      </DropdownContext.Provider>
    </Popper>
```

**What is your product and what release version are you targeting?**
OpenShift web console 4.4

cc @jeff-phillips-18

**Comment by doruskova** [comment]
@mcarrano Hey there! Sorry for my delayed answer. I've been working on an exploration of contextual menus and here's my summary [Context menu- story mocks link](https://marvelapp.com/dhj94fe)

Here are my findings in short: 

- The context menu should contain a small set of relevant actions. 
- Keep the list length manageable by including fewer than 10-12 items. 
- It usually includes just 1 flyout submenu. 
- For hidden contextual menus (this case) >> perform actions that don’t rely on gestures. For Topology View is the list of actions also included in the dropdown of Pod/Cluster/Node detail.  

From my point of view, the flyout menu for context menu and for this use-case is suitable because the context menu needs to be short and easy to use. The other solutions such as drill down or accordion tend to hide more and more items. And it goes against the definition of the context menu.

**Comment by mcarrano** [comment]
@doruskova I really like this approach. @mceledonia @maryshak1996 @mattnolting can you also take a look at this? I just want to make sure the way we collapse the menu into a drill-down on mobile is consistent with what we are planning to do with the masthead and overflow menus.

**Comment by maryshak1996** [comment]
@doruskova I think that, on mobile, this mimicks what we have proposed for masthead responsiveness pretty closely. The main thing that seems to differ is the use of blue text in yours versus black text in the masthead mobile dropdown (https://marvelapp.com/5cjajdg/screen/63256959)

**Comment by doruskova** [comment]
@maryshak1996 yes, that's the only difference (blue/black color). I used a blue color because I wanted to visually differentiate the current position. But, I like your approach too.

**Comment by doruskova** [comment]
The blue text was changed to black, so the mocks should be up to date. [Marvel mocks](https://marvelapp.com/dhj94fe)

**Comment by doruskova** [comment]
@mcarrano So, I'm adding this guideline for dev with padding etc. for a clear description. 
You can see it [here in Marvel](https://marvelapp.com/dhj94fe/screen/67940185). 
<img width="1071" alt="preview" src="https://user-images.githubusercontent.com/32618096/78674178-81dee800-78e3-11ea-87bc-8cfaa8c7ae82.png">

**Comment by mcarrano** [comment]
@doruskova thank you for your efforts on this. I have opened https://github.com/patternfly/patternfly/issues/2950 in the core repo to track implementation work and added to milestone 2020.07

cc @LHinson
