### ISSUE TITLE
Define spacing for inputs in the same form group

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#776]
Identify the appropriate spacing for stacked form elements when placed within the same form-group. This is a follow up to the issue here: https://github.com/patternfly/patternfly-next/issues/2489

**Comment by kybaker** [comment]
@mcoker This should be a simple exercise where we can just add a sm spacer. It would be best to see this int he browser.

@mcarrano I think we can move this out of visual design.

**Comment by mcarrano** [comment]
This is complete. Handed off to CSS.
