### ISSUE TITLE
card: add support for expandable card

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#777]
Request from the OpenShift Developer team for expandable card support.

In ODC we display cards representing builder images (each card would have an icon and label associated with them) in one of our flows.  The user needs to select a single builder image.  The user needs to be able to view a brief description and optionally select a version, if more than one version is available.  We are currently planning on doing this in PF3 with an expandable card

We are requesting similar support in PF4 for this same use case.  If there's an alternative design/pattern to achieve the same results, please let us know.

FYI @mcarrano @gdoyle1 @kybaker

**Comment by mcarrano** [comment]
@serenamarie125 I am working with @LHinson to do some issue clean-up and wanted to revisit this request as it has been sitting in our backlog for a while.  Is this still something that is needed? We are currently in the process of introducing a master-detail view and I'm wondering if that could be used to solve this problem. See this mockup, for example: https://marvelapp.com/9iefh5b/screen/63807611  I wonder if that can be a more universal solution for this use case. I believe this is being adopted by OS console and some Integration projects.

**Comment by mcarrano** [comment]
@rachael-phillips This request is quite stale. Is it still something that is needed in the Dev Console?

**Comment by rachael-phillips** [comment]
Hey Matt, I just chatted with DevTools team, and we can close this. I will close now, and feel free to reopen if deemed relevant. Thanks for following up on this!
