### ISSUE TITLE
* Table View: Data Toolbar should be Toolbar 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#78]
On the table view page [1], replace all instances of "Data Toolbar" with "Toolbar" and link them over to the Toolbar pattern here: http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/

[1] http://www.patternfly.org/pattern-library/content-views/table-view/

**Comment by catrobson** [comment]
I'm working on this issue.

**Comment by LHinson** [comment]
Addressed with PR #93
