### ISSUE TITLE
Console demo needed 

### ISSUE THREAD

**Issue by lwrigh** [patternfly/patternfly-design#781]
We have a console component in RHV that allows the user to view their VM in browser. A PF4 component for this will be necessary for a PF4 migration in RHV. 

Current console page: 
![52848569-5ca37f00-310f-11e9-9c71-8e236645ab01](https://user-images.githubusercontent.com/20227374/57137719-b7e42580-6d7e-11e9-96d0-c3fc8dc460ef.png)

**Comment by lwrigh** [comment]
> Agree @lizsurette . My thinking is that from a PF perspective, this may be just a container where someone can drop anything - a console, terminal window, or even an editor. The ability to make this go full screen is an important requirement and would be a useful add to PF IMO. Going to pull this into the PF design backlog for further consideration. @rachael-phillips @LHinson should evaluate for roadmap prioritization.

Those design requirements for the console sounds good to me.

**Comment by rachael-phillips** [comment]
@mcarrano a horizontal drawer will be needed for the OpenShift implementation of the terminal: https://docs.google.com/document/d/1uVDz1FucVtuzhENq5rlyzYjeB6pWsKf0oEMudMMR_dA/edit#

**Comment by mcarrano** [comment]
After discussions with @mcoker about how to approach this I have opened two new core issues:

* https://github.com/patternfly/patternfly/issues/2948 adds a horizontal version of the Drawer component.

* https://github.com/patternfly/patternfly/issues/2949 introduces a new component that enables the user to take content full screen.

Once these enhancements are available, it will be possible to create this Console as a demo. Therefore I have changed this issue from Console Component to Console Demo and will keep it open as a design issue to track design mocks for that demo.

cc @LHinson @rachael-phillips

**Comment by mcarrano** [comment]
@lwrigh @lizsurette is there still a product need for this? The original issue is quite old. We expect to be introducing both a horizontal drawer and draggable splitter component over the next two releases that would enable this functionality. The ability to go full-screen is opened in our backlog but not currently scheduled. We can also build a patternFly demo to show how these can be used together in a page, but a "console" is a bit out of scope for PatternFly.

Let me know what currently needs/expectations are here and I can get this on the roadmap if needed.

**Comment by lwrigh** [comment]
No problem for the time being this component isn't needed anymore.

**Comment by mcarrano** [comment]
Thanks, @lwrigh . I am going to close in that case. We can always revisit in the future if that changes.
