### ISSUE TITLE
Audit the PatternFly icon sets 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#787]
Audit the icon sets and identify discrepancies so we can file issues to continue to improve that icons and their definitions. 

Action items: 

- [x] Replace the current PF4 icon page with an "under construction" page
- [x] Review proposed icon selections with Michael
- [x] Streamline the spreadsheet to only include those selections, ensure it includes all icons from the Sketch toolkit

-----
Icon docs on patternfly.org https://www.patternfly.org/v4/design-guidelines/styles/icons
Core icons https://pf4.patternfly.org/icons/
React icons https://patternfly-react.surge.sh/patternfly-4/icons/

**Comment by mcarrano** [comment]
@bdellasc thanks for providing the summary of our meeting. @LHinson @rachael-phillips I have transferred this issue to patternfly-design for future tracking. Once we complete steps 1-3 above, I believe this issue can be closed and I will open new issues in patternfly-org to make corresponding website updates. 

Regarding #1 above, we feel like the current Icons page on the website is misleading and may only cause confusion. In the interim, we believe that page should either be taken down or marked with a disclaimer. Is that something we can consider @rachael-phillips ? Let's discuss.

**Comment by rachael-phillips** [comment]
Yes, I agree @mcarrano. In the meantime we need to decide how developers will access the icons and provide them instructions.

**Comment by bdellasc** [comment]
I'm adding the existing usage content (from PF3 site) to my spreadsheet. The additional usage content gaps would need to be a separate story. Regarding the content strings for each icon, I'm not sure who would add that to the table as I'm not familiar with how the underlying icon calls are set up in the code.

**After the new consolidated icon table is posted**
If folks are using some of the icons from the old PF4 page, and some of those icons do not return, how do we migrate them to the new replacement icon if their icon was replaced in the recommendations? I believe it's an issue you and I spoke about @LHinson when we first started discussing this effort.

If those icons would still be present in the toolkit (albeit not documented anymore), then they shouldn't disappear for the consumers of those icons at rollout of this new reference page. But in the interests of getting eventual icon consistency across all consumers, would the calls to the new icons need to be changed by consumers to point to the new icon version? I think this aspect is a migration step, but my sense is that it falls outside the bounds of this story.

**Comment by mcarrano** [comment]
Thanks for the update @bdellasc . My understanding is that we would not be removing any icons from the code base as not to break anyone. Perhaps on the webpage we could add a section for deprecated icons that shows mapping to the updated recommendation to make it easier for consumers to complete the migration.

**Comment by bdellasc** [comment]
Update: I met with @gdoyle1 and @mceledonia this morning to review the questions and open issues in the spreadsheet. Since that conversation, I've gone through the content and added next step notes on the icons we spoke about. The notes include:

- requests for Gina to add the agreed icons to the design toolkit
- "usage" content questions 
- open questions for the wider team
- suggestions for usage gaps

https://docs.google.com/spreadsheets/d/1FwcP3qQm6zseNT-MKM2BwEmlu1La6KSmWe7i-9JzNFw/edit?usp=sharing

**Comment by bdellasc** [comment]
Update: Met with @gdoyle1 and @mceledonia to go through the icon list and get clarifications on open questions. After that conversation, completed the following: added  "Usage" text suggestions for most of the icons in the list and "To Do" text. The "To Do" text includes:

- Requests for icon additions/deletions from the design tool kit
- Clarifications for a few icons RE: usage text
- potential SVG fixes (for PF icons)

**Asks of the wider team:**

- Review of usage text suggestions
- Input RE: which sort icons to use? Alpha, numeric, bars? Bars seems to be the most language -neutral
- Any other comments

https://docs.google.com/spreadsheets/d/1FwcP3qQm6zseNT-MKM2BwEmlu1La6KSmWe7i-9JzNFw/edit?usp=sharing

**Comment by bdellasc** [comment]
Here is a PDF of the spreadsheet as well, just in case the online one is slow in loading (given the number of icon images embedded in it)

[PatternFlyIcons-31Jan2020.pdf](https://github.com/patternfly/patternfly-design/files/4141668/PatternFlyIcons-31Jan2020.pdf)

**Comment by mcarrano** [comment]
@bdellasc This is great work! I did review the spreadsheet and left a bunch of comments and questions. Let me know if you'd like to go through those live. Looks like we are close to being able to move on to next steps.

**Comment by bdellasc** [comment]
Thanks @mcarrano. Here's the status of the spreadsheet:
- icons with open questions are marked in yellow (12)
- icons that need to be added(?) to the PF font are marked in blue (5)
- icons that have been replaced and will be added to the migration table are marked in pink (9) 
- usage suggestions are prepended with "Suggestion:"

Next steps:
- Spoke with @mceledonia, @gdoyle1 and @LHinson - everyone agreed we can just use the standard PF table to display the data. I believe the columns we want are: Icon, Name, Font Set, Usage. We'll probably also want sort and filter as well?
- We can include all icons in the spreadsheet in this table
- For now, we can include all usage text that doesn't have any open questions
- The handful of icons that are missing from the PF font (marked in blue) and may need to be added. [SVG files](https://drive.google.com/open?id=1lzCgQHUTb7DXHceKniW6ZbFXl8HiLO5d)

**Comment by mcarrano** [comment]
Thanks for all of your hard work on this @bdellasc . I have opened a new issue in patternfly-org to update the website: https://github.com/patternfly/patternfly-org/issues/1687 and will close this out. @LHinson @gdoyle1 do we need any additional issues for Sketch Library or Font updates?

**Comment by bdellasc** [comment]
@mcarrano I'm putting together two follow-up issues to this one that I spoke with @LHinson about a little while ago.

**Comment by gdoyle1** [comment]
@mcarrano I have an icons issue assigned to myself for the design kit that I have already finished! https://github.com/patternfly/patternfly-design-kit/issues/162 . Have yet to merge until I review it with Michael to ensure the new sizes are correct
