### ISSUE TITLE
Topology View - Round 2 Design Solutions

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-design#788]
Ref patternfly/patternfly-next#1718 

The latest topology efforts have surfaced a number of design needs which should be solved in order to provide a more complete foundational topology graph component. Design problems to solve:

-  **Groups within groups** within groups within groups styling pattern - `visuals` - Offer a solution which scales elegantly for any number of nested groups. // **[DESIGN PROPOSAL](https://marvelapp.com/1id81c16/screen/61993516)**
-  **Scaling for large numbers of nodes and zoom levels** - `visuals, ixd, dev` - Offer a solution which balances performance with functionality.
-  **Highest zoom level** - `visuals, ixd` - Related to the above. How do we effectively summarize information at the highest zoom level, also a balance of performance and functionality.
- **Group preview** - `visuals, ixd` - I believe this relates directly to above, probably could use the same pattern. Some way to summarize the items contained in a node group in a condensed and effective way.
-  **Hide/show functionality design** - `visuals, ixd` - Ability for the user to hide/show various elements of the topology graph - Mainly indicators such as labels/tags, actions, edge information, etc. 
-  **Filter functionality** - `visuals`  - How do we visualize nodes which have been found through a filter/search?
-  **Animation tweaks** - `visuals, ixd, dev` - Fine tuning the physics of nodes and how they move. Do we want them to move at all? Do we offer both options to the dev? To the user?
-  **Layout pass** - `ixd, dev` - Do we want the ability to reset to a default layout, or lock to the current layout? Do we offer a second layout option which is a fixed tree-like view?
- **Drag/Drop vs move** - `ixd` - Clicking and dragging a node to reposition it is a standard interaction pattern. But with the introduction of node groups we introduce more complexity here. When a user clicks and drags a node within a group, how do we know if they want to reposition the node, remove it from the group, or both? We should support both actions in an intuitive way.

FYI
@mcarrano @LHinson @rachael-phillips @serenamarie125 @Veethika @jeff-phillips-18 

[Refactored from below]

~~Topology task - redesign a screen from cloudforms to update visual styling to current PF4 topology designs. Look for areas of easy overlap and potential opportunities of improvement with new visuals.~~

**Comment by mcarrano** [comment]
Move to backlog for now. No current activity.

**Comment by mcarrano** [comment]
@mceledonia Any reason to keep this open?

**Comment by mceledonia** [comment]
@mcarrano Nope, this effort has been put on pause while we focus on the next few PatternFly releases.

**Comment by mcarrano** [comment]
OK. I will close then.
