### ISSUE TITLE
Patternfly next login at maximum width on wide screen monitors is frustrating placed

### ISSUE THREAD

**Issue by smarterclayton** [patternfly/patternfly-design#796]
Login is a pretty key interaction for users, and the placement of the Login box to the far left of a very wide screen (especially in multi-monitor setups) is unpleasant to use.  The point of the page is to get the user to fill two text boxes, but the left alignment feels unnatural compared to every other login page (which are more visually centered).

(on a widescreen 16x9): https://www.dropbox.com/s/9gzuqtdmsknrtuz/Screenshot%202020-01-20%2010.52.56.png?dl=0

Can we visually shift the login box 1/6 or so towards the center at the most extreme widths?  That would reduce the effort on the user's part while still preserving the ability to visually style the right portion of the page with branding backgrounds.

**Comment by mcarrano** [comment]
@mceledonia please add details of your proposal for login redesign here. Thanks.

**Comment by mcarrano** [comment]
@mcoker has this been addressed? If so I will close out this design issue.

**Comment by mcoker** [comment]
@mcarrano yes, this was merged in https://github.com/patternfly/patternfly-next/pull/2754 and available in `@patternfly/patternfly@2.66.0`. The new layout will be available in the react component in the upcoming release next week.

**Comment by mcarrano** [comment]
Thanks @mcoker  and @mceledonia . I will close this then.
