### ISSUE TITLE
Update branding for downstream (RCUE)

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#797]
This issue is to track visual design work required to create a RH theme.

cc @mceledonia @LHinson

**Comment by mceledonia** [comment]
Slide deck with current progress [here](https://docs.google.com/presentation/d/1jkTW0dl_DSYMh6oyZUpdANczX6TVvI3VH5MVmc-jcP4/edit?usp=sharing)

**Comment by ajacobs21e** [comment]
@mcarrano is there a plan for when we'll start work on #2 from Michael's deck?

> Smaller/granular UI alignments which add up to a notable shift in look-and-feel.

**Comment by mcarrano** [comment]
No, not really @ajacobs21e . Are there specific things that you are looking for? From this statement I don't know what we're referring to.

cc @mceledonia

**Comment by ajacobs21e** [comment]
Here's a list that was started a while ago of potential components to get an RCUE treatment https://docs.google.com/document/d/1_yNchMcfEH7RqRwGZa2zCPmDoooaCWfEc_W5jbajC1U/edit?ts=5e458a38#

**Comment by mcarrano** [comment]
None of this is currently on our roadmap. I'm not sure what prior conversations or assumptions may have taken place. Once we complete the theming work, which is currently focused around dark theme, it will be easier to do this. But right now it's not clear what the priority would be or who owns this effort. It's really downstream from PatternFly.

@LHinson any background to add?

**Comment by ajacobs21e** [comment]
Yes it's for our downstream which ideally would be a collaboration between PF and the PF web group that would be using the downstream

**Comment by mcarrano** [comment]
This issue seems pretty stale at this point, so closing it out. We can always open a new issue if/when this comes around again.
