### ISSUE TITLE
Evaluate need for card background in full screen views

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#798]
We often use the gray background / card layout for various types of screens that may not need them. This forces a large amount of padding (padding between the page and the card, then the card and the content) and makes the page feel bloated or cramped. It is also confusing when determining whether to use a card layout versus a full page layout. To card or not to card? That is the question, and we must answer it with a good solution.

cc @mceledonia @LHinson

**Comment by mcarrano** [comment]
@lboehling @mceledonia I'm looking at this issue and wondering what the relationship is between this and #799 . Should these two issues be addressed at the same time or do you see them as distinct?

**Comment by lboehling** [comment]
Here is the marvel file of the work I showed during our review today: https://marvelapp.com/22g12786

We discussed splitting this up into separate issues. One with card usage/background color guidelines and one where we rethink the full-width views for data list and tables (specifically considering the expanded panel visual treatment). 

@mcarrano @mceledonia

**Comment by mcarrano** [comment]
@lboehling Based on this analysis, I have opened the following new issues for follow-up work:

* Updated related demos: https://github.com/patternfly/patternfly-design/issues/846
* Revise styling on expanded rows in Tables and Data lists: https://github.com/patternfly/patternfly-design/issues/847
* Introduce design guidelines for Cards: https://github.com/patternfly/patternfly-org/issues/1804

cc @LHinson
