### ISSUE TITLE
* Link to line chart from the Bar Chart pattern 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#80]
Upon mention of the "line chart", the bar chart pattern (https://github.com/patternfly/patternfly-design/blob/master/pattern-library/data-visualization/bar-chart/design/overview.md) should link to it  (http://www.patternfly.org/pattern-library/data-visualization/line-chart/#/api). 

"Line Chart" should has have header style capitalization.

**Comment by maryclarke** [comment]
I'll do this one

**Comment by maryclarke** [comment]
Matt will do it

**Comment by LHinson** [comment]
This has been fixed.
