### ISSUE TITLE
Revisit masthead design for improved scalability and efficiency

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#801]
Typically the masthead contains the product logo on the left, and any global user settings/notifications/icons on the right. This leaves a majority of the masthead unused, and with being a relatively large height it can be perceived as a waste of space.

At the same time, on mobile screen sizes, in some applications (Openshift) there is the opposite problem, not enough room for the required amount of actions. I think this just calls for a need for a more scalable design which is flexible enough for both large and small formats.

cc @mceledonia @LHinson

**Comment by mcarrano** [comment]
Per more discussion with @mceledonia , we would like to avoid wholesale changes in the short term. Goals of this issue to include:

* Improving responsive behavior. See https://github.com/patternfly/patternfly-next/issues/2482
* Accommodating context selector or other controls. See mockup ideas here: https://marvelapp.com/project/4674979  This could be done by creating a second tier of the masthead and rethinking space allocation. Could be offered as a new masthead variant rather than requiring a breaking change.

**Comment by mceledonia** [comment]
As a side-effort or overlap of this, I also want to keep in mind ways this would be affected by the RCUE effort, i.e. how we can incorporate Red Hat brand styling to Red Hat products. 

In more general terms, how we can allow for more brand styling to show through the masthead for any company which wants to use PatternFly in conjunction with their own visual brand styling.

@mcarrano @LHinson

**Comment by mceledonia** [comment]
Sharing this here as it's relevant to this effort: [Scalable branding solution for mobile viewports](https://docs.google.com/presentation/d/1SX4NiVzrmj3HlhY8YsHb7Lf_gvBFOegE7uVQc2JAqH0/edit?usp=sharing)

In short: Keep branding the same until it runs out of room at smaller viewports. Then shift the layout to a "brand bar" above the masthead which hides/shows on scroll. See the presentation for an animated mockup of that interaction.

@mcarrano

**Comment by mcarrano** [comment]
I like it @mceledonia . Here also is a link to concepts I was working on for placing context selector controls in the masthead: https://marvelapp.com/4c9d368

**Comment by mcarrano** [comment]
Completed designs here: https://github.com/patternfly/patternfly-next/issues/2801

https://github.com/patternfly/patternfly-next/issues/2801 has been opened to track Core changes, Thanks for all your work on this @mceledonia . I will close this design issue.
