### ISSUE TITLE
Vertical tabs

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#802]
Filing a Pattern or a Bug? Delete the sections that do not apply.

## For Pattern Contributions: 
- New pattern
- Proposed for the web site system
- Vertical tabs are used to preserve vertical space in the main content area and/or when the number of tabs exceeds what will fit in the horizontal tab space. Vertical tabs differ from left navigation in that they do not navigate to another page. 
- PatternFly Web issue: https://github.com/patternfly/patternfly-unified-design-kit/issues/77 
- Related to horizontal tabs and scrollspy (new issue coming soon)
- https://sketch.cloud/s/jeKZz/p/tabs-pf (look at vertical tabs only)

@patternfly/patternfly-design-maintainers  

Specific design notes

- Primary tabs
    - Spacing: 8px 32px 8px 16px
    - Leading / trailing border line: 24px
    - Highlight height: 32px, centered (extending 4px above and below text)
- Secondary tabs (box)
    - Spacing: 16px 32px 16px 16px
    - Leading / trailing border line: 32px
- Color
    - Border color, dark theme: secondary (#6A6E73)
    - Inactive text, light theme: secondary (#6A6E73)
    - Inactive text, dark theme: #D2D2D2 (Color--light-300)
    - Inactive tab background, light theme: #F0F0F0 (BackgroundColor--200)
    - Inactive tab background, dark theme: #3C3F42 (BackgroundColor--dark-200)

![Tab proposal vertical](https://user-images.githubusercontent.com/6415742/72762336-36068780-3bad-11ea-8932-49b1ca8ec256.png)

**Comment by mcarrano** [comment]
Thanks for filing this @ajacobs21e . I'm wondering if this becomes a new component or just a variant of vertical navigation. Is it functionally any different than vertical nav? 

cc @mceledonia

**Comment by ajacobs21e** [comment]
@mcarrano Are horizontal tabs a variant of horizontal navigation? I would assume it would have the same relationship as those components. 

The way it's used on the Portal is to flip through blocks of content on the same page, rather than navigating to a different page. Do the current horizontal tabs in PF4 have that same distinction?

**Comment by mcarrano** [comment]
Yeah, that's a good distinction @ajacobs21e. We need to look at how we want to support this in-page navigation as a whole. How does this relate to the Scroll-Spy Nav we talked about, for example? Should they be the same or different visually? I will move this to our design backlog for further consideration.

**Comment by ajacobs21e** [comment]
Thanks @mcarrano . The vertical tabs and scrollspy are visually the same and scrollspy adds the heading "Jump to section". We did this to the components could be interchangeable. We had a use case of docs having a 'view as single page' or 'view as multipage' option and we thought it would confuse the user for the visual design of the tabs/scrollspy to change. 

I also realize the screenshot I posted has RCUE colors. It's an older screenshot. The sketch file has the correct PF colors.

**Comment by mcarrano** [comment]
Vertical tabs were implemented as part of the 2020.07 release. https://www.patternfly.org/v4/documentation/react/components/tabs  There is a separate, but related issue here for scrollspy navigation. https://github.com/patternfly/patternfly-design/issues/792 Closing this one out.
