### ISSUE TITLE
Inline Alert demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#807]
We currently have an [Alert demo in PF core](https://www.patternfly.org/v4/documentation/core/demos/alert) that shows placement of a Toast alert but are missing anything that demonstrates placement of inline alerts. There is some design guidance here that is a bit vague: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/alerts-and-notifications#inline-alerts

It would be great to have more specific example(s) that show placement on an inline alert on a page that can be used to create related demos on core and React. This would consider various use cases for inline alerts and how placement might differ (if at all).

**Comment by gdoyle1** [comment]
I mocked this up (content probably needs to change) https://marvelapp.com/218i9ggg that seemed to be a very common use case (using inline alerts within forms). Might be worth creating another demo example where the inline alert is placed within the header when there is a table below, but LMK what you think @mcarrano !

Here's where I've been tracking other use cases as well: https://docs.google.com/document/d/1NTXN308COIYv7PUXbGBge8UvDHVzsXP5j1P9Ut-x2Iw/edit?usp=sharing

**Comment by gdoyle1** [comment]
Marvel project: https://marvelapp.com/218i9ggg. Updated the examples and specs and left comments on the examples so that they explained the use cases I was going for! @mcarrano

**Comment by mcarrano** [comment]
Looks great @gdoyle1 

@lwrigh please take a look at this and let me know if you think this will address the issue you raised here: https://github.com/patternfly/patternfly-design/issues/779 Thanks.

**Comment by lwrigh** [comment]
@gdoyle1 @mcarrano This looks like a good solution to me!

**Comment by mcarrano** [comment]
Excellent! I am going to close out #779 then.

**Comment by mcarrano** [comment]
Design complete. Opened https://github.com/patternfly/patternfly-org/issues/1697 to update Alerts and notifications design guidelines with new placement and https://github.com/patternfly/patternfly-next/issues/2736 for implementation in Core.
