### ISSUE TITLE
Add favoriting functionality in Dropdown items

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-design#810]
Could we look into making split-button functionality in `Dropdown` component function out of the box?

Looking at Application launcher it can have two buttons per item, a link/action and a favourites button.
![image](https://user-images.githubusercontent.com/6598829/73731783-6582cb80-4739-11ea-9990-0f30f223dc63.png)

![image](https://user-images.githubusercontent.com/6598829/73731797-69aee900-4739-11ea-87a3-4b1feaa02fa9.png)

If we were to add a child ourselves there isn't a way to get the buttons to align next to each other
![image](https://user-images.githubusercontent.com/6598829/73733221-d9be6e80-473b-11ea-9afd-d3d8df563313.png)

We have to explicitly overwrite the styling, similarly to how Application launcher has done. Otherwise we wouldn't get the functionality.
![image](https://user-images.githubusercontent.com/6598829/73733303-01153b80-473c-11ea-9a94-320d8a5ae8e7.png)

One of my use cases:
If we want a way to display actions on lists of items and one of the actions is `Set Active` or `Mark as Favorite`.
![image](https://user-images.githubusercontent.com/6598829/73733641-9ca6ac00-473c-11ea-9a84-a3d3a9a46262.png)

**Comment by mcarrano** [comment]
@SpyTec I am revisiting this issue and in re-reading your comments. I had though you were asking to apply the favoriting functionality in Application Launcher to any dropdowns. But upon closer reading, I may have misunderstood. Are you just asking for the general ability to nest a button or other action inside a menu item? From your comment, looks like you want to construct something like this, can you confirm?

![Menu with actions.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/4e7dac7e-5a35-4bd5-9645-44331527d4d7)

**Comment by SpyTec** [comment]
Not necessarily, just a general ability to put any icon there as a secondary action. For example marking as favorite, or indicating it's an external link (with no action).

Having ability to do nested dropdowns would be nice as well, but not really what I'm asking for

**Comment by mcarrano** [comment]
After discussing with @mcoker , I am adding this requirement to the modular menu component identified here: https://github.com/patternfly/patternfly/issues/2950 In the future, this menu can be used along with a [modular toggle](https://github.com/patternfly/patternfly/issues/3015) to build custom dropdowns. We feel like that will be a cleaner approach than adding to the existing Dropdown component.

@SpyTec will that address your needs?

**Comment by SpyTec** [comment]
I'm sure it will in some regard, thanks @mcarrano and @mcoker

**Comment by mcarrano** [comment]
I am going to close this out then in favor of https://github.com/patternfly/patternfly/issues/2950.
