### ISSUE TITLE
Primary tabs in Sketch library have a different background color

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design#811]
Primary tabs in the Sketch library have a light grey (#FAFAFA) background-color but the implementation and [PatternFly documentation ](https://www.patternfly.org/v4/documentation/react/components/tabs) uses a white/transparent background-color. Which color is right? @gdoyle1 

![bg](https://user-images.githubusercontent.com/32618096/73831062-ff17af00-4805-11ea-8f41-23ae025fee92.png)

**Comment by gdoyle1** [comment]
@doruskova that was a mistake on the library part! I forgot to change the fill color for the primary tab from #FAFAFA to #FFFFFF. Fixing it now so that it has a white background. Sorry about that!

**Comment by doruskova** [comment]
That's ok. Thank you so much for fixing it 👍
