### ISSUE TITLE
Toggle Button Groups for Topology View

### ISSUE THREAD

**Issue by Veethika** [patternfly/patternfly-design#813]
## Requesting new features, enhancements, or design changes to PatternFly 
**Type:** Enhancement - to dropdown component
**Use case:** In the Developers Console of OpenShift, a display dropdown menu is used to expose a list of toggles that help in the customization of the view. The toggles are segregated into categories and therefore have to be visually represented as being grouped together. The main dropdown toggle contains a badge to display a count of active toggles inside.

**Problem with existing pattern:** The existing component does not allow listing toggles inside a dropdown and also doesn't allow adding a badge inside the main dropdown toggle box to show the number of toggles active.

Implemented for 4.4 release of OpenShift:

<img width="830" alt="Screenshot 2020-02-13 at 2 14 34 PM" src="https://user-images.githubusercontent.com/35127763/74417227-5f44cb80-4e6c-11ea-8088-bf7ac809d0fb.png">

_Design would be modified as per suggestions from PF_

**Comment by mcarrano** [comment]
@Veethika doesn't the Grouped Checkbox Input here give you exactly what you are looking for? https://www.patternfly.org/v4/documentation/react/components/select#grouped-checkbox-input

**Comment by Veethika** [comment]
@mcarrano It does! Didn't realize it allows putting the badge as well, thanks!

**Comment by mcarrano** [comment]
Great to hear that @Veethika . I will close this out then.
