### ISSUE TITLE
Need support for input field with clear button

### ISSUE THREAD

**Issue by karthikjeeyar** [patternfly/patternfly-design#814]
**Describe the issue. What is the expected and unexpected behavior?**
In Openshift Developer Console, topology filter by name field needs search input field with clear text button,  result count in the input filed

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

1. On click x button, it needs to clear the field
2. Matched result count needs to be shown as a badge

![image-2020-01-28-07-15-17-310](https://user-images.githubusercontent.com/9964343/74242963-d8c1aa00-4d04-11ea-83f8-a1c97f373ce6.png)

**What is your product and what release version are you targeting?**
Openshift Developer Console ( Target Release 4.4)

cc:  @jeff-phillips-18 @serenamarie125

**Comment by maryshak1996** [comment]
@mcarrano I think that this and #815 are both done from the design side with this deck: https://marvelapp.com/e9ge7g7
Related, but kind of not related, #816 is in progress

**Comment by mcarrano** [comment]
Have opened https://github.com/patternfly/patternfly/issues/3151 for core implementation.
