### ISSUE TITLE
Need support for search input field with navigation options

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#816]
Describe the issue. What is the expected and unexpected behavior?
In Openshift Developer Console, topology filter by name field needs search input field with clear text button, result count in the input filed

Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?
Enhancement

We'd like to use navigation buttons to traverse through the items that are found

![image](https://user-images.githubusercontent.com/12504403/74374885-4aedc980-4dad-11ea-848e-d1b437bf4713.png)

What is your product and what release version are you targeting?
Openshift Developer Console ( Target Release 4.5)

cc: @jeff-phillips-18

**Comment by christianvogt** [comment]
@mcarrano yes that's what this request is about.

Design mocked this up:
![image](https://user-images.githubusercontent.com/14068621/74466789-f35f6480-4e65-11ea-8330-62afc341c2f2.png)

**Comment by maryshak1996** [comment]
Design docs:
Marvel: https://marvelapp.com/4h047dc
Sketch: https://www.sketch.com/s/f5e692d4-a2d0-4721-b75b-7163f1945a66

**Comment by mcarrano** [comment]
Have opened https://github.com/patternfly/patternfly/issues/3151 for core implementation

**Comment by mcarrano** [comment]
Design is complete. See patternfly/patternfly#3151 to track core implementation. This issue will be closed.
