### ISSUE TITLE
Add a max width to the Page component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#817]
Want to support a max-width of a page to prevent pages from becoming too stretched on ultra-wide monitors. We might want an exception to be allowed for things like big dashboards where it might be cool to have 25 cards spread across the screen, or a table with 25 columns, but in general most content layouts aren’t going to be very usable when spread across an ultrawide.

cc @kybaker @mceledonia @LHinson

**Comment by kybaker** [comment]
Here is the latest link to the work - [https://marvelapp.com/7191idb/screen/67734666]

**Comment by mcarrano** [comment]
Thanks @kybaker . I have opened https://github.com/patternfly/patternfly/issues/2910 to track the core work. Will close.
