### ISSUE TITLE
Guidelines about long text in tables

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-design#821]
We came up with a challenge in Patch Manager and Vulnerabilities having too many columns in a table. Our suggestion is to truncate the text and show the rest on hover. 
See the mockup here https://marvelapp.com/6bhc03d/screen/66159925

As it came up several times, we know we want to keep the patternfly guidelines flexible but in terms of consistency it would be nice to have more clear rules on this pattern. 

Shared it in design share with @mcarrano

**Comment by mcarrano** [comment]
@seanforyou23 I'd be interested in your thoughts on this one. I assume that the default behavior for a table cell is that the text just wraps when it overflows the width of the cell. If we wanted it to truncate, can the table handle that behavior or would the truncation need to be handled by the consumer?

**Comment by seanforyou23** [comment]
@mcarrano I think by default, the column widths are not explicit widths, so by default the table columns seem to try and adjust themselves as necessary to accommodate any text provided. At some point, of course it becomes too much to fit and things start wrapping.

We did find that there's a simple way of controlling the column widths (including an immediate `div` as a child of the td and applying set widths/overflow to that instead.

I think we could teach the Table to do this, or rely on users to apply these styles on their own - all just a matter of what we want Table to be capable of out of box.

Does this help? We could create this as a simple example of the existing table, or as a feature of its own. Considering the complexity of Table, I'm inclined to say let's have the users manage this if possible. Creating a simple example wouldn't take long.

**Comment by mcarrano** [comment]
@terezanovotna does this address what you are looking for? It is not clear to me if you are asking that the Table component handle the truncation automatically or if you think we should just have a design guideline about when to truncate.

**Comment by terezanovotna** [comment]
@mcarrano Both - design guideline but also a component that does it. cc @karelhala and @jiridostal

**Comment by karelhala** [comment]
@mcarrano I think that adding a truncated text to table as design demo would be awesome. We'd be consistent in how many characters will be visible and where to show tooltip and such.

**Comment by mcarrano** [comment]
@terezanovotna @karelhala I agree that having a demo would be good. Is there a certain character count you'd have in mind before truncating? It's hard to know when text would wrap due to the variability of number and width of columns.

**Comment by mcarrano** [comment]
This issue is currently being addressed as part of this React issue: https://github.com/patternfly/patternfly-react/issues/3670 and the open PR here: https://github.com/patternfly/patternfly-react/pull/4209 Basically the cell text will wrap whenever the text overflows the width of a cell when this feature is enabled

I am going to close this design issue @terezanovotna as there's nothing further to address from design. But feel free to reopen if you still think there is a design concern.
