### ISSUE TITLE
Test alternative Nav concepts for patternfly.org

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#824]
Perform user testing of alternative nav concepts to improve findability of content on Patternfly website.

cc @rachael-phillips @phcox

**Comment by nazzzzym** [comment]
just in the case if @sjcauffm needs any help. 

I have conducted a small user testing before seeing this issue and here are some outcomes.
I have introduced participants with different options:
1. current with non-fixed navbar and sidebar
(benefits: less distractions from the main content, drawbacks: extra time for scrolling up)
2. non-fixed navbar and sidebar + button that returns the user to the beginning of the page
(benefits: less distractions, drawbacks: extra click for for returning to the beginning of the page, misclicking)
3. fixed navbar fixed sidebar
(benefits: quick switching between sections, drawbacks: additional distractions occur -> less space for the content)

Then I have observed how do they behave using other platforms ([Material](https://material.io), [Materialize] (https://materializecss.com), [IOS design guidelines] (https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/onboarding/)).

The responses of users as well as the time they spend to switch between sections were evaluated. As a result, users found the 3rd option (fixed navbar fixed sidebar) more convenient that others. However, sidebar is accessed frequently, therefore is preferred to be fixed, while navbar is accessed less frequently, thus there is no need for fixing it for advance of larger window size.

**Comment by mcarrano** [comment]
Thanks for this @nazzzzym . Do you have wireframes or other examples of the concepts you tested? Not clear exactly what you mean by fixed vs non-fixed. Any other info on your study would also be helpful, i.e. how many participants tested and how the tests were conducted.

cc @sjcauffm @rachael-phillips

**Comment by sjcauffm** [comment]
Here is the results deck from this study. Let me know if anyone has any questions!

[https://docs.google.com/presentation/d/15qomOHITAJhghWWrddGn-SpRgsaHhEzIxp0Pvh9MaGY/edit?usp=sharing](url)

**Comment by nazzzzym** [comment]
@mcarrano I will share with you alternative concepts later, I cannot do this now.
About my study:
Participants - 3 students (front-end) and 1 UI/UX designer.
Method 1 - Observation. I let them discover the website by themselves.
Method 2 - Observation. I asked them to switch between different sections (for example, I asked to try to find an Icon, while there we on Colors page, or I asked to select 4-5 components that might be useful for their current projects).
Method 3 - Interview. I showed them 2 alternatives (via gif) of navigation and to evaluate how the changes might affect the speed of switching between pages, convenience of access.

**Comment by mcarrano** [comment]
Thanks for your efforts @sjcauffm . I am going to close this issue. @nazzzzym if you have further input please feel free to post here or in out PatternFly channel on Slack.
