### ISSUE TITLE
Understand webiste documentation preferences

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#825]
Perform user research into preferences for presentation of component documentation on the PatternFly website.

cc @rachael-phillips @phcox

**Comment by sjcauffm** [comment]
Here the part 1 results. This study was a first click study combined with qualitative questions to see which of set of navigation alternatives worked best for users and how users were interpreting certain categories within the navigation. 

[https://docs.google.com/presentation/d/1_E7zxiSXjtNbRkxlOPARTmTSjdmUDhLPz8fArzeMY4s/edit?usp=sharing](url)
