### ISSUE TITLE
Tree-view pattern

### ISSUE THREAD

**Issue by aprilma419** [patternfly/patternfly-design#829]
## Requesting for the implementation of tree-view table patterns.
In Keycloak Admin Console, we have a feature called Groups, which allows users to create groups of users to a parent group, and there could be hundreds of children groups in a parent group with approximately 5-10 levels of nesting groups. Users also can cut and paste a group to a target parent group.

The original Group feature looks like this:

<img width="1352" alt="Screen Shot 2020-03-12 at 6 12 37 PM" src="https://user-images.githubusercontent.com/44431015/76510761-198c1a80-648d-11ea-8eba-21052576fd98.png">

 The exact use cases of Groups that we'll potentially do as below: 

- Move single or multiple groups to a parent group by using a one-column tree table to achieve that.
- There are normally 5-10 levels of nesting groups in a top-level parent group or even more.
- Have pagination inside a parent group to inform users about the numbers of children when there are hundreds of children.

I noticed there are [tree-view table designs](https://sketch.cloud/s/oVajQ/a/9breQD) still work in progress, including a full table version and one-column version. So it raised a question to me of when we could get a completed version of these tree patterns, **would they be done by September 2020 or there are other plans on them?**

<img width="879" alt="Screen Shot 2020-03-13 at 10 22 18 AM" src="https://user-images.githubusercontent.com/44431015/76583636-b80f8e80-6514-11ea-8116-eb4133429483.png">
<img width="1190" alt="Screen Shot 2020-03-14 at 11 22 26 AM" src="https://user-images.githubusercontent.com/44431015/76674039-253f2480-65e6-11ea-850d-12844a91c8c2.png">

**Comment by mcarrano** [comment]
@aprilma419 The tree-table development is currently on hold as had encountered problems making this work as a table. Do you require anything other than a one-column tree? If not, we may be able to deliver that.

I'm a bit confused about this statement:

> Have pagination inside a parent group to inform users about the numbers of children when there are hundreds of children.

Also are you really looking for a collapsible tree or something more like a tree drill-down?  It would help if you can provide some wireframes that illustrate what you need.

cc @LHinson

**Comment by aprilma419** [comment]
@mcarrano Thanks for the answer. We've learned that it's impossible to show children level paginations in a table, so we were thinking of using a left side tree-view list to show the levels of groups. Below are the two screenshots of what we will most likely to have the Group page look like:

<img width="837" alt="Screen Shot 2020-03-16 at 5 23 15 PM" src="https://user-images.githubusercontent.com/44431015/76741965-5b79d100-67ab-11ea-94be-42ae1f0d59e2.png">

<img width="897" alt="Screen Shot 2020-03-16 at 5 22 46 PM" src="https://user-images.githubusercontent.com/44431015/76741957-59177700-67ab-11ea-8527-3890180a5533.png">

The way of showing each level of groups we were using is similar to what Google Drive has(like the pic below), user can choose to view children groups or detail pages at the right part of the page by clicking the group name in the list, or to drill down by clicking the arrows. To better navigate among those levels of groups, after looking through some other products, we think breadcrumbs could be a good solution.

On the top left corner of the list, there's a "Move to" button, which is something we want to use the one-column tree patterns to achieve, same as Google drive's "Move to" menu. 

<img width="1079" alt="Screen Shot 2020-03-16 at 5 49 01 PM" src="https://user-images.githubusercontent.com/44431015/76743986-7a2d9700-67ae-11ea-88a5-9416e7c217ab.png">

**Comment by mcarrano** [comment]
So if I understand correctly @aprilma419 , you are looking for us to introduce a tree browser control like the one on the left, is that right? The drill-down tree is also something we've investigated for other use cases. There is an open issue here: https://github.com/patternfly/patternfly-design/issues/774 But it's true that we are missing the expandable tree in PatternFly. Do I understand correctly?

**Comment by aprilma419** [comment]
@mcarrano Yes, what exactly we want at this time is the tree browser at the left side of the page and the one-column tree pattern, so that we can implement them by Sep 2020.

**Comment by mcarrano** [comment]
@aprilma419 . We have added this to our roadmap to be available in a June-July timeframe. You can look for design updates to be posted here as we work on this.

**Comment by aprilma419** [comment]
@mcarrano Great! Look forward to the updates. Thanks!

**Comment by yih-wang** [comment]
@mcarrano Will the expandable tree browser control support some extreme cases? For example, how to display if a parent node has thousands of children nodes?

**Comment by mcarrano** [comment]
That's a good question @yih-wang . What would you expect in that situation?

**Comment by yih-wang** [comment]
@mcarrano Keycloak may have such extreme cases like a parent node has thousands of children nodes or thousands of embedded levels. Maybe an "explore from here" function would work. Users can right-click on a node to make it the new root. The following screenshot shows the case that exploring from the node "ContentPresenter".
![image](https://user-images.githubusercontent.com/23331885/78097206-41c4c480-740e-11ea-89bb-ab39c3ede7f6.png)

**Comment by mcarrano** [comment]
Thanks @yih-wang I agree that we should have the option to report the number of children associated with a node. I think that "explore from here" is an interesting idea. Maybe this works as some sort of drill-down where the breadcrumb at the top shows me how many levels deep I am?

**Comment by yih-wang** [comment]
@mcarrano Yes, exactly!

**Comment by ajacobs21e** [comment]
https://github.com/patternfly/patternfly/issues/2635#issuecomment-608053401 I have a similar use case that I posted on the multi-level dropdown issue but my context is more of a tree view than a dropdown and would be used as a filter for a table. 
My use case would have nested items around 5 levels deep, but 10+ levels are possible. The names of each level are usually a few words long too. For those reasons doing an indented design like April's won't work. 
Here's my example in context (this page and the next two)
https://marvelapp.com/70e251a/screen/67725428

@nlcwong has a similar use case as well.

**Comment by aprilma419** [comment]
Hi @mcarrano, a quick question on the interactions of the one-column tree pattern.

Can users click on the row(anywhere except the arrow area to drill down) to be selected for actions in a compact-sized one-column tree？Or they're only allowed to click on the Action link to do actions in a row?

<img width="297" alt="Screen Shot 2020-04-16 at 6 41 21 PM" src="https://user-images.githubusercontent.com/44431015/79447405-63c76500-8012-11ea-8688-e2d729310180.png">

**Comment by mcarrano** [comment]
@aprilma419 Since this component does not exist yet, I'll turn this around and ask what you expect. For consistency with what we've done with similar patterns, I'd say that the user should click on the action link to trigger the action. Do you agree?

**Comment by aprilma419** [comment]
@mcarrano In our case, the users will select one of the rows and then click a confirm button below the rows to finish the task, and this whole pattern will be in a modal. It seems a bit odd to me if users click on the action link in a row to leave the modal.

However, it's fine if the pattern remains for consistency reasons, I think we can use something like a radio button to let users make the selection.

**Comment by doruskova** [comment]
@mcarrano I'm adding a mockup for a tree view with some variants. It includes: 
- default version, 
- with search, 
- with checkboxes, 
- with chips,
- clear version without these chips that indicate a number of nodes. 

More specific mocks with padding are in progress.

**Comment by ajacobs21e** [comment]
@doruskova These designs look great, I especially like how you're showing context of what's selected. 
However I don't think these meet my use case. The directory names in my tree could be very long (8+ words) - do you know if longer names would wrap or truncate etc? My directory could also go pretty deep, I was told 10 levels deep is a fairly common example. I think it will be unmanageable to read each level if they're long names and indenting 10+ times.

**Comment by doruskova** [comment]
@mceledonia I updated the mocks for the tree view pattern [here](https://marvelapp.com/8cdg211). Let me know if it makes sense to you or if you see any issue. 
I just need to add a tooltip for the truncated name and change the search bar because the tree should be filtered without clicking on a search icon.

**Comment by doruskova** [comment]
@mcarrano mocks have been updated. [Link here](https://marvelapp.com/8cdg211)
Changes: search bar, a tooltip with the full name. The badges should indicate the number of children. I hope that I understood it correctly.

**Comment by mcarrano** [comment]
This looks good @doruskova . I think that the only question is what happens to this when we shrink into a mobile viewport. Does it remain a tree or transform into something else?

**Comment by doruskova** [comment]
@mcarrano I think it should be still a tree. It's just an accordion menu, so it shouldn't transform into something else. I've added a screen for it [(link here)](https://marvelapp.com/8cdg211/screen/69465894) 
The only thing I changed is the truncation for the mobile version because the user can't trigger a hover action to see the full name. So, I wrapped the lines for the mobile version.

**Comment by doruskova** [comment]
@mcarrano Menu with icons and specification have been added [here](https://marvelapp.com/8cdg211)
Also, I added some examples of additional features for a future [here](https://marvelapp.com/8cdg211/screen/69897125)

**Comment by doruskova** [comment]
@mcarrano I've updated the mocks with an[ action item on the right side](https://marvelapp.com/8cdg211/screen/68897369). The action should be triggered on a hover. I was trying to make it as universal as possible and I think that using kebab is the most universal solution that covers most of the use-cases. But, IMHO should be possible to add any type of action (icon) on the right side depending on the use-case. Do we want to limit these actions by using just a kebab icon? Let me know what do you think. [Here's the screen](https://marvelapp.com/8cdg211/screen/69897125) with possible additional features.
I talked to @gdoyle1 about adding this into a template, so I would like to clarify that this behavior (with kebab+other actions) makes sense to you.

**Comment by gdoyle1** [comment]
@doruskova Awesome, that looks good to me! I think the only thing I was wondering is if the icon button should be shown all the time or only on hover?

**Comment by mcarrano** [comment]
This looks good @doruskova . Good question about hover. What were your thoughts?

@mcoker can you also take a look here? The general goal is to support an action in a menu item independent of selecting the item (like we do for favorites now). How much can we generalize that? Does it make sense to drop anything there like a single action or a kabob menu as shown? Or do we need to restrict this to something that's an icon button? The more flexibility the better.

**Comment by doruskova** [comment]
@mcarrano @gdoyle1 I think that the icon should be shown only on hover, because imagine that every item in the menu will have, for example, the kebab. It would be messy and look like this: 
![kebab](https://user-images.githubusercontent.com/32618096/84879569-ad244700-b08b-11ea-810d-fb977acba333.jpg)

**Comment by doruskova** [comment]
@mcarrano added a placeholder icon for an action item on the right. Link [here](https://marvelapp.com/8cdg211/screen/69215826)

**Comment by mcarrano** [comment]
I am going to move this to development for the basic collapsible tree pattern as described in the Marvel deck. A new issue has been opened to address the drill-down tree menu as a separate component. See #867.

Thanks for all your work on this @doruskova

**Comment by mcoker** [comment]
@mcarrano sorry for the delay

> The general goal is to support an action in a menu item independent of selecting the item (like we do for favorites now)

The favorites button is a specific action button for the dropdown menu item. And it's generalized so that you can put any kind of icon in it you want. That said, it wouldn't work as a dropdown toggle currently - though it could potentially work as a dropdown if a user were to attach the upcoming context menu to it.

That said, we could extend this to general use of the plain button or plain (kebab) dropdown, by changing the way the button and dropdown components appear when placed beside a menu item. Then a user could add any plain button or plain button dropdown to the item that they want.
