### ISSUE TITLE
Design changes in Icons page (Design guidelines -> Styles -> Icons)

### ISSUE THREAD

**Issue by nazzzzym** [patternfly/patternfly-design#830]
**Current design:**

    (a) When the user wants to interact (copy or download) with the icon he/she needs to click on it
    (b) Interaction options appear in the new form
    (c) The user needs to click on the icon again or click on X button to close the form
<img width="1066" alt="icons-current" src="https://user-images.githubusercontent.com/57250339/76597988-011f0d00-652c-11ea-978e-ca688f5b07ea.png">

I did the primary research with 7 people (all related to front-end development UI/UX design) and the following **problems** are investigated:

    (a) It took time to realize that icons are clickable
    (b) Form takes extra place and moves other icons, confusing users. The repeating name of icon is unnecessary
    (c) No one of the participants realized that the double click on icon results in closing the form.
    ( ) Overall observation: it takes extra time to open/close the interaction form.

**Proposed design:**
    Interaction options are located inside the icon form. They appear by mouse over.

![icons-proposed](https://user-images.githubusercontent.com/57250339/76598020-1136ec80-652c-11ea-908c-5c8aee76aef7.gif)

**Comment by mcarrano** [comment]
@nazzzzym Thanks for filing this. Our Icons page is being completely redesigned. There is an open issue here: https://github.com/patternfly/patternfly-org/issues/1687 Feel free to add your comments there. I will close this as a duplicate.
