### ISSUE TITLE
Revisit Hint styling

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#837]
Want to revisit styling of the Hint component to ensure synergy with restyling of Alerts (https://github.com/patternfly/patternfly-design/issues/804). Want to make sure Hints and Alerts work together visually when placed on a page.

Current designs here: https://docs.google.com/document/d/1qAYYv-VPuOst1o-BFx0R7Wgh3jt6X9ATmV4WQU5hXcw/edit?usp=sharing

**Comment by ajacobs21e** [comment]
https://marvelapp.com/113b745e/screen/67626468
Here are some examples and feedback of the hint and banner in use.

**Comment by mcarrano** [comment]
@ajacobs21e Thanks for posting these. I looked at the Marvel deck. I'd say that the banner definitely is not intended for this use case. But I do agree that the current Hint does not work so well here. This is definitely a very different visual layout than what we were looking at in product so we will consider this usage as we revisit the component.

**Comment by maryshak1996** [comment]
Updated the link above (https://docs.google.com/document/d/1qAYYv-VPuOst1o-BFx0R7Wgh3jt6X9ATmV4WQU5hXcw/edit) to include quick update to the default style.
![image](https://user-images.githubusercontent.com/19824574/79132083-aa4d6300-7d77-11ea-97c4-07af0221e43d.png)

**Comment by mcarrano** [comment]
@maryshak1996 Thanks for making these updates. Since we already have an open design kit issue, I am just going to close this.
