### ISSUE TITLE
Contextual help widget for modal

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-design#843]
## Requesting new features, enhancements, or design changes to PatternFly 
In Cockpit we have need a widget for Field level help in the Networking Bond dialog.
We use a dialog for creating a new bond, but we found in research that a lot of the fundamental concepts about [network bonding](https://www.interserver.net/tips/kb/network-bonding-types-network-bonding/) is tricky for our target audience.
So we want to point to some documentation specifically for network bonding, and ended up with this custom (PF3) widget.
![Screenshot from 2020-04-02 15-20-37](https://user-images.githubusercontent.com/209895/78254580-6bf1b180-74f6-11ea-89a1-62786afe2289.png)
The documentation it points to is this: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/managing-networking-in-the-web-console_system-management-using-the-rhel-8-web-console#configuring-network-bonds-using-the-web-console_managing-networking-in-the-web-console

Placement of this widget could be up for debate. Might be impacted by a11y requirements.
I think we would need this in Patternfly before we can port the Networking page from PF3 to PF4.

**Comment by jgiardino** [comment]
I have a similar need for this in the context of a wizard that displays in a modal.
https://github.com/osbuild/cockpit-composer/issues/935

**Comment by mceledonia** [comment]
This is something we should support. I think the contextual help icon should exist in the modal header as shown by @andreasn screenshot above. Here is what I'm thinking for spacing/positioning, we can stack the help icon with the close icon as the built in padding for icon buttons is plenty.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/30935938/89923545-c13d7e00-dbce-11ea-8caa-cf6d06618e3c.png">

**Comment by mcarrano** [comment]
@mcoker do you see any issues with this?

**Comment by mceledonia** [comment]
After discussion with @mcoker we may have to approach this a bit differently due to how the close action is implemented in modals. From what I gather it may just mean that we shift the help icon position to the end of the modal title rather than stacking it with the close icon.

**Comment by mcarrano** [comment]
I think we can call this design issue complete. I've opened https://github.com/patternfly/patternfly/issues/3474 to track the core implementation. Thanks for your efforts on this @mceledonia !
