### ISSUE TITLE
Label group component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#845]
Introduce a Label group component that allows for grouping labels with a category name similar to how we group chips. See https://github.com/patternfly/patternfly-react/issues/4084 for more details about how this would be used. This should allow for labels to be grouped in a horizontal group (like a Chip group) or collapsed into a pop-up group when space is constrained. See design ideas in https://github.com/patternfly/patternfly-design/issues/842

**Comment by maryshak1996** [comment]
Marvel deck: https://marvelapp.com/prototype/5ajfj8fhttps://marvelapp.com/prototype/5ajfj8f
Sketch Cloud: https://www.sketch.com/s/a552bfaf-8c51-4898-a87e-44b7ca34c89f

**Comment by mcarrano** [comment]
@mcoker when you get a chance, can you look at Mary's mocks for this? It's something I'd like to queue up for milestone 11. It's pretty equivalent to a chip group, but let us know if you see any issues. Thanks.

**Comment by mcoker** [comment]
@mcarrano @maryshak1996 lgtm. A couple of questions - will this be adding a vertical layout variation (that doesn't exist on the current chip group)? And is there specific behavior/layout for the responsive groups, or do the labels/buttons just wrap as space allows like the chip group behaves currently?

**Comment by mcarrano** [comment]
@mcoker Yes, for a label group we want the vertical layout that does not exist of a chip group. I guess that would also need to scroll if the number of chips exceeds the height of it;'s container. As for responsive behavior, yes, I think that wrapping would be the default. I also speculated whether at a mobile breakpoint you might want the horizontal group to convert to a vertical pop-up group, but I'm not sure if that something we should enforce at the component level or if it would be best left to the consumer to code that if they in fact want that behavior. Thoughts?

**Comment by mcoker** [comment]
@mcarrano 

From the designs, I imagine you could have either a horizontal or vertical group, and you can put those groups on a page, in a popup, etc, and we can include the ability to switch between horizontal and vertical layouts at breakpoints if that's needed. That's really straight forward.

> the horizontal group to convert to a vertical pop-up group

Are you thinking about behavior like the overflow menu, except instead of actions being put into a dropdown triggered by a button, they would be put into a popover?

**Comment by mcarrano** [comment]
@mcoker Yes, this is what I was thinking. Hard to know if that's useful within context. @maryshak1996 thoughts?

@marshmalien You had originally filed this request. Do you think having the label group collapse into a single icon with a popover at a certain breakpoint would be useful or would you just expect the group to just wrap?

**Comment by marshmalien** [comment]
@mcarrano We would expect the label group to wrap at a given breakpoint instead of collapsing into an icon.

**Comment by mcarrano** [comment]
Thanks, @marshmalien . In that case, let's just stick with the wrapping behavior @mcoker . So we would have the vertical/pop-up group just as a separate layout variant. If someone wanted the overflow behavior I described, they could code that on the consumer side.
