### ISSUE TITLE
Update demos to remove card backgrounds

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#846]
Following up on the analysis done in #798, we should update related full page demos to eliminate use of card backgrounds. Demos affected include:

Data List
Table
Forms
Master-detail

**Comment by lboehling** [comment]
Here are the full-page demo mocks! 
Marvel: https://marvelapp.com/5996ff7/screen/69836554
Sketch: https://www.sketch.com/s/2e4e5751-e94f-4507-87ef-04f5546ac9df/v/JAVo25/

@mcarrano

**Comment by mcarrano** [comment]
Looks good. @mceledonia and @mcoker can you also take a look to see if there are any issues?

**Comment by mcoker** [comment]
@mcarrano lgtm. Do you think removing the expanded row borders (blue left border and divider between the expanded row and expanded contents) will be considered a breaking change?

**Comment by mcarrano** [comment]
Design work is complete. Opened https://github.com/patternfly/patternfly/issues/3221 to update core demos.

**Comment by mcarrano** [comment]
Design work is complete but we decided to put a hold on implementation for concerns about visual breaking changes. Closing the design issue.
