### ISSUE TITLE
Catalog View

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#848]
Define standards for a Catalog View that can drive consistency across products and applications. The following slide deck captures current catalog view examples: https://docs.google.com/presentation/d/19dwdHHTNn2b75ObVkMTu1L3UPw-bxK9j8acc2Eoaiw4/edit?usp=sharing

Some potential next steps:

* Take a look at the content guidelines @amysueg  created and think about how we can start moving towards them and if things need to be added or changed: https://docs.google.com/presentation/d/1M6oJfFUnPEwIsxlcF0uJT7__eprysJ7sJp9Z0-Wgeqg/edit?usp=sharing

* Create guidelines for cross-product design

* Create standardized card/tile template for visual consistency across products

* Create a demo to show different catalog view options.

PatternFly currrently supports a Card View that is similar to the catalog views outlined in the attachment. It may be that we would extend or replace Card View with a set of catalog view examples.

**Comment by mceledonia** [comment]
[Catalogue tile template proposal](https://docs.google.com/presentation/d/12YH5SN8V2wjIzYiPWd5wWbRRrsqZkf1DyeBNOhbOO5k/edit?usp=sharing)

**Comment by maryshak1996** [comment]
WIP design: https://marvelapp.com/prototype/24g4a7g6

**Comment by mcarrano** [comment]
Designs are looking great @maryshak1996 . 

@ajacobs21e please take a look and see if the left-hand filter approach would satisfy your needs.

**Comment by maryshak1996** [comment]
Same link as before (https://marvelapp.com/prototype/24g4a7g6), but would love to get some feedback on the two left side panel options: catalog panel as it's own perscriptive component vs a panel with dictated spacing that user can put whatever components they want in.
@mceledonia @mcarrano @lboehling

**Comment by maryshak1996** [comment]
@mcarrano I've applied feedback based on the PF design sync yesterday and chatted with @rachael-phillips a bit too. Feedback seems to have slowed on this, so unless you have any other thoughts, I think that we can consider these designs complete!
Marvel: https://marvelapp.com/prototype/24g4a7g6
SketchCloud: https://www.sketch.com/s/381a44dc-d625-4d90-80e0-d98e802c6035

**Comment by ajacobs21e** [comment]
@mcarrano @maryshak1996 sorry for taking forever to get to this! I do like this design a lot and it meets the needs for the web space. The only thing I would want to consider is to make the category label different than its contents. What about a blue highlight like the accordion? Or making the text bold or blue when expanded? Or making the categories bigger / bolder all the time?
