### ISSUE TITLE
Save/bookmark a search in a toolbar

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design#849]
A common ask in enterprise apps is to "save" a search, or filter setting. 
This would be a helpful demo for PF to have.

**Comment by lclay2** [comment]
Kogito is interested in this as well. In addition to saving a filter query, with a user defined name, they would also like to be able to remove the saved filter. 
cc @cristianonicolai @amysueg

**Comment by mcarrano** [comment]
Plan to document as a new design pattern on the PF website. See https://github.com/patternfly/patternfly-org/issues/3419 for follow-up work.
