### ISSUE TITLE
* Remove the word "Overview" as it's redundant on Heat Map pattern 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#85]
Remove the word "Overview" as it's redundant on Heat Map pattern  https://github.com/patternfly/patternfly-design/blob/master/pattern-library/data-visualization/heat-map/design/overview.md

**Comment by tiffanynolan** [comment]
I'll do this one.

**Comment by tiffanynolan** [comment]
This can be closed.
