### ISSUE TITLE
Enhancement to menus (add Favorities)

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#851]
## Requesting enhancements to PatternFly menus (dropdowns, select, context selector)
- OpenShift is planning on adding favorites in table view (already in [#1860](https://github.com/patternfly/patternfly/issues/1860)) and our "project selector" (which is a dropdown right now and I think could use the same type of styling as favorited items in application launcher) for our 4.7 release, where we'll start implementation work around August.

What the project selector looks like currently. The +/- gives you the ability to add that project as a "favorite". Once that project is added as a favorite, it can be set as your "default" project by selecting the star. You can only have 1 project set as default.
<img width="370" alt="Screen Shot 2020-05-07 at 1 41 46 PM" src="https://user-images.githubusercontent.com/30870144/81419629-8eda3b80-911c-11ea-9d03-4ee0988c477f.png">

2. Here's what I was proposing as a possible design update for that and used the application launcher styling and symbols to create it (excluding the label)
<img width="1109" alt="Screen Shot 2020-05-08 at 11 11 28 AM" src="https://user-images.githubusercontent.com/30870144/81419705-b204eb00-911c-11ea-98e8-c3e8a9039d90.png">

Here's the [favoriting doc](https://docs.google.com/document/d/1PzTl5gvMumWWvPZKWHvcJrg6j4g7nRYggcB9q4byD5s/edit?usp=sharing) that includes more info if necessary. 

cc: @mcarrano

**Comment by gdoyle1** [comment]
@mcarrano this is something we can go with for now! It follows the exact same functionality as the application launcher but for a select menu. Also fyi this mockup includes a search filter within the select menu as well.

<img width="898" alt="Screen Shot 2020-06-22 at 9 41 39 PM" src="https://user-images.githubusercontent.com/30870144/85351206-2929ef00-b4d1-11ea-878e-627a48d06865.png">

**Comment by mcarrano** [comment]
Thanks for this @gdoyle1 . I have opened https://github.com/patternfly/patternfly/issues/3209 to track the core implementation.

**Comment by gdoyle1** [comment]
@mcarrano can I close this since core implementation was completed?

**Comment by mcarrano** [comment]
It's still waiting for implementation in React.

**Comment by evwilkin** [comment]
React issue: https://github.com/patternfly/patternfly-react/issues/4528
