### ISSUE TITLE
Tabs demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#853]
Introduce a Tabs demo that will illustrate usage of different style tabs in context. This will be important as we introduce alternative tab styles per https://github.com/patternfly/patternfly-next/issues/1855. Goal would be to provide some visual examples of where and how to use different tab styling.

**Comment by mcarrano** [comment]
@mceledonia @mcoker based on our conversation this morning, I have transferred this issue back to design to explore the usage around tabs and create corresponding mockups for a demo. I will pull this into the next milestone for design work and hopefully we can get this on the feature roadmap somewhere as I think showing common usage of tabs in context will be very helpful.

cc @LHinson

**Comment by gdoyle1** [comment]
Attaching the google doc that @abichen has started here: https://docs.google.com/document/d/1_LFmUOEWuCkGxywuMx-YCiQytrROAKpt_54ql8nlX5M/edit?usp=sharing

**Comment by gdoyle1** [comment]
Here's what I came up with for this demo! https://marvelapp.com/prototype/5fba0cj
@mceledonia @mcarrano if you could take a look and leave comments on the Marvel, that'd be great

**Comment by gdoyle1** [comment]
[WIP google doc](https://docs.google.com/document/d/1dCbpJfvp3Sk-6A5rVtCJcAFdVlw7tTGjYXlwH4Ljai8/edit?usp=sharing) for tab design guidelines

**Comment by gdoyle1** [comment]
[Updated this marve](https://marvelapp.com/prototype/5fba0cj)l to contain specs for each variation! @mcarrano

**Comment by mcarrano** [comment]
Thanks @gdoyle1 . @mcoker can you review this and let me know if you see any issues? If not, I will open a new core issue to get this into the upcoming sprint.

**Comment by mcoker** [comment]
Yep this all looks good to me. A couple of notes:

We don't support this kind of card layout out of the box. I would probably build that by using a page section with a grey background with a grid layout inside, with cards for the main section and 2 cards on the right. I'm also assuming that would need to be responsive? And also assuming that the Tab Content panel (the thing that changes based on the current item in primary tabs) is the main card with Status and sub-tabs? Or is that whole page section, including the stacked cards on the right, part of the tab's Tab Content?

<img width="2017" alt="Screen Shot 2020-11-16 at 4 26 37 PM" src="https://user-images.githubusercontent.com/35148959/99315810-d9a1e200-2828-11eb-82ab-5c252baf72e1.png">

This looks like a split layout, with the vertical tabs on the left, and the tab content on the right - though the Tab Content component doesn't have padding by default. We could add that as an option.

We could also nest a page main section inside the right side of the split layout, though we typically only use page sections as direct children of the page component's main section area.

Another thing we could do is, now that we have page section groups, which allow the user to group multiple page sections together (to make a group of sections sticky, for example), the group could also support a horizontal layout for creating a row of page sections.

An inline or static drawer could also work there. That would work well as the drawer panel and content can either have padding or not.

Would it also need to be responsive?

<img width="1703" alt="Screen Shot 2020-11-16 at 4 27 32 PM" src="https://user-images.githubusercontent.com/35148959/99316281-b461a380-2829-11eb-91b0-19c9b46b0520.png">

**Comment by mcarrano** [comment]
> We don't support this kind of card layout out of the box. I would probably build that by using a page section with a grey background with a grid layout inside, with cards for the main section and 2 cards on the right. 

I'm not sure there's a good reason to complicate this. @gdoyle1 is there any good reason to have this two column layout here or can we demonstrate the same tabs functionality with something more standard?

> Would it also need to be responsive?
Regarding the vertical tabs, it's a great question what happens to this when you switch to mobile. It may be a similar problem to what we are doing with jump links. Seems like the vertical tabs will need to live in their own page section? @mcoker let me know if you think there's a general solution for this type of layout or if we need to open a design story for this.

**Comment by mcoker** [comment]
@mcarrano re: vertical tabs, a user could use either the flex or grid layout to create a responsive layout that goes from stacked on mobile to split on a desktop viewport width. I think along with that, we would need to extend the tabs component so that a user can specify either a vertical or horizontal layout at different breakpoints. And then it would be up to the user to specify the tabs change from horizontal to vertical at the same point their flex/grid layout changes from stacked to split. Does that seem like a reasonable approach? Or should the page sections also support the stacked/split layout? It would probably be easy enough for `pf-c-page__main` (the main section container) and `pf-c-page__main-group` (a group of regular page sections) to support a horizontal layout of page sections.

**Comment by gdoyle1** [comment]
@mcarrano @mcoker Updated that card view so we no longer have that problem!
![horizontal tabs with grey bg](https://user-images.githubusercontent.com/30870144/99716592-4cec6380-2a76-11eb-9c5e-7cdd4a3b393b.png)

**Comment by mcarrano** [comment]
Thanks @gdoyle1 . I have opened https://github.com/patternfly/patternfly/issues/3700 to track core implementation. I have also opened a new issue here to implement responsive versions of vertical tabs that should work with this demo: https://github.com/patternfly/patternfly/issues/3698
