### ISSUE TITLE
Keep table headers sticky when scrolling table contents

### ISSUE THREAD

**Issue by amysueg** [patternfly/patternfly-design#855]
When scrolling table data it is often preferable to keep table headers stationary as the user scrolls the data, to enhance understanding of row contents. Without a sticky header, it is difficult to know how to interpret values once the header scrolls out of view.

This request was made by the Business Automation team, but I can see it being useful for any product that uses the table component.

@mcarrano

**Comment by mcarrano** [comment]
@mcoker I know we talked about this behavior in the past. Is there an open core issue to track this? Business Automation needs this and I was not sure if we already have it on the roadmap.

**Comment by amysueg** [comment]
cc: @lclay2

**Comment by mcoker** [comment]
@mcarrano yep, here is the issue - https://github.com/patternfly/patternfly/issues/2838

And I have a PR up for it here - https://github.com/patternfly/patternfly/pull/3093

**Comment by mcarrano** [comment]
Thanks @mcoker . In that case I am going to close this design request @amysueg . Please feel free to follow the core issue referenced above. I assume this will require a React follow-up @mcoker ?

**Comment by mcoker** [comment]
@mcarrano yep, it will be an opt-in, so react will need to add a prop for users to specify if they want sticky headers.
