### ISSUE TITLE
Investigation into HSLa() colors

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-design#860]
We can do a lot of really cool things in CSS using the `hsl/hsla()` color functions.

* Define colors by individual values for hue, saturation, and lightness. This allows us to modify contrast, light/darkness, etc by modifying a single part of the function as opposed to redefining the color entirely.
  * Great for theming (light/dark theme, high contrast, etc)
* Introduce an alpha layer for transparency in the color itself, which we don't get with hex (though we would get with `rgba()`, too)
* Use CSS vars for the individual H, S, and L values combined with math to create different variations of the colors.

I [made a quick demo](https://codepen.io/mcoker/pen/dyGPVKR?editors=1100) where I defined 2 colors, our primary blue and danger red colors, then created light and dark versions of the colors by just adjusting the "lightness" value. This is a really simple example, but gets the point across. I'm also adjusting both the blue and red colors to be "dark" and "light" by using a single variable that adjusts lightness in both colors. Meaning, we could assign a single variable to adjust the lightness value of all of our colors, as opposed to having to define a unique dark hex value of all of our colors.

This is a really good article that talks about it some more, with more examples:
https://tsh.io/blog/why-should-you-use-hsl-color-representation-in-css/

With the investigation into color theming, this seems like a good opportunity to bring this up. Let me know if you have any questions or want to see more demos!

cc @mceledonia @mcarrano

**Comment by mcarrano** [comment]
Very interesting @mcoker . I see the potential value of this. But if we did this, would it impact consumers of PatternFly at all or would this be totally hidden to the if they are just using the color variable system? My concern would be replacing the familiar color system with something that will be less familiar to many designers and developers.

**Comment by mcoker** [comment]
> if we did this, would it impact consumers of PatternFly at all or would this be totally hidden to the if they are just using the color variable system?

Users wouldn't be impacted, as long as we represented each hex color as its `hsla()` equivalent.

> My concern would be replacing the familiar color system with something that will be less familiar to many designers and developers.

Agree, what we have now works fine. The only thing I wish we had sometimes is alpha channel for transparency, but we have ways around it. I think it would really be up to the designers as to whether this sort of thing would be beneficial by evaluating things like creating color palettes by adjusting H, S, and L independently or maybe mathematically. There are lots of things you could do with it. Some designers probably have a better understanding of the benefits than I do.

Here is a similar concept defining a font-size scale using a base font, and a multiplier to create larger fonts. So your base font (`--base`) is `16px`, and you have a scale multiplier (`--multiplier`) of `0.2`. You could also have a multiplier for each change in font-size, too, but this is just a simple example. So you would generate a font scale like:

`--font-xs: (--base - (--base * (--multiplier * 2)));
`--font-sm: (--base - (--base * --multiplier));
`--font-md: --base;
`--font-lg: (--base + (--base * --multiplier));
`--font-xl: (--base + (--base * (--multiplier * 2)));

That's a simple example, but does something similar where you can just update the `--base` size and the rest of your fonts update to scale. Or update the scale, and all of your fonts adjust automatically.

**Comment by doruskova** [comment]
@mcarrano @mcoker I agree that this change is not going to have an impact on designers because they still get HEX code for the color. It might help designers to read and define colors because the HSL color model is more intuitive and human-friendly. A huge advantage of this (HSL) color model is the maintenance because you can tweak one aspect of the value and don't have to change all values. That means fewer variables. Sketch doesn't have any issue showing the HSL color model. No changes are needed on a Design kit if the color model changes. I created this simple tutorial how to read the colors when using the HSL model. 
![HSL-color-model](https://user-images.githubusercontent.com/32618096/159263942-fb513c77-d1c7-45e6-805e-ca9a06bae404.png)

**Comment by mcarrano** [comment]
Let's consider this done for now. While we could move in this direction for PF4, after discussing with @mcoker we agree that this would be something to consider as part of an overall visual refresh. Will close.

cc @mceledonia
