### ISSUE TITLE
Alerts - Custom icons and/or more types

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design#861]
Based on discussion in patternfly-design channel on Slack.

I have a use case where I need to tell the user that they have launched something that is running in the background. The background process hasn't succeeded or failed, it is just running (and may be running for a while).

None of the existing alert types are a good match for this notification:
![Xnip2020-04-07_09-19-38](https://user-images.githubusercontent.com/23172038/78673994-eaf93800-78b0-11ea-827c-ed10d288e6ba.jpg)

Success - The process hasn't succeeded!
Info - This is vague, and the (i) icon implies (to me) some sort of hint/instructional information -- but this is not that
Bell - The default bell is very generic but also implies (to me) something timely - its an alert bell!
Progress - Does not currently exist, but would be a custom icon
No icon - Does not currently exist, but takes that icon question out altogether.

The ask here is for Patternfly to consider:
a - allowing for custom icons OR
b - creating a "progress" alert OR
c - allowing for a no-icon toast alert

**Comment by KendraMar** [comment]
Becca and I brought up something similar today (june 11) at the cloudredhat.com design share for sources. The wizard has kicked of a process and can't notify the user thru the wizard that it fully succeeded ( the backend to do this doesn't exist). Instead, we can only say "hey, we started the process! go to this other page to see if it completed successfully."

**Comment by mcarrano** [comment]
@katierik @KendraMar What I think we could do here is to open up the "default" style alert to take any icon. We chose the bell because it was the most generic thing we could think of, but I can see where you might want to use a more meaningful icon here. 

Would this satisfy the request? Do you have any specific timeframe when this is needed?

**Comment by KendraMar** [comment]
let's talk at design share on Thurs, June 18? I'm always partial to the info icon, but couldn't argue against the bell.

**Comment by mcarrano** [comment]
My proposal here is to open up the alert and allow the consumer to substitute a different icon for the default alert to handle this kind of use case. @mcoker what would be involved in doing this? Would you need any input from design or can I just more this to core to make that change?

**Comment by mcoker** [comment]
@mcarrano is it expected that the user would use another icon font icon (font awesome, pf-icons, etc) or an icon from the patternfly react-icons library? Or would we want to support any sort of custom icon/format there?

**Comment by mcarrano** [comment]
Yes, we would restrict the icon to currently supported icon types, only. I've opened https://github.com/patternfly/patternfly/issues/3257 to track implementation and will get this on the roadmap.
