### ISSUE TITLE
Inline alert/error message demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#862]
We currently have no guidance about how to display inline messages that result from validating information on a page that occurs after clicking a Submit button or other validation. Inline alerts are useful for providing global messaging at the top of a page (or a modal) but are less appropriate for inserting into the body of a page.

It would be helpful to define some typical use cases and mockups to guide designers on usage and placements of inline alerts and/or form validation errors when you want to communicate one or more errors to the user. These should be translated to a demo that illustrates the intended design.

**Comment by mmenestr** [comment]
**My initial thoughts are the following:**
- Always use inline validation as a default. 
- Optionally: you can also choose to add an inline alert at the top of the form or page to emphasize the error states. However, it should never be used on its own (unless there is nowhere to do inline validation) .
- If you have inline validation along with the inline alert, you do not need to go into detail about the errors in the inline alert. 
But if you do not have inline validation along with your general inline alert, you should go into more detail about the error. 

![image](https://user-images.githubusercontent.com/51165119/86409585-2a081100-bc87-11ea-880a-abe0cf070b70.png)

I can't currently think of any cases where you would have an error validation without a form? or at least some sort of user input? Can you? @mcarrano @gdoyle1  or do you have any specific use cases you can think that I should be addressing?

I think another thing that we could use this issue for is potentially designing an error state for selection inputs in forms (ie: radio buttons, checkboxes). Because right now it seems only text input, or drop-downs have error states. Here is a first stab:

![image](https://user-images.githubusercontent.com/51165119/86409636-4906a300-bc87-11ea-802d-a722640ed3ae.png)

**Comment by mcarrano** [comment]
This looks great @mmenestr . I agree that it's hard to envision circumstances where you would need this outside of a form. I thin that the design you propose if fine for validation errors on things that are not form fields, except that I would sway the order of the text and icon to be consistent with the way that other alerts appear. @mceledonia thoughts? There are just a couple of things to consider:

* Are there other statuses that we should consider? Warning states perhaps as I've seen the desire to place warning messages inline on a form. Maybe success or info also? This would allow someone to place an alert in the body of a form that can convey any kind of information but is not as heavy handed as an inline alert.
* We should consider what the rules are for placement. I think the example here is fine. But would think always be placed below a label? What if we had left-aligned labels? Are there other placement situations that might come up?

**Comment by mmenestr** [comment]
@mcarrano I agree looking back that the icon would be better on the left, and text on the right!
As for left-aligned labels, i'm thinking it would still sit underneath the label like this:
![image](https://user-images.githubusercontent.com/51165119/86611832-3d63f680-bf7d-11ea-8c7d-92fa26a5ccff.png)

My thinking in general in terms of placement (and i'm just thinking out loud here), is that as a user, it would be easier to understand where the error is if it's right next to the respective label, as opposed to underneath a group of options. Especially in this case where the error is in the last field of the form. Having the "This is a required field" underneath the radio buttons but right above the submit button instead might be interpreted as not being directly related to that field, but maybe an error somewhere else in the form: (illustrated here:)
![image](https://user-images.githubusercontent.com/51165119/86612070-8ddb5400-bf7d-11ea-8562-9e9f96e884c7.png)

**Comment by mcarrano** [comment]
I think this makes sense @mmenestr .

@mcoker do you see any problems with this approach?

**Comment by mcoker** [comment]
@mcarrano this looks fine to me. Just to confirm, we're creating a demo to show alternate placement of the form error message

* Associated with the form label versus the control (displaying under the label)
* Associated with a group of controls (eg, a group of inline checkbox controls)
* An inline alert message - at the top of the form and/or the top of the page

**Comment by mcarrano** [comment]
Yes, that sounds like a good summary to me @mcoker Do you agree @mmenestr ?

I will go ahead and open a new core issue to get this into the implementation queue.

**Comment by mcarrano** [comment]
OK. I've opened https://github.com/patternfly/patternfly/issues/3282  @mmenestr can you place the design recommendations in a Marvel deck or similar and attach them to that core issue for reference? Thanks.

**Comment by mmenestr** [comment]
@mcarrano I still need to finalize the placement of an inline error for a group of controls. It would **either** be underneath the label, or underneath the controls, so from my understanding it would be either or for the first two bullets, not both. But let me know if that wasn't your takeaway from the meeting!
The third bullet is right though! You'd have a demo with an inline alert appearing at the top of the page, but underneath the header & description of a page!

So once I finalize where to place the inline alert, i'll be sure to add the recommendations and mocks to the issue :)

**Comment by mcarrano** [comment]
OK. I will keep this design issue active then. @mcoker I will push the implementation out to milestone 11 in this case.

**Comment by mmenestr** [comment]
Here are the mocks: https://marvelapp.com/prototype/4j6agce 
I'm thinking just one example with vertical form, and one with horizontal? But open to any suggestions here.

I also edited the form guidelines to add in some guidance about this. You can find it in [this doc](https://docs.google.com/document/d/19gVVVJxnaP8eS8sw5as_BwgJnAJVlYkZlpXtWE_QrXE/edit#), in the error and validation section. Whatever is new is in purple text!

**Comment by mcarrano** [comment]
@mmenestr Yes. I think this is a good solution. Please just link the Marvel doc to the Core issue and we can move this forward. Thanks!

**Comment by mmenestr** [comment]
@mcarrano can we close this or not yet?

**Comment by mcarrano** [comment]
Yes, this is complete. But I'm not closing design issues immediately so we can use them to link any ongoing work.
