### ISSUE TITLE
Introduce Modal Alert variation of a modal

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#863]
We currently have design guidance on modal alerts here but not a simple way to include icons within the modal title area. https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal#types-of-modals Want to create new modal variant that takes an icon to reflect known status conditions similar to an alert.

**Comment by mmenestr** [comment]
Here is what i'm thinking for a simple icon on the left of a modal header. 

This is what it would look like with a 16px icon, and 8px spacing:
![image](https://user-images.githubusercontent.com/51165119/88588083-fb325000-d024-11ea-98e6-6ea46057b69c.png)

To me, the icons seems very small here, but i'm respecting the 16px icon sizing choice. Here is what it looks like with the icon being 24px, and the spacing being 16px. @mceledonia @gdoyle1  I was wondering if there is any room for flexibility when it comes to this, and whether we could use 24px icons in here?
![image](https://user-images.githubusercontent.com/51165119/88588168-1f8e2c80-d025-11ea-9b30-b7d0f4b29156.png)

Here's a side by side of the difference it makes:
![image](https://user-images.githubusercontent.com/51165119/88588196-2ae15800-d025-11ea-9a62-9c0ace4c21bd.png)

**Comment by gdoyle1** [comment]
@mmenestr 24px icons look like they fit better here with the default modal header text size. Thoughts @mceledonia ?

**Comment by mmenestr** [comment]
**Final decision:** Go with 24px icon in the modal header. 
Here are the specs fro both a compact modal and large modal. Everything else in the modal would work the same as any other modal, the only difference is the ability to have an icon on the left of the header, and switch it to other icons for other use cases (although the demo should probably have an exclamation-triangle icon as shown).

![image](https://user-images.githubusercontent.com/51165119/89337676-538ed080-d669-11ea-8188-2e04bbc5dd60.png)

@mcarrano ready to close and move to implementation

**Comment by mcarrano** [comment]
I have created https://github.com/patternfly/patternfly/issues/3374 for core implementation.
