### ISSUE TITLE
NotificationDrawer: Add 'x' to drawer to help understand how to close an open drawer

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-design#865]
There is a current openshift bug that is requesting an 'x' be added to the notification drawer so that the user understands how to close it.

https://bugzilla.redhat.com/show_bug.cgi?id=1800614

**Comment by maryshak1996** [comment]
I think that this covers what we need: https://marvelapp.com/prototype/8i964cj
@mcarrano @mceledonia @lboehling

**Comment by mcarrano** [comment]
Works for me!

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/3331 for core implementation.
