### ISSUE TITLE
Tooltip for dark theme

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#868]
Requesting a tooltip with a white background that is suitable for dark theme and/or over a dark area of the screen.
Design (by @coreyvickery):
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/9a5cafe6-30a9-431a-8958-174c033c2b0f/

**Comment by mcarrano** [comment]
@mceledonia do you see any issue with adding a light tooltip? Do you think this should automatically change according to theming or be a consumer choice?

**Comment by ajacobs21e** [comment]
Is it possible to be both? There could be a use case where I have an area of the screen that's dark but am using the light theme.

**Comment by doruskova** [comment]
@mcarrano Here's the updated mock with example https://marvelapp.com/prototype/963bhhh/section/1210399

**Comment by doruskova** [comment]
@mcarrano updated mock that we agreed on at the meeting https://marvelapp.com/prototype/963bhhh/section/1210399
