### ISSUE TITLE
Marketing card with larger spacing and text 

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#873]
Requesting variations for a card to support larger spacing, headlines, text, and CTAs for marketing contexts. 
Designs by @awatkins-rh
https://www.sketch.com/s/9713de1d-eb6e-48f7-9d75-2e46f569bc48

**Comment by ashton** [comment]
I don't think these designs are mine hahaha

**Comment by ajacobs21e** [comment]
@ashton oops sorry about that, autofill failed me!

**Comment by ashton** [comment]
Hahaha no problem

**Comment by mcarrano** [comment]
@ajacobs21e @awatkins-rh the link in the description appears to be private. Can you share it out?

**Comment by gdoyle1** [comment]
@mceledonia @mcarrano @ajacobs21e @awatkins-rh

Checked the sketch file out and I think we'd just add a "large" spacing version of the card component... I tried spec-ing out the examples provided here:
![MarketingCardProposal](https://user-images.githubusercontent.com/30870144/96601446-057c8700-12c0-11eb-9532-cb49b9f8d6cf.png)

**Comment by ajacobs21e** [comment]
The other difference is marketing cards have rounded corners. @coreyvickery @dcaryll Is there a significant need to have rounded corners for a marketing context?

**Comment by coreyvickery** [comment]
@ajacobs21e It was a decision that was made a long time ago to 'soften' the look of our layouts since they're longer and more open.

**Comment by gdoyle1** [comment]
Updated to add the ability to add rounded corners! The only thing is I'm not sure how that should be applied to the existing cards - can the rounded corners only be applied to the "large" card?
![Proposal](https://user-images.githubusercontent.com/30870144/96928645-dfedaa00-1486-11eb-915a-6c3e2477c206.png)

**Comment by coreyvickery** [comment]
@ajacobs21e @gdoyle1 @mcarrano Is it a business requirement to round corners on all cards or are we just trying to match styles across websites?

**Comment by gdoyle1** [comment]
> @ajacobs21e @gdoyle1 @mcarrano Is it a business requirement to round corners on all cards or are we just trying to match styles across websites?

@coreyvickery Personally, I have not heard another use case of needing rounded corners on cards from product teams, so I'd say it's not a "business requirement" although I'm not sure I understood your question. I'm also not as up to date with the web use cases.

My thoughts were that we could:
1. Give all users the _option_ to use rounded corners on cards
2. Not provide that option to users, and if you want rounded corners, you'd have to customize it yourself

**Comment by mcarrano** [comment]
Yeah, we have no requirement to apply rounded corners across the system. We could introduce a rounded card as an option for marketing use cases. But I would not wanted to open the door for inconsistent usage in product. 

@mcoker do you have any thoughts here?

**Comment by mcoker** [comment]
> We could introduce a rounded card as an option for marketing use cases.

Agree, I think the easiest way would be to add it as a variation. 

> But I would not wanted to open the door for inconsistent usage in product.

That would be an issue with a generic modifier. One thing that could help is calling the modifier something specific indicating the use case, not just the visual change. eg, something like `pf-m-marketing` vs `pf-m-rounded-corners`. Is it the case that most/all marketing uses of the card should have rounded corners, or only some?

**Comment by coreyvickery** [comment]
@mcoker The intention is for all cards used in marketing contexts to have rounded corners. If they don't appear to on some older pages, they're probably in some backlog to be updated at some point.

Here's a decent example of a marketing page with lots of cards with rounded corners.

https://www.redhat.com/en/technologies/all-products

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/3670 for core implementation to include "large" card variants and separately introduce the ability to add rounded corners to any card.
