### ISSUE TITLE
Horizontal jump links

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#875]
Requesting a horizontal version of vertical jump links (https://github.com/patternfly/patternfly-design/issues/792)
Jump links will navigate a user to a section lower on the same page. The band housing the horizontal jump links could also house other things, such as a logo or button. 

Design: 
https://www.sketch.com/s/f6a52c25-8657-4680-9d3e-4c09131e6ed0/a/mYbkyw
https://www.sketch.com/s/f6a52c25-8657-4680-9d3e-4c09131e6ed0/a/Da0Aj2
These are differentiated from tabs by putting the highlight line on top rather than the bottom. 
Still need to determine where to put the label.

**Comment by mcarrano** [comment]
I combined this with #792 (attached the referenced designs) and noted that jump links need the ability to be vertical or horizontal. Prefer to track this as one new component and therefore will close this out.
