### ISSUE TITLE
Strength indicator

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#877]
Requesting a strength indicator. I need it for a password strength indicator but there may be other use cases for a strength and/or completion indicator for a form. 
The component should have some sort of label to indicate strength (low, med, high etc) and possibly have the option to show helper text for tips to improve the strength.

**Comment by ajacobs21e** [comment]
![image](https://user-images.githubusercontent.com/6415742/95940020-64676b00-0dab-11eb-97ec-ac756e5642a2.png)
I modified the progress bar component to put the bar chart in line with the label and value text

**Comment by ajacobs21e** [comment]
"We found that meters with a variety of visual appearances led users to create longer passwords. However, significant increases in resistance to a password-cracking algorithm were only achieved using meters that scored passwords stringently"
From https://users.ece.cmu.edu/~lbauer/papers/2012/usenix2012-meters.pdf

**Comment by doruskova** [comment]
@ajacobs21e Could you describe your use-case more so that I can imagine it better? Do you need it for a login page or somewhere else? Do you have any mocks where do you need to use the indicator? Thanks!

**Comment by ajacobs21e** [comment]
Here are two examples that I'm using in my mockups. They're different pages but both for a password. 

Example before typing:
https://marvelapp.com/prototype/98fd61b/screen/76733076

Example after typing:
https://marvelapp.com/prototype/98fd61b/screen/75352348

**Comment by doruskova** [comment]
@mcarrano @ajacobs21e Here's the update for the password strength meter. There are few variations of how to display the indicator and the description (guidance) for a password. https://marvelapp.com/prototype/6jehce7/screen/77881829

I like the first option where the indicator is below the input field and the description could be in the popover to save space. I'm curious about the feedback.

**Comment by ajacobs21e** [comment]
@doruskova Thanks Marie! I left comments on the Marvel.
I plan on updating my help text to this component when it's available: https://marvelapp.com/prototype/5bjdj7c/screen/67735781

I have an idea of how to combine these two, let me mock it up and share here and see what you and @jknilans think

**Comment by ajacobs21e** [comment]
https://marvelapp.com/prototype/5cjahdc/screen/77895654 Here are a pile of ideas, please tear them apart :D 
@doruskova @jknilans @mceledonia @mcarrano

**Comment by mcarrano** [comment]
Thanks for offering these options @ajacobs21e . Personally I like the one with the strength meter directly below the field and the requirements below that. But however we approach this, we should make sure these elements could be used separately or together. For example, I might just want the password strength meter by itself. Or I might want to use the real-time requirements checking for something other then passwords.

**Comment by mcarrano** [comment]
@ajacobs21e so looks like this is just a Javascript library that does the validation and not the UI. Is that right? I wasn't thinking that PatternFly would write it's own validation, so I suppose the consumer of our component could use this or anything else. What were your expectations?

**Comment by ajacobs21e** [comment]
@mcarrano I don't have any expectations other than documenting this info somewhere so it doesn't get lost in my head :)

**Comment by doruskova** [comment]
@mcarrano @ajacobs21e Here's the update including the validation. https://marvelapp.com/prototype/6jehce7/screen/78177955 
I don't know how do we want to approach this if we want to keep the indicator and validation separate or not, but my preference is still having the indicator below the field and validation below the indicator. Let me know your thoughts. Is even possible to use the validation for some other use-cases except for passwords?
<img width="549" alt="Snímek obrazovky 2021-04-01 v 15 47 23" src="https://user-images.githubusercontent.com/32618096/113303789-b708f500-9301-11eb-89d6-448d09c75de9.png">

**Comment by ajacobs21e** [comment]
@doruskova Thanks Marie. I still think this looks like a progress indicator for the validation requirements. I am wondering if we need the strength bar with the validation requirements. 

What if it was something more like this?
![image](https://user-images.githubusercontent.com/6415742/113305514-1d295400-92d1-11eb-9a36-fcb526fb49e9.png)

**Comment by doruskova** [comment]
@ajacobs21e Great point! Or we can have only unstructured text below the indicator without the icons that indicate the validation and make it confusing. 
<img width="341" alt="Snímek obrazovky 2021-04-01 v 16 24 24" src="https://user-images.githubusercontent.com/32618096/113308769-c8a0cb80-9306-11eb-920b-6bcff27bb804.png">

**Comment by ajacobs21e** [comment]
@doruskova Yeah I think that works much better if it's just simple help text like "Password must be at least 8 characters" etc. 
And then if it's something more complicated like my example, we recommend using the validation list that Josh designed. 

What do you think about using some kind of status indicator on the word? Maybe a label isn't the right thing to use but something like that.

**Comment by doruskova** [comment]
@ajacobs21e I'd use what you have there, just without the label, haha. 
<img width="468" alt="Snímek obrazovky 2021-04-01 v 16 37 24" src="https://user-images.githubusercontent.com/32618096/113310469-8ed0c480-9308-11eb-9d04-3d430512cda0.png">

**Comment by ajacobs21e** [comment]
SOLD! :D

**Comment by doruskova** [comment]
So, I assume that this is what we're proposing as a result. Correct? @ajacobs21e @mcarrano 
<img width="720" alt="Snímek obrazovky 2021-04-01 v 16 49 07" src="https://user-images.githubusercontent.com/32618096/113312053-34386800-930a-11eb-97fd-f225caf3d3b7.png">

**Comment by ajacobs21e** [comment]
Yes, although I would use a simpler example of the help text in the left one. I think our guidance should be that if the requirements for a given field are that complex, you should use the example on the right.

**Comment by mcarrano** [comment]
I agree that this is a good approach. Maybe present again at next Wednesday's design share for more feedback @doruskova . I think that validation list should be something that can be applied to any text field (for naming conventions, for example) so that should be separate. But that's really more of an implementation issue.

**Comment by ajacobs21e** [comment]
https://www.nngroup.com/articles/password-creation/ 
the article says
_strength meters motivated users to create stronger passwords._
and also
_Note that indicating progress toward compliance isn’t the same as a strength meter._

but then no guidance on how to use both. oh well. 

I asked my dev team if it's possible to show what parameter failed the strength checker so we can show that to users. Even if it is, the code that evaluates the pw strength isn't part of the PF component, so we should assume we can't show exact guidance on how to make your specific password stronger.

**Comment by jeperry** [comment]
@ajacobs21e my interpretation is that there is distinction between compliance (validity) and strength. The strength of a non-compliant password is irrelevant so we shouldn't refer to it as weak, it is just invalid.

Ex: If password must have 8 characters and at least one lowercase, one uppercase, and one number:
- 'passw0rd' is not valid, strength is moot
- 'Passw0rd' is valid but weak

My takeaway is that strength meters and grades like weak/medium/strong are primarily useful when a system allows relatively weak passwords. Otherwise, when password rules are more stringent (e.g. several conditions), showing progress toward compliance seems to be the better practice. I'm not sure you'd want to combine these two treatments. In other words I think you guys are on the right track.

**Comment by ajacobs21e** [comment]
I met with infosec and for RHSSO we do want to be showing both validity (the requirements checklist) and strength. I agree with Vince and @jeperry that strength is moot if the password is invalid. It is still useful to give feedback on the strength for passwords that meet complexity requirements. The more we can do to steer users to choosing good passwords, the better. 
Here's how that can work (with some updated guidance from infosec):
https://marvelapp.com/prototype/5cjahdc/screen/78425548

I realize my use case is very Red Hat specific. Ideally my wires are at least PF compliant if this is not something we'll offer in PF. 

Password strength meters output a score to determine the color / level / fill amount so it's not possible to offer specific guidance on why the password is weak.

**Comment by doruskova** [comment]
@ajacobs21e @mcarrano I agree with Allie's approach. However, I've added the initial status for a strength meter because the user doesn't know that the meter will appear on the right after completion of all requirements. They could expect a different place because, for example, Apple has a strength meter below the requirements. https://marvelapp.com/prototype/6jehce7/screen/78472547

Also there is a question if we need to wait for all requirement to be able to measure the password strength. In this case I think it's important to wait for the first two, but then it should be possible to measure the strength of a password. So it depends on a type of the requirement IMHO. But, to be consistent > it would make sense to do this after all requirements meet.

**Comment by mcarrano** [comment]
@doruskova I guess that I don't have a problem with hiding the strength meter until there is something that can be displayed. If we are to show it, not sure "waiting" is the right word, but don't have a better one. As for what the rules are about when  a password becomes valid, I don't think we can define that from a PatternFly perspective. We are just giving the product some valid options to utilize according to their requirements.

**Comment by doruskova** [comment]
@mcarrano Agree. So, let's make it simple and leave it without the initial state. Added this [version here](https://marvelapp.com/prototype/6jehce7/screen/78472547)

**Comment by mcarrano** [comment]
I like this much better @doruskova . If we all agree, can you update the document to only show what we consider the final version and move others to an archive page or just delete? I'd like to get this ready to hand off to development by next week. It should also be clear that while the strength meter is something explicitly associated with a password field, the validation checker is a pattern that stands on it's own and can be added to any text input. We'll need to consult with devs on the best way to implement this.

**Comment by doruskova** [comment]
@ajacobs21e are you ok with the second version without the initial state?
@mcarrano Here's the updated mock without the first version https://marvelapp.com/prototype/6jehce7/screen/78511266
Other versions have been archived.

**Comment by ajacobs21e** [comment]
@doruskova yes this is great! Thank you.

I have one nitpick :)
![image](https://user-images.githubusercontent.com/6415742/114881842-5b466d80-9dd1-11eb-83eb-ba3fd0b79ed5.png)
Do you think the icon should move up a pixel or two so it's bottom aligned with the text?

Should we update https://github.com/patternfly/patternfly-design/issues/949 to use dots instead of the minus icon for the initial state of the requirements?

**Comment by doruskova** [comment]
@ajacobs21e Thanks for pointing this, it should be fixed now.

**Comment by ajacobs21e** [comment]
@doruskova Perfect, thank you!

**Comment by mcarrano** [comment]
@doruskova So just to be clear, did we just settle on the designs I see on this page? https://marvelapp.com/prototype/6jehce7/screen/78511266  Does that mean we are no longer using the process bar to indicate strength - just the icon and text above the field to the right and the validation/helper text below the field?

**Comment by doruskova** [comment]
@mcarrano Yes!
