### ISSUE TITLE
Search page?

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#878]
Red Hat's web site systems need a uniform design for a search page and search results. While some of this is probably going to be Red Hat specific, there may be other elements that could be part of PF4. For example, most of the PF4 filters seem geared toward a table / list context rather than a whole page search.

Things this could include:
- larger search bar & search button
- page level filters (in a side bar?)
- page level pagination
- search results

Existing search pages:
https://access.redhat.com/search/#/?q=rhel&p=1&sort=relevant&scoped=false
https://www.redhat.com/en/search/rhel
https://catalog.redhat.com/hardware/servers/search?q=rhel&p=1
https://developers.redhat.com/search/?t=rhel

[Search page research](https://docs.google.com/document/d/1wA006psTV6oy8KzpFX5_giY0m8zkjwU7UHE9yytTqPA/edit)
[Pagination research](https://docs.google.com/document/d/1hr2V3Dt2PYeH-3y1fpr8e0umkSnG1EYk-6pm1E_LBOM/edit)

@mceledonia @coreyvickery

**Comment by dcaryll** [comment]
@ajacobs21e this would be a great project for the Website System Architecture team to help drive. I know it's probably already on their roadmap, just maybe not priority. But they could help to consolidate requirements.

**Comment by ajacobs21e** [comment]
Initial requirements gathering for pagination: https://docs.google.com/document/d/1hr2V3Dt2PYeH-3y1fpr8e0umkSnG1EYk-6pm1E_LBOM/edit

**Comment by ajacobs21e** [comment]
@maryshak1996

**Comment by maryshak1996** [comment]
thanks @ajacobs21e :) I've got some work in progress stuff as well that I can share here, and will look at what we both have to see if there's any gaps in PF components, and mock up some examples with both of our contexts in the same styling :) 
Here's my doc: https://docs.google.com/document/d/1HZJnIBgTnBTpL9FOas3KopmOGYNEMfN3OoHuQqejP50/edit

**Comment by ajacobs21e** [comment]
Potentially similar use cases:
Page level pagination
- Web use cases: blog, catalog, search, etc

Filters outside of a toolbar

- Rox - [SAP context selector](https://marvelapp.com/prototype/24cg5g7g/screen/71540168) (maybe)
- Shaks - [catalog view](https://github.com/patternfly/patternfly-design/issues/848)
- Brie - OpenShift operator hub
- Vince - tree view for a filter, on its own page
-

**Comment by maryshak1996** [comment]
@ajacobs21e I made some new updates to the marvel deck above if you wanna give it another look!

**Comment by mcarrano** [comment]
Reviewed this again and I think this would make a good PatternFly demo for building a full page web search. Will look to get this on the roadmap for sometime later in 2021.
