### ISSUE TITLE
Progress stepper

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#879]
Requesting a horizontal stepper to show progress through a workflow, similar to the PF3 wizard: https://www.patternfly.org/v3/pattern-library/communication/wizard/
It would be able to show completed, active, and not yet started steps. It could be numbered or just icons. It should be flexible to handle different branches in the flow, for example the answer to one step could change the number or order of subsequent steps.

**Comment by mcarrano** [comment]
@ajacobs21e do you have examples of how this might be used? We made a conscious decision to not support a horizontal stepper in PatternFly 4 due to responsive design concerns. Would like to better understand the requirement for this.

**Comment by ajacobs21e** [comment]
@dcaryll do you have a screenshot of the product trial progress bar?

**Comment by mcarrano** [comment]
What is the expected responsive behavior of this?

**Comment by coreyvickery** [comment]
@ajacobs21e Here is one we used a long time ago.

https://xd.adobe.com/view/2c764d19-3e2a-44d0-8fa0-9ff8df223702-7925/

**Comment by mcarrano** [comment]
@coreyvickery I think that a basic stepper like this in PatternFly makes sense. However, what would you expect the experience to be if someone were to access this page from their phone? The model starts to break down there.

**Comment by coreyvickery** [comment]
@mcarrano I guess I'd expect it to reduce in visual size, but the experience that we needed a stepper for didn't apply to mobile, so we didn't mock anything up for small screens. Happy to discuss further in Wednesday's meeting if you can make it.

**Comment by mcarrano** [comment]
Yes, let's discuss further on Wednesday.

**Comment by coreyvickery** [comment]
@mcarrano @ajacobs21e Here's what I've been working on for `Horizontal stepper` which will appear in our new trial experience flow soon. It's tentatively named `Progress stepper` to be free of labels such as orientation or device.

https://xd.adobe.com/view/a9362bd3-9f03-4db8-b79d-af9e6e0c03f8-fc65/

**Comment by mcarrano** [comment]
Thanks for posting this @coreyvickery . Just a couple of questions. Did you consider using the PatternFly blue instead of the green for completed steps? I think this looks OK in isolation, but would be interesting to see this in the context of a page where this might be used. I'm also interested in your thoughts on responsive resizing, especially as all steps can no longer fit within the screen horizontally. This complication was one of the reasons we abandoned the horizontal stepper approach when we were designing the PatternFly wizard.

@mceledonia can you also take a look at this?

**Comment by coreyvickery** [comment]
@mcarrano @mceledonia Thanks Matt, I think exploring other colors is a good idea. I chose a green check for obvious reasons, it's not an RCUE thing.

Regarding responsive resizing, I am happy to explore how the component scales across screen sizes with Michael's help. The version I posted was only meant to be used at one size for a specific project.

**Comment by ajacobs21e** [comment]
Ideally we should design this in a way that it could be clickable to navigate to each step

**Comment by vconzola** [comment]
@mcarrano Here's a screenshot of the pipeline we're displaying in the migration toolkit UIs.
![Screen Shot 2021-02-03 at 10 58 45 AM](https://user-images.githubusercontent.com/22823035/106773371-fae7c280-660e-11eb-82ad-f28b83f74d8f.png)

**Comment by ajacobs21e** [comment]
OpenShift pipelines modified canvas view example

![image](https://user-images.githubusercontent.com/6415742/106773806-7b0e2800-660f-11eb-8137-635823306c1a.png)

**Comment by coreyvickery** [comment]
@ajacobs21e I see a few variants that could be included: Mine, a version of mine with links, Vince's compact version, and the OpenShift version above with a white background and a drop shadow. Do we also want to explore a vertical version or anything else, like mobile?

**Comment by coreyvickery** [comment]
cc @mcarrano @mceledonia

**Comment by ajacobs21e** [comment]
I'll let @mattreid answer about openshift but I would imagine a version of Corey's with step labels could work. 
@mattreid does your use case need branching? Or is that second row more like details on the 'build product' step?

**Comment by coreyvickery** [comment]
@ajacobs21e Do we need to combine this with the [Progressive Form](https://github.com/patternfly/patternfly-design/issues/750) issue or how do you think we should proceed with finalizing this component? I or we can design the three variants as outlined in my comment 11 days ago, but this will need to be wrapped up very soon as we're preparing to develop one of the Product Trial experiences.

**Comment by ajacobs21e** [comment]
@coreyvickery Mobile could follow the same pattern as Wizard https://www.patternfly.org/v4/components/wizard/react-demos/in-page/ or it could use a vertical version like Progressive Form. If it's the former, I don't think this story needs to be combined with Progressive Form.

**Comment by mcarrano** [comment]
Agree with @ajacobs21e . I wouldn't combine this with Progressive Form.

**Comment by ajacobs21e** [comment]
Matt Reid is on PTO, I pinged him to look at this when he's back

**Comment by coreyvickery** [comment]
@ajacobs21e @mcarrano Here's a new round of designs that will be discussed on Wednesday.

https://xd.adobe.com/view/9a5a5c65-9ba2-4f43-8a0e-fc86e54a95f1-cf09/

**Comment by andybraren** [comment]
Here are a couple of recent examples of this pattern bubbling up in products. Consensus on a design like Corey's would be great. 👍

A forward-looking stepper mockup from OCM that shows the progress of a cluster installation in discrete steps, with left-aligned text:

![image](https://user-images.githubusercontent.com/9122899/115768450-4ee58600-a378-11eb-94db-a90c59da9582.png)

A work-in-progress stepper being developed in ACM for the same use case. Very similar to IBM Carbon's [Progress Indicator component](https://www.carbondesignsystem.com/components/progress-indicator/usage), which unfortunately doesn't include a responsive/mobile state but does have a vertical modifier.

![image](https://user-images.githubusercontent.com/9122899/115768835-d29f7280-a378-11eb-9688-9c2637e7fd5a.png)

**Comment by coreyvickery** [comment]
@andybraren Should we try and combine what you are working on with what I designed?

**Comment by andybraren** [comment]
@shirimordechay @nirfarkas @imjoyjean If @coreyvickery's design [here](https://xd.adobe.com/view/9a5a5c65-9ba2-4f43-8a0e-fc86e54a95f1-cf09/screen/a530854b-9999-4347-943a-f11f7bc02eae/) was available as a PatternFly component, would it meet the needs of OCM, ACM, and the Assisted Installer?

**Comment by shirimordechay** [comment]
@abenari We can definitely use this component to show long process progress in OCM (Such as installing and uninstall)! We can add an "X out of Y steps" indication and a minimized version of this for the popover view we have today:
![image](https://user-images.githubusercontent.com/10331355/116806369-37a35700-ab35-11eb-9be0-0fafc1a0dc76.png)

**Comment by nirfarkas** [comment]
In the Assisted Installer steps run simultaneously, so I'm not sure if this will fit us.

**Comment by imjoyjean** [comment]
Yes @andybraren as you've pointed out, I think we'll (ACM) find something like this useful. (A version of it is being explored right now, including it turning vertical for responsiveness per Andy's links, similar to what Shiri has above in the tooltip, but with a bar on the left that fills as steps are being completed) 
![image](https://user-images.githubusercontent.com/57908474/116904578-80c1dc80-ac03-11eb-8a0a-31a1cd268a27.png)

**Comment by vconzola** [comment]
Is there a version of this with reduced size and spacing that will fit
inside a table row? That's a requirement for the migration tools.

Vince Conzola

Red Hat <https://www.redhat.com/>

100 E. Davie Street

Raleigh, NC 27609

***@***.***    T: 919-716-5041
M: 919-459-7865
<https://red.ht/sig>

**Comment by coreyvickery** [comment]
@shirimordechay That's a great idea.

@vconzola Can you provide specs for the table? This component is responsive, so we can adjust it for small spaces.

https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/cbf08024-32d6-4303-a15d-1542fac0b54e

**Comment by andybraren** [comment]
Quick note: I've heard that ACM is aligning on something more like OCM's mockup, and OCM would like to align on something more like Corey's/PatternFly's design, so yeah, there's an opportunity here. 🙂

**Comment by AdamJ** [comment]
+1 to a horizontal stepper - CIM would have a use for an officially supported model. Right now, we’re using a wizard, but it doesn’t really fit.

**Comment by coreyvickery** [comment]
@mcarrano Here are my latest designs that we discussed in the smaller meeting. I can provide the XD source file if necessary. These could be considered final or ready for whatever will be added to them next.

https://xd.adobe.com/view/799b9517-3841-451b-a3d5-2867dd14ca44-2cc8/

**Comment by mcarrano** [comment]
@coreyvickery this is looking good. Just to reiterate the points I made at today's PF design share meeting, for the horizontal version, it would be great to left align the label of the first item and right align the last item so the the first and last nodes can align to the edges of the enclosing container.

@andybraren @shirimordechay @imjoyjean @AdamJ if we move forward with this design, will this work for your use cases?

**Comment by andybraren** [comment]
- +1 on trying out left/right alignment of the labels in the first and last steps. In isolation centering looks great, but in the context of a full page with step labels of uneven lengths (like the screenshots above) the component may feel imbalanced otherwise.
- We may want to test out status icons other than the nicely-rounded success/error and empty. Every in-product example mentioned above includes some kind of icon to indicate that the backend is doing something - `pf-icon-in-progress`, `fa-sync-alt`, `pf-icon-resources-X`, `pf-icon-pending`, and even the PF spinner. Will those work as-is, or maybe there needs to be a little blank space between status icons and the line in those cases?
- Shiri's popover and Vince's table examples may require a miniature version of this component. Maybe a mockup isn't necessary, but it could be good for the component to ultimately support small icons and small font sizes to work well in those contexts.
- Is the empty circle used here `pf-icon-resources-empty`? I wonder if the component should support using others too, like the greyed out `pf-icon-resources-almost-empty` used in Vince's pipeline context.

**Comment by gdoyle1** [comment]
Sketch file

[Progress steps.sketch.zip](https://github.com/patternfly/patternfly-design/files/6616838/Progress.steps.sketch.zip)

**Comment by shirimordechay** [comment]
See updated design [here](https://marvelapp.com/prototype/gfa4i5b/screen/80132907). Changes were made according to the feedbacks above and ACM/ AI/ OCM designers' requirements.

@andybraren @nirfarkas @imjoyjean @AdamJ @mcarrano please take a look.

**Comment by mcarrano** [comment]
This looks great @shirimordechay . I left a couple of comments on the Marvel deck. We can discuss more when we meet.  @vconzola also had a requirement for a compact version. Maybe a version with no labels fulfills that need? Vince, what do you think?

**Comment by vconzola** [comment]
@shirimordechay I see you added a compact (inside a table cell) version as an example. Compressed spacing with a single label for the current (or last) step. That's exactly what I need. Thanks.

**Comment by andybraren** [comment]
Thank you for all of these updates @shirimordechay, this is great!

- In the horizontal version, are centered labels like @coreyvickery's design no longer an option? I can imagine centered labels looking a bit nicer visually in some (but not all) scenarios.
- Somewhat related to centered labels, @mcarrano previously suggested "it would be great to left align the label of the first item and right align the last item so the the first and last nodes can align to the edges of the enclosing container." - does a right-aligned last item look odd?

**Comment by shirimordechay** [comment]
@andybraren Good point about the centered labels. I guess we can make it optional to change the alignment @mcarrano WDYT?

Regarding the last item alignment, it looks odd with right alignment for anything containing more than 1-2 words, especially with the sub-text IMO

**Comment by mcarrano** [comment]
@shirimordechay I am OK with allowing the option to center rather than left-align labels. However, I'm wary of supporting two options if there are not clear criteria for when to use one or the other. @andybraren are there specific cases you can think of where you would want centered vs left-aligned labels?

**Comment by andybraren** [comment]
@mcarrano One example would be Red Hat's product trial flows for [RHEL](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/try-it) or [Ansible](https://www.redhat.com/en/technologies/management/ansible/try-it) which use a similar-looking component with (very short) centered labels within a centered card.

I can't think of an in-product example where we do the same today, but any pairing of this component with a layout like [Bullseye](https://www.patternfly.org/v4/layouts/bullseye) or [Level](https://www.patternfly.org/v4/layouts/level) could potentially look nicer with centered labels. [OpenShift’s operator installation page](http://openshift.github.io/openshift-origin-design/designs/administrator/olm/convey-installing-operator/) has a centered card today, and if it were a multi-phase process and used this component then maybe the page could have been designed with centered labels, but I know that's a hypothetical scenario. 🙂

**Comment by mcarrano** [comment]
That makes sense @andybraren . Those product trial flows are probably using web components per @coreyvickery 's designs. So maybe we should have a version that is more in line with those? But I'm still not sure how to differentiate these. What do you think @shirimordechay @mceledonia ?

Other than that, I think this is pretty complete. I think the only thing left would be to create a visual spec with all of the prescribed spacings and font sizes to development. @shirimordechay let @mceledonia or I know if you have any questions about what to do here. Thanks.

**Comment by shirimordechay** [comment]
I think allowing the centered labels doesn't change the component much and it makes sense to add it. I don't think much differentiation is needed, it's just a small visual tweak IMO. @mceledonia WDYT?

Regarding the visual spec, it should all be in the [mockups](https://marvelapp.com/prototype/gfa4i5b/screen/80215316) but please take a look and let me know if something is missing @mcarrano . the sketch file can also be found in the PF sketch cloud workspace.

**Comment by mcarrano** [comment]
@shirimordechay Yes, I see the specs now. They look great. Let go with an option for centered labels with the default being left-aligned. I left a comment to just add that mockup and then I think this is ready for handoff to development. Thanks.

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/4214 to begin core implementation. Thanks for all your work on the @shirimordechay !

**Comment by nirfarkas** [comment]
The current design of the stepper doesn't align well with what we have inside the Assisted Installer/Central infrastructure Management. The steps in those are not linear, meaning, it's not that "Control plane" is being installed and only then "Workers" are being installed, they're being installed simultaneously. The same applies to the "Operators" and "Finalization" steps. Another thing is that the Assisted/CIM installers have data regarding the progress of the whole installation (% complete) and we don't want to downgrade to a stepper that doesn't inform the users about this.
I think we need to discuss this @matthewcarleton  @shirimordechay , @andybraren , @joy

**Comment by mcarrano** [comment]
@nirfarkas the stepper is intended to show the progress of a sequential, step-by-step linear process. If that's not what you have, then maybe the stepper is not the right solution. If you want to set up some time to discuss, that will be fine. I would need to see more details about the task you describe above to be able to comment further.

**Comment by matthewcarleton** [comment]
> The current design of the stepper doesn't align well with what we have inside the Assisted Installer/Central infrastructure Management. The steps in those are not linear, meaning, it's not that "Control plane" is being installed and only then "Workers" are being installed, they're being installed simultaneously. The same applies to the "Operators" and "Finalization" steps. Another thing is that the Assisted/CIM installers have data regarding the progress of the whole installation (% complete) and we don't want to downgrade to a stepper that doesn't inform the users about this.
> I think we need to discuss this @matthewcarleton @shirimordechay , @andybraren , @JOY

I agree, what you are proposing does seem like a variation of the PF stepper, maybe it could be a modified version of it.

**Comment by nirfarkas** [comment]
Thanks Matt!
I think I need to set a meeting around it with all stakeholders.
I'll send you an invitation.
Nir
