### ISSUE TITLE
Popover, dark

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#880]
Requesting a darker colored popover to use in contexts where it is difficult to see the white popover against the background. Here is an example of a popover on top of a table and it gets lost
![image](https://user-images.githubusercontent.com/6415742/85344730-7fd9fd80-b4be-11ea-8882-5d21461a1fed.png)

**Comment by mcarrano** [comment]
This issue is dependent on resolution to how dark theming will be implemented. Need to consider how elements like buttons or other controls that can exist inside of a popover would behave.

**Comment by doruskova** [comment]
@mcarrano In progress https://marvelapp.com/prototype/b6f31d1

**Comment by mcarrano** [comment]
cc @mceledonia

**Comment by doruskova** [comment]
@mcarrano Here's an updated mock with an example https://marvelapp.com/prototype/963bhhh/section/1210399

**Comment by doruskova** [comment]
@mcarrano updated mock that we agreed on at the meeting https://marvelapp.com/prototype/963bhhh/section/1210399

**Comment by mcarrano** [comment]
Thanks @doruskova Can you also add here the proposed change for the light theme popover (i.e. heavier shadow we proposed)?

**Comment by doruskova** [comment]
@mcarrano I think that we need to discuss it again because the last proposal to use a grey 600 is not working in the popover in combination with labels. Labels are using grey 600. That's why I used grey 700.

**Comment by doruskova** [comment]
@mcarrano Updated design here > need a feedback https://marvelapp.com/prototype/963bhhh/screen/75172511

**Comment by mcarrano** [comment]
I have opened https://github.com/patternfly/patternfly-design/issues/973 to track proposed changes to the light theme popover and will mark this as complete.
