### ISSUE TITLE
List variants - horizontal rule and icons

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#881]
Requesting an additional variant for a list to separate list items by a horizontal rule

**Comment by mcarrano** [comment]
@ajacobs21e when you say a list variant, do you mean a new variant of this Simple List component? https://www.patternfly.org/v4/documentation/react/components/simplelist  Can you say more about what's driving the need for this?

**Comment by ajacobs21e** [comment]
I think it would be more a variation of https://www.patternfly.org/v4/documentation/react/components/list

It's something that's currently used in a marketing context. Here are some examples:
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/5bf4b81c-d880-4395-8d80-bb17dec75843/Card-list

**Comment by mcarrano** [comment]
@ajacobs21e just taking a closer look at this. So if I understand correctly, the ask is to have more variety of list styling for presentation of static content as lists, correct? I think this has also come up from product where you want to list a set of items but bullets don't make sense.

I looked at the XD examples and I see a variety of things besides that horizontal separators? Would you expect to see all of those variations offered or is just adding the horizontal separators enough?

**Comment by ajacobs21e** [comment]
Yes, it's an additional list style.
The list with icons is used on the web as well so we should probably include that in PF too. Should I make a new story for that or can this story cover both new styles?

**Comment by mcarrano** [comment]
Thanks @ajacobs21e . We can use this issue to cover both. I've updated the title accordingly.

**Comment by maryshak1996** [comment]
I did some initial ideas @mcarrano @ajacobs21e but ran into a couple instances where I have questions about the type of direction we want to take an what the use case is that we are trying to support. I left some annotations my early design here: https://marvelapp.com/prototype/7gc36d1

**Comment by ajacobs21e** [comment]
@maryshak1996 Here's a use case from the marketing side: https://docs.google.com/document/d/1QWuD8l2nH3oFqz0IUad1S9V23lEIDYUtBxcSjDRX7Zg/edit#heading=h.oiftjocoex3
It's kind of between the list with small icons & list with large icons. Although it probably would be closer in format to the 'list with small icons' just with an option to use a slightly larger icon size

**Comment by mcarrano** [comment]
@maryshak1996 These look good. As I understood this issue, it's strictly about styling a standard HTML list item (i.e. a list created by an <li> tag and does to apply to interactive menus like the Simple List. There is a related issue here that shows some additional usage examples: https://github.com/patternfly/patternfly/issues/1635  Right now, the [List component ](https://www.patternfly.org/v4/components/list)only supports standard bulleted or numbered lists, so the effect of this would be to create additional styling options for lists of links or other content placed within the body or a card or a page.

**Comment by maryshak1996** [comment]
ahhhhh that makes more sense @mcarrano and @ajacobs21e thanks for that extra context :) I think that I was able to simplify the design so that it's aligned with just the basic list component, and I also lightened it up a bit in visual styling as well. Let me know what you think. Same link as before, but here it is again just in case: https://marvelapp.com/prototype/7gc36d1

**Comment by ajacobs21e** [comment]
@maryshak1996 it's perfect!

**Comment by maryshak1996** [comment]
@mcarrano made the updates mentioned in the last PF design sync:
- Indicated Hover + Default on the mockup
- Made the icon color use the standard icon color (bit darker grey)

**Comment by mcarrano** [comment]
Looks good @maryshak1996 . 

@mceledonia can you also verify?

**Comment by mceledonia** [comment]
Looks good to me, thanks @maryshak1996 @mcarrano !

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/3743 for core implementation. Thanks @maryshak1996 !
