### ISSUE TITLE
New tabs have a lot of white space

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design#883]
The new tab designs look great, but seem to have incorporated more white space than they used to have, making the tabs taller, and adding more white space to designs.

With the recent PF effort of reducing white space, I wonder if we should revert the spacing back to what it used to be - or at a minimum reduce the top and bottom spacing to 8px (and leave the left and right spacing to 16px if that is more visually desirable).

For visual of the old and new box tab:
![image](https://user-images.githubusercontent.com/51165119/85408901-206a0500-b533-11ea-9fd4-779642607a10.png)

**Comment by ajacobs21e** [comment]
The intention of making the tabs larger was to increase the click target, which had been a complaint with the old tabs

**Comment by mmenestr** [comment]
Ah! Ok, I didn't know that @ajacobs21e  - in that case I can just go ahead and close this. It just seemed contradicting to me at an initial glance, but that makes sense :)

**Comment by gdoyle1** [comment]
@ajacobs21e @mmenestr We might want to keep this alive depending on what comes out of the conversation between Michael and Matt Nolting! Seems like there are two stories going on right now that we need to find a single outcome from :)

**Comment by mcarrano** [comment]
@mceledonia @mattnolting I think this was addressed, but can you confirm?

**Comment by mcarrano** [comment]
@mmenestr can you verify if this is still an issue with the latest PF release (2020.08) and close if not? We think this has been addressed.

**Comment by mmenestr** [comment]
Seems like it was addressed since all I'm seeing in the documentation is these 'shorter' tabs, so i'll close.
![image](https://user-images.githubusercontent.com/51165119/86835473-2c44e380-c06a-11ea-9d84-9f8ed7bafe46.png)
