### ISSUE TITLE
Ability to have radio buttons in tables

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-design#884]
@mmenestr commented on [Tue Jun 23 2020](https://github.com/patternfly/patternfly-react/issues/4436)

Currently, tables in PF only support checkboxes. Would be useful to have tables that support radio buttons as well, without having to customize the component!

**Use case in cloud.redhat.com:**
Users have the opportunity to create a role from an existing role, and are presented with a table containing the existing roles they can choose from. They can only choose a single role here, before going to the next step.

![image](https://user-images.githubusercontent.com/51165119/85407058-b2bcd980-b530-11ea-89e8-bbde2ff13d0a.png)

@ryelo

**Comment by tlabaj** [comment]
moved to design repo

**Comment by mcarrano** [comment]
@mmenestr Let's discuss. I'm wondering if there's another way to solve this. How large is the list of roles likely to be?

**Comment by mmenestr** [comment]
If I had to give a best guess, I would say the list of roles would probably be around 30+ items long

**Comment by mcarrano** [comment]
@lboehling did you design a selectable row state for tables? I think so, but it may have only gotten implemented for the Data list. I would prefer to use that existing approach rather than introduce radio buttons to reflect row selection.

**Comment by trahman73** [comment]
@mcarrano The Ansible Platform teams would also be interested in support for single select radio buttons in tables. We also have some additional use cases where the resource title can also be a link to it's details page. In this case, selecting the entire row would not work. Example:

![image](https://user-images.githubusercontent.com/13351591/85775911-37a12200-b6ee-11ea-9a26-429eb7d58dde.png)

**Comment by lboehling** [comment]
After speaking with @mcarrano and @mmenestr, we've decided that our recommendation is to move forward with enabling radio buttons in lists/tables for single-row select (Option 1 in Marvel deck).

Design explorations: https://marvelapp.com/prototype/909de61/screen/72064645

**Comment by mmenestr** [comment]
Also, here is a screen recording of current work on implementing this on cloud.redhat.com (this is still in staging)

[radio buttons in table.zip](https://github.com/patternfly/patternfly-design/files/5099305/radio.buttons.in.table.zip)
