### ISSUE TITLE
Enhancement to in-page Wizard variation: Make left-panel sticky

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#888]
## Enhancement to in-page Wizard variation

**Use case**
In OpenShift, when creating a virtual machine, we have the option of creating one with an in-page wizard. When you scroll through the content of step 1 (or any step), you lose context of where you are.
<img width="1017" alt="Screen Shot 2020-06-30 at 11 51 22 AM" src="https://user-images.githubusercontent.com/30870144/86148160-44e05700-bac8-11ea-919a-d3c1a50be352.png">
<img width="1056" alt="Screen Shot 2020-06-30 at 11 51 27 AM" src="https://user-images.githubusercontent.com/30870144/86148167-46aa1a80-bac8-11ea-9a54-5b852e52ced5.png">

**Proposal**
Proposing that we make the left-panel sticky so that you are always aware of the step you are on and future/previous steps.

cc: @matthewcarleton

**Comment by mcarrano** [comment]
@mcoker What are your thoughts on this? I would be in favor of making this the default behavior for a wizard if that's easy enough to do.

**Comment by mcoker** [comment]
@mcarrano @gdoyle1 I created an issue here to add that enhancement - https://github.com/patternfly/patternfly/issues/3255

@mcarrano do you want to add it to the roadmap? I've put it in the backlog for now.

**Comment by mcoker** [comment]
Hey @gdoyle1 and @matthewcarleton! We're working on this issue this sprint and I was curious if you could clarify something. 


I filed an issue last year (https://github.com/patternfly/patternfly/issues/3255), that will make the in-page wizard layout behave the same as the modal wizard layout by introducing these changes:

* Keep the nav/steps sticky
* If there is overflow content in either the nav or the body, those sections scroll independently. 
* **Keep the footer/actions sticky to the bottom of the wizard body** - this is the part I'm unsure about. In the screenshots above, the footer/actions are not sticky, so I wasn't sure if you preferred that or would rather they be sticky.

I've put together a demo that shows those proposed changes - https://codepen.io/mcoker/pen/XWjvVBq

Is that how you would expect the in-page layout to behave, or do you prefer scrolling to the actions at the bottom of the wizard body content if the content is taller than the wizard?

**Comment by matthewcarleton** [comment]
Hey @mcoker this looks great.
I'd be in favour of the sticky action footer (maybe it should be optional though?) We have a use case on the OpenShift side where having it sticky is very useful but I'm not sure if it's always the case. I know there is an argument for forcing users down the page so they can see everything available to them before they proceed.

**Comment by mcoker** [comment]
@matthewcarleton thanks! I'll see what I can do! Also, not sure if this makes a difference, but I noticed there was no shadow on the wizard actions. In other layouts where we have layouts like this, the sticky section has a shadow where it overlaps a section underneath. I added one to [the codepen](https://codepen.io/mcoker/pen/XWjvVBq). Do you think that helps, and would help queue to the user there is more info to scroll to?

**Comment by matthewcarleton** [comment]
@mcoker yup! I think the shadow helps a lot and is a good idea. I still think the modifier is the right way to go if we can do it but the shadow is a nice addition to it for sure.

**Comment by gdoyle1** [comment]
Nice @mcoker that definitely would help the use case mentioned above! We have a few areas in OCM where a sticky action footer would be useful too! And yes adding the shadow is a huge help - thank you!!!
