### ISSUE TITLE
Splitter demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#891]
Create mockups for a demo to show general usage of the drawer component that includes both a horizontal as vertical drawer with a splitter bar and representative content.

**Comment by maryshak1996** [comment]
@mcarrano I put together these three examples of the splitter in context -- I'd love to get your thoughts :) 
https://www.sketch.com/s/3fe9a72b-a9c3-4d12-a02d-c843c41128d4

**Comment by mcarrano** [comment]
These look great @maryshak1996 . I definitely agree that the Primary detail and card view with a horizontal drawer would make great demos. Less sure about whether we would ever add a splitter to the Notification drawer (although we could). What are your thoughts @mceledonia ? Is that something you could see us supporting?

@mcoker @nicolethoen This is directly related to our conversion from the other day. Welcome any feedback you have, also.

**Comment by mcarrano** [comment]
Opened a new core issue to build out these layouts placing a Splitter in a drawer. https://github.com/patternfly/patternfly/issues/3610

**Comment by mceledonia** [comment]
@maryshak1996 @mcarrano These look good to me!

**Comment by mcarrano** [comment]
Thanks @mceledonia . I will move this over for implementation then.
