### ISSUE TITLE
NotificationBadge: new unread state looks too much like browser focus state

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-design#895]
This is a request to change the design for the Notification Badge when in an unread state. See pics below. The unread state and the browser focus state are too common. When added to openshift, comments were added to the ui forum that the notification badge had a bug and was stuck in the focus state.

Browser focus state: 
![Screen Shot 2020-07-16 at 3 17 37 PM](https://user-images.githubusercontent.com/35978579/87719208-02ce3b00-c781-11ea-9629-c14ff8885284.png)

New design read/unread state:
![badge-icon](https://user-images.githubusercontent.com/35978579/87719297-20030980-c781-11ea-850d-413b6d265863.gif)

**Comment by mceledonia** [comment]
Let's go with a blue fill here rather than the border. And no ( ! ) icon in the bell, only the attention state should have that. 

<img width="567" alt="image" src="https://user-images.githubusercontent.com/30935938/87821263-8b121600-c83d-11ea-87e4-52a4fcfb8006.png">

**Comment by mcarrano** [comment]
@mcoker @evwilkin We weren't sure what the process should be for adding the bell with "!" It's not part of our current icon set, but hopefully can be included in this update.

**Comment by evwilkin** [comment]
@mceledonia do we have a design update here?  I think we're trying to push this through design, core & react for this current milestone.  It looks like your note mentions no ! in the bell and Matt's asks about adding an icon with the ! in the bell, hoping you can clarify and we can move forward here.
cc @mcoker

**Comment by evwilkin** [comment]
Please disregard above - I see now the unread state won't have the ! in the icon, and the attention state will have the ! in the icon. I will look into how to get this new icon added.

**Comment by evwilkin** [comment]
Core issue: https://github.com/patternfly/patternfly/issues/3308

**Comment by mceledonia** [comment]
I want to leave this open @mcarrano, OpenShift recently has implemented this and decided to remove the unread state due to their seemingly unique situation of almost always having some form of unread alerts. Given that scenario, the unread indicator isn't very useful, but the blue fill is also a bit distracting when it is now less of an indicator and more of an always-present state. I think OpenShift went with the right solution, but I am interested to see if other products have similar alerting scenarios or if the current design works well for them.

**Comment by mcarrano** [comment]
OK. I am pulling back to design. We can discuss further.

**Comment by mcarrano** [comment]
@jcaianirh @mceledonia I think we solved this with the latest notification badge design. Please confirm. If yes, I will close this.

**Comment by jcaianirh** [comment]
@mcarrano confirm!

**Comment by mcarrano** [comment]
Closing then...
