### ISSUE TITLE
enhancement(ContextSelector): Look into rendering content before searchbar

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-design#897]
## Requesting new features, enhancements, or design changes to PatternFly 
Explore rendering content before the searchbar, per contribution here: https://github.com/patternfly/patternfly-react/pull/4517

**Comment by gdoyle1** [comment]
@mcarrano @mceledonia Here's what I came up with for this! Let me know what you think.
![Context selector](https://user-images.githubusercontent.com/30870144/89792360-71898480-daf2-11ea-952e-d05aa13c4f9f.png)

**Comment by mcarrano** [comment]
@gdoyle1 I think this works. So in this case, is All projects just another menu item that's pinned to the top of the menu? Does it get filtered like other items in the list?

**Comment by gdoyle1** [comment]
Yes, that was what I was thinking! @mcarrano

**Comment by MariaAga** [comment]
@gdoyle1 Hi! the 'before searchbar' is needed for us to also add a 'mange projects' button with the 'all projects' button, how will this work with this design?

**Comment by gdoyle1** [comment]
@MariaAga does the "manage projects" item act as an action? Right now, all these menu items will be changing the context of the page so that it shows the data related to all projects, my project, openshift cluster, etc.

**Comment by MariaAga** [comment]
The "manage projects" item acts as a link to a "manage projects" page

**Comment by mcarrano** [comment]
@MariaAga @gdoyle1 If we want to add actions like this to a menu, I wonder if the better way to do this would be to add a footer to the menu. I have been working with @doruskova on some designs here to address a similar use case: https://github.com/patternfly/patternfly-design/issues/867 I'd like to have a consistent approach that can work across a variety of types of menus. Thoughts?

**Comment by gdoyle1** [comment]
Thanks for bringing that up @mcarrano ! I took a stab at creating something that is more consistent with that...
<img width="614" alt="Screen Shot 2020-08-13 at 1 55 13 PM" src="https://user-images.githubusercontent.com/30870144/90169525-b0c30a00-dd6c-11ea-8407-45b2720fe956.png">

**Comment by mcarrano** [comment]
This looks good @gdoyle1 . Do you have a preference between these? I feel like the link style button is more appropriate here, but don't feel strongly about that. Would also be great to get your thoughts @mceledonia .

**Comment by gdoyle1** [comment]
@mcarrano here's the most recent mock that we discussed!
<img width="645" alt="Screen Shot 2020-08-26 at 4 08 41 PM" src="https://user-images.githubusercontent.com/30870144/91351641-9e0df380-e7b6-11ea-83fe-734a741e94c2.png">

Here is the marvel as well: https://marvelapp.com/prototype/7ahigh3
