### ISSUE TITLE
Create "Community" page for PF website

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-design#898]
We want to add a "Community" page to patternfly.org which would link to PatternFly Elements as a community project built around PatternFly, and it could also house any other similar projects, accessibility info, events/updates from the PF team, and anything similar outside of our normal PF agenda that we need a place to communicate.

**Comment by mcarrano** [comment]
@abigaeljamie can you attach your proposed content here and I will move this over to Dev for next steps.

**Comment by abigaeljamie** [comment]
Sure! Here is the link to the content: https://docs.google.com/document/d/13RD3FmaABC99Nz_jHyg4CZsiXvFoIzuh85-ZhfCHeJY/edit?usp=sharing Thanks, @mcarrano !

**Comment by mcarrano** [comment]
Thanks for your work on this @abigaeljamie . I have opened a new issue to implement the page in the org repo here: https://github.com/patternfly/patternfly-org/issues/2109 Will close this one out.
