### ISSUE TITLE
missing open formats (such as SVG) for designs

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-design#900]
PatternFly designs are nowhere to be found on the website.

There's reference to Sketch, but that's macOS only.

Open source communities need to be able to access all content, including designs, to be truly open. This means having everything in formats that people can access from a variety of platforms and tooling. In the case of design, publishing SVGs (or even PDFs) would be essential. (Currently, there aren't even PNG exports which would be the absolute bare minimum.)

Designers using Inkscape on Linux or Illustrator on Windows (or even Illustrator on a Mac) currently cannot access any of the design documentation of PatternFly, and therefore, cannot participate in the design process.

Additionally, it's critical to have designs available to everyone on projects, including not just designers, but also programmers implementing the software. If they're running Linux or Windows, it's not even possible to check to make sure the implementation looks correct. (Even if they have a Mac, they might not have access to Sketch.)

As it stands right now, PatternFly design is a closed silo with an admission fee of buying a Mac and Sketch to even start to hope to participate. Please do the bare minimum of exporting the files to an open format so everyone can work with the project.

**Comment by mairin** [comment]
^ All of this. I'm re-implementing everything from scratch in Inkscape and not even confident that I'm getting the scaling and fonts correct, because there's no reliably-rendering version like PDF or PNG output to use as a guide. The interns I have onboarded onto the project I work on that uses PatternFly have also suffered from a poor experience as they use the FLOSS tools as well. The system needs to be accessible from FLOSS tools to enable upstream community participation, which is critical for those of us working in the upstream design trenches daily.

**Comment by garrett** [comment]
Agreed! :100: 

Andreas and I have also spent so many hours making and remaking design assets based on pixel-peeping the website. And then the the widgets change every PF release in subtle ways, so it's back to the "hamster wheel" yet again. And this is just trying to play catch-up with the public-facing assets.

We cannot even participate in design suggestions or get previews of what's being discussed or talked about for future versions of PatternFly, or communicate how something might work (or not) in our projects. It's usually surprise with everything "tossed over the wall".

Sure, the community meetings on BlueJeans help (quit a bit actually), but it's still a sub-par, badly-video-encoded glimpse at upcoming changes around the time they land in the repo as code. It's not the same thing. Plus, the BlueJeans calls only touch the highlights that people remember to talk about; a lot of subtle things are left out.

We're not asking you to abandon Sketch or whatever other proprietary tooling you might be comfortable with. We're simply asking that you don't force us to abandon our tools (and buy hardware for thousands, license Sketch on top, and force us to relearn how to do _everything_ — even at an OS level).

We want to more actively participate; tear down the artificial walls stopping us from doing so.

Simply: Meet us in the middle with open formats that all tools can read and write.

**Comment by andreasn** [comment]
Looking at the [official Patternfly documentation](https://www.patternfly.org/v4/get-started/designers), it does seem I would need to expense a second laptop from work in order to consume Patternfly, since I don't own a Mac.

After some brief web searching, it seems Sketch is capable of exporting SVGs, so maybe that could be a route?

For reference, here is the widget template we use for Cockpit, but that's all hand-traced by me and @garrett and falls out of date quickly and easily.
https://github.com/cockpit-project/cockpit-design/blob/master/widget-template.svg

**Comment by garrett** [comment]
There's a npm/yarn installable Sketch-to-SVG command line tool that convinces Sketch to export everything as SVG. (It can do this by default, but I'm not sure how the Sketch document is set up.) Perhaps this would help, if the Sketch document is not set up properly in Sketch? https://github.com/eBay/SketchSVG (It's macOS only, of course, as it relies on Sketch itself.)

We cannot really do anything from our side. Opening Sketch files in third party software just to act as a go-between to convert them to SVG (or PDF) will almost certainly result in unusable files. This is an issue case with almost all intermediary conversions — especially those which do not have open document formats.

We need someone with a Mac to open Sketch on macOS to export to SVG/PDF.

**Comment by notklaatu** [comment]
Adding myself here so I can track progress. 

The proprietary dependencies of Patternfly make it impractical (or impossible?) for someone running only open source to contribute or fully utilize what Patternfly offers.

**Comment by garrett** [comment]
I just got off a call with several people on the PatternFly team and they said they will figure out the best way to export SVG and PNG files so that we can use them in Inkscape (and other tools). 

Meanwhile, a first pass might be a PDF export, as that is most likely easier to export than SVG. (It could be something like "print" to a PDF, for example.) It probably won't be ideal, but it should be a start.

Eventually, once we figure out the best way to get the designs exported (as there are several settings and ways to export to SVG in Sketch), then we can hopefully get it automated. The idea we're working toward is to have a git repo (for instance) that's updated with "daily" snapshots (when things change).

Meanwhile, I asked them to post experiments of exporting to SVG, PDF, and PNG here on this issue, so we can see how well things translate from Sketch to Inkscape.

**Comment by garrett** [comment]
_Additionally_, not open format related, but still design related:

The PatternFly team will post information on the website, with links, to help us all get more insight to what's happening on the design side of things. This will probably be in the form of links to a ZenHub board (which requires a GitHub account, as it has GitHub integration) and a MarvelApp link (which should allow anyone — even without an account, if I understand correctly) to preview and comment on designs.

Also, they'll make a point to dedicate a part of the PF community calls to talk about work-in-progress designs.

**Comment by mcarrano** [comment]
Based on discussion with @garrett and @andresasn we will investigate an approach for exporting assets from Sketch to SVG. We agreed that an ideal solution would be automated and would result in a bulk export of assets when we post a new version of the Sketch kit. These assets could then be posted to an accessible location TBD.

In addition, design requests and work in progress can always be viewed via the [PatternFly Design workspace in ZenHub](https://app.zenhub.com/workspaces/pf4-design-workspace-5b2142ff9499cb7cdaf1e632/board?repos=61041252&showPRs=false&showClosed=false). I have opened https://github.com/patternfly/patternfly-org/issues/2018 to add this link to the PatternFly website to make it easier to follow and comment on ongoing design work. In most cases, designs are shared in [Marvel](https://marvelapp.com/) which allows anyone with a link to view and comment.

cc @gdoyle1 @evwilkin @dgutride

**Comment by garrett** [comment]
@mcarrano: Thanks again for talking with us about this and helping us find a solution! We appreciate it so much!

**Comment by garrett** [comment]
Note to all (especially stale-bots :wink:): Please keep this issue open until we have the exports solved and automated. :grin:

**Comment by mcarrano** [comment]
@garrett I did a quick experiment to export from Sketch to PDF. Here is the result of exporting our template file. https://drive.google.com/file/d/1SCavFPundU_SthBwswsss_By64UthdSj/view?usp=sharing I'm sharing via Google Drive as the resulting file is too large to upload here. If this is useful long term we can find a location on GitHub to push it. The same information is available here on Sketch Cloud: https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89 I'm not sure if this requires a Sketch account to just view, but I sometimes use this to just look at things without the need for the actual asset files. It's organized by pages and artboards so a bit easier to consume than the PDF.

The template files presents a variety of higher level patterns and relies on the PatternFly symbol library where lower-level components live. This is harder to export in bulk because everything is stored in symbols.

Hope this helps in the short term, and stated above, we'll be researching a more robust solution.

**Comment by garrett** [comment]
@mcarrano Thanks for the quick conversions!

I've downloaded the zip file from the Sketch link and also converted the PDF to SVG with Inkscape (with a little scripting). Then I took all of that and put it in a git repo @ https://github.com/garrett/patternfly-design-exports — just intended to be a WIP place to put stuff for the time being.

(We'll do all of this more officially soon.)

The Sketch → PDF → Inkscape SVG works reasonably well.

In most places, the text is actually editable, but it usually outputs each line as a separate text object. Also, to properly edit the text in Inkscape, you need to select it and remove kerns (from the text menu). There are a few SVGs where the text is (oddly) symbols and uneditable.

As I guessed, the blurred shadows are rendered as images, so they aren't really editable in Inkscape (aside from the usual things one can do to a raster image). It's not a huge deal, as there aren't many shadows (anymore).

Also, I as I scripted Inkscape to export each page separately, there winds up being no context as to which pages are what. So we have to look through everything to find what we want. Not ideal. We could work around this if need be. Hopefully direct SVG exports from Sketch would be named more appropriately (if the PNG is any indication).

But, in general, it looks like most things came through just fine otherwise. This is a great first step. I'm looking forward to Sketch SVG exports which should address some of the issues with PDF export.

**Comment by garrett** [comment]
@mcarrano: Oh, right — I set the license to MIT on the repo. Is that correct? It's what PatternFly is licensed under. Is that what the designs should be licensed under as well?

**Comment by mcarrano** [comment]
@garrett I have asked @gdoyle1 to take the lead on this from the PatternFly side, and she can work with you figuring out the details.

As for the repo, @evwilkin or @dgutride can you answer the question about licensing? We do already have a repo set up for the Sketch design kit here, https://github.com/patternfly/patternfly-design-kit. We can decide later whether to just use that as a repository or if a separate repo makes sense.

**Comment by dgutride** [comment]
@mcarrano  - everything in PatternFly should be licensed under MIT

**Comment by gdoyle1** [comment]
@garrett Hey Garrett! When you get a chance, do you mind trying these accordion symbol svgs out? I have exported them with the padding which I was hoping would give you more of an indication of the exact spacing.
[Accordion.zip](https://github.com/patternfly/patternfly-design/files/5057532/Accordion.zip)

I noticed a couple things where these svg exports differ from Sketch:

1. The text styles do not maintain their line heights
2. Text boxes with multiple lines (like content.svg) exports as multiple text boxes

**Comment by garrett** [comment]
@gdoyle1: Thanks for working on this!

---

## Overall

I think it looks good overall!

## content.svg exports

When exporting the SVG at 96 DPI (default), the resolution is 106×145. Here's the export @ 1:1:
![Content](https://user-images.githubusercontent.com/10246/89986697-35cef600-dc7d-11ea-9521-51d6b5f007b8.png)

Here's a 2x:
![Content@2x](https://user-images.githubusercontent.com/10246/89986890-77f83780-dc7d-11ea-9be1-2cc00327887b.png)

## Text quirks

I see what you mean with regard to the text boxes with multiple lines using [`<tspan>` elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan) for positioning. I think it's probably not really a problem; looking at how Inkscape handles text shows that it's using tspans in the results too. Here's the snippet in question:
```svg
        <text id="✏️-Content" font-family="RedHatText-Regular, Red Hat Text" font-size="14" font-weight="normal" line-spacing="21" fill="#6A6E73">
            <tspan x="16" y="22">ctrl+enter </tspan>
            <tspan x="16" y="43">to add lines </tspan>
            <tspan x="16" y="64">in override.</tspan>
            <tspan x="16" y="85">Default </tspan>
            <tspan x="16" y="106">height is </tspan>
            <tspan x="16" y="127">“fixed”</tspan>
        </text>
```

I think the problem we're running into is the "line-spacing". Inkscape uses `line-height` and has units (otherwise it has multiples of the lines, and we don't want 21 lines in-between each line). This is [what the SVG spec does](https://www.w3.org/TR/SVG2/text.html#LineHeightProperty), and it's similar to CSS for the web. 

It seems Sketch is exporting assuming pixels and is using a non-standard `line-spacing` instead. I've found if I change line-spacing="21" to line-height="21px", then it shows up as expected in the editing part of Inkscape and copy/pasting of the text style works as well, and with the same text, it looks exactly the same as the Sketch export.

Additionally, the font family has "RedHatText-Regular, " in front of "Red Hat Text". Inkscape doesn't like this in the font selection UI, but it does seem to figure out the correct font with its font matching for the actual document. Fixing this is as simple as removing "RedHatText-Regular, " — this lets Inkscape have the correct font in the font selector.

While the settings are off, Inkscape does show the SVG correctly in the document and allows editing the text by default.

I think, at least so far, we could make a simple cleanup script to normalize the font and adjust a few values (just line-spacing to line-height and adding px as the unit so far). The question I have is: how well would this then open back up in Sketch?

## Re-import test

Here's the manually-modified SVG where I changed those two things, as a script would: 
**[Content-modified.zip](https://github.com/patternfly/patternfly-design/files/5061507/Content-modified.zip)**.

It has a modified file, with just the manual changes and a modified-Inkscape file that was the modified file opened and then saved from Inkscape (with no changes). 

Could you try to see what Sketch does when importing both of these? Do both look and work as you would expect?


## Additional exports (toggles)

Also, these are the exports of toggles (at 96 DPI, which should be 1:1):

Default
![Default](https://user-images.githubusercontent.com/10246/89987036-abd35d00-dc7d-11ea-9b93-a8bc102e54a6.png)

Expanded
![Expanded](https://user-images.githubusercontent.com/10246/89987049-ae35b700-dc7d-11ea-91ed-83f5e5dc40a4.png)

Focus
![Focus](https://user-images.githubusercontent.com/10246/89987062-b130a780-dc7d-11ea-9914-665c23197677.png)

Hover
![Hover](https://user-images.githubusercontent.com/10246/89987072-b42b9800-dc7d-11ea-89f1-b052020cdc44.png)

**Comment by gdoyle1** [comment]
@garrett Thank you so much for such a detailed response! I wanted to update you telling you I'm looking into this and plugins that we could use so I don't have to manually go through our 100+ symbols and export them as SVGs (hence why it's taking a little longer to find a solution for this). In summary, I seriously appreciate your detailed response and I am working on a solution!!!

**Comment by garrett** [comment]
@gdoyle1: Thanks for the update!

I agree :100: — having it automated is definitely the right approach. Thanks for working on this!

**Comment by gdoyle1** [comment]
@garrett Tried exporting all symbols as svgs here! https://github.com/patternfly/patternfly-design-kit/blob/master/PatternFlyLibrarySVGs.zip 

Was wondering if you had feedback on this proposal for the process of updating that .zip file in the future:
1. Continue to overwrite that same file, keeping track of dates that the file was uploaded through commit messages
OR
2. Create a new folder for the PatternFly symbol SVGs in the repo. Every time we upload a new version the zip, attach a date to that file so they do not overwrite. (e.g. PatternFlyLibrarySVGs10-16-2020)

**Comment by andreasn** [comment]
For me I would have a slight preference of git commit dates, since it's kind of built in and less noisy. I don't think there is any strong reason for keeping older versions of the library.

**Comment by garrett** [comment]
Would it be possible to commit the SVGs directly to a git repo instead of a ZIP file? A zip file has to be decompressed, so it's not immediately useful, and git does not handle zips all that well, whereas SVGs are handled very well by git, as they're text-based.

If a file doesn't change between snapshots, git would detect that, so it would also help to show what really changed between releases. Additionally, in GitHub, we could visually spot the differences between versions as well, with the side-by-side comparison, onion skin, and swiping modes.

**Comment by gdoyle1** [comment]
@andreasn @garrett added here: https://github.com/patternfly/patternfly-design-kit/tree/master/Symbol-SVGs. Let me know if that works!!

**Comment by mairin** [comment]
@garrett @andreasn do you think there's any shot at scripting a conversion of these to inkscape symbols?

**Comment by gdoyle1** [comment]
@mairin I'm meeting with a PF developer tomorrow and pass this idea by him! Will keep you updated.

**Comment by garrett** [comment]
@gdoyle1 Thanks for adding the SVGs directly! 

However, they shouldn't be in a date-based directory. If the same files are in different directories, git cannot version control them, and we wouldn't be able to see the changes.

Please move the directories one level higher, so that instead of:
https://github.com/patternfly/patternfly-design-kit/blob/master/Symbol-SVGs/2020-10-17/Accordion/Content.svg
it's:
https://github.com/patternfly/patternfly-design-kit/blob/master/Symbol-SVGs/Accordion/Content.svg

Any time there are updates, you could remove the Symbol-SVGs directory (or the contents under it), recreate it, and check it into git. Git will then just update the parts that changed. You could just add the changes on top too, but then if any file is ever removed, it won't be in git (unless you manually remove it).

**Comment by garrett** [comment]
> @garrett @andreasn do you think there's any shot at scripting a conversion of these to inkscape symbols? (and by shot at i mean, is it possible?)

It's probably possible to automate the conversion of the SVGs to symbols. However, I haven't found Inkscape symbols to be useful _at all_, as they're not editable and they also don't preserve stroke width. (Unless I'm missing something or they've changed in the past few years since I've looked at them.) I would be more than happy to be wrong about this though! :grin:

**Comment by gdoyle1** [comment]
> @gdoyle1 Thanks for adding the SVGs directly!
> 
> However, they shouldn't be in a date-based directory. If the same files are in different directories, git cannot version control them, and we wouldn't be able to see the changes.
> 
> Please move the directories one level higher, so that instead of:
> https://github.com/patternfly/patternfly-design-kit/blob/master/Symbol-SVGs/2020-10-17/Accordion/Content.svg
> it's:
> https://github.com/patternfly/patternfly-design-kit/blob/master/Symbol-SVGs/Accordion/Content.svg
> 
> Any time there are updates, you could remove the Symbol-SVGs directory (or the contents under it), recreate it, and check it into git. Git will then just update the parts that changed. You could just add the changes on top too, but then if any file is ever removed, it won't be in git (unless you manually remove it).

Will do!

**Comment by mairin** [comment]
@garrett I find them super handy if not a complete solution. If I need to change text I unlink the clone easy peasy.

**Comment by garrett** [comment]
I've been looking into this today and it creates a mammoth-sized file.

Meanwhile, I split out the icons as a stand-alone symbol set. Here's a zip of the icons (as GitHub doesn't allow uploading SVGs directly):

**[🠟 pficon-symbols.svg.zip](https://github.com/patternfly/patternfly-design/files/5256029/pficon-symbols.svg.zip)**

I've removed the duplicates and also did not include the brand logos (on purpose). It should otherwise be complete.

**Comment by gdoyle1** [comment]
@garrett Is that how you'd prefer this to be uploaded to GitHub? When I pulled it into sketch everything was stacked over one another and pretty impossible to sort through. We can easily just remove duplicates and brand logos if that's necessary from the upload I made!

**Comment by garrett** [comment]
@gdoyle1: This is just a test and only contains a subset of the icons. And the icons aren't even the right size, sadly. I'm new to this whole symbol thing and have been trying to figure it out all day. I know the icons are at least something @andreasn and I could also benefit from immediately, if we could get them working.

@mairin: I have a forked repo with some changes that make gulp work again and support subdirectories @ https://github.com/garrett/inkscape-open-symbols — that's how I created the SVGs with symbols.

I'm not sure how best to handle the widgets. Using the above-referenced repo makes a several MB SVG that causes Inkscape to crash when I include _all_ the SVGs. (I think I'm doing something wrong.) Hopefully @mairin can make sense of this.

**Comment by mcarrano** [comment]
Is there anything more to do here from a PatternFly perspective? If not I will close this out.

**Comment by gdoyle1** [comment]
@mcarrano I'm not sure if I can do anything more with the SVGs especially since we want to be inclusive to all design tools. So transferring them into symbols for specific programs I think should be something that the users do? But I'm open to other thoughts/feedback!

**Comment by garrett** [comment]
> Is there anything more to do here from a PatternFly perspective?

1. Keep the SVG exports up to date. :wink: 
2. Mention the SVG files on https://www.patternfly.org/v4/get-started/design and that they work with Inkscape, Illustrator, etc.

But as far as the symbols: I agree with @gdoyle1 that it's out of scope for this particular issue. If someone figures out a good way how to convert the SVGs into symbols, then I'd ask that it would be included _somehow_. 

I did take a look at converting the SVGs to symbols and I couldn't figure it out (for _all_ of the SVGs — I only got the icons working)... but I don't use symbols in Inkscape (at least yet).

**Comment by mcarrano** [comment]
Thanks @garrett . Yes, we do plan to update regularly, and add a mention on the Get Started/Design page as you suggest. There is an open website issue here: https://github.com/patternfly/patternfly-org/issues/2152

I am going to close this then. Thanks for all the work on this @gdoyle1 . I am glad we were able to find a workable solution!
