### ISSUE TITLE
Consider improvements to disabled styling - not obvious enough?

### ISSUE THREAD

**Issue by ncameronbritt** [patternfly/patternfly-design#901]
Is it possible to use the not allowed cursor style when things like dropdowns or buttons are disabled? I have gotten a complaint that the disabled dropdown style still appears clickable. For this user, it seems that the visual styling alone does not adequately communicate that the item is disabled.

**Comment by mcarrano** [comment]
See additional comment on the PF forum here: https://forum.patternfly.org/t/disabled-buttons-styles/391

**Comment by mcarrano** [comment]
Need to evaluate what updates we might make and whether those would constitute a breaking change. Adding to the design backlog.

**Comment by mcarrano** [comment]
Going to close this for now, but we should consider if this is still a problem after we roll out the new visual theme,
