### ISSUE TITLE
Consider a pattern for smaller use cases for alerts that aren't covered by the inline variation of the component.

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-design#902]
In the console we see scenarios like this (look at OpenShift OAuth enabled toggle)
![image](https://user-images.githubusercontent.com/287880/89072646-516a0080-d34f-11ea-870b-a8702a978e9c.png)
Interested what others think about PF providing this or if there is similar needs in other products outside of OpenShift.

**Comment by mcarrano** [comment]
@matthewcarleton we have been looking at this sort of thing. See the designs attached to this issue: https://github.com/patternfly/patternfly-design/issues/862  They were primarily targeted at placing an inline alert in the context of a form, but I think could similarly work for a definition list like this.

Thoughts @mmenestr ?

**Comment by mmenestr** [comment]
@matthewcarleton just to make sure I understand the use case, does a user get the warning after making a toggle change, to tell them that they have to save this change somewhere for it to stick?

**Comment by itsptk** [comment]
The use case shown here is when a user flips that toggle in the UI, they need to confirm the action to then write it to the backend (that they did intend to flip it.) There is no save/cancel buttons at the bottom of the page, all editing is happening inline. I don't know the exact history but I guess it was thought that [these toggles](https://github.com/openshift/console/blob/c07050bccf2e2c1d94001d138a063f6d4206043b/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#booleanswitch) were worth confirming the user's intent.

**Comment by mmenestr** [comment]
@itsptk Oh so they would confirm the change by clicking "Confirm change"? If that's the case I feel like this is a use case all together, but the styling is very similar to what I designed for in-line error messages for non text form inputs: 

![image](https://user-images.githubusercontent.com/51165119/89324971-22f16b80-d656-11ea-8997-107820f22f75.png)

**Comment by mcarrano** [comment]
@matthewcarleton @itsptk now I understand better what the ask is. Sounds like this is more than just wanting a static alert and more like an inline edit use case. We do have support for that here: https://www.patternfly.org/v4/documentation/core/components/inlineedit It's a bit different from what you've designed. We do not have a React demo of this at the moment, but basically any element on the page could be wrapped in an editable container that would allow the ability to confirm changes before committing. 

Would this satisfy your use case here? @mattnolting did the PatternFly implementation and could elaborate more on how to use in your product.

**Comment by matthewcarleton** [comment]
@itsptk I wonder after looking at this if the pattern should be to edit the setting in a modal. I don't know of any other settings in the details view that do this type of inline edit. WDYT? I know there is a larger effort around future enhancements for inline edit of the details view that could maybe tackle this.

**Comment by itsptk** [comment]
Yeah I agree, this definitely seems to be an outlier in the OCP console. I was taking a look at the inline edit case and do think that could probably be used for this particular editing/confirm case. Agreed that this could be included in the larger inline conversion effort.

Of note is that this error message can also be shown if the change is confirmed and the change fails to write to the backend. Perhaps this example captures the initial ask of a smaller alert that could appear in a form?
![image](https://user-images.githubusercontent.com/54860125/89662201-bd91ba80-d8a1-11ea-9cea-6a1ab9eace7f.png)

**Comment by mcarrano** [comment]
Given all of this. Is there a reason to keep this issue open @matthewcarleton ? Is there still a PatternFly ask here?

**Comment by matthewcarleton** [comment]
@mcarrano I think what @mmenestr has already done for forms will cover requirements. Given that we've determined this is not the recommended approach for the details page I'm ok with closing this. Thanks everyone for the lively chat!
