### ISSUE TITLE
Consider (optionally) not indenting Accordion headings to align with other form controls

### ISSUE THREAD

**Issue by itsptk** [patternfly/patternfly-design#904]
The PF Accordion component style adds left padding to the Accordion toggle, which causes it not to align with the rest of the normal form field headings. Could the Accordion be changed to remove this left padding, or perhaps have an option to not include it? The OpenShift console is already doing this today with custom code.

Existing Accordion behavior (with gap to left of heading):
![image](https://user-images.githubusercontent.com/54860125/89664060-938dc780-d8a4-11ea-9aaf-d898d034f5cb.png)

Custom adjusted PF accordion being used in OCP console (Note how Node Spec and Index Management align with Name and Labels):
![image](https://user-images.githubusercontent.com/54860125/89664271-e6677f00-d8a4-11ea-8a72-e2ad8331f8e8.png)

This request was generated from: https://github.com/openshift/openshift-origin-design/pull/427#discussion_r458432807

cc @matthewcarleton @TheRealJon

**Comment by mcarrano** [comment]
@itsptk did you consider using the Expandable section for this rather than the Accordion? See https://www.patternfly.org/v4/documentation/react/components/expandablesection  Discussed with @mceledonia and we agreed this might be a better approach.

**Comment by TheRealJon** [comment]
@mcarrano I think we considered this on initial implementation, but the Expandable section component doesn't represent hierarchy as well as Accordion. The child fields are not indented and there is no visual representation of grouping like the blue border you get with accordions. I think the decision probably came down to the fact that accordions more closely matched our use case and required less custom styling to get the visual hierarchy we needed. There might actually be a case for an upstream PF Fieldset component that can be used with the Form component. This would make it possible to make semantically accurate collapsible fieldsets which would be great for accessibility purposes.

**Comment by mcarrano** [comment]
Thanks for the feedback @TheRealJon . When you say "fieldset" component, how does that relate to what's being requested in this issue here: https://github.com/patternfly/patternfly-design/issues/889? It may be that we should allow form sections to be collapsible. 

I understand what you are saying about the Accordion and the Expandable sections. The problem is that the Accordion was not really designed for this type of layout, either. But perhaps we can figure out the right solution here.

**Comment by TheRealJon** [comment]
I didn't know about #889  but it does seem pretty closely related. Definitely seems like that issue is starting to get some attention again, so I can comment on that and add in these other considerations for the design.

**Comment by TheRealJon** [comment]
IMO, I think the best solution would be for the component that comes out of #889 to meet our use cases for the Operand creation form so that we can move away from using the accordion component. I believe that would make this issue obsolete.

**Comment by itsptk** [comment]
Agreed, closing and watching component that comes out of #889
