### ISSUE TITLE
Collapsible multi-level breadcrumbs

### ISSUE THREAD

**Issue by aprilma419** [patternfly/patternfly-design#909]
## Requesting a collapsible breadcrumb for multiple levels
In the Keycloak Groups feature, breadcrumbs on a page header can have more than 5 levels(5-10 levels). Currently, we're using "**...**" to collapse the middle levels of breadcrumbs for Keycloak Groups feature on a page header which Pattrnfly doesn't have right now, and using a simple dropdown to indicate the users the collapsed levels.

<img width="711" alt="Screen Shot 2020-08-12 at 11 33 01 AM" src="https://user-images.githubusercontent.com/44431015/89972122-96672e80-dc8f-11ea-80b9-c5757779dd08.png">

Besides, there's also a potential usage for collapsible breadcrumbs. In other App-service apps, the feedback I received is we could show the history path of visited pages across the console. Like my rough proposal below, I also used a "**...**" to indicate users to click it to see the history path in a dropdown. 

<img width="657" alt="Screen Shot 2020-08-12 at 11 31 23 AM" src="https://user-images.githubusercontent.com/44431015/89972016-5bfd9180-dc8f-11ea-9c3c-c161921be0f1.png">

**Comment by mcarrano** [comment]
@aprilma419 This issue will be solved as part of the solution for menu breadcrumbs here: https://github.com/patternfly/patternfly/issues/3491 It is already implemented in core and should be available as a React component in a coming release. Will close this design issue.
