### ISSUE TITLE
Create "Tour" Demos

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design#914]
Want to create a demo page for tours, that we could eventually add a design guidelines tab for.
Would need to create mocks, or can pull from current implementation of open shift or DMN tours for example.

There are three types of tours we could have demos for:
1. Guided tours
2. Task walkthroughs
3. Interactive tutorials 

Here's a deck with more information on the tours: https://docs.google.com/presentation/d/1-znYB7qFE6-BEvFZ9bcPJLDy9EjEF0kJESCimyBJa6k/edit#slide=id.g8ac6e736b8_0_785

@mcarrano

**Comment by lwrigh** [comment]
For reference here is the Miro board guided tour inventory some of the OpenShift team has been working on https://miro.com/app/board/o9J_lJBwKPg=/. It features some of the current guided tour designs we have been considering. 

After talking as a group about this, we think it makes sense to find a common layout for the guided tour. All of the designs overlap on things like number of steps, titles, next/back buttons, etc. The content seems pretty unique to each example but  it would be great if we could all use the same layout.

It would be great to contribute this back to PatternFly!

**Comment by mcarrano** [comment]
Closing as this currently feels beyond the PatternFly scope.
