### ISSUE TITLE
Consider demos needed for Toolbar and Filters.

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#915]
Currently we have a set of HTML Toolbar demos here: https://www.patternfly.org/v4/documentation/core/demos/toolbar These demonstrate the layout of a Toolbar with various filter configurations. Want a set of React demos that address Toolbar and Filters as separate entities. Goals:

* Show how different toolbar items and groups can be used.
* Demonstrate filter usage for filtering data in tables using various common filter types.
* Translate into full page React demos.

**Comment by mmenestr** [comment]
Here is a marvel project I created with filter demo proposals: https://marvelapp.com/prototype/7i0dj2d
Let me know what you think!
Tried to have one demo per filter type mention in the design guidelines.

**Comment by mcarrano** [comment]
Thanks @mmenestr This should be all set!
