### ISSUE TITLE
Create graphics for new Community page on website.

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#920]
Visual design support is needed to create graphics for a new Community page on the PatternFly website. A preliminary version of the page can be seen here: https://patternfly-org-pr-2167-v4.surge.sh/v4/community

cc @abigaeljamie @evwilkin

**Comment by abigaeljamie** [comment]
I submitted this as a request via the Visual Design team's request form a couple weeks ago. I put the due date as 2 weeks from when I submitted (10/14). @mceledonia will be taking on this work 👍

**Comment by mcarrano** [comment]
Thanks for working on this @mceledonia . I'm going to close this design issue as we should be all set here.
