### ISSUE TITLE
[Icon Request] Request for "New" and "Not Started" Icons

### ISSUE THREAD

**Issue by bgliwa01** [patternfly/patternfly-design#921]
Use case and requirements of icon 
- The new icon being used in OpenShift is very similar to the pf icon for pending. OpenShift wants to make all uses of the pending icon in the console consistent.
- The not started icon needs to be created for the pipeline and build decorator in topology
                     As a developer, if i ADD a pipeline during my creation process:
                         since pipeline has been added, the bottom left decorator should indicate that there is an associated pipeline 
                         that is not started

Type - Status

<img width="632" alt="Screen Shot 2020-09-29 at 4 01 09 PM" src="https://user-images.githubusercontent.com/51342070/94609818-51ae4b80-026d-11eb-8d1f-c4d908bc14fc.png">

**Comment by gdoyle1** [comment]
@bdellasc @rachael-phillips @cshinn @mcarrano Wanted to get all of your eyes on this to see if you have any input on status icons used within OpenShift. We've tried creating the table here to show what is currently implemented vs. being proposed! That circle + asterisk is something I created combining 2 Font Awesome icons

**Comment by bdellasc** [comment]
@gdoyle1 Thanks for sharing this! As for my 2¢:
- For "not yet started", the power-off icon doesn't feel quite right to me. I think the empty circle is the better option (plus it would round out the set below, and it might make sense to name it with the same format as the other three):
     - pf-icon-resources-almost-empty
     - pf-icon-resources-almost-full
     - pf-icon-resources-full
     **- pf-icon-resources-empty**
- For "new" I think the asterisk inside the circle works better than the resources full icon

**Comment by mceledonia** [comment]
+1 to Brian's suggestions

- New: I think the asterisk inside the circle is the best option there
- Not yet started: Empty circle feels a little odd without the context of the rest of the resources icon set. I guess it feels less like an empty circle that could be filled, and rather just a circle. That being said I think it would still be a useful icon to add to round out that set as `pf-icon-resources-empty`. 

@bdellasc what do you think about en ellipses or a minus-circle icon for not yet started?

<img width="473" alt="image" src="https://user-images.githubusercontent.com/30935938/95777613-8ae6b280-0c94-11eb-9588-7a9ad9690b4a.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/30935938/95777653-9fc34600-0c94-11eb-992c-eeff501171bd.png">

I was also thinking about the classic paused icon, but paused is an actual state which differs in meaning from not yet started, so it would be misleading.

**Comment by bgliwa01** [comment]
@mceledonia I just realized we use the minus-circle icon for remove in openshift so that one won't work...

**Comment by beaumorley** [comment]
If you are going to go with the (...) for "not started, we are thinking of using the circle within a circle for "stopped" in Che. This came up on our internal team call. Currently the stopped icon in Che is a circle with a slanted slash through it which is already used for "canceled".

**Comment by bgliwa01** [comment]
Here is the proposed icons for new and not started @mceledonia 

![New and Not started icons](https://user-images.githubusercontent.com/51342070/96033141-b650d500-0e2d-11eb-8570-a925069c9bf0.png)

**Comment by bdellasc** [comment]
@bgliwa01 "Not started" looks good to me. Was there a reason we abandoned the asterisk in the circle idea for "New"? A number of people (including me) felt that the empty hourglass wouldn't be obviously different enough from the one with sand in it. The thought was the asterisk is used in other software to indicate "new".

CC @mcarrano @mceledonia

**Comment by mcarrano** [comment]
@mceledonia @bgliwa01 and I met today to discuss this. We decided to stick with what's proposed above with the qualification that we name the New icon something more use case specific like "New process" to differentiate it from a general purpose New icon that could be added in the future. I will open a core issue to implement these in the icon set and tag you to attach the related SVGs.

**Comment by doruskova** [comment]
@mceledonia @bgliwa01 Could you add related SVGs for these icons so that I can update our symbol library? Thank you :)

**Comment by mceledonia** [comment]
@doruskova @mcoker Here are the two icon files for "new-process" and "not-started." These are the two we concluded on adding to the set with no other changes. 

Please let me know how they work! 
[newprocessnotstarted.zip](https://github.com/patternfly/patternfly-design/files/5525717/newprocessnotstarted.zip)

**Comment by mcoker** [comment]
These have been added to core, and will be available in react this release - https://pf4.patternfly.org/icons

**Comment by doruskova** [comment]
@mceledonia They're available in a Sketch library :) It worked well. Thanks!
