### ISSUE TITLE
Reconsider placement and usage of Teriary nav component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#922]
There has been a lot of confusion about usage of the Tertiary nav variant. Common questions include:

* How are tertiary nav and tabs different (they look the same)
* If tertiary nav is used, where should it live on the page?
* What is the correct placement and spacing of page header elements including tertiary nav or tabs (if used), the page title, breadcrumbs (if used)

There is currently a Tertiary nav demo that seems inconsistent with current usage: https://www.patternfly.org/v4/components/page/react-demos/tertiary-nav/ You can also see a related issue here: https://github.com/patternfly/patternfly/issues/3559

Here is an example of desired product usage:

![Screen Shot 2020-10-05 at 1.18.37 PM.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/5c15814f-bcd0-4504-b990-93fcf1c26499)

**Comment by mcoker** [comment]
Here is the current spacing for reference. We have 3 types of page sections - one for the tertiary nav, one for breadcrumbs, and one for a generic page section (title, text, table/data-list, cards, etc)

Tertiary nav: in our designs always comes first. It has 16px top padding, 0px bottom padding. The space between the tertiary nav and whatever comes after it is defined by the padding of the thing that follows it.

<img width="1117" alt="Screen Shot 2020-10-05 at 4 41 32 PM" src="https://user-images.githubusercontent.com/35148959/95135696-70f41f80-072a-11eb-8fc1-e0c348924de9.png">


Breadcrumbs: comes after tertiary nav. Also has 16px top padding, 0px bottom padding. Same deal with the spacing below it.

<img width="1332" alt="Screen Shot 2020-10-05 at 4 41 44 PM" src="https://user-images.githubusercontent.com/35148959/95135706-75203d00-072a-11eb-8bbf-c1b73b1ba0a9.png">


Generic section: has 16px all around < 1200px viewport, 24px all around > 1200px - except when it follows breadcrumbs, then it has 16px top padding on all viewports.

<img width="1342" alt="Screen Shot 2020-10-05 at 4 41 57 PM" src="https://user-images.githubusercontent.com/35148959/95135712-781b2d80-072a-11eb-8ee8-8a207d897f89.png">

<img width="1336" alt="Screen Shot 2020-10-05 at 4 42 05 PM" src="https://user-images.githubusercontent.com/35148959/95135721-7b161e00-072a-11eb-8509-8d75613c0fbb.png">

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/3936 to update demo of tertiary nav in a page using newly designed sub-nav as seen here. Design:https://marvelapp.com/prototype/fj0941h/screen/77719996 Will close this design issue.
