### ISSUE TITLE
Validation Guidance on Optional Steps within Wizard

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#925]
We're hoping to get some more guidance/clarification on Validation placement and behavior within the wizard.

How should the validation button show when all fields within a step are optional and validation is **not required** to move onto the next step in the wizard, _but_ if a user chooses to fill out these fields then they _will_ require validation?

For example, the Debezium UI currently uses the validate placement/behavior written in the existing PF wizard design guidelines (showing it in place of the next button, and having the next button show after successful validation). This step is an optional step, so it really isn't necessary to validate these fields before viewing the next step. 

![image](https://user-images.githubusercontent.com/46571616/95506975-b6a92600-097e-11eb-922d-62363ff977cf.png)

It seems like there could be a few different ways to show this behavior, but we are hoping for more guidance. Here are some possibilities we have considered: 

- Showing a validation button near the specific field/fieldset that requires validation within a step

- Having an optional validate button in the footer that applies to all fields within a single step (but still surfacing the next button)

- Showing the validate button ONLY on the final/review step and having it apply to all fields across steps that require validation, and then displaying a list of errors and links to their respective fields. 

CC: @jgiardino @tiffanynolan @amysueg

**Comment by mcarrano** [comment]
@lboehling why do we even need a Validate button? What I would expect is to see a Next button and upon clicking that button, the software does the validation is needed. If validation is successful, it simply advances to the next step. If not, errors will be returned on the page and the user will be kept on the current step until they are corrected. That's consistent with our current implementation and guidance.

**Comment by jgiardino** [comment]
> Showing a validation button near the specific field/fieldset that requires validation within a step

Just to add some more details for this one, when chatting with the engineering team, they mentioned that validation could be split up within a wizard step (e.g. different section of inputs in the form on one page could have a separate validate button). One reason they provided in support of this pattern was that they were "not sure they can always nail down the bad properties." 🙃

**Comment by lboehling** [comment]
Spoke with @mcarrano  today, and our suggestion is to default to built-in validation when users click "next." However, if you want to have an explicit option to validate or "test" a set of fields before moving forward with the rest of the configurations within that step, then you should provide a validation button for the specific fieldset and consider changing the button copy to “Test [basic connection properties]” instead of "Validate". It would also be worth looking into using the new spinner button component to give clear feedback for the users. If you want to require that users test the basic properties before proceeding, you could disable the next button until the basic properties are checked. The remainder of the fields would still go through the backend validation after clicking “next.”

**Comment by jgiardino** [comment]
Thanks for discussing this! This approach sounds good to me. 

In the case where the user clicks a step in the wizard instead of the Next button, I'm assuming the validation would happen in that case as well? Or is the recommendation to always disable step navigation in this scenario, and require the Next button? If the latter, I'm wondering in the case where the user goes back and makes edits, should the steps then be disabled again.

Are there any recommendations on what to show to the user while validation is happening? For example, in cases where the user is entering some connection/authentication info, then I imagine checking the values could take some time.

**Comment by mcarrano** [comment]
@lboehling @jgiardino Just wanted to follow up on this. We could pursue a couple of options for reflecting progress while validation is taking place. A progress bar would work if you could reflect progress from the backend. We also recently introduced this button with a built in spinner: https://www.patternfly.org/v4/components/button#progress  Maybe use that variant for the Next button?

**Comment by mcarrano** [comment]
@jgiardino @lboehling Do we still need to keep this open? Is there any action you are looking for from PatternFly at this point?

**Comment by mcarrano** [comment]
@lboehling @jgiardino I am going to close this out. If you think this solution is something we should document on the website, feel free to open an issue in https://github.com/patternfly/patternfly-org
