### ISSUE TITLE
Show password option for login page

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#927]
Requesting to add in an option for a way to show the password on the login form. 

I propose adding a link button below the password field, right aligned
![image](https://user-images.githubusercontent.com/6415742/95614401-6db3a900-0a34-11eb-9017-56afe6a89c0b.png)

I also tried an icon but Michael and I think the text link is more obvious and clearer about what it does
![image](https://user-images.githubusercontent.com/6415742/95614613-c6834180-0a34-11eb-8da8-490ff7c323f6.png)

**Comment by ajacobs21e** [comment]
@katierik uses the icon:
![image](https://user-images.githubusercontent.com/6415742/95617376-54612b80-0a39-11eb-9b1d-9a7a9bf83c91.png)

**Comment by mcarrano** [comment]
@ajacobs21e I will get this on our roadmap. Do you need this in any particular timeframe?

**Comment by ajacobs21e** [comment]
Thanks Matt. By end of Q1 would be great.

**Comment by mcarrano** [comment]
@mceledonia @ajacobs21e I discussed these options today with @mcoker . The second option (show/hide icon at right of the field) would be easy to implement. We could add a tooltip to make this more discoverable if needed. The preferred option with the "Show password" action right-aligned in the space below the field could potentially cause wrapping issues if the text associated with the checkbox were to be longer (this is currently a variable string passed in via a React prop). If we prefer this approach, our suggestion would be to move "Show password" to be right-aligned above the field, in line with the field label.

Let me know what you think and the second option up if we choose to go that way.

**Comment by ajacobs21e** [comment]
Icon it is!

https://www.sketch.com/s/b6e64fc8-2a0c-4c7f-9cd6-87e2c3679d80/a/vVb49e

**Comment by mcarrano** [comment]
Let's go with the icon approach then. For implementation, besides creating a new Login page variant, it occurs to be that we will need to add this icon to our icons set as it does not exist there now. Looks like we will want to use 'fa-eye' to show the password and 'fa-eye-slash' to hide it. @mcoker @bdellasc can you remind me what versions of font awesome icons we package? far vs fas?

**Comment by bdellasc** [comment]
I believe fas is included automatically in the toolkit while far has to be specifically chosen by the consumer. @mcoker or @evwilkin can weigh in/correct me if my recollection is wrong.

**Comment by mcarrano** [comment]
I have opened https://github.com/patternfly/patternfly/issues/3770 for core implementation.
