### ISSUE TITLE
Enhance select list to include a "view more" option for option overflow

### ISSUE THREAD

**Issue by nlcwong** [patternfly/patternfly-design#928]
Could there be an enhancement made to select component to include a row at the bottom of the list to allow the user to view more options that could be listed in the select?

I have a case (cost management's settings) where there could be thousands of options listed in a select component's list. I would like to know if there is guidance or a single solution we should go with.

I have seen two solutions so far in the CRHC platform:
1. The select component would load the first n options with a "view more" link at the bottom of the select list that would load the rest of the options the user could select. (CRHC RBAC feature)
2. The select component would load the first x options with a "view more" link at the bottom of the list that would launch a modal dialog that would display a list or table the user could select from that would have additional filter and sort capabilities. (one of the Insights apps in CRHC)

**Comment by mcarrano** [comment]
@nlcwong It would be a relatively easy enhancement to provide the option to navigate off to a modal or another page to manage the list. We are in the process of introducing an enhancement to the Context selector component to do that here: https://www.patternfly.org/v4/components/context-selector/html#with-footer  Supporting a 'View more' option to load more items into the list would be a better approach IMO. @tlabaj can you take a look at this and let me know if we support that now or if it's a feature that could be added either to the component or by the consumer? Thanks.

**Comment by mmenestr** [comment]
Here is my proposal with both keeping it in the menu + having a modal: https://marvelapp.com/project/5558454

**Comment by mcarrano** [comment]
@mmenestr Had you considered creating a footer like we have here: https://www.patternfly.org/v4/components/context-selector#with-footer? Ideally I'd like this to be something that is general to hold 'View more' or any other action you wanted to add. Thoughts?

**Comment by mmenestr** [comment]
I just added a [mock to show that option](https://marvelapp.com/prototype/c49ebi3/screen/77899796)! I think the only thing I wonder is how the interaction would work. If it opens up a modal I think the interaction is great, makes sense, and it helps that the button is always so visible, but when the "view more" just makes the menu scrollable, what should happen with the footer? Does the footer just stay there floating on top of the options, but the menu becomes scrollable? And would the effect of clicking "view more" be obvious to a user?

In the context selector it makes sense because the footer contains external actions, but in this case I'm not sure how it should work!

**Comment by nlcwong** [comment]
To give the sense of a menu becoming scrollable, i would think footer or inline link would always be at the end of the list never floating on top.

With that said, I like the inline link for a menu that becomes scrollable and a footer link for a menu that will launch a modal.

**Comment by mcarrano** [comment]
@mmenestr I opened https://github.com/patternfly/patternfly/issues/3953 to begin implementation in our next sprint milestones. Please add your final designs to that issue when complete (and also here for reference).

**Comment by mmenestr** [comment]
Final design: https://marvelapp.com/prototype/c49ebi3/screen/77975699

Went with "View more" inside the menu which would be located after the first 8-10 options. Clicking view more would surface more options which users could scroll through. At this point the list could become endlessly scrollable, with a spinner showing as options are loaded OR users could be made to click "View more" repeatedly to surface more options each time (this would probably be if a technical limitation applied).

If users want the additional options to surface in a menu, the recommendation would be to have a menu footer containing the "View more" link which would act as a link to open up said modal.

**Comment by mcarrano** [comment]
Thanks @mmenestr . I have opened https://github.com/patternfly/patternfly/issues/3953 to begin implementation.

**Comment by mcarrano** [comment]
Design doc updates covered in patternfly-org/2206
