### ISSUE TITLE
Revisit Context Selector placement

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#933]
Multiple issues/requests have surfaced concerning the Context Selector. These mainly focus on placement of the control

These issues are being tracked in a Google Doc here: https://docs.google.com/document/d/1c0tKt8DBNWx67QmLocvpUnbR_EeJodxKSyaHzLVXxIw/edit?usp=sharing

A successful conclusion to this story will include one or more specific enhancements that can be implemented in PatternFly.

cc: @rachael-phillips @LHinson @catrobson

**Comment by mcarrano** [comment]
@gdoyle1 looks like you transferred this back to patternfly-design. Is there anything more to do here? If not I will close.

**Comment by gdoyle1** [comment]
@mcarrano Yes transferred this to patternfly-design to become an epic to then add patternfly-design-kit issues to it! I assume this is done from a design standpoint though, so should be good to close
