### ISSUE TITLE
Ability to add a pill label or "tag" to a disabled tile

### ISSUE THREAD

**Issue by amysueg** [patternfly/patternfly-design#936]
- The designs for provisioning a Managed Kafka instance include a wizard that displays a choice of a cloud provider.
- For the initial release, only one cloud provider will be available (Amazon Web Services)
- The design proposes some kind of marker to indicate that the other two choices are not yet available but will be at some point in the future.
- A tooltip *could* be used but is not ideal as it is not obvious that there is anything there. 
- A pill label, or "tag" added to a disabled tile could help represent this idea better.

Slide 20 shows the page where such a label could be helpful, for the Google Cloud choice. 

![image](https://user-images.githubusercontent.com/21063328/97357829-c24a8700-1870-11eb-959a-be70652fc4a9.png)

@jgiardino @lboehling @mcarrano

**Comment by mcarrano** [comment]
@amysueg is there a link to the design you are trying to implement (Slide 20 in what doc)? Seems like a reasonable request but would like to see what you are trying to accomplish. Thanks.

**Comment by jgiardino** [comment]
I was making some edits, so it's now [slide 23](https://docs.google.com/presentation/d/1OsvwZApq9LqfLHK9SJzJDjy7H7xBoM1El345PmwAz_g/edit?usp=sharing).

**Comment by jgiardino** [comment]
Also, if you're interested, slide 25 includes some comments provided by other team members regarding this use case.

**Comment by amysueg** [comment]
thanks @jgiardino -- @mcarrano looks like I left off the link to the design with Slide 20! sorry!

**Comment by mcarrano** [comment]
Thanks @jgiardino . So is the proposal here to just add a label to the right of the title then? @mcoker @tlabaj is it possible to do that now? To just add a Label component following the title text in a Tile?

**Comment by jgiardino** [comment]
I was envisioning more of a footer 🤷 but am curious what @amysueg was envisioning, and am also open to suggestions (including ideas that are doable with existing components). 

For a rough example, I cobbled this together using the inline code editor in PF.org, but it needs some help.

![image](https://user-images.githubusercontent.com/21063328/97359682-836a0080-1873-11eb-8138-3f9ca8303dba.png)

**Comment by amysueg** [comment]
I agree @jgiardino about the placement. I was imagining this label as a header or footer.

**Comment by mcoker** [comment]
> To just add a Label component following the title text in a Tile?

@mcarrano technically you can but it would be better if the title and label were part of a layout so you could control the alignment, spacing, etc. Here are a couple of examples using the pf.org site preview editor.

<img width="886" alt="Screen Shot 2020-10-27 at 4 55 53 PM" src="https://user-images.githubusercontent.com/35148959/97366431-54548e80-1875-11eb-855d-025003ded43e.png">

You can use a layout inside of the `<Title>`, too, if you wanted the label to be read as part of the title element.

**Comment by mcoker** [comment]
@mcarrano @jgiardino my apologies, I misread Tile as Title! To add a label like in @jgiardino's screenshot, I would use a layout in the tile body to manage the spacing/positioning. Here's a demo - https://codesandbox.io/s/elastic-moser-4km8n?file=/index.js

**Comment by mcarrano** [comment]
@jgiardino did the suggestion from @mcoker address this? If so, can I close this out?

**Comment by jgiardino** [comment]
Yes, @mcarrano. And thanks for the suggestion, @mcoker. I'm good with handling this within the app vs building it into the component.
