### ISSUE TITLE
Demo draggable rows in Data list

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#937]
Draggable rows capability was added to the Data list component here: https://www.patternfly.org/v4/components/data-list/react#draggable  This was defined in the context of table column management for a very simple list, but it's unclear how this should work for more complex list types. Some questions:

* Where does the draggable affordance live if there are other elements like checkbox select and/or expansion at the front of a row?
* What is the effect of dragging an expanded row?

@mcoker I've created this design issue based on our discussion yesterday. Are there other questions we should consider?

**Comment by mcoker** [comment]
Also is there anything we should take into consideration for a row that is both selectable and draggable, since you can click anywhere in a row to select it? I'm assuming the draggable button in the row would behave like a kebab action in the row - clicking on the drag button only allows you to drag a row and stops the normal selection event when clicking on a row. It would be good to demo that and make sure it works as expected.

**Comment by mcarrano** [comment]
@beccaglass @lboehling I know that you were looking at further considering the design for draggable data list rows. Perhaps you can consider what should happen in this case when there are multi-line items as per this request: https://github.com/patternfly/patternfly/issues/3712

**Comment by beccaglass** [comment]
@mcarrano mocked up options here: https://marvelapp.com/prototype/2754jdc6/screen/75277643

Let me know what you think!

**Comment by mcarrano** [comment]
Thanks for updating @beccaglass . @mcoker @mceledonia @kmcfaul please give this another look and let us know if you see any more issues. What changes do you think we might need on the core and/or React implementation to realize this behavior?

**Comment by mcoker** [comment]
@mcarrano seems straight forward to me. On the core side, looks like we just need to [update the drag icon alignment](https://github.com/patternfly/patternfly/issues/3712) and the ghost row styles.

**Comment by mcarrano** [comment]
Opned https://github.com/patternfly/patternfly/issues/3765 to begin core implementation of this demo. Thanks for you work on this @beccaglass !

**Comment by doruskova** [comment]
@beccaglass Hey Becca, do you have any example of this feature in a context? I'm just wondering that it might be useful in our PF template.
