### ISSUE TITLE
Inline alert for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#938]
The current inline alert styling with a "pastel" background might be too bright against a dark background. Evaluate design options.

**Comment by doruskova** [comment]
@mcarrano Here's the update for inline alerts https://marvelapp.com/prototype/963bhhh/section/1189946
I also took a look at toast alerts because I think that inline and toast should look the same. It seems that the only difference is in placement.

**Comment by mcarrano** [comment]
These look good to me @doruskova . Can you also take a look @mceledonia ?
