### ISSUE TITLE
Badge for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#939]
Current badge does not work on a dark background. Is there a solution that will work on both? Do we need a unique dark theme badge?

**Comment by mceledonia** [comment]
![image](https://user-images.githubusercontent.com/30935938/101918680-a3415380-3b97-11eb-9cdb-ff37720264c0.png)

Badge styling

Default
Fill - #36373A
Text - #FFFFFF 

Unread
Same as regular theme!

**Comment by mcarrano** [comment]
Looks good @mceledonia
