### ISSUE TITLE
Banner for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#940]
Need to re-evaluate banner colors against a dark background.

**Comment by doruskova** [comment]
@mcarrano Adding an update [here](https://marvelapp.com/prototype/963bhhh/section/1215235)

**Comment by mcarrano** [comment]
Thanks @doruskova . Let's review when we meet this week.

cc @mceledonia @mcoker

**Comment by mcarrano** [comment]
Need one more iteration on the red banner.

**Comment by doruskova** [comment]
Update on red banner. Mock is [here](https://marvelapp.com/prototype/963bhhh/section/1215235). I'm taking back what I said the last time. The new red looks fine. I changed the CSS in a demo and it looks good. See below: 
![patternfly-pr-3686 surge sh_components_banner_html-demos_basic_](https://user-images.githubusercontent.com/32618096/103998322-34f2af80-519c-11eb-868c-2aab8dd3a174.png)

**Comment by mcarrano** [comment]
Looks good. Will close per our 8 Jan meeting.
