### ISSUE TITLE
Label for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#942]
Explore how current Label colors work against a dark background and recommend modified colors to be applied through CSS variables. A consistent approach between Inline alerts and Labels would be desirable to reduce the number of unique new variables.

**Comment by doruskova** [comment]
@mcarrano I'm adding a mock for labels [here](https://marvelapp.com/prototype/963bhhh/screen/74197638) and the color palette [here](https://marvelapp.com/prototype/963bhhh/screen/74194783)

**Comment by mcarrano** [comment]
Thanks @doruskova . @mceledonia please also take a look.

It would be great to see these in the context on a full screen mockup, if possible. I think we need to see how these balance with pother elements on the screen.

**Comment by doruskova** [comment]
@mcarrano Sure, it's still in progress. I need to find a balance for labels and inline alerts together.

**Comment by doruskova** [comment]
I've added a [darker version for labels](https://marvelapp.com/prototype/963bhhh/screen/74197638) and a specific example in a page [here](https://marvelapp.com/prototype/963bhhh/screen/74204341)

**Comment by doruskova** [comment]
@mcarrano @mceledonia Here's the update. I took it from a different side and I didn't use colorful bg at all and I was trying to keep the pastel colors for a text and icons. 
Here's the visual and example in a table: https://marvelapp.com/prototype/963bhhh/section/1189948
Here's the clickable hover state with more variations (my preference is a grey border): https://marvelapp.com/prototype/963bhhh/section/1194728

**Comment by mcarrano** [comment]
Want to converge on only one label style for dark theme (Filled labels) with outlined hover style.

**Comment by doruskova** [comment]
Mock's been updated - includes only 1 version for a dark theme.

**Comment by mcarrano** [comment]
Looks good to me. Thanks @doruskova
