### ISSUE TITLE
Add option to hide dropdown carot in typeahead select component

### ISSUE THREAD

**Issue by jeudy100** [patternfly/patternfly-design#943]
**Describe the issue. What is the expected and unexpected behavior?**
We are using the typehead select to filter through a list, but we need the typeahead to look like an input by removing the dropdown carot. It doesn't seem like there is an option to replace or hide the carot in the current typeahead select component. Would it be possible to add a prop that would hide the carot or a new typeahead input component, if that is more appropriate.

P.S. We are only using the single typeahead, but I could see this being useful for both the single and multi select.

**Implementation as per my suggestion:**

    Accept 1 new props (hideDropdownCarot)
    If the user passes hideDropdownCarot prop then the dropdown carot  would be hidden.

https://www.patternfly.org/v4/components/select#typeahead

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?
enhancement**

**What is your product and what release version are you targeting?**

**Comment by anujsingla** [comment]
Thanks @mcarrano for quick response. We are using typehead in our project and need this feature ASAP.
Shall I raise a PR for this improvement?

**Comment by mcarrano** [comment]
@anujsingla sounds like what you really want is a search input like this with type-ahead support added: https://www.patternfly.org/v4/components/search-input Is that right?

I've discussed this with some other folks on the team and we all agree that the Select is intended for selection from a dropdown menu, so hiding the affordance to open the menu does not make sense here. If you wanted to explore adding this to the Search input, we can work on that. Also, if you can provide more details about the project, any sample designs, etc I might be able to offer some alternatives.
