### ISSUE TITLE
Investigate dark theme styling for read-only text fields

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#946]
Consider styling for read-only fields use in any component that supports a read-only appearance, e.g. Clipboard copy, File upload, text input, etc. Does lighter gray really afford read-only? Are there other ways to afford this? Research what other design systems are doing.

**Comment by mceledonia** [comment]
Here's what I've come up with for both disabled and read-only:

I think for both we can remove the bottom border. For disabled, we can change the background and text colors to lower contrast and make them feel more muted/disabled. For read only, I think we can leave everything as-is, and the missing border does a good job of creating a read-only look.

New disabled colors
- Background: New dark theme black-500 (#42474B)
- Text: New dark theme black-200 (#A9ADAF)
 
![image](https://user-images.githubusercontent.com/30935938/99675041-bce1f600-2a44-11eb-8ecb-2d37157296cf.png)
