### ISSUE TITLE
Group headers for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#948]
Consider restyling for group headings in all dropdown menus.

* Do dark theme versions provide enough contrast?
* Are there other styling options we should consider to differentiate headers and menu items?

**Comment by mceledonia** [comment]
Here are some headers from the topology work and a conversion to dark theme, they use 14px menu items though so I might need to update that or propose it as an additional change.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/30935938/102511387-bb611900-4056-11eb-98e6-c65eba412483.png">

@mcarrano @doruskova @mcoker

**Comment by mcarrano** [comment]
I have opened https://github.com/patternfly/patternfly-design/issues/974 to also propose this update for light theme components using grouped menu items and will mark this issue as complete.
