### ISSUE TITLE
Real-time format checker for long naming requirements 

### ISSUE THREAD

**Issue by shirimordechay** [patternfly/patternfly-design#949]
In a number of name fields in the OCP console, we have a long validation list of naming rules but we do not provide all requirements upfront. The validation occurs on submission and only one error in the field is shown even if the value has a large number of errors. 

This type of immediate feedback exists only on one rule at a time (https://www.patternfly.org/v4/components/form#invalid)

**Suggested component (enhancement):**
**Error-prevention:** Instead of giving the user non-informative error messages, we will help users to avoid those errors in the first place by making all requirements clear upfront. (Better to use a list of what the user SHOULD do and not what he shouldn’t do)
**Interactive Feedback:** Interfaces should give clear feedback to users about what’s going on- show an interactive list of requirements in case there is more than one. The list is interactive and shows the user exactly which requirements they have satisfied and which still need to be completed. 

**Wireframe examples:**
In form real-time format checker
![In-form-inlineValidation](https://user-images.githubusercontent.com/10331355/98808157-63fed600-2424-11eb-96f8-96855a8e4020.png)

Another possible usage is password creation:
![In-form-inlineValidation-Pass](https://user-images.githubusercontent.com/10331355/98808084-4e89ac00-2424-11eb-9f0c-efbf953cfd38.png)

**Comment by nirfarkas** [comment]
+1 for this!
 Here's an [implemented demonstration](https://cddirector.io/cdd/sign-in.jsp) of something very similar.

**Comment by jknilans** [comment]
+1 - We created our own version of this using existing PF components for a validation state. Here's how we implemented it in our site.

<img width="608" alt="instant-validation" src="https://user-images.githubusercontent.com/25486044/98947426-3026bd80-24c3-11eb-9aee-a29546004655.png">

**Comment by yuvalgalanti** [comment]
+1 for that, totally needed in the OCP console today

**Comment by mturley** [comment]
Probably getting ahead of myself, but just a thought for later: once this gets to the React implementation stage, we should consider not integrating it directly with the bare TextInput component and maybe instead providing a validation helper function and some separate component to display the results. If it's built into the field component I anticipate that conflicting with (or being redundant with) consumer form-level validation implementations. If we expose the logic as a helper function it could be integrated with whatever validation the consumer is already doing.

**Comment by mceledonia** [comment]
Wanted to add a quick change to @jknilans version above since it already seemed to use FA icons - 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/30935938/101647694-08197400-3a07-11eb-9da2-052210e4f2ce.png">

Using secondary text color to create emphasis on remaining/incomplete items. The idea being that once you did them they are less relevant than those which are incomplete. I think this could live either below the field as in Josh's example or in a popover like in Shiri's version. The green/red text seems to sort of compete for emphasis and when there are a lot of requirements it can feel a bit like Christmas colors 😄

**Comment by ajacobs21e** [comment]
Yes, RH SSO could use this! @mcarrano is this on the roadmap yet? @mceledonia is your design baked enough that I can use it in wireframes?

**Comment by mcarrano** [comment]
@ajacobs21e I do have this on the roadmap for availability in June.

**Comment by mcarrano** [comment]
I've opened https://github.com/patternfly/patternfly/issues/4017 to implement this as a new feature called Rich Helper Text that can be applied to any form field. See designs here: https://marvelapp.com/prototype/6jehce7/screen/78511266 Going to close the design issue.
