### ISSUE TITLE
Responsive toolbar buttons/dropdowns

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#950]
As we shrink the width of a toolbar, want to reduce labeled items like buttons or dropdowns to something only represented by an icon to save space. Reference this OpenShift design: http://openshift.github.io/openshift-origin-design/designs/administrator/future-openshift/log%20toolbars/  This should be controlled by setting an appropriate responsive breakpoint.

@jcaianirh anything to add here?  @mcoker what would this require? Do we have a way to do this now or would we need to enhance our button, dropdown, and/or toolbar components to support this?

**Comment by mcoker** [comment]
Assuming you can pass HTML, we have utilities that hide/show things at breakpoints https://codepen.io/mcoker/pen/OJXrrXR

We could also look at building something into these components that allows for this.

**Comment by mcarrano** [comment]
I am going to close out this design issue as it seems like these responsive toolbar issues are being explored as part of this PR: https://github.com/patternfly/patternfly-react/pull/5196
