### ISSUE TITLE
Popovers trigger event - making our popovers affordability better

### ISSUE THREAD

**Issue by nirfarkas** [patternfly/patternfly-design#951]
Currently, our popovers over interactive elements in OpenShift are triggered by "OnClick" event, which makes them less affordable and a non-predicted pattern. 
It will be useful to explore the idea of making them behave as "persistent tooltip" which means they will be triggered by "OnHover" event and keep their persistence behavior. 
Here's [a presentation](https://docs.google.com/presentation/d/19qd1HTxFt8nZPcTryChUqyyzd1dAKiDOvdA0YujAttI/edit?usp=sharing) describing the problem and the offered solution.
Some concerns have been raised about the accessibility of those persistent tooltips by several team members, so we might need to investigate this further.

**Comment by mcarrano** [comment]
@tlabaj any reason we couldn't add the option to trigger a popover on hover vs click? I think providing that flexibility would be the best way to address this request.

**Comment by jschuler** [comment]
@nirfarkas You can control the Popover's visibility manually though the `isVisible` prop. You could do something similar to this example:
https://codesandbox.io/s/nifty-jones-or1y5?file=/index.js
Would this come close to what you're looking for? Thanks -

**Comment by nirfarkas** [comment]
@jschuler Thanks for your reply! This looks great! Is it possible to inject HTML & CSS into this popover? I'm interested in introducing links inside

**Comment by mcarrano** [comment]
@jschuler can you respond to the question above? If we are all set with this, I'd like to close it out.

**Comment by jschuler** [comment]
@nirfarkas Yes you can put anything you want into the `bodyContent` of the Popover, for example
```
import "./myStyles.css";

bodyContent={
  <div>
    <a href="www.google.com">Google</a>
    <span className="my-class">Hello</span>
  </div>
}
```

I'll close this issue, if you have any more questions feel free to comment anyways!

Thanks,
J
