### ISSUE TITLE
Hint for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#953]
Reconsider design of Hint for dark theme. Similar issues to inline alerts.

**Comment by doruskova** [comment]
@mcarrano Updated hint: includes grey and a blue version with examples https://marvelapp.com/prototype/963bhhh/section/1189947

**Comment by mcarrano** [comment]
Thanks for creating these options @doruskova . What do you think @mceledonia ?

**Comment by doruskova** [comment]
[Updated mock](https://marvelapp.com/prototype/963bhhh/section/1189947) - includes only the grey border version that we agreed on.
