### ISSUE TITLE
Favorites for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#954]
Need to specify static, selected, and hover colors to be applied everywhere dark theme is supported.

**Comment by mceledonia** [comment]
@mcarrano @doruskova @mcoker 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/30935938/102509704-d92d7e80-4054-11eb-93d6-c9021dcc066d.png">

**Comment by doruskova** [comment]
@mceledonia Looks great!

**Comment by mcarrano** [comment]
Thanks @mceledonia !
