### ISSUE TITLE
PatternFly needs a native Log Viewer component

### ISSUE THREAD

**Issue by ssbarnea** [patternfly/patternfly-design#955]
Lots of application need to display command line output from executed commands, either looking as a just console/terminal output (ANSI enabled) or just like log tailing.

Please note that this refers to a static terminal view, not an interactive ones, more of a log viewer which user may want to configure to limit its size, display of line numbers and eventually soft-wrapping or rows.

At the most basic level that used to be covered by a simple `<pre>` element but once you want to render ANSI and adde extra features, you realize a more advanced component is needed.

In some cases this content may be streamed but most of the time the source is a multiline string, likely one that contains ANSI sequences.

A good example for that we had on [Zuul CI](https://review.opendev.org/#/c/739444/) where we need to display output in various places. There we made use of [ReactAnsi](https://github.com/RaoHai/react-ansi) which is very easy to integrate but the project is not actively maintained and lack in many areas, including a default theme that not assure best text contrast. 

![example-of-terminal-component](https://sbarnea.com/ss/Screen-Shot-2020-08-25-16-23-03.45.png)

If a Terminal like component would be a native patternfly component it would be much easier for users to integrate this features in a consistent way across applications.

**Comment by ssbarnea** [comment]
I am one of those contributing to https://zuul-ci.org/ which recently migrated from pf3 to pf4.  As Zuul is fully opensource and community driven, there is no fixed date for having it ready. I already posted a message on the mailing list to invite others to engage on this.

Keep in mind that it would be a good idea to limit the initial ANSI support to the basic 3-4 bit support and avoid scope creeping with more advanced terminal support. Most tools produce output using only these. The only trick here is that we will likely want to use a custom 16-color theme that improves the contrast and readability of text, also integrating better with patternfly design.

I am more than happy to propose a theme for this as [original-rgb values are not ideal](https://sbarnea.com/ss/ansi-colors-original-rgb.png) and can make text invisible, but there [theming alternatives that can improve visibility](https://sbarnea.com/ss/ansi-colors-themed.png).

**Comment by mcarrano** [comment]
Thanks for providing this additional information @ssbarnea . We will review this request against other priorities and get back to you with next steps.

**Comment by ssbarnea** [comment]
Thanks too! As a note, I am expecting pf team to implement it but it would be very useful if it could guide us regarding which steps should be followed.  Based on who has time, we may be able to progress to having such a component.

**Comment by mcarrano** [comment]
@dgutride @evwilkin Any thoughts on this? I know we currently have a Console extension in patternfly -react but not sure if that can be leveraged here.

cc @tlabaj

**Comment by ssbarnea** [comment]
I am afraid that an interactive console is totally different that what I describe here. If what I seen as react-console is more of a react-tty which will never be able to cover for "log viewing". A terminal(TTY) has a fixed/limited number of lines, a web page does not.

I  hope that I described the use-case well enough, the expectation is to have a pre-like component which renders text quickly and with ANSI rendering ability, **later** we can add line numbers with hyperlinks for easy sharing.

There are only two bits that I see being possible to share with the TTY console we have: 16-color theme (if it has one) and maybe the code used for rendering ANSI to html, if it is already optimized for speed. As opposed to a real TTY, the view console does not need full ANSI support like cursor movement, which makes rendering very slow. Covering the subset of ANSI codes that change color should be sufficient.

**Comment by mcarrano** [comment]
@ssbernea thanks for clarifying. Now I think I understand what you are looking for. I will check across projects to see if we can capture requirements and get this onto our PatternFly roadmap.

**Comment by mcarrano** [comment]
Attaching this Google doc as a place to capture cross-project requirements: https://docs.google.com/document/d/1AnOzU-1jm6wV_sDNJkjObKF5lASLlj5dT1-wrP_gjKQ/edit?usp=sharing  Feel free to add requirements, use cases, or examples, as needed.

**Comment by evwilkin** [comment]
@mcarrano FYI OpenShift is currently testing an [existing logger vs custom building their own solution](https://github.com/redhatinsights/logger-demo), we will work with them to get a demo of their progress in the new year. Juntao has been working on building a [toolbar example for the logger](https://github.com/patternfly/patternfly-react/issues/5174) in PatternFly as well. We may be able to combine this work with the work towards Code Editor @nicolethoen has been working on for a complete solution.

**Comment by mcarrano** [comment]
@mceledonia @andybraren I made further updates to my designs following our meeting yesterday. You can see those here: https://marvelapp.com/prototype/bia3j2d  Please take a look and feel free to leave comments. Note that this is still mostly focused on the toolbar and I have not yet addressed color coding or readability of the log data itself.

**Comment by mcarrano** [comment]
@mcoker See design mockups for the log viewer linked above. This is still a work in progress but I welcome any feeback.

**Comment by mcoker** [comment]
@mcarrano thanks, this looks fairly straight forward. Are the items/actions to the right of the toolbar something a product would add/change for what they need, or are those actions built in to our component?

If those actions are all defined by the user, the overflow menu doesn't currently support what's in the responsive design, though the behavior in the design is possible by hiding toolbar actions at a mobile breakpoint, and showing a hidden menu at that same breakpoint.

**Comment by mcarrano** [comment]
Requirements for an MVP based on meeting with @andybraren @jcaianirh @evwilkin @mcoker @mceledonia Ryan Long and Alerxander Rivera can be found here: https://docs.google.com/document/d/16NXwf2u8gd8v69plMH4H4xWf0GsK1AWN0wpBu_Xg_GE/edit?usp=sharing

Updated designs based on feedback: https://marvelapp.com/prototype/bia3j2d

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/3811 to begin core implementation. https://github.com/patternfly/patternfly-react/issues/5341 for React implementation.
