### ISSUE TITLE
Switch for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#959]
Evaluate switch styling for dark theme and recommend changes. Known issues based on initial audit:

* Check mark should be dark color // 
* “Off” state colors should get darker // 
* “Disabled” state colors should change

**Comment by doruskova** [comment]
@mcarrano @mceledonia Here's the update on the switch component https://marvelapp.com/prototype/963bhhh/section/1197904

**Comment by mcarrano** [comment]
Looks good to me @doruskova . What do you think @mceledonia @mcoker ?

**Comment by mcoker** [comment]
Looks good!
