### ISSUE TITLE
Toolbar filter field clear button 'x' should have a hover state

### ISSUE THREAD

**Issue by mattreid** [patternfly/patternfly-design#961]
## Requesting new features, enhancements, or design changes to PatternFly 
- Describe the use cases and requirements of the new feature or enhancement you are requesting.
The current toolbar design includes an 'x' button to quickly clear the field, but it doesn't have a hover state, or change the mouse cursor to the hand icon to look interactive. Other clear x's like those used in [labels](https://www.patternfly.org/v4/components/label) have a hover state and change the cursor.
- Explain *why* this feature is needed and/or why these requirements cannot be met using existing components.
Application developers shouldn't have to customize the widget to get this functionality. I would expect this to come standard.
- If this is for specific applications, list them here along with any dates that you need this for.
- Link any detailed design documents, rough sketches, wireframes or workflows.
Carbon does more what I would expect here
https://www.carbondesignsystem.com/components/search/usage
- State whether this is a new feature or an enhancement on an existing pattern by labeling it accordingly
Enhancement
- If this is an enhancement to an existing feature, identify the feature that you want to modify.
https://www.patternfly.org/v4/components/toolbar

As an aside, it looks like only the x itself is clickable, which presents a small click target.

**Comment by mcarrano** [comment]
@mattreid what you are seeing is the result of the browser adding the clear button inside of the field when the user is entering text. This is browser dependent. Chrome adds a clear button and Firefox does not. We would need to override the browser's native behavior to fix this. As an alternative we do have a custom search input where we control the appearance of the clear button as seen here: https://www.patternfly.org/v4/components/search-input  Would that solve this?

**Comment by mattreid** [comment]
Oh, interesting. I assumed that was PF and not browser behavior. Not wanting to overwrite browser behavior makes sense to me, I'll look into the search input more, thanks @mcarrano
