### ISSUE TITLE
Define tertiary level for PF website navigation

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#962]
The current webiste navigation is based on the PF vertical navigation and supports nesting one level deep (i.e., a two-level expandable navigation). There are cases where we can use an additional level of nesting to break up pages with large amounts of content and reduce the number of items that require a new first-level section.

Explore visual design solutions that address this problem.

**Comment by beccaglass** [comment]
@mcarrano starting to mock up some options for this issue... is there a use case that jumps out at you that I can use to show variations? I.e. In the current site, what are nested elements that would be grouped into a third level?

**Comment by mcarrano** [comment]
@beccaglass That's a great question. I know that I was involved in multiple discussions where this came up. One in particular concerned the UX Writing guidelines. This would naturally fit within the Guidelines category, but the document became too long and it was decided to break it up into multiple pages so we needed to pull "UX Writing" out to a top level section. The result of this is that it forces us to have more items at the top level than we would like to have.

Does that help?

**Comment by beccaglass** [comment]
@mcarrano yes, that definitely helps.

I mocked up three visual options to start with... I happened to group some of the 'Guidelines' elements to illustrate the pattern, but of course this just serves to show possible 3-level patterns, rather than imply how we'd change the grouping of site pages.

Let me know your thoughts!

Mocks: https://marvelapp.com/prototype/g8666ge/screen/78452062

**Comment by mcarrano** [comment]
Thanks @beccaglass . Of your options, I think either the first or third are possible (or some combination). The second option is probably not workable because we already use horizontal tabs at the top of some of our pages. I'll set up some time with other team members to review these options.

**Comment by beccaglass** [comment]
@mcarrano sounds good keep me posted. Am I correct in remembering that Patternfly3 had a flyout/nested menu component that was nixed for PF4?

**Comment by mcarrano** [comment]
Yes, that's correct. We were trying to avoid flyouts for PatternFly 4

**Comment by beccaglass** [comment]
@mcarrano updated mocks and nav shown in context (both for PF site and c.rh.c)

https://marvelapp.com/prototype/g8666ge/section/1332343

**Comment by mcarrano** [comment]
Closing in favor of https://github.com/patternfly/patternfly-design/issues/1099
