### ISSUE TITLE
Update/Revisit Custom Row Wrapper Visuals

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#963]
The current example for custom row wrappers on the PF website is conflicting with our styling for selected rows. Can we revisit the visuals for this and provide an example that's differentiated from the existing selected state?

https://www.patternfly.org/v4/components/table#custom-row-wrapper

![image](https://user-images.githubusercontent.com/46571616/100786199-c9b8ff00-33df-11eb-90dd-143f6c12ffe7.png)

FYI @mcarrano @mceledonia

**Comment by mcarrano** [comment]
We will definitely take a look at this @lboehling . The example you are referencing is not reflective of any specific PatternFly design direction. Is this something you are using in product? If so, let me know what product and whether you need this in any specific timeframe.

**Comment by mcarrano** [comment]
@nicolethoen @tlabaj This is an old issue that I was just revisiting. Do you understand what the purpose of the "custom row wrapper" example is in the Table documentation. @lboehling 's point, which I agree with is that this seems to duplicate the styling for selectable rows, which it is not. Do we need this example or should we change it?

**Comment by nicolethoen** [comment]
This example demonstrates how you can apply custom styles to specific rows. The user can define a rowwrapper that applies styles or modifications to rows and they can define their own logic as to when those adjustments would be applied to a row and when it wont be.

We could update the styles in the example to be almost anything. Maybe people like highlighting certain rows so they stand out for a visual scan?

**Comment by mcarrano** [comment]
Thanks @nicolethoen . Yes maybe we just want to update this example. 

@andrew-ronaldson This could relate to the row highlighting issue you were working on. Maybe we use this capability to demonstrate how to highlight newly arriving rows? Just a thought...

**Comment by andrew-ronaldson** [comment]
This was the example I created for highlighting rows in a table when the table refreshes and adds new data. 
<img width="1801" alt="Screen Shot 2022-03-03 at 3 11 55 PM" src="https://user-images.githubusercontent.com/28658548/156635790-1794e6a3-d219-437d-9fc5-e3bcb82b361b.png">

**Comment by andrew-ronaldson** [comment]
@mcarrano I used primary blue .pf-color-blue-400 but reduced the opacity to 50%. Originally we were going to fade this out over a few seconds to show the new data added to the table.

**Comment by mcarrano** [comment]
I've opened https://github.com/patternfly/patternfly-react/issues/7037 to address this in React.
