### ISSUE TITLE
Enhancement for Labels: Add spinner

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#966]
Can we add support for placing a spinner within the label component? This would greatly help with "in progress" status labels.

**Comment by mcarrano** [comment]
@mcoker @tlabaj could this work now by just replacing the icon with a spinner component by passing in in via a prop?

**Comment by mcoker** [comment]
@mcarrano currently it only works with a small spinner. We would need to make a change to get it to work with a medium spinner.

small
![Dec-09-2020 12-45-38](https://user-images.githubusercontent.com/35148959/101675316-4458ce80-3a1f-11eb-9daa-2f26e0bfdf8d.gif)


medium

![Dec-09-2020 13-05-19](https://user-images.githubusercontent.com/35148959/101675322-46bb2880-3a1f-11eb-87f5-db65f10dc726.gif)

**Comment by mcarrano** [comment]
I think that using a small spinner is sufficient. What do you think @lboehling ?

**Comment by lboehling** [comment]
+1, I'm fine with the small spinner! @mcarrano @mcoker

**Comment by mcarrano** [comment]
Sounds good @lboehling . Can I close this issue out then? @maryshak1996 do you think it would be worth adding this as a demo use case?
