### ISSUE TITLE
Update filled labels to work on a gray background

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#967]
Filled labels need a border to be differentiated when used against a gray background. See comments here for more discussion: https://marvelapp.com/prototype/bd077ag

**Comment by maryshak1996** [comment]
I have the design solutions we deided on for both this issue and #971 linked here
https://marvelapp.com/prototype/553965i

**Comment by mcarrano** [comment]
Looks good to me @maryshak1996

**Comment by mcarrano** [comment]
Thanks for your efforts on the @maryshak1996 . I've opened https://github.com/patternfly/patternfly/issues/3810 to begin implementation.
