### ISSUE TITLE
Nav component doesn't have a disabled state for links

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-design#968]
In the docs there is a `.pf-m-disabled` for `.pf-c-nav__link` but no styles for the state were written.

**Comment by mceledonia** [comment]
Going to take a look at this, for real this time!

**Comment by mcarrano** [comment]
I am going to move this to our design backlog but will not add to the roadmap until or unless we have a specific product use case for this.

**Comment by mcarrano** [comment]
Per discussion today with @mceledonia @lboehling @mmenestr we agreed this should be closed. If nav items are unavailable we should either hide or display and empty state.
