### ISSUE TITLE
Update popover shadow for better visibility

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#973]
As part of the work on defining a dark theme popover, we identified an opportunity to make Popover on a light background be more easily differentiated from the background. Even though this is visually breaking, we believe all users will benefit.

Designs here: https://marvelapp.com/prototype/963bhhh/screen/75172511

cc @doruskova @mceledonia

**Comment by coreyvickery** [comment]
@mcarrano @doruskova @mceledonia Feel free to answer now or we can wait until tomorrow, but is the only change increasing the size and opacity of the shadow? I ask because my teams wants to use this component on redhat.com.

**Comment by ajacobs21e** [comment]
![Popover](https://user-images.githubusercontent.com/6415742/104473482-07867700-558b-11eb-8968-20cd434ae4e3.png)
Example of the popover in my table context

**Comment by coreyvickery** [comment]
@ajacobs21e In this example, are you using what's on the PatternFly website right now or the updated pattern that's seen in the first post above?

**Comment by ajacobs21e** [comment]
@coreyvickery my example is exploring three options for an updated pattern

**Comment by mcarrano** [comment]
I think that our current plan is to update the default popover to use the large shadow to better differentiate the popover from the background. @doruskova is the large shadow in @ajacobs21e 's example consistent with your mocks? We may want to make sure we are all in agreement about this spec before I hand this over to development.

**Comment by doruskova** [comment]
@mcarrano Yeah, I think it's consistent. I used` --pf-global--BoxShadow--lg` @ajacobs21e . I believe Allie used the same shadow.

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/3814 to begin core implementation. Will get this on the roadmap.
