### ISSUE TITLE
Enhance navigation items and groups to animate upon selection

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#983]
**Medium priority**

Navigation items today don't have a smooth transition from default to selected states. Because of this, it seems a bit jumpy. Same goes for navigation groups where the expansion could be smoother. This issue is proposing to make those transitions smoother. Also it would be good to apply whatever animation comes out of this issue to similar components.

This [prototype](https://xd.adobe.com/view/823b1d9e-c651-4269-61d3-86eca2bd7039-f40a/screen/cdfac230-d370-43f6-81e6-a7e80407536e) is a bit out of date, but it softens the expansion of the group and also animates the blue underline. I think we could possibly do something similar to the horizontal blue line that appear on nav items.

**Comment by mcarrano** [comment]
Will address as part of https://github.com/patternfly/patternfly/issues/4979
