### ISSUE TITLE
Enhance toolbar to include animation when bulk selection is enabled

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#988]
**Low priority** On hold until we get feedback on if this is useful

In the case of bulk actions, only certain actions can be taken when items are selected. Those actions are usually different than the ones initially shown on the toolbar. It's difficult to include both on the toolbar after selection, since we are dealing with limited space and then have to somehow disable actions that are not applicable.

This issue is proposing to allow for the toolbar to be animated upon item selection. The idea would be that either the whole toolbar would be replaced by new actions that the user can take on the items or that the actions would transition into the toolbar. Here's a [prototype](https://xd.adobe.com/view/4e189954-36b5-4db0-4d5b-278b452fd6fc-3829/screen/ce5634a2-1061-4354-98f1-cdcd7e8d7d48) with an example.

**Comment by mcarrano** [comment]
We will stick with the current functionality. Seems complex and has not been highlighted as a problem.
