### ISSUE TITLE
Buttons in modal examples in the form pattern should be updated

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#99]
The buttons in the modal examples in the form pattern (link is below) should be updated.https://www.patternfly.org/pattern-library/forms-and-controls/forms/#_

- "Save changes" should be changed to "Save" ( or at a minimum "Save Change" with initial caps)
- "Close" should be changed to "Cancel", since this is canceling the operation not just closing the modal

<img width="635" alt="screen shot 2016-12-14 at 6 37 31 am" src="https://cloud.githubusercontent.com/assets/12504403/21180611/dfd5a2c2-c1c7-11e6-8641-90710f49f650.png">

**Comment by mcarrano** [comment]
There is a story for cleaning this up: https://patternfly.atlassian.net/browse/PTNFLY-2427. Will update when done.
