### ISSUE TITLE
Allow ToggleGroup to have other selected state color than primary blue (and perhaps be shorter)

### ISSUE THREAD

**Issue by itsptk** [patternfly/patternfly-design#990]
In OpenShift, we've previously used a radio button control to allow the user to switch between two views of the same data (a form view and a code view) for creating and editing a resource. We'd now like to use the newer ToggleGroup control as it seems better suited for this purpose, however we find it's use of the primary blue for the selected state to sort of confuse the main call to action on a page where there are also primary buttons for creating/saving the resource. This might be further complicated by the fact that the height of the ToggleGroup is also similar to the buttons.

We were wondering:
- Could ToggleGroup have an optional other color for the selected state? Maybe a darker grey?
- Could ToggleGroup support a shorter height, to allow for it to be less visually prominent on a page?

Current OpenShift console screenshot using radio controls:
![radio-today](https://user-images.githubusercontent.com/54860125/104481619-fee66e80-5593-11eb-92ab-6431943f9343.png)

Mocked OpenShift console with current ToggleGroup component:
![togglegroup-today](https://user-images.githubusercontent.com/54860125/104481639-04dc4f80-5594-11eb-884a-0ac1237a7e34.png)

FYI @mceledonia

**Comment by mceledonia** [comment]
I'd like to propose changing the blue to a dark gray, see here:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/30935938/104484286-1e32cb00-5597-11eb-8c86-f7988ce806cf.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/30935938/104484304-2428ac00-5597-11eb-9e55-e46f78ba8b5d.png">


Quick spec - 
Button background (default) - `$pf-color-white`
Button background (hover) - `$pf-color-black-200`
Button background (selected) - `$pf-color-black-800`
Button text color (selected) - `$pf-color-white`
Button borders - `$pf-color-black-300`

Pros:
- Retains shape + spacing of current implementation
- Removes need for variation, white background creates a nice effect on our secondary gray page background color
- Easily translatable to dark theme, whereas a colored (light blue, etc.) background doesn't
- Solves the issue of looking too similar to our primary button
- If it is too large for certain contexts we can introduce a `compact` variant as we do with other components

Cons
- We don't use this style as a selected state for other things, like tabs, but a styling too close to tabs would run into the same issue we're working to solve here.

@itsptk I also wanted to try it in your context to see how it looks. It led to a suggestion for the page layout that might work better than what you have above, basically just combining the two interactive areas into one to clean it up a bit.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/30935938/104485246-3eaf5500-5598-11eb-9788-a47081dd6690.png">

**Comment by mcarrano** [comment]
Thanks @mceledonia @itsptk . I will look at getting this change on the PF roadmap.

**Comment by itsptk** [comment]
Thanks @mceledonia ! I like that compact version a lot.

Two thoughts:
- I was advocating for the grey selected state but seeing it mocked up (with two toggles in particular) it seems like which of the two states represents "selected" can be kind of confusing. The darker selection option almost looks 'off' like a Switch, and the white one selected. I didn't think about this before.
- The in-context version was actually initially designed as you had drawn it, with the switcher on the same horizontal row as the interactive link buttons to the right. Unfortunately it was determined during development that the switcher needed to live at a level above the entirety of the YAML editor, which is why it is the way it is today.

**Comment by mceledonia** [comment]
@itsptk Good point about the selected vs non selected, I'm hoping that the fact it will always be accompanied by either text or icon should help to dodge that confusion, but definitely curious to hear others thoughts on it too. Regardless I'll try to think of something which is a little more obviously selected looking to see if we can come up with something even better.

**Comment by mceledonia** [comment]
@itsptk @mcarrano Here is another option which hopefully is different enough from other styles on the page but will still fit in with the rest of the system. 

![image](https://user-images.githubusercontent.com/30935938/106477308-03f15c00-6476-11eb-87bf-5c099fc1045f.png)

**Comment by mcarrano** [comment]
I think that's interesting @mceledonia . But then it starts to become a compact version of the Tile component (https://www.patternfly.org/v4/components/tile). So it begs the question of whether the approach here should be to create a new variant of the Toggle Group or a more compact version of the Tile component. Thoughts?

**Comment by mceledonia** [comment]
@mcarrano @itsptk Here are a couple more ideas - 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/30935938/109863537-c11ad380-7c2f-11eb-8fba-e7b15df2fe23.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/30935938/109863558-c5df8780-7c2f-11eb-83a6-06a92ece94db.png">

The blue uses a different selected styling to try to differentiate a bit from buttons and tiles
The dark gray uses a different default state to avoid the confusion between default and selected, since we don't use light gray for selected items.

**Comment by mcarrano** [comment]
@mceledonia I definitely have a preference for the first version with the light blue for selection. IMO the gray buttons are too easy to confuse with disabled styles, and the dark gray selection might be too prominent and have a similar issue with the primary blue for drawing too much attention to the component when placed in a page.

**Comment by itsptk** [comment]
+1! I like the light blue a lot.

**Comment by mcarrano** [comment]
Based on the feedback from today's PF design share meeting, let's plan to move forward with the light blue styling for selected states. @mceledonia can you attach a spec here? I will then open a core issue to move this into development.

**Comment by doruskova** [comment]
@mcarrano @mceledonia Could you add a design specification for the styling so that we can update it in a Design kit? I just want to ask, we have disabled state for the toggle group. What's the styling for the disabled states? And I noticed that we have a "light version" that is used on a grey background. Do we differentiate it here as well or is it only one version for grey and white background? Thank you!

**Comment by mceledonia** [comment]
Just realized I never added the spec here, see below!
![image](https://user-images.githubusercontent.com/30935938/117030638-d5ca2500-accd-11eb-8593-6670275d0387.png)

**Comment by doruskova** [comment]
@mceledonia Thank youu! Could you also add spec for disabled ones? Not sure about the border color.

**Comment by mceledonia** [comment]
@doruskova Disabled state will be the same as the current styling, just the fill and text color. 
Fill: pf-black-300
Text: pf-black-600
