### ISSUE TITLE
Treeview: Component needs a compact version for a sidebar use case in openshift

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-design#994]
**Describe the issue. What is the expected and unexpected behavior?**
For the story: 
https://issues.redhat.com/browse/CONSOLE-2500

It would be desirable for the treeview component to also have a compact version that allows it to be rendered in a sidebar and take advantage of space saving patterns so a leaf node wouldn't display as a single word per line, etc.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement
**What is your product and what release version are you targeting?**
Openshift, release not yet specified.

cc: @evwilkin

**Comment by mcarrano** [comment]
This has been addressed by https://github.com/patternfly/patternfly-design/issues/1043.  Opened https://github.com/patternfly/patternfly/issues/4177 to track core implementation.
