### ISSUE TITLE
Animation the entrance of the banner component

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#995]
**MEDIUM**

Our banner component sits at the top of all pages but, other than the use of color and placement, there isn't a ton of prominence on it. And if it's in the same spot on the page for a while, users sometimes ignore it.

This story is to animate the appearance of that component - whether that be the first time the user comes to the page or just when it's added to the page itself.

**Comment by mcarrano** [comment]
Per discussion with @mceledonia @mcoker , this should be easy, but requires more design consideration. How exactly should this animation take place? Fade in? slide in?

**Comment by JustinXHale** [comment]
I've been working on this issue and have created a few possible solutions. 
[Figma Prototype](https://www.figma.com/proto/XLVyWWRD1IlW1eFSSWzQTw/Animated-Banner?node-id=32%3A7&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=32%3A25&show-proto-sidebar=1) [Figma Board](https://www.figma.com/file/XLVyWWRD1IlW1eFSSWzQTw/Animated-Banner?node-id=7%3A41)

With each, the expectation is the banner to overlay on top of the header (if that isn't apparent in the prototype).

**Comment by mcarrano** [comment]
Thanks for posting @JustinXHale . These look good. It would be great to present these at Thursday's sync meeting for more feedback. Can you add this to the agenda?

**Comment by JustinXHale** [comment]
Unfortunately I cannot @mcarrano, I will be on PTO in Las Vegas having a miserable time lol.

**Comment by mcarrano** [comment]
Yeah, no one ever has much fun there LOL. Maybe next week, then,

**Comment by JustinXHale** [comment]
I've updated the prototype 
[Figma Prototype](https://www.figma.com/proto/XLVyWWRD1IlW1eFSSWzQTw/Animated-Banner?node-id=143%3A522&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=143%3A425&show-proto-sidebar=1) | [Figma Board](https://www.figma.com/file/XLVyWWRD1IlW1eFSSWzQTw/Animated-Banner?node-id=7%3A41)

![image](https://user-images.githubusercontent.com/91554933/201215638-f2cf084a-8021-4588-b94b-4eb8d68ada83.png)

https://user-images.githubusercontent.com/91554933/201216548-1a9c4eed-6d75-4e1a-b231-09c5a803e2c7.mp4

**Comment by mcarrano** [comment]
@JustinXHale Thanks for posting this spec. I think this looks great.

@mcoker @srambach how do you want to handle this? I know we have a larger issue to look at animations for PatternFly 5. We should include this in the mix. Do you want be to open a core issue specifically for this update or roll it into an existing issue/epic?

cc @mceledonia

**Comment by srambach** [comment]
From my perspective, it would be nice to have separate issues for implementation collected in to this epic https://github.com/patternfly/patternfly/issues/4979
