### ISSUE TITLE
Animate the selection of multiple tabs

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#996]
**MEDIUM**

When we have multiple tabs in a row, there is an underline (or box overline if boxed tabs) that appears when the tab item is selected. This issue is to add some sort animation to that selection state when going back and forth between tabs.

[Prototype example](https://drive.google.com/file/d/1ekfc9kgGZxG3rag8mensjd92VK2ti48r/view?usp=sharing) is attached here. Make sure to consider open vs boxed tabs

**Comment by mcarrano** [comment]
Will address as part of https://github.com/patternfly/patternfly/issues/4979
