### ISSUE TITLE
Animation the expansion of the menu component

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#997]
**MEDIUM**

The menu component is used within many components, for example dropdowns and selects. Today it expands without any animation and just appears on the screen with a shadow.

This story is to animate the expansion so that it smoothly appears on the screen upon opening.

[Example prototype](https://drive.google.com/file/d/1q8z9ctEzlInEIWTTUql1an_1FccJDhqf/view?usp=sharing) to use

**Comment by mcarrano** [comment]
Will address as part of https://github.com/patternfly/patternfly/issues/4979
