### ISSUE TITLE
Animate the hover states on components that have background color changes

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#998]
**MEDIUM**

Components like cards and buttons have a background change upon hover, whether it be a darker color, thicker border, or shadow. This story is to make that transition smoother and animate the appearance of that color. 

[Example prototype](https://drive.google.com/file/d/1JtJq70VGr3T9fHpYJffOaSjbsuaCCspH/view?usp=sharing)

**Comment by mcarrano** [comment]
Will address as part of https://github.com/patternfly/patternfly/issues/4979
