### ISSUE TITLE
Animate appearance of tooltips

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#999]
**LOW**

Tooltips today just appear without animation, which works well, but we'd like to create a version with animation as an optional variant. This story is to add animation upon the appearance of the tooltip (in relation to the object that has that tooltip). It will definitely help draw more attention to that item itself.

[Example prototype](https://drive.google.com/file/d/12-zG9QAK1LEa7TUyVBy8Gx_YzFYnpQn2/view?usp=sharing)

**Comment by mcarrano** [comment]
Will address as part of https://github.com/patternfly/patternfly/issues/4979
